### ISSUE TITLE
Astro and HIPAA doc

### ISSUE THREAD

**Issue by chomipi88** [astronomer/docs#1021]
**Request type:**

- [X] **New document:**: Add the `docs-content` label to this issue.
- [ ] **Addition to an existing document**: Add the `enhancement` label to this issue.

**What is the purpose of the document/enhancement? Select all that apply:**

- [X] Document a new feature for an upcoming release. Add the appropriate release version label to this issue.
- [ ] Information for an existing feature that isn't yet documented.
- [ ] Additional considerations/ reference material for an existing document.

**Problem/feature that requires documentation:**
https://www.notion.so/astronomerio/Astro-and-HIPAA-8f8d9ffc312f47c6bb56040593cedc3d

**Are you the right person to review a draft of the document for technical accuracy? If not, who is?**
yes

**Comment by paolaperaza** [comment]
Thanks @chomipi88 ! Rob, let's add this as a new standalone doc under the **Reference** > **Security** menu.
