### ISSUE TITLE
CI uses xenial, which will fail after November 15th

### ISSUE THREAD

**Issue by danielhoherd** [astronomer/docs#1036]
While looking at the [CI logs](https://app.netlify.com/sites/gallant-neumann-56599d/deploys/62f66301ce13df0009532915) i saw this warning:

```
NOTICE: Builds using the Xenial build image will fail after November 15th, 2022.
```

xenial (ubuntu 16.04) was released in 2016. definitely time to upgrade.

**Comment by jwitz** [comment]
Oh weird, our main branch still uses Focal 20.04 to build the site. No idea why the preview site for the PR was using such an old version. 

In any case, I checked the deploy info for other branches and I seemed to have fixed this. Closing out the issue for now - thanks for calling out @danielhoherd !
