### ISSUE TITLE
How to Use Temporary Storage in Your DAG

### ISSUE THREAD

**Issue by ghost** [astronomer/docs#1039]
**Request type:**

- [X] **New document:**: Add the `docs-content` label to this issue.
- [ ] **Addition to an existing document**: Add the `enhancement` label to this issue.

**What is the purpose of the document/enhancement? Select all that apply:**

- [ ] Document a new feature for an upcoming release. Add the appropriate release version label to this issue.
- [X] Information for an existing feature that isn't yet documented.
- [ ] Additional considerations/ reference material for an existing document.

**Problem/feature that requires documentation:**

We currently leave it to users to make assumptions on how to use temporary storage in their DAGs on Astro. This leads to users leveraging anti-patterns and running into undocumented known limits. We should be proactive with our guidance on this topic.

**Are you the right person to review a draft of the document for technical accuracy? If not, who is?**

CRE is likely to have strong opinions here based on lived experience.

**Comment by jwitz** [comment]
Duplicate on https://github.com/astronomer/docs/issues/1014, waiting for word from Stu about the extent to which we should document what to do/ not do in docs

**Comment by jwitz** [comment]
@astro-rft Can we close this out now that we have information on using ephemeral storage in AWS, both for standard operators and the KPO?

https://docs.astronomer.io/astro/resource-reference-aws#worker-node-types
https://docs.astronomer.io/astro/kubernetespodoperator#mount-a-temporary-directory-aws-only

**Comment by astro-rft** [comment]
@jwitz I would think we need similar coverage for Google Cloud and Azure as well, right? And wouldn't there be use cases outside of KPO for the pipeline author?

**Comment by jwitz** [comment]
@astro-rft do we have similar/ recommended node types with enough ephemeral storage for these operations on the other clouds? Happy to add those details in and also create a dedicated section for writing to ephemeral storage

**Comment by astro-rft** [comment]
@dnarain-astro @chomipi88 ?

**Comment by dnarain-astro** [comment]
Those instructions should apply to KPO tasks all clouds, not just AWS. 
We don't offer any guidance for regular tasks though.  

PS: The reason we had so much noise on AWS was that we have really low storage defaults on AWS - 20GB.  On the other clouds they are 5-6x larger and we have yet to hear from a customer who has run into those limits

**Comment by astro-rft** [comment]
@dnarain-astro do we have storage-attached nodes on Azure and GCP?

**Comment by kwcanuck** [comment]
@jwitz given the departure of @dnarain-astro and the time that this issue has been sitting, can it be closed?

**Comment by jwitz** [comment]
Not yet - we are about to have this feature covered for all clouds with the introduction of the Kubernetes executor. If you want, we can get started on this early by writing an example DAG showing how to create an `empty_dir` in the `pod_override` configuration.

**Comment by kwcanuck** [comment]
@jwitz here's an example DAG we can use:

```
from kubernetes.client import models as k8s
import pendulum
import time

from airflow import DAG
from airflow.decorators import task
from airflow.example_dags.libs.helper import print_stuff


volumes = [k8s.V1Volume(name="cache-volume", empty_dir=k8s.V1EmptyDirVolumeSource())]

volume_mounts = [k8s.V1VolumeMount(mount_path="/cache", name="cache-volume")]

executor_config = {
    "pod_override": k8s.V1Pod(
        spec=k8s.V1PodSpec(
            containers=[k8s.V1Container(name="base", volume_mounts=volume_mounts)],
            volumes=volumes,
        )
    )
}

with DAG(
    dag_id="empty_dir_example_dag",
    schedule=None,
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
    catchup=False,
) as dag:

    @task(executor_config=executor_config)
    def empty_dir_example():
        print_stuff()
        time.sleep(60)

    empty_dir_example()
```

**Comment by jwitz** [comment]
@kwcanuck sweet, do you want to add this to your Kubernetes Executor PR as another example next to the resource request example? I think we could then close out this issue once the KE PR is merged.

Ideally that DAG would have a task which accesses the created storage, but it's good enough for now to show how the pod override should be configured.

**Comment by kwcanuck** [comment]
@jwitz I added a new section titled _Create temporary storage_ to the topic _Manage Deployment executors_. When time permits, please review and add any edits you think are necessary. Thanks!

**Comment by jwitz** [comment]
Closing out due to lack of interest from customers/ external teams
