### ISSUE TITLE
Customer Feedback - AWS IAM Role setup not clear enough

### ISSUE THREAD

**Issue by aspain** [astronomer/docs#1046]
**Affected Document:**
https://docs.astronomer.io/astro/connect-external-services#aws-iam-roles

**Problem Type (Priority):**

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [X] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**
In a customer call today (Melio Payments) - the customer mentioned our steps for setting up AWS IAM Roles are unclear, and that they weren't sure which account (Astro vs Their own) some of the steps referred to. 
I myself am not familiar enough with the process to make the correction in the docs but do agree that, for example, step 3 doesn't specify which account they are navigating to the IAM section in. 

They were also confused about the `AirflowS3Logs` name in this snippet - wondering if they needed to create a role in _their_ account with that same name, or if this belonged to the Astro account

```
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": [
                    "arn:aws:iam::<dataplane-AWS-account-ID>:role/AirflowS3Logs-<cluster-ID>"
                ]
            },
```

**Comment by aspain** [comment]
@kwcanuck was the update for step 6 in [this PR](https://github.com/astronomer/docs/pull/1056/files#diff-7549440594acd8b94c23d7cdea467b6ca05ce1325b46020f60e406f9fdc16a29R144) intended to be in a code block? 


![image](https://user-images.githubusercontent.com/15913202/188721658-ec3259bd-abcd-4bf6-9d5e-da5b412a1a16.png)

**Comment by kwcanuck** [comment]
@aspain I think this formatting issue has been addressed.
