### ISSUE TITLE
New instructions on KPO Images with ECR

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#1051]
[Slack discussion here
](https://astronomer.slack.com/archives/C028YCH4682/p1660925673762439)
### Context

We currently state in our docs that running docker images from Amazon ECR in a KubernetesPodOperator task is not supported on Astro given ECR's token rotation policy. However, our CRE team has recently discovered a working setup for this workflow. It has been validated with 2 customers and an internal sandbox.

Tickets:
- https://astronomer.zendesk.com/agent/tickets/11433
- https://astronomer.zendesk.com/agent/tickets/11817

Generally, the idea is that instead of giving permission to node group to access the registry, we are allowing registry to be accessed from customer's Astro account. (Because ECR is not in customer's Astro Account).

### Ask

Here: https://docs.astronomer.io/astro/kubernetespodoperator#run-images-from-a-private-registry

Two things:
- Remove this caution statement
- Add a new sub-section to `Run images from a private registry` that is specific to ECR

Marking this ticket as `kind/blocked` until we have some internal documentation on how this works. cc: @shubh-am-kumar @ReadytoRocc @stuart23

**Comment by stuart23** [comment]
Also @afastronomer has found some interesting instructions in the AWS docs about how we can do this [here](https://astronomer.slack.com/archives/C0188B7CXJM/p1660755734587719)

**Comment by kwcanuck** [comment]
Branch for this work: _Running Docker Images Hosted On ECR_
