### ISSUE TITLE
[Doc][Observability] New documentation on Airflow Metrics Export to DataDog

### ISSUE THREAD

**Issue by howardyoo** [astronomer/docs#1091]
**Request type:**

- [x] **New document:**: Add the `docs-content` label to this issue.
- [ ] **Addition to an existing document**: Add the `enhancement` label to this issue.

**What is the purpose of the document/enhancement? Select all that apply:**

- [x] Document a new feature for an upcoming release. Add the appropriate release version label to this issue.
- [ ] Information for an existing feature that isn't yet documented.
- [ ] Additional considerations/ reference material for an existing document.

## Problem/feature that requires documentation: ##
This new documentation is related to the feature outlined here: https://github.com/astronomer/astro/issues/3107
the enables Astro to export its Airflow related metrics (https://airflow.apache.org/docs/apache-airflow/stable/logging-monitoring/metrics.html) to a third party monitoring tool [Dataodg](https://www.datadoghq.com/).

By setting up a special environment variable `DATADOG_API_KEY` as secret type in the deployment configuration, you will enable the Astro to push a new sidecar container that runs dogstatsd agent, as well as configure existing statsd-exporter to export its metrics to user's DataDog service (based on the provided key).

The full list of the metrics exported are listed out here: https://docs.datadoghq.com/integrations/airflow/?tab=host#data-collected

## Are you the right person to review a draft of the document for technical accuracy? If not, who is? ##
Yes, I would be person who can review the draft of the documentation.

**Comment by stuart23** [comment]
Can we please prioritize this? We have already had one customer approach us to set this up for them, when they can in-fact easily self-service https://astronomer.zendesk.com/agent/tickets/12233

Thank you

**Comment by howardyoo** [comment]
Closing this issue, as the documentation is now published: https://docs.astronomer.io/astro/deployment-metrics#export-airflow-deployment-metrics-to-datadog

**Comment by stuart23** [comment]
Thanks @howardyoo. My concern is that it is not clear that the only thing they need to do is add the DD key. I think customers still think that they need to have something enabled on our end based on "After you configure this integration"

**Comment by howardyoo** [comment]
> Thanks @howardyoo. My concern is that it is not clear that the only thing they need to do is add the DD key. I think customers still think that they need to have something enabled on our end based on "After you configure this integration"

I see. To clarify, the only thing (surprisingly) that they need to do is add the DD API key, and when it happens, it will trigger a chain action of Harmony pushing the sidecar specs to Airflow operator, and eventually it will roll out dogstatd agent, and necessary configurations to start forwarding the airflow metrics.

Customers can then check whether the `airflow.*` metrics is flowing from it in their datadog UI, and that should pretty much it.

However, do you think if there's anything that we should add to the documentation to make certain things clearer? Please let me or @jwitz know here.

**Comment by stuart23** [comment]
Thanks for clarifying. Is there a way we can make this clearer in the instructions that there is nothing that Astronomer needs to do? Maybe @jwitz or @kwcanuck can help with wording?

**Comment by jwitz** [comment]
@stuart23 I tried removing the ambiguous language about "integration" and "setup" to make it clear that the only thing users have to do is add an API key. I also said Astro "automatially" launches the container to make it clear that there's no manual process to get this sorted.
