### ISSUE TITLE
For Astro, we need to have a Privatelink for Azure section to mirror the AWS one

### ISSUE THREAD

**Issue by dnarain-astro** [astronomer/docs#1096]
**Affected Document:** https://docs.astronomer.io/astro/connect-external-services

**Problem Type (Priority):**

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [ x] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**

**Additional Notes:**

**Comment by kwcanuck** [comment]
@dnarain-astro asked that I close this issue as he doesn't currently have time to provide the information necessary to complete it. This issue can be reopened when Deepak has time to focus on it.

**Comment by paolaperaza** [comment]
@kwcanuck If the documentation ask exists, let's keep this issue open and mark it as `/blocked`.

**Comment by ElanDWeiner** [comment]
@paolaperaza any updates on this? Blocking Teck from evaluating at this time

**Comment by kwcanuck** [comment]
@ElanDWeiner I'm glad you found the content! Apologies for the confusion, but there have been numerous issues opened to request updates to the existing content. I meant to close this issue, but it was missed.

**Comment by kwcanuck** [comment]
This issues was addressed by another issue.
