### ISSUE TITLE
For Astro, we need to have a Private Service Connect section to mirror the AWS Privatelink one

### ISSUE THREAD

**Issue by dnarain-astro** [astronomer/docs#1097]
**Affected Document:** https://docs.astronomer.io/astro/connect-external-services

**Problem Type (Priority):**

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [ x] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**

**Additional Notes:**

**Comment by kwcanuck** [comment]
@dnarain-astro asked that I close this issue as he doesn't currently have time to provide the information necessary to complete it. This issue can be reopened when Deepak has time to focus on it.
