### ISSUE TITLE
Clarify CLI install for different platforms + upgrade process

### ISSUE THREAD

**Issue by BasPH** [astronomer/docs#1102]
**Affected Document:**

https://docs.astronomer.io/astro/cli/overview

**Problem Type (Priority):**

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [x] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**

The CLI install section shows only MacOS install instructions, while the Software docs do show Windows + Linux instructions: https://docs.astronomer.io/software/install-cli#install-the-astro-cli. This should be streamlined.

Also, there's no mention of "upgrade". For Mac & Linux (don't know about windows), the upgrade instructions are exactly the same as the install instructions, but this could/should be mentioned explicitly.

**Additional Notes:**

**Comment by jwitz** [comment]
@BasPH We were inspired by the GitHub CLI homepage to present a single, simple command that most people can use for installation. On the the GH CLI homepage, they prioritize one installation method and include a link to other methods below:

![Screen Shot 2022-08-30 at 5 24 31 PM](https://user-images.githubusercontent.com/74574233/187489717-016f6871-2161-4072-ac0e-93013842bff5.png)

Similarly, we wanted to provide Homebrew as the primary installation method and link out to other methods below that. The link here goes to https://docs.astronomer.io/astro/cli/configure-cli#install-the-astro-cli:

![Screen Shot 2022-08-30 at 5 25 40 PM](https://user-images.githubusercontent.com/74574233/187489943-a210912e-f087-41c2-b1dd-4503ba09ec57.png)

As for the upgrade steps, the Windows upgrade process is still different than the installation process. Until that's not the case, I think it's still good to have separate explicit upgrade steps. All upgrade steps are available here: https://docs.astronomer.io/astro/cli/configure-cli#upgrade-the-cli

**Comment by BasPH** [comment]
Thanks for clarifying! Closing this issue.
