### ISSUE TITLE
Need to replace assets2.astronomer.io CDN

### ISSUE THREAD

**Issue by danielhoherd** [astronomer/docs#1112]
**Affected Document:**

Approximately 154 docs.

**Problem Type (Priority):**

assets2.astronomer.io is a CDN we don't want to use anymore. We need to find what the newer best place is to host the assets2.astronomer.io images that are used in our docs.

This is being discussed in <https://github.com/astronomer/issues/issues/2338>

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**

- <https://github.com/astronomer/docs/search?q=assets2.astronomer.io>

**Additional Notes:**

It's entirely possible that this doesn't need to be done and that we are still maintaining that CDN. Please discuss this possibility in the original ticket if needed.

**Comment by jwitz** [comment]
What's the timeline for this project? We are actually in the middle of migrating all assets off of this CDN, but it might take a while longer. The estimated completion for our assets migration is the end of September/ early October

**Comment by danielhoherd** [comment]
@jwitz I don't think this is an urgent thing. The original issue 2338 was filed in Dec 2020.

**Comment by kwcanuck** [comment]
Branch for this work: relocate software docs images
