### ISSUE TITLE
Fix CPU/Memory maximum capacity for larger workers in resource references

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#1130]
Reported by @BasPH. [Slack discussion here](https://astronomer.slack.com/archives/C01UA03TPV1/p1662017253127779).

### Context

Worker sizes used to be capped at 400 AU prior to the rollout of worker queues. That meant that our CPU and Memory capacity as defined in [resource reference docs](https://docs.astronomer.io/astro/resource-reference-aws) was artificially capped at 94 CPUs and 352.5 Gib MEM.

With the removal of the worker size slider, that information is no longer correct and we CAN support larger CPU and memory requests for larger nodes.

### Ask

- [ ] Identify all instances of worker sizes that have an actual capacity that is more than 94 CPUs and 352.5 Gib MEM
- [ ] Pull actual capacity numbers for those pods
- [ ] Update AWS, GCP, and Azure resource references for that information as needed

Most of these changes will apply to AWS as that's where most of our worker types are supported. cc: @afastronomer

**Comment by kwcanuck** [comment]
Resources required for Astro on AWS:

![image](https://user-images.githubusercontent.com/104205257/188702182-68c56c42-32c3-48ba-97cd-0faa5b72e719.png)

**Comment by kwcanuck** [comment]
@paolaperaza this appears to have been resolved by [PR 1139](https://github.com/astronomer/docs/pull/1139). The only updates required were in the AWS doc. Please confirm.

**Comment by paolaperaza** [comment]
@kwcanuck I should've updated this last week -- you're right, I think we did most of the work here. Before we close out, can you just remove this section from the doc on scheduler resources?

<img width="825" alt="image" src="https://user-images.githubusercontent.com/31111752/188770389-f8ed1952-d063-4138-bf5f-5102d2e06324.png">

No longer fitting/relevant/accurate -- we'll have to add another section at some point to address it but I think https://docs.astronomer.io/astro/configure-deployment-resources#scheduler-resources is good for now

**Comment by kwcanuck** [comment]
@paolaperaza the change you requested was implemented as a hotfix.
