### ISSUE TITLE
Screenshot for deleting an API key missing

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#1147]
Doc: https://docs.astronomer.io/astro/api-keys#delete-an-api-key

- I don't actually see this screenshot appear, I just see a link to the image (which is correct!)
- I do see all other screenshots as expected, which makes me think it's not an issue specific to my browser or machine

![image](https://user-images.githubusercontent.com/31111752/188520393-a2cdf6c6-39dd-4b51-80c8-578d336510bc.png)

**Comment by jwitz** [comment]
Went ahead and hotfixed this! https://github.com/astronomer/docs/commit/ef42c829149aeeaeb3c4e22700b7459460843a8f
