### ISSUE TITLE
Update Auth Integration Doc to reflect OpenID Connect changes

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#115]
**Topic:**

v0.9.5 includes integration with OpenID Connect, which on the backend simplifies code for auth integrations and opens the door for EE users to more easily add integrations for compliant providers.

We're set to patch up that that release this week and should update our docs to reflect any changes in configuration users will need to make.

**Cloud, EE, or Both?:**
EE

**Menu:**
https://www.astronomer.io/docs/ee-integrating-auth-systems/

**User Story**

Got some initial questions from an EE customer that this doc should answer.

> 1. So the way set the values for the new openid connection is by adding the configurations to the `config.yaml` the same way we did it before but by changing the variables with the new ones (`discoveryUrl` instead of `baseDomain`). Am I correct ?
> 
> 2. How do we declare another IdP (in our case Gluu) ? do we override the Auth0 config with our own IdP discoveryUrl? or do we make another one like this :
> ```gluu:
>       enabled: true
>       clientId: <client_id>
>       discoveryUrl: <gluu_discovery_url>
> ```
> 
> 3. The PR mentions an `.env` file. Is this the proper way to set the configurations ? or is it simply a solution for local deployments ?

@petedejoy Assigning you on this one 😃
cc: @ashb

**Comment by petedejoy** [comment]
Work in progress up on preview! Just waiting on a few confirmations from Ash before taking this live: https://preview.astronomer.io/docs/ee-integrating-auth-systems/

**Comment by paolaperaza** [comment]
Damn thanks for jumping on this, @petedejoy

**Comment by ashb** [comment]
@petedejoy 

- `clockTolerance` is for server (it just happens when you were testing your machine was client and server)
- Okta example still has baseDomain, should be discovery URL, (and lets make sure that has `https://` at the start of it)
- Auth0 has baseDomain still do. Again, include https:// please

**Comment by petedejoy** [comment]
Thanks for the updates, @ashb! Just pushed up a fix, will merge to master.
