### ISSUE TITLE
New tutorial: Get started with Airflow - Part 2

### ISSUE THREAD

**Issue by TJaniF** [astronomer/docs#1158]
**What is the purpose of the document/enhancement? Select all that apply:**

- Additional considerations/ reference material for an existing document.

**Problem/feature that requires documentation:**

Beginner level introduction to Airflow providers and connections in tutorial format.

**Are you the right person to review a draft of the document for technical accuracy? If not, who is?**

Team: Paola, Jake, Rob, Kenten and me. 🙂

**Comment by TJaniF** [comment]
PR #1161

**Comment by kentdanas** [comment]
Tutorial has been published https://docs.astronomer.io/learn/get-started-with-airflow-part-2
