### ISSUE TITLE
Add Procedure for Exporting AWS Task Logs to Datadog

### ISSUE THREAD

**Issue by kwcanuck** [astronomer/docs#1169]
[This Slack conversation](https://astronomer.slack.com/archives/C02PABPU6B0/p1662637450402899) identified a need to add a procedure for exporting AWS task logs to Datadog to the existing _[Deployment metrics](https://docs.astronomer.io/astro/deployment-metrics)_ topic.

@howardyoo indicated in the Slack conversation that the "support team has a runbook for the task log export (on AWS only)". The support documentation is available here: https://support.astronomer.io/hc/en-us/articles/7188391615123-Datadog-Log-Forwarder. This documentation should serve as the foundation for the new procedure.

**Comment by paolaperaza** [comment]
A few notes here:

- As part of this GH issue, we should update the `View Task Logs` doc and create a dedicated section for exporting logs to Datadog
- Customer questions we should make sure are addressed in some way:
    - Does it require Datadog agents running on Astronomer workers? If so do we have them?
    - Can we customize the statsd endpoint?

From @howardyoo:
- Datadog agent is running as the sidecar container inside the statsd pod in Astro deployment.
- The statsd and datadog agent running together in the pod do not expose the ports to outside world, so there was no feature to customize the statsd endpoint at this moment.
