### ISSUE TITLE
Add CLI features to product roadmap

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#12]
We've been cranking out CLI features that will be part of the v0.8 release, but they're not currently shown on our [product roadmap page](https://www.astronomer.io/docs/roadmap/).

@benjamingregory, can you add a section to at least v0.8 with some of the features you've both (1) already merged or (2) plan to merge for the upcoming release?

**Comment by benjamingregory** [comment]
Closed with 0.8 branch and https://github.com/astronomer/docs/commit/1a025d36dca182bccdbbe8c5d4f393078d31165c
