### ISSUE TITLE
Add details on how to retrieve metrics from Datadog

### ISSUE THREAD

**Issue by stuart23** [astronomer/docs#1209]
In our documentation about how Airflow metrics are shipped from Astro dataplanes, we instruct the customer how to enable the feature and what metrics get sent but we never tell them how to retrieve the metrics once they are in DD. Can we also add a section on how to get the metrics back out of DD, eg what to search for: dogstatsd.* or airflow.* 

For ref: https://astronomer.zendesk.com/agent/tickets/12528

**Comment by howardyoo** [comment]
Sure, let me talk to @jwitz and work with him. Yeah, I think we need to add those into the doc. Thanks!

**Comment by howardyoo** [comment]
Thanks all!
