### ISSUE TITLE
Improve look of website logo

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#122]
It would be nice to have a more cohesive looking logo for the docs site. The current one looks a bit disjointed, given the change in font between the logo and the title:

![Screen Shot 2021-10-08 at 4 28 23 PM](https://user-images.githubusercontent.com/74574233/136583527-db1d56a9-3268-42c0-b4e6-3884b48d8c51.png)

It would be nice to have the logo and title combined into a more cohesive object, like here:
![Screen Shot 2021-10-08 at 4 30 24 PM](https://user-images.githubusercontent.com/74574233/136583794-89e7290a-29bf-46af-ab1d-419bc058116d.png)

I actually think our Platform site does a great job of this already, so anything similar to that is also good: 

![Screen Shot 2021-10-08 at 4 31 41 PM](https://user-images.githubusercontent.com/74574233/136584125-8a1d2298-30bd-49ad-b750-85bdd1787921.png)

**Comment by paolaperaza** [comment]
Closing this in favor of #316
