### ISSUE TITLE
Specify which Datadog metrics we do/don't support

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#1222]
### Context

We recently published a new topic called `Export Airflow metrics to Datadog`: https://docs.astronomer.io/astro/deployment-metrics#export-airflow-metrics-to-datadog

Here, we tell the user that we ship ALL Airflow metrics that Datadog supports, but in reality we don't.

### Ask

We need to either:
- Update this doc somehow with a note that tells the user we don't ship all metrics.
- Create a new technical reference doc with a list of metrics that we support.

This is the "source of truth" file for the metrics that we do export:
https://github.com/astronomer/ap-vendor/blob/main/statsd-exporter/include/mappings-gen2.yml

Anything not on this list is not supported. 

cc: @howardyoo @conorbev @stuart23

**Comment by conorbev** [comment]
@paolaperaza @stuart23 @howardyoo 

My understanding is that the current doc is _correct_ and that we do send ALL the Airflow metrics to Datadog. (and if not imo it'd be a product bug instead of a doc bug )

The linked "source of truth" file controls what we send internally to Chronosphere. It shouldn't be involved for the Datadog integration. 

I assume something is causing people to think otherwise?

**Comment by howardyoo** [comment]
> @paolaperaza @stuart23 @howardyoo
> 
> My understanding is that the current doc is _correct_ and that we do send ALL the Airflow metrics to Datadog. (and if not imo it'd be a product bug instead of a doc bug )
> 
> The linked "source of truth" file controls what we send internally to Chronosphere. It shouldn't be involved for the Datadog integration.
> 
> I assume something is causing people to think otherwise?

That is correct.
https://github.com/prometheus/statsd_exporter#transitioning-from-an-existing-statsd-setup states:
> Use the --statsd.relay.address to forward metrics to your existing StatsD UDP endpoint. Relaying forwards statsd events unmodified, preserving the original metric name and tags in any format.

Looks like the relay forwards metrics `unmodified` - which is what we're using for forwarding metrics to DataDog.

**Comment by paolaperaza** [comment]
Ah, thanks for the clarification guys. Let's put a pin in this issue if there's still confusion. @stuart23 Can you connect with Howard and Conor (outside of this GH issue) for the customer issue/bug you mentioned today?

It sounds like if a customer _isn't_ receiving the metrics they're supposed to, it's a bug elsewhere that isn't expected.

Will keep this GH issue open for a few days in case we conclude that (even if not this) there are _other_ related changes to documentation that'd be beneficial in creating clarity for users for this topic

**Comment by stuart23** [comment]
Sorry I missed this followup. Aren't the stats that we ship to DD here?
https://github.com/astronomer/ap-vendor/blob/main/dogstatsd/include/dogstatsd.yaml

**Comment by christine-sherry** [comment]
@stuart23 do you have an example of a metric listed as supported but not available in the current integration?

**Comment by stuart23** [comment]
I do not. Maybe @sreenusuuda might have a working example?

**Comment by sreenusuuda** [comment]
I am setting up Environment to test. I see some metrics are not populated in the Datadog. Will give some clarity once I do some testing on it. 

Right now I am considering all the metrics mentioned in the below link should populate in the Datadog.

**Comment by paolaperaza** [comment]
@sreenusuuda Let's use the actual doc as our intended source of truth. It's my understanding that *everything* in this doc should be shipping from Astro and available to the customer in Datadog: https://docs.astronomer.io/astro/deployment-metrics#export-airflow-metrics-to-datadog

**Comment by sreenusuuda** [comment]
We can see what all metrics we are pushing to Datadog under integrations -> Airflow -> Data collected.(PFA). Not sure if this list is up to date. 
<img width="1399" alt="Screenshot 2022-10-03 at 11 47 47 AM" src="https://user-images.githubusercontent.com/99465779/193512767-d1641897-33d2-4fdd-839c-6cb85eedac2b.png">

We can see metrics from metrics -> summary

**Comment by paolaperaza** [comment]
@sreenusuuda That screenshot just looks like in-product documentation vs. real-time confirmation that we ARE sending those metrics.

Can you confirm with an Astro Deployment that these metrics are in fact available, when you follow our instructions here:

> 1. In the Datadog UI, go to Metrics > Summary.
> 2. Search for metrics starting with airflow and open any Airflow metric.
> 3. In the Tags table, check the values for the namespace tag key. The namespaces of the Deployments you configured to export logs should appear as tag values.


@kwcanuck Let's keep this issue as `/blocked` until we've got confirmation here.

**Comment by sreenusuuda** [comment]
@kwcanuck  I am working on some other priority items. Is this urgent request from customer? If yes then I need to talk to @ernest-kr  to set priority to my tasks.

cc: @paolaperaza

**Comment by kwcanuck** [comment]
Slack message sent to @sreenusuuda 2022-10-18 requesting a status update for this issue.

**Comment by kwcanuck** [comment]
After much discussion it was determined that we cannot currently confirm what Datadog metrics are available. I spoke to @sreenusuuda and @ernest-kr numerous times and these are the responses I received:

![image](https://user-images.githubusercontent.com/104205257/196764774-4d5dfe8d-aa35-4fae-8f7d-002dd2ef98fd.png)

![image](https://user-images.githubusercontent.com/104205257/196764965-4afa9a0c-baae-49ee-8bca-a0e71f1ed6fc.png)
