### ISSUE TITLE
Astro documentation for integrating email alert with sendgrid is incorrect

### ISSUE THREAD

**Issue by howardyoo** [astronomer/docs#1231]
**Affected Document:**
https://docs.astronomer.io/astro/airflow-alerts#integrate-with-sendgrid

**Problem Type (Priority):**

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [x] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**
I have followed the steps to setup sendgrid, and found out the following:
![image](https://user-images.githubusercontent.com/32691630/191345807-57416a67-a07f-4656-a2f6-7564eb48d7a2.png)
In the step 6, the document mentions to add this backend, along with the airflow connection in step 7.
- This part never worked, and what I have found out is that the required package (https://pypi.org/project/apache-airflow-providers-sendgrid/) that contains the `airflow.providers.sendgrid.utils.emailer.send_email` is not included with the Astro runtime, thus this part never works.
- I was able to make it work by adding the environment variable mentioned in the following URL: https://airflow.apache.org/docs/apache-airflow/stable/howto/email-config.html#using-default-smtp as such:
![image](https://user-images.githubusercontent.com/32691630/191346542-61192fa6-d0ae-474b-bb3e-65def0bbb341.png)

**Additional Notes:**
- Also, in order for sendgrid to properly send out the email, you need to make sure the FROM EMAIL ID is identical to the send validated email that you set in sendgrid, due to the security reasons. The Astronomer documentation also does not seem to mention the importance of this as well.

**Comment by kwcanuck** [comment]
Met with @howardyoo 2022-09-27 to discuss the doc requirements for this issue. It appears that the methodology described in the existing documentation (using the `airflow.providers.sendgrid.utils.emailer.send_email` package) doesn't work. Howard is going to create an issue to determine if the package should be fixed, or if the workaround described in this issue should be provided instead. For the workaround, step 6 would need to be updated to instruct users to add the environment variables listed in the Airflow doc and step 7 would be removed. The branch for this work is: _integrate-with-SendGrid-update_.

Awaiting confirmation from @howardyoo on the way forward.

**Comment by howardyoo** [comment]
Howard here. I just tested the thing again, and looks like I do not see that error anymore, so it seems the problem is fixed.
I guess the only thing that we're now missing would be the instruction in the doc to add 
`apache-airflow-providers-sendgrid` to the requirements.txt file!
