### ISSUE TITLE
Add instructions for ArgoCD

### ISSUE THREAD

**Issue by stuart23** [astronomer/docs#1233]
**Request type:**

- [x] **New document:**: Add the `docs-content` label to this issue.
- [ ] **Addition to an existing document**: Add the `enhancement` label to this issue.

**What is the purpose of the document/enhancement? Select all that apply:**

- [ ] Document a new feature for an upcoming release. Add the appropriate release version label to this issue.
- [x] Information for an existing feature that isn't yet documented.
- [ ] Additional considerations/ reference material for an existing document.

**Problem/feature that requires documentation:**

We support ArgoCD by following the instructions here: https://forum.astronomer.io/t/installing-astronomer-with-argocd/1341

These should be in the software docs rather than the customer having to find a blog post.

**Are you the right person to review a draft of the document for technical accuracy? If not, who is?**

Yes. Also @rbankston

**Comment by jwitz** [comment]
@stuart23 I have a couple of questions before getting started on this doc:

- Which part of the base installation has to be modified for this? Is it only [Step 9](https://docs.astronomer.io/software/install-aws#step-9-install-astronomer), or are there other details of the installation that are modified?
- Can people use ArgoCD on airgapped installations? Does the process look any different there?
