### ISSUE TITLE
Tutorial: Migrate your first DAG from MWAA to Astro

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#1260]
### Context

We've committed to writing a tutorial that showcases how easy it is for a user to migrate a running DAG from MWAA to Astro. Generally, this tutorial should:

- Assume all compatible versions of Airflow and Python.
- Show creating a Deployment and project on Astro
- Actually moving the DAG (and turning on/off) from MWAA to Astro (with screenshots)

More details to come, but we can plan to work on this with Kevin Ruppel's field team.

**Comment by jwitz** [comment]
Closing this out now that we have proper migration tools/ docs!
