### ISSUE TITLE
New guide on accessing dagrun context

### ISSUE THREAD

**Issue by kentdanas** [astronomer/docs#1279]
**Request type:**

- [ ] **New document:**: Add the `docs-content` label to this issue.
- [x] **Addition to an existing document**: Add the `enhancement` label to this issue.

**What is the purpose of the document/enhancement? Select all that apply:**

- [ ] Document a new feature for an upcoming release. Add the appropriate release version label to this issue.
- [x] Information for an existing feature that isn't yet documented.
- [ ] Additional considerations/ reference material for an existing document.

**Problem/feature that requires documentation:**
Ported from guides repo issue: https://github.com/astronomer/airflow-guides/issues/393

There's not a lot of info on accessing a dagrun's context, and what exists in the airflow docs is hard to find or unclear. For example, the [section on accessing current context](https://airflow.apache.org/docs/apache-airflow/2.0.2/concepts.html#accessing-current-context) seems to have been removed since 2.1.0, and the [template reference](https://airflow.apache.org/docs/apache-airflow/stable/templates-ref.html) doesn't make it clear that how to access the values it describes in a DAG (or even that you can access them outside of jinja).

This could go into the [templating guide](https://www.astronomer.io/guides/templating), but IMO this topic warrants its own guide as it's not exactly the same as templating.

**Are you the right person to review a draft of the document for technical accuracy? If not, who is?**

**Comment by TJaniF** [comment]
Related to #2239
