### ISSUE TITLE
New custom callbacks tutorial

### ISSUE THREAD

**Issue by kentdanas** [astronomer/docs#1280]
**Request type:**

- [x] **New document:**: Add the `docs-content` label to this issue.
- [ ] **Addition to an existing document**: Add the `enhancement` label to this issue.

**What is the purpose of the document/enhancement? Select all that apply:**

- [ ] Document a new feature for an upcoming release. Add the appropriate release version label to this issue.
- [x] Information for an existing feature that isn't yet documented.
- [ ] Additional considerations/ reference material for an existing document.

**Problem/feature that requires documentation:** We've had multiple requests for a guide covering custom callbacks. This should probably be a tutorial on implementing a specific type of callback.

Issue ported from guides repo: https://github.com/astronomer/airflow-guides/issues/278

**Are you the right person to review a draft of the document for technical accuracy? If not, who is?**

**Comment by TJaniF** [comment]
Closed via #2181 :)
