### ISSUE TITLE
New tutorial on launching K8s pods in other clusters on Astro

### ISSUE THREAD

**Issue by kentdanas** [astronomer/docs#1281]
**Request type:**

- [x] **New document:**: Add the `docs-content` label to this issue.
- [ ] **Addition to an existing document**: Add the `enhancement` label to this issue.

**What is the purpose of the document/enhancement? Select all that apply:**

- [ ] Document a new feature for an upcoming release. Add the appropriate release version label to this issue.
- [x] Information for an existing feature that isn't yet documented.
- [ ] Additional considerations/ reference material for an existing document.

**Problem/feature that requires documentation:**

Issue ported from guides repo: https://github.com/astronomer/airflow-guides/issues/367

Customers want to launch pods that interact with their resources in their own cloud accounts. The architecture of Astro forces them to use a separate account for their data plane, so this makes these cross-cluster and cross-account pod deployments.

@manmeetkaur wrote this Notion page that is a great start for this guide

https://www.notion.so/astronomerio/Astro-KPO-remote-EKS-Cluster-56ab0e4600c34c7f8973a72394134df6

**Are you the right person to review a draft of the document for technical accuracy? If not, who is?**

**Comment by kentdanas** [comment]
@TJaniF maybe a good Astro use case...

**Comment by TJaniF** [comment]
@kentdanas yeah definitely! I think some of the content is already in the KPO guide? https://docs.astronomer.io/learn/kubepod-operator#example-use-kubernetespodoperator-to-run-a-pod-in-a-separate-cluster 
But it should definitely be its own doc, the KPO guide got quite long 😅

**Comment by kentdanas** [comment]
Now addressed in the Astro KPO doc: https://docs.astronomer.io/astro/kubernetespodoperator
