### ISSUE TITLE
Update Custom XCom Backends guide

### ISSUE THREAD

**Issue by kentdanas** [astronomer/docs#1284]
**Affected Document:** Custom XCom backends Airflow concept guide

**Problem Type (Priority):**

- [x] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [ ] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**

We've had a couple of requests with this one - ported issues from the guides repo:
https://github.com/astronomer/airflow-guides/issues/333
https://github.com/astronomer/airflow-guides/issues/332

From @frankcash:
Since the xcom backend is a plugin for airflow it should added to the plugins directory and not the includes directory. 
Currently the custom [xcom back-end guide](https://www.astronomer.io/guides/custom-xcom-backends) details writing to a live bucket, which is fine for a dev/qa/prod environment.

It would be nice to detail a better way to get this running with all local infrastructure. This can be down with [minio](https://github.com/minio/minio) or [localstack](https://github.com/localstack/localstack)

If not there should be a linkage of utilizing the docker-compose override documents for someone to work it out on their own.

From @MatrixManAtYrService 

I consulted this document for help with implementing custom xcom backends. Specifically, I wanted to have a custom backend available for testing https://github.com/apache/airflow/pull/17405. It didn't work out very well because I couldn't figure out which storage bucket items went with which task ID's.

One thing that's kind of strange about the sample code is that it creates a uuid every time a new value is written to the custom backend. So if you rerun a task 100 times (perhaps via the CLI invocation: airflow tasks run {dag_id} {task_id} {run_id}), you end up with 101 entries in your storage bucket--100 of which have no mapping back to an airflow DAG.

We should consider mentioning that in addition to serialize_value and deserialize_value you can also implement set and clear so that your storage bucket items have the associated dag_id, task_id, etc. in their names. This way, when airflow clears the reference (currently a UUID stored in traditional XCOM) it also clears the associated data in the storage bucket--rather than just leaving it lying around.

Additional Notes:
In case more context is helpful:

I got some help from a community member here: https://github.com/apache/airflow/pull/17405#issuecomment-929962066
The place in my custom XCOM code where I associate the dag_id, etc. with the to-be-serialized value is here: https://github.com/astronomer/qa-scenario-dags/blob/master/include/ycom.py#L126

**Additional Notes:** Should consider turning this one into tutorial format.

**Comment by kentdanas** [comment]
@TJaniF FYI for when you're back - these are the other current issues with the xcom backends guide

**Comment by TJaniF** [comment]
PR #1666 :)

**Comment by kentdanas** [comment]
Resolved by #1666
