### ISSUE TITLE
Contribute to out-of-date dbt <> Airflow guide on Astro CLI in dbt Docs

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#1292]
### Context

It's common for Airflow users to integrate with dbt. A few months ago, dbt published a guide on their own website to integrate dbt and Airflow: https://docs.getdbt.com/guides/orchestration/airflow-and-dbt-cloud/2-setting-up-airflow-and-dbt-cloud

This guide includes instructions to install `astrocloud`, our old CLI that is no longer supported and has been replaced by `astro`.

### Ask

Open up a Pull Request to dbt docs that fixes all references to `astrocloud` and updates language related to the latest Astro CLI. Source code is here: https://github.com/dbt-labs/docs.getdbt.com/tree/current/website/docs/guides/orchestration/airflow-and-dbt-cloud

Work with their team to get this approved in GitHub :)

**Comment by kwcanuck** [comment]
Issue created here: https://github.com/dbt-labs/docs.getdbt.com/issues/2110

**Comment by kwcanuck** [comment]
I submitted the update request as a new issue and followed up with the dbt team. I have not received a response from my inquiry and it does not appear that the update is a priority.  Closing this as there is nothing further that can be done. This can be reopened if it's decided we want to continue monitoring and tracking this issue.
