### ISSUE TITLE
Request for graphQL version handling

### ISSUE THREAD

**Issue by rwalshe** [astronomer/docs#1296]
**Request type:**

- [ ] **New document:**: Add the `docs-content` label to this issue.
- [ X] **Addition to an existing document**: Add the `enhancement` label to this issue.

**What is the purpose of the document/enhancement? Select all that apply:**

- [ ] Document a new feature for an upcoming release. Add the appropriate release version label to this issue.
- [ X] Information for an existing feature that isn't yet documented.
- [ X] Additional considerations/ reference material for an existing document.

**Problem/feature that requires documentation:**

Customers on Astronomer Certified will need to migrate to RunTime.  Those who leverage Houston graphQL for deployments will need to make changes to handle the AC version migrating to the RunTime version.  

This should be highlighted in:
* https://docs.astronomer.io/software/migrate-to-runtime 
Would be also helpful to mention in 
* https://docs.astronomer.io/software/houston-api#access-the-graphql-playground 

**Are you the right person to review a draft of the document for technical accuracy? If not, who is?**

No, possibly Constance?

**Comment by cmarteepants** [comment]
This requires product-level changes before we can document; standard practice is for graphql apis to be versionless. For Houston, only V1 exists. 

cc @aliotta @vishwas-astro

**Comment by paolaperaza** [comment]
@cmarteepants Are you tracking this anywhere on your end? I'd like to get this off our radar docs wise if it's not soon to be actionable... unless you think any immediate term changes to this doc (https://docs.astronomer.io/software/houston-api) are needed?

**Comment by cmarteepants** [comment]
I'm re-reading, and I took @rwalshe's request too literally. 

1. I'm not tracking the request to start versioning the graphql API. We're moving away from graphql, and it's not worth investing in version handling at this time. It also wouldn't help much for this circumstance, as it's technically not a breaking change. Both args are available, and scripts may need to leverage one or the other depending on the circumstance (like bootstrapping an older version of Airflow not available in runtime). 
2. The spirit of the request - documenting that as part of migrating from AC to runtime, people leveraging the API will need to update the parts of their script that are today using the `airflowVersion` arg to now use the `runtimeVersion` arg - is a valid point. 

I agree that we should add something about this to the migrate to runtime doc, give an example of a query or mutation that has both args, and reference the auto-generated docs in the playground for them to evaluate the API calls their scripts are using. It's not worth listing out every query and mutation as there are a lot.

**Comment by rwalshe** [comment]
Adding an additional request to document the steps to migrate from AC to Runtime via graphQL leveraging 'updateDeploymentRuntime'.  It would be good to mention the options around upgrading (AC) then migrating (to Runtime), or migrating (to RunTime) then upgrading (RunTime) from a graphQL perspective.  I expect most customers migrating will upgrade at the same time if newer versions are available.  

`Mutation.updateDeploymentRuntime(
deploymentUuid: Uuid!
desiredRuntimeVersion: String!
): Deployment`
