### ISSUE TITLE
New Doc: "Astronomer Concepts"

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#13]
This should include a definition and context around the following "Astronomer Concepts":

- Astronomer Organization
- Workspace
- Deployment
- Runtime
- "Deploy"
- Local v. on Astronomer Cloud

Information on HOW people should organize code between Workspace/Deployment/User/Team should go in a new RECIPE: "User Management Best Practices".

**Comment by kwcanuck** [comment]
@jwitz is this still something that we want to do? It's been over a year since this issue was opened.

**Comment by jwitz** [comment]
Labeling as "Blocked" until we've finalized RBAC and system component terms.

**Comment by kwcanuck** [comment]
From @paolaperaza:

_I think we can close for now given that we haven’t defined a strategy to go about doing this and it’s not something we will “forget” about. I expect that we create a new issue for it with a new scope and assignee._
