### ISSUE TITLE
Software and Runtime Release Docs do not match

### ISSUE THREAD

**Issue by erdos2n** [astronomer/docs#1303]
**Affected Document:**
Software Runtime Release Docs

**Problem Type (Priority):**

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [ X] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**
https://docs.astronomer.io/software/runtime-release-notes 

should match

https://docs.astronomer.io/astro/runtime-release-notes

**Additional Notes:**
6.0.2 release is missing from the docs page

**Comment by jwitz** [comment]
Thanks for catching this @erdos2n , I updated the Software release notes via this commit: https://github.com/astronomer/docs/commit/f6fdcd5ba08b06d79cbcf59e1434bd271503f4e5
