### ISSUE TITLE
Connections as env var (guide Connections)

### ISSUE THREAD

**Issue by magdagultekin** [astronomer/docs#1313]
**Affected Document:** https://www.astronomer.io/guides/connections/

**Problem Type (Priority):**

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [x] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):** 
In the section [Define Connections via Environment Variables](https://www.astronomer.io/guides/connections/#define-connections-via-environment-variables) it would be worth to mention that if you want to use CLI comment `astro deployment variable update/create/etc`, you need a connection stored like this:

`AIRFLOW_CONN_MYTESTCONN='{"conn_type": "http","host": "swapi.dev/api/","schema": "https"}'`

not this:
```
AIRFLOW_CONN_MYTESTCONN='{
    "conn_type": "http",
    "host": "swapi.dev/api/",
    "schema": "https"
}'
```
Meaning everything needs to be in one line as each line is understood as a new variable.

The issue came from a customer who wasn't able to update his variable because of the JSON example in the guide.

**Comment by paolaperaza** [comment]
@kwcanuck @jwitz Did we ever get to this one?

**Comment by jwitz** [comment]
I thought anything tagged `learn` was for Kenten/ Tamara but happy to get this fixed!

**Comment by kwcanuck** [comment]
@paolaperaza - like @jwitz, I assumed anything identified as `learn` and located within the `Learn` section of the help was the responsibility of Kenten or Tamara.

**Comment by kentdanas** [comment]
It should be me or Tamara - if we're not getting to something quickly enough feel free to assign issues to us at any point!
