### ISSUE TITLE
Remove gcr.io if not used as image repo

### ISSUE THREAD

**Issue by rwalshe** [astronomer/docs#1319]
**Affected Document:**

https://docs.astronomer.io/software/install-airgapped

**Problem Type (Priority):**

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [ X ] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**

>  By default, the Software installation process requires accessing public repositories to download various components:
> 
> Docker images from quay.io/astronomer, docker.io, and gcr.io

remove reference to gcr.io.  Specify quay.io 'or' docker.io; rather than 'and'.  

**Additional Notes:**

Needs confirmed, but I don't believe gcr.io hosts our images.  

https://astronomer.slack.com/archives/CEPE4K68P/p1665100250007999

**Comment by jwitz** [comment]
Hey @rwalshe given that this is a straightforward change that was confirmed on Slack, I went ahead and hotfixed it directly to docs: https://github.com/astronomer/docs/commit/08b356db562b925870c3cc708eb55d8b7ad36019

Thank you!
