### ISSUE TITLE
Fix the wording in Get Started with Airflow tutorial

### ISSUE THREAD

**Issue by magdagultekin** [astronomer/docs#1325]
**Affected Document:** https://docs.astronomer.io/tutorials/get-started-with-airflow

**Problem Type (Priority):**

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [x] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**

In the section `Step 6: Write a new DAG` point 5 is not clear (there is just one task but the description mentions the second one). 

![image](https://user-images.githubusercontent.com/97064715/195066085-43ac6e88-766a-4e1b-9eab-a8467d3af6a1.png)

**Comment by jwitz** [comment]
Thank you for spotting this @magdagultekin ! This seemed fairly straightforward, so I went ahead an hotfixed it to the main branch: https://github.com/astronomer/docs/commit/e7c409a08950aa359ea7234952fbeed8b68c55fd
