### ISSUE TITLE
Re-write "Customize your Image" Doc

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#135]
@paolaperaza commented on [Tue Jul 07 2020](https://github.com/astronomer/issues/issues/1499)

We need to re-write our current ["Customize your Image" doc](https://www.astronomer.io/docs/customizing-your-image/) to:

- [x] Fix all references to old, non-AC images
- [x] Add mention of Debian Images
- [x] Simplify Env Vars section and link out to [new "Environment Variables" doc](https://www.astronomer.io/docs/environment-variables/)
- [x] Clean up "Build from Private Repo Section"
- [x] Add section on how to mount aws creds into a CLI image ([Slack convo](https://astronomerteam.slack.com/archives/CLRKTKHGU/p1594226960060400))

**Note:** In "Docs 2.0", I added all content from the "Build from a Private Repo" doc and merged it into this "Customize your Image" doc, as the content is overlapping and short. Commit here: https://github.com/astronomer/astro-docs/pull/3/commits/f8cfedf9a275d289cc71df8653119ffebaa3d4f2

Reminder: Add redirect before closing this issue

**Comment by paolaperaza** [comment]
@jwitz Just re-visited this GH issue and realized we've covered all of these changes in the current version of our "Customize your Image" doc.

More improvements can always be made, but I think we've checked off the boxes in the scope of this issue and it's no longer actionable 😊  Closing.
