### ISSUE TITLE
Add guidance on multiple Deployments

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#1357]
### Context

Feedback from @ReadytoRocc [in Slack](https://astronomer.slack.com/archives/C01UA03TPV1/p1665506473131249) that I think is very fair:

> Hey Team, do we have any docs/slides on why having multiple Airflow instances in an organization provides benefit? e.g.
> Isolation of Teams and Processes
> Reducing interaction of independent processes e.g. 1 team pushes an error which interrupts another team.
> Ability to create instances for hot-fixes, feature branches, or trying new versions.
> If not I plan on making some, but wanted to see if this exists already. Thanks!

### Ask

In: https://docs.astronomer.io/astro/create-deployment

Let's add a more explicit section somewhere in this doc about how to think about creating multiple Deployments that incorporates some of Rocco's feedback. Will require some internal discussion, but creating a GH issue for now a placeholder that can become actionable once we better define scope.

**Comment by kwcanuck** [comment]
@paolaperaza is it time to revisit or close this issue?

**Comment by kwcanuck** [comment]
Unsuccessful attempts to solicit the information necessary to move this issue forward were made November 14, 2022, November 30, 2022, January 4, 2023 and January 9, 2023. Adding the blocked label today.

**Comment by erdos2n** [comment]
@paolaperaza , @kwcanuck has anyone taken this yet? I think we could easily start this section by discussing the benefits of using `dev`, `staging` and `prod` deployments, especially when testing an upgraded version of `AP-Airflow` or `Runtime`. We can always bake the multiple workspace logic in later.

**Comment by jwitz** [comment]
Closing this out because we've covered multi-deployment usage through a number of different avenues now, including https://docs.astronomer.io/astro/best-practices/cross-deployment-dependencies, https://docs.astronomer.io/astro/best-practices/connections-branch-deploys,and   https://docs.astronomer.io/astro/deploy-github-integration
