### ISSUE TITLE
Create "Comparing OSS Airflow to Astronomer" doc

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#136]
**Request type:**

- [X] **New document:**: Add the `docs-content` label to this issue.
- [ ] **Addition to an existing document**: Add the `enhancement` label to this issue.

**What is the purpose of the document/enhancement? Select all that apply:**

- [ ] Document a new feature for an upcoming release. Add the appropriate release version label to this issue.
- [ ] Information for an existing feature that isn't yet documented.
- [X] Additional considerations/ reference material

**Problem/feature that requires documentation:** 

Let's have a reference doc that explains the differences between OSS Airflow and Astronomer. This can live in docs for now, but later on it would be nice to have a unique page like [Databricks has](https://databricks.com/spark/comparing-databricks-to-apache-spark).

**Comment by kwcanuck** [comment]
@jwitz how can we move forward with this? Is there a SME who can provide the necessary information? Would this be better implemented by marketing?

**Comment by jwitz** [comment]
Let's close this out for now. We're nowhere near close to getting this resolved soon. We should focus on migration tutorials instead of references like these.
