### ISSUE TITLE
Improve description metadata for docs

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#1365]
**Affected Document:** Many

**Problem Type (Priority):**

SEO improvement

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):** Harjindra has given us a few guidelines for writing description text that Google will use as snippets:

1. Length of the description - for marketing site we generally keep them between 160-180 chrs and that's what we recommend.
2. Dynamic meta tags - This is something search engines don't like although they haven't explicitly said that we shouldn't use dynamic metas but you can check various threads on Internet, people generally face indexing issues when they use dynamic metas. On the marketing site, we do it manually. What I would suggest here is - For the top 25 docs and guides, that generally get the most traffic, please create the meta tags manually. And for others, we can use dynamic tags.

Let's rewrite our descriptions and use manual meta tags where necessary to make sure Google always shows the best text in its search. There's a decent amount to cover, so we could split this work between a few people. 

Ignore the most popular _Learn docs_ since we already have some drafts for those descriptions. For each popular doc, we need to:

1. Remove the description frontmatter from the doc.

2. Add the following HTML to the start of the document:

```
<head>
  <meta name="description" content="The new and improved description">
  <meta name="og:description" content="The new and improved description">
</head>
```

**Comment by kwcanuck** [comment]
Branch for this effort: metadata-updates
