### ISSUE TITLE
🎄 Add example timetable for Holidays

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#1366]
Doc: https://docs.astronomer.io/learn/scheduling-in-airflow#timetables
Forum post: https://forum.astronomer.io/t/holidays-schedule-using-timetables/2213/3

As the holiday season nears, many customers may want to re-schedule their DAGs to run on a schedule that's in line with federal holidays. We should add a section in our existing DAG scheduling and timetable doc with a simple example for holidays.

**Comment by kwcanuck** [comment]
@kentdanas I contacted @paolaperaza about this issue and she indicated that it could be closed. Let me know if you want to take care of it, or want me to do it. Thanks!
