### ISSUE TITLE
Specific information about lineage we collect across systems

### ISSUE THREAD

**Issue by virajmparekh** [astronomer/docs#1409]
**Request type:**

- [ ] **New document:** Add the `docs-content` label to this issue.
- [x] **Addition to an existing document**: Add the `enhancement` label to this issue.

**What is the purpose of the document/enhancement? Select all that apply:**

- [ ] Document a new feature for an upcoming release. Add the appropriate release version label to this issue.
- [x] Information for an existing feature that isn't yet documented.
- [x] Additional considerations/ reference material for an existing document.

**Problem/feature that requires documentation:**
We should have more specific information on what sort of lineage information we collect across systems. We collect different metrics around data quality, column lineage, table lineage, etc. as part of lineage, but it's not clear what exactly we collect for which system. 

I don't know where the best place for this would be, as it's both OSS and commercially focused, but maybe somewhere in the `Data Lineage` section that links out to the appropriate docs in the `Learn` tab? Don't have a strong opinion, but just think it's important to differentiate 

**Are you the right person to review a draft of the document for technical accuracy? If not, who is?**
Julien, Ross, Harel, Benji, someone from Carlos's team

**Comment by kentdanas** [comment]
@jwitz given that this is somewhat impacted by your PR to consolidate some docs - I'm wondering if we should split that OpenLineage guide that's currently in `integrations/` and have it be a Concept doc that includes definitions and all the high level overview (including what Viraj is suggesting here), and then a separate tutorial with step by step instructions on running OL + Marquez locally. And then I guess any updates to our Astro docs to talk about the commercial side. Thoughts?

**Comment by denimalpaca** [comment]
I think the OL team can speak to this better, but fundamentally I don't think different facets are collected from different systems. It's all more or less the same schema, data quality, and upstream/downstream info.
