### ISSUE TITLE
Add Instructions for next LTS Upgrade to Enterprise Upgrade Guide

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#144]
@paolaperaza commented on [Tue Apr 21 2020](https://github.com/astronomer/issues/issues/1198)

As we continue to help customers through Enterprise Upgrades to v0.13 and beyond + work towards making this a process customers can go through themselves, we need to update our existing ["Enterprise Upgrade Guide"](https://www.astronomer.io/docs/ee-upgrade-guide/) with our latest guidelines.

This could encompass:

- Pre-requisites
- High-level overview of the process and effect on the platform
     - "Will there be downtime? What is the effect of upgrading on my Airflow Deployments?"
- Step by step instructions
- Reference to any scripts we've written that our customers could use for any part of the process
- Link to rollback plan (if possible)

@sjmiller609 I know you've already been working on this and am sure you have more thoughts on what this should look like, but I wanted to make sure there was an issue for it in GH for whenever we're ready to put this together. Happy to help as much as I can - let me know what you think.

cc: @vishwas-astro @ianstanton 

---

@vishwas-astro commented on [Sun Jun 14 2020](https://github.com/astronomer/issues/issues/1198#issuecomment-643728400)

@ianstanton @sjmiller609 Wanted to see if either of you had thoughts on when we would be ready to provide such an upgrade guide to users. 

---

@paolaperaza commented on [Sun Jun 14 2020](https://github.com/astronomer/issues/issues/1198#issuecomment-643775942)

@vishwas-astro Feels like we should we aim to get this done alongside our new  "Validated Designs" and as soon as we're ready to open the door back up to Enterprise upgrades for v0.15 and beyond.

@sjmiller609 @ianstanton For the v0.15, 0.16 and 0.17 upgrades already scheduled (RMN, Honeywell etc.) - will there be any self-service work we could document to get a foundation started on this one?

I'd say customers are expecting the upgrade process to be as self-service as it can be. We got this note from Rimeto this week: 

> Can you advice what astro version is available to us for upgrade? We are currently on 0.10.3. Where are docs for that upgrade?

---

@paolaperaza commented on [Wed Nov 11 2020](https://github.com/astronomer/issues/issues/1198#issuecomment-725606807)

Draft PR from @sjmiller609: https://github.com/astronomer/astronomer/pull/881

**Comment by sjmiller609** [comment]
Hi @jwitz I plan to move this out of draft soon, hopefully today. I will tidy up this guide with any changes to process.

**Comment by sjmiller609** [comment]
The instructions are in this PR, which should be getting in soon https://github.com/astronomer/astronomer/pull/881 . I figure we will fill out the instructions more during QA
