### ISSUE TITLE
Add Snowflake section to "Enable data lineage" doc (& other updates)

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#1466]
### Context

In discussing with @denimalpaca and @virajmparekh about an upcoming workshop with a customer about Open Lineage, Airflow/Astro, and Snowflake -- we recognized that:

- There is nothing about Snowflake and OL in our current docs
- There is no information about what lineage data we collect with the Snowflake Operator
- Our integration guides seem hidden in our overall doc, when it should be the most prominent

### Ask

- [ ] Review the introduction and overview to `Enable data lineage`
- [ ] Consider shrinking the data lineage architecture image. It takes up too much page real estate.
- [ ] Move `Retrieve your OpenLineage API Key` to an H2
- [ ] Consider moving the integration guides OUT of tabs and into H2s so that they're easier to see and link to
- [ ] Remove the `Astronomer` section/tab, as it's only there for older versions of Astro Runtime
- [ ] Add more links to OL docs as needed
- [ ] Create a new `Snowflake` tab or section based on @denimalpaca's doc (https://www.notion.so/astronomerio/Lineage-Collection-in-Snowflake-8ea974cbff1540f4b315367450f80b6b)
- [ ] Include a matrix of open lineage data we collect with Airflow/Astro (from Benji also)

@kwcanuck @jwitz I think we'll need my/other folks' guidance here so hold up before getting started on this issue

**Comment by jwitz** [comment]
Based on discussions: 

- Remove "Architecture" info / tighten it up to be more feature-focused
- Add Snowflake tab to explain that experience 
- Possibly break tabs out into separate information
