### ISSUE TITLE
Fix `SkipToContent` appearing in URLs

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#1472]
**Affected Document:** All

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**

Ever since we upgraded to Docusaurus 2.2.0, the site sometimes appends `skipToContent` to the end of URLs. It seems to happen the most with links accessed from the search bar. I have a hunch it's related to this PR: https://github.com/facebook/docusaurus/pull/8204

We should make sure our custom components are able to handle this change and not show `skipToContent` unless it's needed

**Comment by katiebrady-astro** [comment]
Hey Jake, finally have a PR open to fix this issue!
