### ISSUE TITLE
Create toggleable new feature banner for home pages

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#1486]
We should have a CSS element that's similar to `AstroCard` but can be hidden by a user when they click an `x` button. Instead of having additional large buttons, it would only have plain text and hyperlinked text. 

![Screen Shot 2022-11-15 at 3 04 55 PM](https://user-images.githubusercontent.com/74574233/201954880-0e477ade-589c-49dc-b2e6-59ad7f023b32.png)

This would be used by the docs team to highlight a significant new change and would not always be active on the site.

**Comment by katiebrady-astro** [comment]
Hey @paolaperaza and @jwitz, sure thing! I'll get a version of the one we use on the marketing site on a branch this week for the docs site 🙂

**Comment by katiebrady-astro** [comment]
Hey @jwitz and @paolaperaza! Finally have a PR and preview ready for adding this feature to the site! Currently matches the style we're using on the marketing site but let me know if we want to tweak any of the colors/style.

The banner closes when clicking either the orange CTA button or the `x` close button. It will stay closed until the next user session, but we can increase the time out if we'd prefer.

<img width="1214" alt="image" src="https://github.com/astronomer/docs/assets/96535736/aef362b9-d2e1-4332-be20-1f93265d3b6a">

**Comment by jwitz** [comment]
@katiebrady-astro I definitely like that banner for community events announcements and think we should keep it for that, but I would say it's too noticeable/ high level for a feature banner. 

The reason why I used the `AstroCard` as inspiration is that you can put it on individual pages, so that we could have a card in the Astro CLI tab overview that's different than the one in the Astro tab overview. My guess is that some of the features we'd highlight would only apply to users in a single tab, so having that flexibility is a must. WDYT @paolaperaza since you suggested top-level banner fold? (sorry should have suggested this before you put all the work in!)
