### ISSUE TITLE
Software: New Git-Sync Architecture

### ISSUE THREAD

**Issue by cmarteepants** [astronomer/docs#1490]
**Request type:**

- [ ] **New document:** Add the `docs-content` label to this issue.
- [x] **Addition to an existing document**: Add the `enhancement` label to this issue.

**What is the purpose of the document/enhancement? Select all that apply:**

- [ ] Document a new feature for an upcoming release. Add the appropriate release version label to this issue.
- [ ] Information for an existing feature that isn't yet documented.
- [x] Additional considerations/ reference material for an existing document.

**Problem/feature that requires documentation:**
We have implemented a better architecture for git-sync for 0.31. We need to update this [doc](https://docs.astronomer.io/software/deploy-git-sync) and remove the experimental feature. We can also include a quick blurb about the new architecture if that makes sense. I don't know if there are configuration changes.

Main issues:
- https://github.com/astronomer/issues/issues/4059
- https://github.com/astronomer/issues/issues/3980

@danielhoherd and @bote795 are the subject matter experts.

**Are you the right person to review a draft of the document for technical accuracy? If not, who is?**

**Comment by bote795** [comment]
and @ajayy004 as he implemented the new changes
