### ISSUE TITLE
Add recommendations on `/include` folder

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#1496]
### Context

With the new `astro deploy --dags` feature, the `/include` folder in the Astro project directory is not deployed with DAGs and is instead built into the image by default.

For users who only have Python functions or other tidbits they need in their DAGs, they often don't _have_ to be in the image and could really just be built next to their DAGs. This would make them more likely to use `astro deploy --dags`.

We should make this option clear, and go as far as recommending that users move `/include` files from a top-level directory to a sub-directory in `/dags` now that Airflow 2.4 supports sub-directories and can be parsed by the scheduler.

 @ReadytoRocc has similarly recommended that a lot of customers do this instead.

### Doc Asks

- In [Develop a Project](https://docs.astronomer.io/astro/develop-project), add a section on the `/include` folder that states:
   - What kind of files are typically included here?
   - Tell users that these files are built into the base image by default but that Astronomer recommends adding them to the `DAGs` directory in most cases
   - Confirm that Airflow 2.4 is needed for this

Let's make sure to work with @ReadytoRocc + @jlaneve on this PR and get as crisp as possible on "what customers actually do"

**Comment by ReadytoRocc** [comment]
Hey @paolaperaza, one thing I think we should highlight is that this should be a **new** folder under `dags`, rather than just moving the `include` folder under DAGs. This is because `include` is mounted to the Airflow containers created by `astro dev start`, which provides functionality when developing locally with the CLI.

**Comment by paolaperaza** [comment]
@kwcanuck This can be a follow-on to your earlier PR, but I'm actually gonna open this back up based on ongoing feedback from @ReadytoRocc -- 

- This is what is suggested in the OSS docs: https://airflow.apache.org/docs/apache-airflow/2.4.3/modules_management.html
- Having this structure allows DAG/user code to be deployed without an image restart.
- Confirm in docs that the Triggerer does not restart on a dags only deploy
- Address Rocco's comment ^above
- Add an example `dags` directory and move this information out of `tip` as it applies to everyone

@ReadytoRocc Are you open to just opening a PR that includes everything you think we need to tell users?
