### ISSUE TITLE
Update GKE install guide

### ISSUE THREAD

**Issue by vparekh94** [astronomer/docs#15]
The GKE install guide needs to be updated to be a little more natural to someone who is not super familiar with Kubernetes and GKE

**Comment by ianstanton** [comment]
Working here: https://github.com/astronomer/docs/blob/develop-gke-install/docs/ee-installation-gke.md

**Comment by vparekh94** [comment]
Love where we are at so far - definitely think this is a lot cleaner than before. Some notes:

- We should explain why each step is necessary before moving onto the next step so the user gets an idea of what they are installing. This doesn't have to be an extensive explanation, but just a little blurb:

e.g. for  `Create a Static IP Address`, something like "This will be the IP address that....."

Similar blurbs should be there for the Create a Namespace section, the tiller part, etc.

- We should definitely make SMTP creds a pre-req for the install - the email invites won't work without them.

- There should be a section that goes into different installation methods we can do and when we recommend  each type (e.g. single namespace mode, no EFK stack mode, etc.).

**Comment by schnie** [comment]
Was randomly thinking about those things too @vparekh94. I think doing a better job of detailing why each particular step is useful/required will go a long way towards customers being able to get set up on their own.

**Comment by ianstanton** [comment]
- [ ] 'Are you admin enough' section
- [ ] Details for each section (what this is / why this is important)
- [ ] macOS + Linux commands when they differ
- [ ] Note about running `astronomer-tls` create command as `sudo`
- [ ] 'Additional info' links to resources like kubernetes docs, helm docs, etc.
- [ ] Describe different configuration options like single namespace, toggle logging features, auth options, etc.
- [ ] Note about tiller service account in single namespace mode
