### ISSUE TITLE
Update static asset links from HTML to Markdowm

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#151]
When we started using Docusaurus, static embeds worked much better with HTML than with Markdown. Now, they seem to be about the same. We should update our HTML image links to Markdown image links

**Comment by kwcanuck** [comment]
@jwitz to confirm, to resolve this issue would require the following actions:

- Moving all images currently stored in other repositories/folders to /astronomer/docs/tree/main/static/img/docs

- Locating image references with the following path https://assets2.astronomer.io/main/docs/ee or similar and updating them to the new path (img src="/img/docs/...) and image syntax

I've done a quick search and there are approximately 448 image paths in Astro that require updating and 59 in Software. 

Is my understanding of the issue correct? Is this still an issue that you want to resolve?

**Comment by kwcanuck** [comment]
Thanks for the clarification @jwitz. I'm glad I asked! :)

It appears that there are 23 instances of <div class="text--center"> in Astro and 2 in software. If you prefer I fix these items, just reassign this issue to me. Otherwise, I'll leave it in your capable hands!
