### ISSUE TITLE
Add Ping ID as a supported IdP

### ISSUE THREAD

**Issue by chomipi88** [astronomer/docs#1526]
**Request type:**

- [ ] **New document:** Add the `docs-content` label to this issue.
- [x] **Addition to an existing document**: Add the `enhancement` label to this issue.

**What is the purpose of the document/enhancement? Select all that apply:**

- [ ] Document a new feature for an upcoming release. Add the appropriate release version label to this issue.
- [x] Information for an existing feature that isn't yet documented.
- [ ] Additional considerations/ reference material for an existing document.

**Problem/feature that requires documentation:**

https://www.notion.so/astronomerio/How-to-Enable-Ping-Identity-SAML-Authentication-cd0b29474fce4e0e8d9d069f22fceade

**Are you the right person to review a draft of the document for technical accuracy? If not, who is?**

**Comment by kwcanuck** [comment]
From @chomipi88 2022-11-28:

_Please continue holding. My front end resource is out on sick leave so this has taken a back seat for now._
