### ISSUE TITLE
Documentation for connecting to Route53 resolver service

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#1527]
**Request type:**

- [ ] **New document:** Add the `docs-content` label to this issue.
- [X] **Addition to an existing document**: Add the `enhancement` label to this issue.

**What is the purpose of the document/enhancement? Select all that apply:**

- [ ] Document a new feature for an upcoming release. Add the appropriate release version label to this issue.
- [C] Information for an existing feature that isn't yet documented.
- [ ] Additional considerations/ reference material for an existing document.

**Problem/feature that requires documentation:**

Original thread: https://astronomer.slack.com/archives/C015V2JFKT5/p1668718429873769

Let's have a "Contact Astronomer support" style setup in https://docs.astronomer.io/astro/connect-aws for setting up Route53. @stuart23 should review

**Comment by paolaperaza** [comment]
For reference, the support team's runbook on this: https://support.astronomer.io/hc/en-us/articles/9310556041875

We should consider:
- Adding a section dedicated to Resolver 53 with brief description
- Asking customers to provide the following, with links to docs:
      - CResolver rule in AWS Resource Access Manager
      - Astro AWS account ID
      - Resolver rule ID (e.g. rslvr-rr-10bd960d8a61456ba).
