### ISSUE TITLE
Enhance IAM Integration Document

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#156]
@ianstanton commented on [Mon Sep 21 2020](https://github.com/astronomer/issues/issues/1834)

- The IAM Role Integration doc has missing steps that customers are starting to notice
- Needs to be rewritten to clearly differentiate GCP and AWS specific steps
- Needs to be simplified
- https://www.astronomer.io/docs/enterprise/v0.16/customize-airflow/integrate-iam/

---

@ianstanton commented on [Mon Nov 16 2020](https://github.com/astronomer/issues/issues/1834#issuecomment-728202601)

https://github.com/astronomer/docs/pull/53 solves this for AWS. We have an internal doc for GCP that should be polished up and released on our site https://www.notion.so/astronomerio/GCP-IAM-Role-Integration-c6ce2e82eb8a4ffa8cedd205a4bc8599

**Comment by paolaperaza** [comment]
@jwitz I think this issue was addressed by @ianstanton in this PR: https://github.com/astronomer/docs/pull/53

Closing this out.
