### ISSUE TITLE
Fix Enterprise/version tab behavior and design

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#157]
We need to fix a few key aspects of the top navbar before we can ship our Enterprise docs migration, mainly: 

- [x] The version tab is bumping up close to the darkmode switch
- [ ] The version tab is visible when you're in the Cloud docset. It should always be hidden when not in Enterprise
- [x] "Docs" looks like it's the same type of link as "Cloud" and "Enterprise", even though it's the title of the site
- [ ] The "Cloud" tab is always highlighted blue regardless of what tab you're on

I'd recommend pulling the branch in this PR and working in there: https://github.com/astronomer/cloud-docs/pull/156 

This is the most up-to-date branch content and structure-wise. Extra information about the dropdown menu object can be found here: https://docusaurus.io/docs/api/themes/configuration#navbar-docs-version-dropdown

**Comment by brittanyleigh** [comment]
@jwitz 

> The version tab is visible when you're in the Cloud docset. It should always be hidden when not in Enterprise

I'm not sure if this is possible (it definitely should be, imo), looking at their docs on [versioned and unversioned]( https://docusaurus.io/docs/docs-multi-instance#versioned-and-unversioned-doc), they mention the example that on the docusaurus site -- the /docs/* section is versioned and the /community/* section is unversioned. So looking at the /community section on their site, I still see the versions dropdown... doesn't seem like it's ever hidden, regardless of whether or not it applies to the section you're in. 

> The "Cloud" tab is always highlighted blue regardless of what tab you're on

Could we switch the path for cloud to `/cloud` instead of `/`? I believe this is happening because the path for cloud is`/`, so it is technically always active. If we set the site up similar to our current docs with `/cloud` and `/enterprise` paths and redirect `/` to `/cloud`, it would solve this issue.

**Comment by jwitz** [comment]
@brittanyleigh Yeah I noticed that on their site,  I guess they haven't considered that because "Community" is still largely related to the top version as opposed to a separately versioned product. A placeholder idea would be scrapping the dropdown and giving instructions in docs about how to access the differently versioned docs via editing the URL. It's not the cleanest but it's more clean than having the wrong version number on Cloud. And in the meantime I can see if there's anything they can fix/ patch in Docusaurus so that we don't have to implement custom logic for this.

On the second point, that's cool with me! I'll update that tomorrow and see if it fixes the issue.

**Comment by brittanyleigh** [comment]
@jwitz Ok, I just had an idea! I kind of made our own version dropdown. I removed the "real" version dropdown and turned the original Enterprise link into a normal dropdown with links to each version. I went ahead and pushed it up so you can pull it down to see it.

![Screen Shot 2021-11-11 at 1 53 46 PM](https://user-images.githubusercontent.com/15950548/141353096-b05ecd24-b696-4b1a-8272-f4698ef6f6bc.png)

**Comment by ryanahamilton** [comment]
Cool idea @brittanyleigh! This addresses one concern I was going to mention where I don't think we should be displaying the version selector unless the User is _in_ Enterprise.

Wondering if the buttons and dropdown contents could/should be something like the following?

-----

[**Cloud**] [**Enterprise** (0.25)]
 - 0.25 [CURRENT]
 - 0.24
 - 0.23

**Comment by brittanyleigh** [comment]
@jwitz Totally! That's all setup in the [docusaurus.config file (lines 55 - 73)](https://github.com/astronomer/cloud-docs/blob/enterprise-v4/docusaurus.config.js#L55-L73), I'll leave that to you - label them however you please. =)

**Comment by jwitz** [comment]
@brittanyleigh New dropdown looks awesome, I think we're close on this!! I pushed some more changes up to the PR, there's one bug that I still can't fix: the base URL of the website (docs.astronomer.io) is still an empty page despite adding a `slug` to the Cloud Overview doc. I think this is due to the specific pathing we use for each plugin - the base URL is in sort of a "nowhere" zone.

Would it make sense for us to configure a redirect from `docs.astronomer.io` to `docs.astronomer.io/cloud`?

**Comment by brittanyleigh** [comment]
@jwitz Alright, set up a redirect and it should be all set now! [https://deploy-preview-156--gallant-neumann-56599d.netlify.app/](https://deploy-preview-156--gallant-neumann-56599d.netlify.app/) -- this should redirect to /cloud. 👍🏻

**Comment by paolaperaza** [comment]
Enterprise navigation menu is _shipped_! Closing this out - we can iterate and evolve this over time.
