### ISSUE TITLE
Module Analysis - Getting Started - Local Development

### ISSUE THREAD

**Issue by kwcanuck** [astronomer/docs#1572]
Module Link:  https://www.notion.so/astronomerio/Modules-Knowledge-Base-395fc8c6c2e74faaa859c326369eeb50#c28916f5b71e48f1b5b47608f71c4513

### Recommended changes

The following are the recommended changes for _Getting Started - Local Development_:

- The existing _Install the Astro CLI_ link should direct users to _[Install the Astro CLI](https://docs.astronomer.io/astro/cli/install-cli)_ and not _[Configure the Astro CLI](https://docs.astronomer.io/astro/cli/configure-cli#install-the-cli)_

- The instructions for running `astro dev pytest` and `astro dev parse` should direct users to the [`astro dev pytest` documentation](https://docs.astronomer.io/astro/cli/astro-dev-pytest#docusaurus_skipToContent_fallback) and [`astro dev parse` documentation](https://docs.astronomer.io/astro/cli/astro-dev-parse#docusaurus_skipToContent_fallback) and not _[Test and troubleshoot locally](https://docs.astronomer.io/astro/test-and-troubleshoot-locally)_

- The existing text _have a local Airflow running with `astro dev start`_ should be updated to _have a local Airflow project running with `astro dev start`_

- _Airflow_ and _Apache Airflow_ are used interchangeably. One term should be used consistently.

- The _Extras/Reference_ heading should be updated to _Related documentation_  and the list should be limited to a list of doc titles without introductory text.

- The text should be rewritten so it meets the minimum Astronomer stylistic standards and uses a consistent voice

### Content to replicate

None

**Comment by lzdanski** [comment]
We've made several structural changes to both the getting started and local development docs since issue was opened. Closing issue.
