### ISSUE TITLE
Module Analysis - Getting Started - Astronomer Cloud

### ISSUE THREAD

**Issue by kwcanuck** [astronomer/docs#1573]
Module Link: https://www.notion.so/astronomerio/Modules-Knowledge-Base-395fc8c6c2e74faaa859c326369eeb50#f3acac3bef544e86a1a6dec657b792fe

### Recommended changes

The following are the recommended changes for Getting Started - Astronomer Cloud:

- The existing _Have the Astro CLI installed_ link should direct users to [Install the Astro CLI](https://docs.astronomer.io/astro/cli/install-cli) and not [Configure the Astro CLI](https://docs.astronomer.io/astro/cli/configure-cli#install-the-cli)

- The existing text _Successfully log in to [cloud.astronomer.io](http://cloud.astronomer.io/)_ should point to _[Log in to Astro](https://docs.astronomer.io/astro/log-in-to-astro#docusaurus_skipToContent_fallback)_

- The existing _Review the [Astro 101](https://academy.astronomer.io/page/the-modules#products_astro) education modules_ link should be updated to _Review the [Astro education modules](https://academy.astronomer.io/page/the-modules#products_astro)_ 

- The text should be rewritten so it meets the minimum Astronomer stylistic standards and uses a consistent voice

### Content to replicate

None

**Comment by lzdanski** [comment]
Architectural changes to the docs have been made since this issue was opened. closing issue.
