### ISSUE TITLE
(error/fyi): Documentation issue related to docker build command - bitbucket.

### ISSUE THREAD

**Issue by sbandepalli** [astronomer/docs#160]
**Affected Document:**
https://www.astronomer.io/docs/cloud/stable/deploy/ci-cd#bitbucket

**Problem Type (Priority):**

Misleading

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**

**Additional Notes:**
Line 11. - docker build -t registry.gcp0001.us-east4.astronomer.io/infrared-photon-7780/airflow:ci-${BITBUCKET_BUILD_NUMBER} 

The above line should end with a period.

**Comment by paolaperaza** [comment]
This hotfix commit closed this out! https://github.com/astronomer/docs/commit/1d888fe8d8534050fdb71afb2b2b75c1b5106845

Verified that our Bitbucket example was the only one missing a ` .` to path in the `docker build` step.
