### ISSUE TITLE
Astro CLI Clarification between Cloud and Software

### ISSUE THREAD

**Issue by erdos2n** [astronomer/docs#1606]
**Affected Document:**
[https://docs.astronomer.io/astro/cli/astro-workspace?tab=astro](https://docs.astronomer.io/astro/cli/astro-workspace?tab=astro)

**Problem Type (Priority):**

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [ X] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**
After a customer call, the customer suggested adding some sort of blurb to highlight that Astro does not have capabilities to use the same commands as Software.

Astro can use `astro workspace list` or `astro workspace switch`, but nothing else. Customer thought there were 2 different CLIs: Astro and Software. 

Some information can be helpful to tell customers there is one CLI but command availability will vary depending on Astro Product and permissions.

**Additional Notes:**

**Comment by kwcanuck** [comment]
@jwitz and @paolaperaza what are your thoughts on this request? We do currently provide clarification statements. For example:

![image](https://user-images.githubusercontent.com/104205257/206722748-d83e1d7d-7da9-4140-aa87-50c62f448e82.png)

![image](https://user-images.githubusercontent.com/104205257/206723146-fd0a9441-66b0-48f8-bde7-ba460d8725b3.png)

Are additional statements clarifying the differences between Astro and Software necessary? I don't think they are, but thought it best to seek consensus.
