### ISSUE TITLE
Guidance on Airflow Connection sharing

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#1610]
### Context

It's very common for customers to ask, "How do I export my local connections to Astro?" or "How do I share connections between Deployments"? From a customer [in slack](https://astronomer.slack.com/archives/C02FUCP3ZHR/p1670598441489529):

> I'm setting up a library of mock Connections for testing airflow dags.  Is there a way to take the output of astro dev object export -c and import those connections into a staging astro deployment?
> 
> I'm thinking no, and I bet I wouldn't want astro to be able to do that easily come to think of it

There isn't a single way to do this, but we've added new functionality in the Astro CLI that gives users some options. We ultimately recommend a secret backend for production deployments.

### Ask

[Note: This is a placeholder GH issue. I'm not sure yet how or where we want to solve for this/consolidate the content]

Take into account the following features on Astro:

- `astro dev object import/export` with `--env-export`
- `astro deployment inspect`
- `astro deployment variable create` with `--load` and `--list` flags
- Env Vars on Astro
- Secret backend support
- Deployments as code (incoming)

These are all documented individually, but there's no narrative around how to manage connections more easily today.

**Comment by manmeetkaur** [comment]
@paolaperaza we have created a Forum post for exporting the connections and this [PR](https://github.com/astronomer/docs/pull/2219), is in progress that addresses these concerns. Do you think there is another sub-item coming out of this ? Asking because I was about to create a new Issue for our "making Connections easier" work.
