### ISSUE TITLE
Premium Feature: Cluster / Workspace Mapping

### ISSUE THREAD

**Issue by chomipi88** [astronomer/docs#1629]
**Request type:**

- [x] **New document:** Add the `docs-content` label to this issue.
- [ ] **Addition to an existing document**: Add the `enhancement` label to this issue.

**What is the purpose of the document/enhancement? Select all that apply:**

- [x] Document a new feature for an upcoming release. Add the appropriate release version label to this issue.
- [ ] Information for an existing feature that isn't yet documented.
- [ ] Additional considerations/ reference material for an existing document.

**Problem/feature that requires documentation:**

We are introducing a new feature to allow Premium tier customers to map clusters to workspaces. Only mapped workspaces can create Deployments on the associated cluster(s).

Engineering design doc: https://www.notion.so/astronomerio/Map-Clusters-to-Workspaces-fba1c82de5e647f5900fe1a1f9612dfc

Live Preview environment: https://pr7142.cloud.astronomer-dev.io/
Invites sent to @kwcanuck and @jwitz 

Standard Tier UX for comparison: https://docs.google.com/document/d/1mzJ3oOy7JDDOdQsHDOPF6XcfZnH9CV4E6e_aw_qK2us/edit

**Are you the right person to review a draft of the document for technical accuracy? If not, who is?**

**Comment by kwcanuck** [comment]
@chomipi88 I didn't receive an invitation to a sample organization.

**Comment by chomipi88** [comment]
@jwitz @kwcanuck maybe invites dont work from PR Preview envs. Anyway... you should be able to login with Google at the below url.

https://pr7142.cloud.astronomer-dev.io/

**Comment by jwitz** [comment]
Got it, was able to get in and see the feature

**Comment by jwitz** [comment]
Didn't realize this issue was still open, this content was published a while ago: https://docs.astronomer.io/astro/modify-cluster#authorize-workspaces-to-a-cluster
