### ISSUE TITLE
error Snowflake Learn page DAG updates

### ISSUE THREAD

**Issue by mdray** [astronomer/docs#1633]
**Affected Document:**
Orchestrate Snowflake Queries with Airflow

**Problem Type (Priority):**

- [x] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [ ] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**

https://docs.astronomer.io/learn/airflow-snowflake

Multiple import issues trying to load example DAG code. Lines 10 and 11 should be:
from astronomer.providers.snowflake.operators.snowflake import    @@@SnowflakeOperatorAsync
from airflow.operators.sql import SQLColumnCheckOperator, SQLTableCheckOperator

There is another issue with `from include.libs.schema_reg.base_schema_transforms import snowflake_load_column_string` that I've not had a chance to look into. 

**Additional Notes:**
@kentdanas

**Comment by kentdanas** [comment]
Resolved by #1680
