### ISSUE TITLE
Astronomer Doc on Migrating from an Alpine to Debian Airflow Image

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#164]
@paolaperaza commented on [Wed Sep 16 2020](https://github.com/astronomer/issues/issues/1796)

### Overview
Astronomer Certified 1.10.12 will be the last AC release that supports both a Debian and Alpine Docker Image (#1743). In preparation for 2.0, AC 1.10.13 and beyond will require users to migrating to our Debian AC Image.

### Scope
As a part of this GH Issue, we need to do two things:

1. Update our existing ["Airflow Versioning"](https://www.astronomer.io/docs/cloud/stable/customize-airflow/airflow-versioning/) doc to specify that AC 1.10.13 and beyond will be Debian-only
2. Create a separate doc (or add a section to Airflow Versioning), available for both Cloud and Enterprise that gives users guidance on what to do when migrating from Alpine to Debian.

Things to consider:
- Differences in Alpine v Debian packages/dependencies

cc: @vishwas-astro

**Comment by paolaperaza** [comment]
Closing this out as the PR to add this information to Enterprise was merged! https://github.com/astronomer/docs/pull/186

Thanks for your help on this, @jwitz.
