### ISSUE TITLE
Improve Private Services Connect docs

### ISSUE THREAD

**Issue by chomipi88** [astronomer/docs#1644]
**Affected Document:** https://docs.astronomer.io/astro/connect-gcp?tab=Private%20Service%20Connect#connection-options

**Problem Type (Priority):**

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [x] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**
1. Provide additional context about what PSC is and how it works. Possibly link to the google doc. https://cloud.google.com/vpc/docs/private-service-connect
2. Clarify that every Astro Data Plane on GCP is automatically configured with a Private Services Connection that accepts `All Google APIs` as the Target. This means that all connectivity to a Google service using the googleapis.com domain will route privately and securely over Google's backbone. Data remains secure on Google’s backbone network.
3. Users can find the list of Google services and their service name [he[re](https://cloud.google.com/vpc-service-controls/docs/supported-products](https://developers.google.com/apis-explorer), or run the command `gcloud services list --available --filter="name:googleapis.com"` using the gcloud cli. For example, for Bigquery the service name is bigquery.googleapis.com
4. Users can use the default DNS name in their DAGs. We have configured a DNS Zone and DNS Records to route the default DNS names through the PSC endpoint.

**Additional Notes:**

**Comment by ReadytoRocc** [comment]
LGTM @chomipi88
