### ISSUE TITLE
New Doc for Subscribing to Astro OSS Release Notes

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#1667]
### Context

We added a new **RSS** feed button to Astro release notes this week. This has been an eagerly awaited feature that will allow customers to subscribe and get notifications about Astro release notes in their browser or in slack.

<img width="485" alt="image" src="https://user-images.githubusercontent.com/31111752/208743033-90f78fb1-18b7-43de-9541-323eda086827.png">

### Ask

A lot of folks know how to use RSS feeds, but the customer team requested a URL with instructions.

- Create a new doc in the **Release Notes** menu called `Subscribe to Astro Release Notes`
- Use this as starting template: https://docs.google.com/document/d/1a0PqwpZzyyJqfsNRDYcmyTEZhQnvcnoDwnXfihxNEl4/edit?usp=sharing

cc: @katiebrady-astro @juliana-astro

**Comment by katiebrady-astro** [comment]
@paolaperaza @juliana-astro Got the page drafted in a PR! https://github.com/astronomer/docs/pull/1676

<img width="1641" alt="image" src="https://user-images.githubusercontent.com/96535736/209403304-ee4262fb-de96-400d-b022-608f4892b288.png">
