### ISSUE TITLE
Create Full CLI Reference Guide

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#167]
## What kind of documentation change are you requesting?

* **New document, topic, or other piece of content**: Add the `newcontent` label to this issue. 
  
### For new documents and enhancements, answer the following questions**

_What is the purpose of the document/enhancement? Select all that apply:_
- [ ] Setup steps a new feature for an upcoming release (Add the appropriate version label to this issue). 
- [ ] Information for an existing feature that isn't yet documented.
- [X] Additional considerations/ reference material for an existing feature or document.

#### _Describe the problem/ feature that requires documentation:_ 

Many organizations have comprehensive reference guides for their CLIs. There's only so much that can be communicated through CLI help text, so it's be nice to have a place on the web that users can explore to learn more about each CLI function.

  
#### _Describe what should be included in the document, making sure to outline what users should be able to achieve with the doc. In addition, include links to any relevant existing documentation, support tickets, messages, or external content:_

Astronomer should have its own CLI reference guide complete with information on commands, flags, and default values. This doc can also host common CLI errors and how to address them.

**Comment by paolaperaza** [comment]
Addressed by this PR: https://github.com/astronomer/docs/pull/202
