### ISSUE TITLE
Document OpenLineage facet functionality in Astro, including how to generate facets

### ISSUE THREAD

**Issue by conorbev** [astronomer/docs#1674]
**Request type:**

- [x ] **New document:** Add the `docs-content` label to this issue.
- [ ] **Addition to an existing document**: Add the `enhancement` label to this issue.

**What is the purpose of the document/enhancement? Select all that apply:**

- [ ] Document a new feature for an upcoming release. Add the appropriate release version label to this issue.
- [ x] Information for an existing feature that isn't yet documented.
- [x ] Additional considerations/ reference material for an existing document.

**Problem/feature that requires documentation:**

A customer, freight waves, is emitting some lineage data. They are adding facets to the data and are unsure if/where those facets would display in the Lineage UI. To make it clearer we could document which Facets specifically populate the data in the Info tab, duration tab and quality tab.

**Are you the right person to review a draft of the document for technical accuracy? If not, who is?**

Yes, you can also reach out to me to discuss. I think we'll prob need help from the o11y Eng team to do this.

**Comment by Esaych** [comment]
Related UI improvement task: https://github.com/astronomer/astro/issues/8001

**Comment by jwitz** [comment]
Blocking this docs issue until we migrate the UI from using context to facets, per @Esaych 's issue
