### ISSUE TITLE
Add Unfurl Metatag to Gen2 Docs

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#171]
### Context

We've been expanding Gen2 docs more and more over the past few weeks and it'd be awesome to have a branded hero that drops every time you share a link.

We'd love for them to look like this:

![image](https://user-images.githubusercontent.com/31111752/143078717-ff25d2b0-5189-4741-8744-05602c500bf9.png)

## Ask

Joanna's team designed a quick "Documentation" hero that we can use, but we need to add metatags to these docs such that that header drops when the link unfurls. The hero is here:

![astronomer_docs_1200x627_2](https://user-images.githubusercontent.com/31111752/143078502-803652e3-3307-49ae-b1dc-0e632f3694d7.png)

## Future
In the future, we'll work towards having a template that automatically generates this hero with the title of the doc and the brief description of the doc we're linking out to.

@llexan Are you able to help with this per chance?

**Comment by llexan** [comment]
Our resoc-image engine is now live! Now you can dynamically create these meta images just by requesting with this link + the title you want. For example:
`https://astro-resoc-engine.netlify.app/templates/docs/images/open-graph.jpg?title=Install%20the%20Astronomer%20CLI`

Will generate:
![https://astro-resoc-engine.netlify.app/templates/docs/images/open-graph.jpg?title=Install%20the%20Astronomer%20CLI](https://astro-resoc-engine.netlify.app/templates/docs/images/open-graph.jpg?title=Install%20the%20Astronomer%20CLI)

Looks like Docusarus has an option for setting meta images, but not sure if you can make them dynamic per doc/page:
[https://docusaurus.io/docs/api/themes/configuration/#image](https://docusaurus.io/docs/api/themes/configuration/#image)

If you need to add the meta tag itself in a template something like this should work:
`<meta property="og:image" content="https://astro-resoc-engine.netlify.app/templates/docs/images/open-graph.jpg?title={{ title }}" />`

Swapping out the hard-coded title with `{{title}}` being the title prop of the doc (not sure what that might actually be in Docusarus 😅).

**Comment by jwitz** [comment]
I found two issues in the Docusaurus repo that would allow us to have custom social cards for each doc. One of the following would have to be merged in order for us to have this functionality:

- https://github.com/facebook/docusaurus/issues/2968 (Implement custom social cards)
- https://github.com/facebook/docusaurus/issues/4492 (Use docs frontmatter in global config)

I feel pretty confident that the first one will eventually be merged into Docusaurus, so I'm not sure it's the best time for us to implement our own custom solution. For now, I think we should stick with the content team's default Hero and work on adding meta descriptions to all docs. This functionality is similar to other products with Docusaurus sites (Redis, dbt, React)

**Comment by paolaperaza** [comment]
Alrighty, as of today we have:

- Meta descriptions for all docs
- Basic default "Documentation" hero that unfurls properly

![image](https://user-images.githubusercontent.com/31111752/146447954-845d41d9-7ef2-4d6f-a941-436ee45f1e6c.png)

Closing this out since this is an accomplishment, and we can create another GH issue for the custom titles once Docusaurus supports it. 🎉  

![image](https://user-images.githubusercontent.com/31111752/146448155-15f026a0-bf1e-47e2-b6e1-2b2366968fe9.png)
