### ISSUE TITLE
Document provided cell types in the Cloud IDE

### ISSUE THREAD

**Issue by jlaneve** [astronomer/docs#1713]
**Request type:**

- [x] **New document:** Add the `docs-content` label to this issue.
- [ ] **Addition to an existing document**: Add the `enhancement` label to this issue.

**What is the purpose of the document/enhancement? Select all that apply:**

- [x] Document a new feature for an upcoming release. Add the appropriate release version label to this issue.
- [x] Information for an existing feature that isn't yet documented.
- [ ] Additional considerations/ reference material for an existing document.

**Problem/feature that requires documentation:**

We should document the provided cell types in the Cloud IDE. After this coming Tuesday's release (1/10), there will be 4 provided cell types. In a few weeks, there will be more, so getting these started now will be helpful. Here are the 4 types:
- `Python` (`aql.dataframe`): Run a Python script with an (optional) return value. The return values are made available to other cell types
- `SQL` (`aql.run_raw_sql`): Run a SQL query and fetch all the results. Note that results are processed in-memory, so this isn't designed to be used with massive amounts of data
- `Warehouse SQL` (`aql.transform`): Run a SQL query, store the results in a table in your data warehouse/connection, and fetch a 250 row preview of the results. The complete results don't leave your data warehouse (unless you consume them in another cell that's not in your warehouse), so you can process much more data. Downside of this SQL type is there are certain SQL statements that don't work (e.g. `CREATE TABLE ...`) because we're wrapping the query in a `CREATE TABLE` statement.
- `Markdown`: Write/preview Markdown to document & annotate your pipeline

**Are you the right person to review a draft of the document for technical accuracy? If not, who is?**

Yes

**Comment by kwcanuck** [comment]
@jwitz I'm not sure how best to present this new information in the existing documentation. Should we create a standalone topic titled _Cloud IDE cell types_ or similar, or should in be incorporated into an existing topic? If we incorporate it into the Quickstart, it will make the procedure _very_ long.

While reviewing the existing IDE content, I noticed that the _Cloud IDE_ parent isn't linked to a topic. Would it not better to have the _Overview_ content appear when the _Cloud IDE_ parent is selected? This would remove the _Overview_ topic from the TOC and would make for a better user experience in my opinion.

**Comment by kwcanuck** [comment]
@jwitz it appears that we are duplicating the introductory text in _Astro Cloud IDE_:

![image](https://user-images.githubusercontent.com/104205257/211323992-a7588766-0cc5-429b-a03b-d10202f63266.png)

Also, you'll notice that the first block of text appears larger than the other introductory text. I'm not sure if this is deliberate, but it seems odd.

**Comment by jlaneve** [comment]
Check out https://learn.hex.tech/docs/logic-cell-types/python-cells for inspo - they have a section on provided cell types (they call them "logic cells" here)

**Comment by kwcanuck** [comment]
While adding the new content, it would be helpful to define where tasks run and if customers pay for tasks that run on the IDE.

**Comment by jwitz** [comment]
@kwcanuck I'll be documenting these new cell types as part of this week's Astro release, that's why I've assigned this issue to myself. My plan is to have a new doc titled "Build and run logic cells" which has info on both each cell type and how you can configure/ run them together. @jlaneve Is it alright to refer to these as "logic cells", or should we say "task cells" instead to make their relationship to Airflow more clear?

**Comment by jlaneve** [comment]
@jwitz will defer to you on actual structure but I like the hex doc model of a single page per cell type, because the docs of some may get extensive
