### ISSUE TITLE
Update Data Plane Cluster Hosting Terminology

### ISSUE THREAD

**Issue by astro-rft** [astronomer/docs#1714]
**Affected Document:** Install Astro on AWS / Azure / GCP

**Problem Type (Priority):**

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [X] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**

We should use our official deployment model names of `Bring Your Own Cloud` and `Hosted` with reference to data plane clusters (as opposed to Astro overall). Note that it is supported (though likely rare) for customers to run clusters of both deployment models.

**Additional Notes:**

**Comment by kwcanuck** [comment]
@jwitz this request could be tricky to implement. A quick search for _data plane_ returned 106 results in 30 files. Is it necessary to differentiate every reference to _data plane_? Most references in the documentation appear to be referring to `Hosted` and the  `BYOC` references already appear to be well defined. Thoughts?

**Comment by jwitz** [comment]
@kwcanuck This issue is just about how we refer to the different hosting methods in our installation guides. Consider our tab structure there:

```

<Tabs
    defaultValue="byoc"
    groupId= "byoc"
    values={[
        {label: 'Self-hosted', value: 'byoc'},
        {label: 'Astronomer-hosted', value: 'astronomer hosted data plane'},
    ]}>
<TabItem value="byoc">
```

We need to replace "Self-hosted" with "Bring your own cloud", and "Astronomer-hosted" with "Hosted"

**Comment by astro-rft** [comment]
For consistency, can we ensure `Bring Your Own Cloud` is capitalized throughout?

The definitions and reference to `hosted cloud` are inconsistent with how we describe this. @juliana-astro could you take a look at the definitions for BYOC and Hosted and offer some suggestions?

**Comment by kwcanuck** [comment]
@astro-rft there are currently no instances of _Bring Your Own Cloud_ (initial capitalization) in the documentation:

![image](https://user-images.githubusercontent.com/104205257/211564004-7798e150-05ca-4990-9523-817d298f211a.png)

Currently, the capitalization of _Bring your own cloud_ is consistent throughout the documentation. Is _Bring your own cloud_ an official product or service name? If not, initial capitalization is not correct.

I'm not clear what you mean by the definitions and references to hosted cloud being inconsistent. Can you provide a _specific_ example of an inconsistent definition or reference? I would be happy to modify the text if you can identify their location.

**Comment by kwcanuck** [comment]
Discussed capitalization with the docs team and it was determined that initial capitalization of _Bring Your Own Cloud_ would  be implemented as it is considered an official Astronomer service offering. [PR 1739](https://github.com/astronomer/docs/pull/1739) was opened to implement the change.  The convention has also been documented in the Astronomer style guide.
