### ISSUE TITLE
Add info on dag.test() command

### ISSUE THREAD

**Issue by virajmparekh** [astronomer/docs#1730]
**Affected Document:**
- https://docs.astronomer.io/astro/test-and-troubleshoot-locally
- https://docs.astronomer.io/learn/testing-airflow#docusaurus_skipToContent_fallback

**Problem Type (Priority):**

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [x] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**
We should add an example of how to take advantage of `dag.test()` and how it fits into using the testing centric commands in the CLI. 

**Additional Notes:**
There may be no change required on our docs here in terms of content/best practice around testing, but we should atleast acknowledge existence of this new command and explicitly direct users one way or another.

**Comment by paolaperaza** [comment]
For reference:

- Original Airflow slack: https://apache-airflow.slack.com/archives/CCR6P6JRL/p1673337666527429
- Astro discussion: https://astronomer.slack.com/archives/C04JJ6QD9S4/p1673378634837309

@RNHTTR figured out example and would be the best technical reviewer for this:

```
from airflow import DAG
with DAG(...) as dag:
    ...

if __name__ == "__main__":
    dag.test()
```

A couple of bugs to be aware about:

1. With non-async operators, the task(s) will run successfully, but once all tasks have run, I get the error `ERROR - Executor have not started before on_dag_run_success`
2. With async operators (`TimeDeltaAsync` and `DateTimeSensorAsync`), the task is immediately marked successful, but then it just hangs in perpetuity

**Comment by jwitz** [comment]
Should this not be in our Learn guide? https://docs.astronomer.io/learn/debugging-dags

Or even better, we could submit an OSS PR since it seems to be something that's not understood even beyond Astro customers.

**Comment by RNHTTR** [comment]
I think both a guide and updating the OSS docs are worthwhile.

**Comment by kwcanuck** [comment]
@kentdanas - FYI as adding this content to a learn guide is being discussed as an option.
