### ISSUE TITLE
Jenkins `--dags` instructions

### ISSUE THREAD

**Issue by mdray** [astronomer/docs#1749]
**Affected Document:** https://docs.astronomer.io/astro/ci-cd#jenkins

**Problem Type (Priority):** Important

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [ ] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):** Would like to see instructions for implementing `astro deploy --dags` with Jenkins syntax similar to what we provide for GitHub Actions in this section: https://docs.astronomer.io/astro/ci-cd#github-actions-dag-based-deploy

**Additional Notes:** Requested by Idelic

**Comment by kwcanuck** [comment]
@jwitz thoughts on who might be able to provide the requested information and act as the SME for the new content?

**Comment by jwitz** [comment]
@pohek321 You've helped us with our Jenkins pipeline templates in the past, would you be able to help us write a script that uses DAG-only deploys as Matt has described here? If you provide the basic script, Rob and I can take it the rest of the way with a docs PR!

**Comment by pohek321** [comment]
@jwitz I'll have to spin up an EC2 instance with Jenkins installed on it, I haven't touched it in a minute -- I should have some cycles today to get it done

**Comment by pohek321** [comment]
@jwitz I just tested this successfully and like it quite a bit better than the GitHub Actions script:

```Jenkinsfile
pipeline {
    agent any
      stages {
        stage('checkout'){
            steps{
                git branch: 'main', url: 'https://github.com/astronomer/jenkins-cicd-pov.git'
            }
        }
        stage('Dag Only Deploy to Astronomer') {
          when {
           expression {
             return env.GIT_BRANCH == "origin/main"
           }
          }
          steps {
              sh '''
                curl -LJO https://github.com/astronomer/astro-cli/releases/download/v1.9.0/astro_1.9.0_linux_amd64.tar.gz
                tar xzf astro_1.9.0_linux_amd64.tar.gz
                files=($(git diff-tree HEAD --name-only --no-commit-id))
                find="dags"
                if [[ ${files[*]} =~ (^|[[:space:]])"$find"($|[[:space:]]) && ${#files[@]} -eq 1 ]]; then
                  ./astro deploy --dags -f;
                else
                  ./astro deploy -f;
                fi
              '''
          }
        }
      }
    post {
      always {
        cleanWs()
      }
    }
}
```

however, I'm trying to figure out how to ditch the `-f` flag jenkins doesn't seem to be doing a clean checkout of the repo

**Comment by pohek321** [comment]
@jwitz just tested this out today and it works nicely - an improvement over the GitHub actions one IMO

```jenkinsfile
pipeline {
    agent any
      stages {
        stage('Dag Only Deploy to Astronomer') {
          when {
           expression {
             return env.GIT_BRANCH == "origin/main"
           }
          }
          steps {
              checkout scm
              sh '''
                curl -LJO https://github.com/astronomer/astro-cli/releases/download/v1.9.0/astro_1.9.0_linux_amd64.tar.gz
                tar -zxvf astro_1.9.0_linux_amd64.tar.gz astro && rm astro_1.9.0_linux_amd64.tar.gz
                files=($(git diff-tree HEAD --name-only --no-commit-id))
                find="dags"
                if [[ ${files[*]} =~ (^|[[:space:]])"$find"($|[[:space:]]) && ${#files[@]} -eq 1 ]]; then
                  ./astro deploy --dags;
                else
                  ./astro deploy;
                fi
              '''
          }
        }
      }
    post {
      always {
        cleanWs()
      }
    }
}
```
