### ISSUE TITLE
Update Astro architecture image

### ISSUE THREAD

**Issue by chomipi88** [astronomer/docs#1758]
**Affected Document:**

**Problem Type (Priority):**

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [x] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

Replace with:
![Solution arch-General](https://user-images.githubusercontent.com/87984472/213601203-d2ada7fc-62a1-42db-b9d4-136c8a809f75.png)

**Comment by kwcanuck** [comment]
Resolved by #1762
