### ISSUE TITLE
Add limitations of ExternalPythonOperator

### ISSUE THREAD

**Issue by virajmparekh** [astronomer/docs#1779]
We should add a section to the ExternalPythonOperator that shows the limitations of the EPO. 
- [This thread](https://astronomer.slack.com/archives/C032W6FBSGP/p1674504356242929) shows a user struggling to integrate it with a secrets backend
- Conceptually, we should be clear which of airlfow's built in features you can use in the context of a EPO (secrets managers, xcoms, etc.) We should also be clear about considerations to keep in mind when going from local environments to production environments

**Comment by kentdanas** [comment]
@TJaniF for your update. Not sure whether it makes sense to cover this stuff in depth, but something to consider mentioning at a high level.
