### ISSUE TITLE
Incorrect Azure default node type

### ISSUE THREAD

**Issue by chomipi88** [astronomer/docs#1801]
**Affected Document:**
https://docs.astronomer.io/astro/install-azure#prerequisites

**Problem Type (Priority):**

- [x] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [ ] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**
Update to correct default of Standard D4d v5

**Additional Notes:**

**Comment by kwcanuck** [comment]
Resolved by PR 1802.
