### ISSUE TITLE
Add docs for Cloud IDE "clone GitHub repo" functionality

### ISSUE THREAD

**Issue by jlaneve** [astronomer/docs#1836]
**Request type:**

- [x] **New document:** Add the `docs-content` label to this issue.
- [ ] **Addition to an existing document**: Add the `enhancement` label to this issue.

**What is the purpose of the document/enhancement? Select all that apply:**

- [ ] Document a new feature for an upcoming release. Add the appropriate release version label to this issue.
- [x] Information for an existing feature that isn't yet documented.
- [ ] Additional considerations/ reference material for an existing document.

**Problem/feature that requires documentation:**

In the Cloud IDE, we allow a user to sync their GitHub repo on the runner where execution happens. This gives a user access to the `include` folder in their DAG. We have some in-product documentation (see screenshot below), but it'd be great to get a new page for it on the docs site. Essentially, the way it works is:

A user checks/toggles the "Clone GitHub repo during cell execution". By default, this will auto-sync the repo. The next time a task is executed, the runner will fetch the GitHub repo so the cell execution has access to the repo files. If auto-sync remains on, every time a cell is executed, we check GitHub repo for updates - if there are updates, we update the files; otherwise, nothing happens. A user can also disable auto-sync in favor of manually syncing the files; if they do so, cell execution won't check for repo updates until a user goes back to the GitHub clone settings and manually syncs the files.

<img width="1161" alt="Screen Shot 2023-02-02 at 3 21 13 PM" src="https://user-images.githubusercontent.com/5252587/216441159-8f83bf85-bf42-410f-89ef-04a4562fa8fa.png">

**Are you the right person to review a draft of the document for technical accuracy? If not, who is?**

Yes

**Comment by jwitz** [comment]
@jlaneve We have this feature documented in https://docs.astronomer.io/astro/cloud-ide/deploy-project#commit-your-project-to-github , but I'm open to reworking how we frame it! To me this seems like more of a "Run cell" feature even though it's in the GitHub repo configuration - maybe we need a new "Run cells" doc with all of these details?

**Comment by jlaneve** [comment]
Hmm, I don't mind either way - what I'm looking for is something dedicated to the GitHub clone, so I can link specifically to that section. Personally, I think that's best served as a completely separate page (and also worth noting that we're going to have other git vendors - GitLab, etc), but will defer to you
