### ISSUE TITLE
FAQ Section

### ISSUE THREAD

**Issue by erdos2n** [astronomer/docs#1844]
**Request type:**

- [X ] **New document:** Add the `docs-content` label to this issue.
- [ ] **Addition to an existing document**: Add the `enhancement` label to this issue.

**What is the purpose of the document/enhancement? Select all that apply:**

- [ ] Document a new feature for an upcoming release. Add the appropriate release version label to this issue.
- [X] Information for an existing feature that isn't yet documented.
- [X] Additional considerations/ reference material for an existing document.

**Problem/feature that requires documentation:**
All. Any and all frequently asked questions that we see in CRE. 

**Are you the right person to review a draft of the document for technical accuracy? If not, who is?**
Yes

**Comment by erdos2n** [comment]
@jwitz have these sections been added yet? I have a KB I'd like to begin and wanted to know what the timeline was for it. 

Thank you

**Comment by jwitz** [comment]
@erdos2n I thought that the next step here was that CRE would provide the FAQ questions and any internal content that you use to address those questions, and we would get that edited and formatted for docs. So far, the only questions we've found are: 

- What do I do if logs aren’t appearing?
- What do I do if tasks are stuck in queued?

If this content doesn't exist yet, I'm happy to work with you on creating it this week and getting it out there!

**Comment by jwitz** [comment]
Taking this work off of GitHub and onto Notion, so closing this issue out for now.
