### ISSUE TITLE
Add mention of task execution error in Cloud IDE

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#1847]
### Context

A customer recently reported an error in Cloud IDE that prevented them from being able to run tasks: Error: `Could not connect to cell execution environment`. Slack here: https://astronomer.slack.com/archives/C03GVMR7W8Y/p1675451391709719

<img width="920" alt="image" src="https://user-images.githubusercontent.com/31111752/216733034-3a945bfc-6bef-422d-b41c-a1124bc453c1.png">

It turns out that:

- When an Astro org is created, our team has to manually set them up by creating an S3 bucket and a few Kubernetes Pod. They do this on a daily basis, but there's a chance we miss an organization
- If we don't do this, then the customer can't actually execute tasks in the IDE and gets this error
- More generally, this error happens if there's a problem with our data plane. It could either be:
     - We didn't set them up
     - The system is down for some other reason

### Ask

This error happens when a user tries to actually run a task, so let's add an info box to these two sections:

- https://docs.astronomer.io/astro/cloud-ide/run-python#run-a-python-cell
- https://docs.astronomer.io/astro/cloud-ide/run-sql

I don't think we have to bother with the quickstart? cc: @jlaneve @fritz-astronomer

**Comment by jwitz** [comment]
Tackling this as part of https://github.com/astronomer/docs/issues/1836 where I'll be creating a new "Run cells" doc
