### ISSUE TITLE
Add instructions for adding multiple email addresses with `astro user invite`

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#1849]
### Context

We recently added support for new Workspace and user commands to the CLI: https://docs.astronomer.io/astro/cli/release-notes#new-commands-to-manage-astro-users

While we updated our CLI command reference guide, we're not necessarily helping folks connect the dots on how to best leverage these commands, especially in the context of missing API tokens (that are coming soon). While there's no native way to add multiple email addresses, a user could write a script that does this. We should help them with that.

### Ask

- Review this doc: https://docs.astronomer.io/astro/add-user
- Consider where we could add guidance on adding multiple users at once with new CLI commands
- Connect with @sunkickr + @chomipi88 + @nicholasfilippi 
- Add an example script to that doc + test it to verify it works

Example Slack exchange on this from a customer: https://astronomer.slack.com/archives/C04F8E3NKFY/p1675443477369349

> for user_email in all_users:
>   `astro user invite {user_email}`

**Comment by jwitz** [comment]
Would this be better to tackle once we have Workspace API keys? Until then we'd be instructing users to make scripts without all the necessary tools for complete automation. I avoided promising too much on the automation front in the current docs because of this.

**Comment by sunkickr** [comment]
@jwitz They can't be used for automation yet, but the a user can run this script in their local terminal if they login through `astro login` first. Running this script locally would be better than running one command for each user you want to add

**Comment by kwcanuck** [comment]
@jwitz I was curious and I did some digging on this and I spoke to @jlaneve. When I inquired about a script, this was the response:

_I don't have one, I just sent this pseudocode to a customer:_

```
for user in user_emails:
    run `astro user add {user}`
```

It doesn't appear that a script to add multiple email addresses is available. Perhaps a script could be created that references a list of users?
