### ISSUE TITLE
Customer Feedback: Moving the Docker buildkit error note

### ISSUE THREAD

**Issue by aspain** [astronomer/docs#185]
**Affected Document:**
https://docs.astronomer.io/deploy-code

**Problem Type (Priority):**

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [ X] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**
See slack conversation from customer: https://astronomer.slack.com/archives/C02NXJGKA3H/p1638802829019200

Notably their feedback "Oh [here](https://docs.astronomer.io/deploy-code#prerequisites) is that note about changing buildkit. It should not come after the docs where you would have gotten this error"

**Additional Notes:**
Should we also just give the code snippet example directly in the doc rather than linking to the form post? We could still include the post for context, but for the specific change being made, could that be included in the doc?

**Comment by paolaperaza** [comment]
@aspain This is now addressed! I kept the reference to the buildkit problem in "Deploy Code" doc, but I also added it to "Create a Project" doc, under the step where a customer first runs `astro dev start` - https://docs.astronomer.io/cloud/create-project#step-2-build-your-project-locally

![image.png](https://images.zenhubusercontent.com/59d78295b0222d5de47a8bfe/bb9878ee-bceb-4c34-a661-118466ccee82)
