### ISSUE TITLE
More detailed docs on Airflow lineage tactics

### ISSUE THREAD

**Issue by rossturk** [astronomer/docs#1873]
**Request type:**

- [ ] **New document:** Add the `docs-content` label to this issue.
- [x] **Addition to an existing document**: Add the `enhancement` label to this issue.

**What is the purpose of the document/enhancement? Select all that apply:**

- [ ] Document a new feature for an upcoming release. Add the appropriate release version label to this issue.
- [ ] Information for an existing feature that isn't yet documented.
- [x] Additional considerations/ reference material for an existing document.

**Problem/feature that requires documentation:**

There are a few tactics that can be used for extracting lineage from Airflow:
* use of operators with built-in extractors (for common use cases where Airflow can directly observe the lineage relationship)
* use of operators with custom extractors (for custom use cases where Airflow can directly observe the lineage relationship)
* use of underlying integrations (for situations where Airflow orchestrates work but can't directly observe it - e.g. Spark, dbt)
* manual specification of inlets / outlets (for situations like `PythonOperator` where automated lineage is not possible)

The state-of-the-art for these tactics has changed appreciably since the existing guides and doc pages were created. I believe that users who are aware of these different tactics and their applicability across various situations are more likely to find lineage valuable.

I feel this can be woven into the following resources:
https://docs.astronomer.io/astro/set-up-data-lineage
https://docs.astronomer.io/learn/airflow-openlineage

I've prepared these slides that might be helpful:
[Airflow Lineage Tactics.pdf](https://github.com/astronomer/docs/files/10691810/Airflow.Lineage.Tactics.pdf)

**Are you the right person to review a draft of the document for technical accuracy? If not, who is?**

Yes, I can help here. If something exceeds my knowledge, I can be responsible for digging up the answer from our engineering experts.

**Comment by jwitz** [comment]
Great ideas @rossturk ! From my perspective these are the deficiencies in our docs:

- The Astro doc is not comprehensive about the ways you can generate lineage (No mention of custom extractors or inlets/outlets in overview)
- No elaboration on difference between OL integrations and operators with extractors. How are they different, which one should you use? 
- No step-by-step tutorials on the Learn side for practical lineage/ Airflow setup. All we have is https://docs.astronomer.io/learn/marquez

We would definitely need help on understanding some of the more advanced customization steps for OL. Can we have a 30 minute meeting to discuss next steps?

**Comment by rossturk** [comment]
Yes, I'd be happy to meet and discuss this 👍

**Comment by jwitz** [comment]
Follow-ups from meeting:

- Provide context around the different types of extraction methods and which ones Astro users should opt for in https://docs.astronomer.io/astro/set-up-data-lineage
- Create steps for configuring extractors that rely on new OL docs for code-level configuration
- Document where to put custom facets and how to view all facet types in https://docs.astronomer.io/astro/data-lineage
