### ISSUE TITLE
Add guidance on using DAG and task run comments

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#1902]
Airflow 2.5 introduced https://github.com/apache/airflow/pull/26457, which lets you write comments for DAG or task runs.

I was thinking either https://docs.astronomer.io/learn/airflow-ui or https://docs.astronomer.io/learn/custom-airflow-ui-docs-tutorial would be a good place to include this information. We could provide more guidance on what the feature should be used for and how to use it - I don't think there are any docs currently on this!

**Comment by kentdanas** [comment]
@jwitz we do have a section on DAG and task notes in our rerunning DAGs guide: https://docs.astronomer.io/learn/rerunning-dags#add-notes-to-cleared-tasks-and-dags. When the feature released we debated about where to put these and decided that would be the most relevant, but it has come up a couple times that people didn't know where to find info about that feature. I'm open to adding a section to either of the docs you mentioned in addition - the tutorial probably makes the most sense to me.
