### ISSUE TITLE
Request to specify RSA TLS while renewing certificate from LetsEncrypt

### ISSUE THREAD

**Issue by sudarshan-uc** [astronomer/docs#1926]
**Affected Document:**
https://github.com/astronomer/docs/blob/main/software/renew-tls-cert.md

**Problem Type (Priority):**
Medium

- [ ] Missing (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**

Lets Encrypt's certbot now uses ECDSA as a default cert type, specifying the required keytype: RSA would allow users to generate certs with correct type leading to downtime in Astronomer Software's registry and similar errors.

Example Command:

sudo certbot certonly --manual --preferred-challenges=dns -d <baedomain> -d \*.<basedomain> --key-type=rsa

**Additional Notes:**
https://github.com/certbot/certbot/releases/tag/v2.0.0

**Comment by kwcanuck** [comment]
Comments from @sudarshan-uc:

_....everytime the customer renews the certs using certbots and via LetsEncrypt and do not specify the Certificate type, they end up generating ECDSA certs where as our cluster is looking for RSA cert at various components. This atleast causes primary error while pushing the new/update deployment. the very recent customer ticket [16701](https://astronomer.zendesk.com/agent/tickets/16701)._

_...simply add note everywhere it instructs to regenerate-certs using LetsEncrypt, we can add a note to specify cert-type: RSA . CRE created [article](https://support.astronomer.io/hc/en-us/articles/13300012364051--Cannot-read-public-key-OID-is-not-RSA-error-in-houston-logs). The example command can be added in the install doc where we instruct to generate certificate and create hyperlink in Renew-certs doc_
