### ISSUE TITLE
Add guidelines on bypassing/customizing `pytest`

### ISSUE THREAD

**Issue by dylanbstorey** [astronomer/docs#1940]
As customers practices mature, they're running into issues with our integration testing. 

While the solutions are usually trivial and to a knowledgable practitioner obvious , they are not well documented.

We should do better at documenting these more "advanced" use cases and ensuring they're findable by our customers. 

https://astronomer.zendesk.com/agent/tickets/15810
https://github.com/astronomer/astro-cli/issues/601
https://astronomer.slack.com/archives/CL44PA4DB/p1674566793622189

**Comment by jwitz** [comment]
Content likely fits in our new help center, gonna block this for now

**Comment by jwitz** [comment]
The work for this ticket is now being tracked on Notion as part of our KB publication project. Closing this ticket
