### ISSUE TITLE
Alternative connection for GCP

### ISSUE THREAD

**Issue by chomipi88** [astronomer/docs#1957]
**Request type:**

- [ ] **New document:** Add the `docs-content` label to this issue.
- [x] **Addition to an existing document**: Add the `enhancement` label to this issue.

**What is the purpose of the document/enhancement? Select all that apply:**

- [ ] Document a new feature for an upcoming release. Add the appropriate release version label to this issue.
- [x] Information for an existing feature that isn't yet documented.
- [ ] Additional considerations/ reference material for an existing document.

**Problem/feature that requires documentation:**

Add to https://docs.astronomer.io/astro/connect-gcp#connection-options

GCP does not support transitive communication when VPC peering. This present challenges when connecting to data services that are already peered to a customer's existing VPC.

Support has an alternative documented in their KB. We should add this as an alternative to VPC peering when there are transitive communication challenges.

https://support.astronomer.io/hc/en-us/articles/11042080348947-Create-site-to-site-VPN-in-GCP-Astro-

**Are you the right person to review a draft of the document for technical accuracy? If not, who is?**

**Comment by kwcanuck** [comment]
Discussed the requirements with @chomipi88 and he requested the addition of a tab labeled _Site-to-site VPN_ below the existing _[Connection options](https://docs.astronomer.io/astro/connect-gcp#connection-options)_ heading. Piotr asked that we make it clear that site-to-site VPN is accomplished using Cloud VPN and that users should review the GCP docs before contacting Astronomer support for assistance.

**Comment by lzdanski** [comment]
@jwitz - i think this work might be complete, can we close this issue?
