### ISSUE TITLE
Replace `get-started` link to `try-astro` in Docs page

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#1983]
### Context

Our `Try Astro` button in docs currently links to: `https://www.astronomer.io/get-started/?referral=docs-nav-button`. As of last week, our homepage now directs 100% of web traffic to our trial getting started page: https://www.astronomer.io/try-astro/

We need to update our docs accordingly

### Ask

- [x] Create a new referral link for `Try Astro`, e.g. `https://www.astronomer.io/try-astro/?referral=docs-nav-button`
- [x] Replace all references of the `get-started` to `try-astro`. Reference: https://github.com/astronomer/docs/search?q=www.astronomer.io%2Fget-started

The `Learn about Astronomer` link can stay the same.

**Comment by katiebrady-astro** [comment]
Hey @paolaperaza sure thing! Opened PR #1984 which updates all the Try Astro links accordingly. 🙂
