### ISSUE TITLE
Update recommendations on `/include` + Helper Functions

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#1985]
Originally reported by @ReadytoRocc: https://astronomer.slack.com/archives/C015V2JFKT5/p1677507794199359

### Context

Astro docs currently have misleading recommendations for how customers are supposed to add utility files (such as CSVs, python scripts, SQL code files) to their Astro project.

We tell them to do 2 things:

- Add a `helper-function` directory: https://docs.astronomer.io/astro/develop-project#add-dag-helper-functions
- Add utility files to `/include`: https://docs.astronomer.io/astro/develop-project#add-dag-utility-files

These sections should be the same and give users the latest product feedback.

### Ask

- [ ] Simplify to one section called `Add Utility Files` and specify that there are two categories of utility files:
       - Files that are needed by and references your DAG code (e.g. python scripts, SQL code files)
       - Files that are needed to be built in your Docker image (e.g  custom operators, test data, etc)
- [ ] Clarify our recommendations:
        - Create a folder called `/utils` in your DAGs directory for things your DAG need
        - Add anything else to your `/include` folder

There's some complexity here, so make sure to get a review from: @cmarteepants @sunkickr @jlaneve @ReadytoRocc

**Comment by jwitz** [comment]
As I'm working through this issue I have a nit: I don't think `include` is for utility files - we should have a separate section explaining that include is for local testing only.
