### ISSUE TITLE
Add details and action items to Azure pre-reqs

### ISSUE THREAD

**Issue by chomipi88** [astronomer/docs#1991]
**Affected Document:** https://docs.astronomer.io/astro/install-azure#prerequisites

**Problem Type (Priority):**

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [x] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**

1. Clean up the section about VM SKU and Zonal requirements for Workers
2. Add details about Azure Postgres Flexible Server SKU and Zonal requirements
3. Add action item for end user to raise a support ticket to raise / enable any restrictions found

**Additional Notes:**

**Comment by lzdanski** [comment]
Stale - close
