### ISSUE TITLE
Permissions for Cloud IDE GitLab Personal Access Token

### ISSUE THREAD

**Issue by pgzmnk** [astronomer/docs#2002]
**Request type:**

- [ ] **New document:** Add the `docs-content` label to this issue.
- [x] **Addition to an existing document**: Add the `enhancement` label to this issue.

**What is the purpose of the document/enhancement? Select all that apply:**

- [ ] Document a new feature for an upcoming release. Add the appropriate release version label to this issue.
- [ ] Information for an existing feature that isn't yet documented.
- [x] Additional considerations/ reference material for an existing document.

**Problem/feature that requires documentation:**

The IDE docs to create a Personal Access Token for GitLab should specify the minimum permissions for the PAT. These are:

- Scope: `api`
- Role: `Developer` (If creating a repo-specific token, which is preferred) This allows the token to create new branches, as shown in GL [docs](https://docs.gitlab.com/ee/user/permissions.html).

**Are you the right person to review a draft of the document for technical accuracy? If not, who is?**
Yes, also @jlaneve

**Comment by jwitz** [comment]
@pgzmnk Thanks for writing up the issue, is this feature out yet? I don't see how to configure GitLab on my own IDE instance.

**Comment by pgzmnk** [comment]
Should be out with the next prod release.

**Comment by jwitz** [comment]
As in today March 14, or March 21?

**Comment by pgzmnk** [comment]
I expect it to be today March 14th.
