### ISSUE TITLE
dbt core guide

### ISSUE THREAD

**Issue by erdos2n** [astronomer/docs#2005]
**Request type:**

- [X ] **New tutorial:**: Add the `docs-content` and `area/learn` labels to this issue.
- [ ] **New Airflow concept:**: Add the `docs-content` and `area/learn` label to this issue.
- [ ] **Addition to an existing guide**: Add the `area-learn` and `enhancement` labels to this issue.

**Use case or feature that should be covered:**
- How to install `dbt-core` with a deployment

**Who the guide is intended for:**
Astro users who want to use `dbt-core` and not `dbt-cloud`. 

**Are you the right person to review a draft of the guide for technical accuracy? If not, who is?**
I can review this document

**Additional Context:**
Airflow does not officially support `dbt-core` AFAIK. This is because there are usually conflicting dependencies between the libraries used in `dbt-core` and and the webserver component. The best way to install `dbt-core` is to use a virtual environment and use the `ExternalPythonOperator`. 

Putting the following information would be helpful:
* Where to put the `dbt` directory in the astro project. The `include/` directory has caused issues because the `dbt deps` command does not work on the image build.
* How to create the virtual environment with its own `requirements.txt` file
* A single task using the `ExternalPythonOperator` to execute a `dbt command

**Comment by kentdanas** [comment]
@erdos2n thanks for raising this. We have a PR open now to update our existing [dbt integration guide](https://docs.astronomer.io/learn/airflow-dbt) to focus on using the Astro dbt provider (#2058), which will be our recommended method for running dbt core jobs from Airflow (and Astro) going forward. We will still link out to other resources that cover additional methods for running dbt core jobs, but these are much more complicated so we won't go into too much detail. All dbt Cloud info will be broken out into a separate tutorial so there isn't any confusion. Hope this helps!

**Comment by paolaperaza** [comment]
@erdos2n I was just talking to @kentdanas -- we're going to close this GH issue in favor of one I just created that reflects changes to our dbt guides based on Cosmos: https://github.com/astronomer/docs/issues/2084
