### ISSUE TITLE
FAQ topic: How to confirm that my DAG deploy worked

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#2011]
We should compile all of the steps that a user should take to confirm that a DAG deploy worked as expected. This includes basic steps like checking image/ bundle tags, as well as reading CLI logs.

See https://astronomer.slack.com/archives/C01UA03TPV1/p1678880798296689

**Comment by manmeetkaur** [comment]
this was not auto-resolved when the PR merged. closing manually.
