### ISSUE TITLE
Configuration for Alertmanager alerting

### ISSUE THREAD

**Issue by wolfier** [astronomer/docs#202]
**Affected Document:**
  
**Severity:**

- [ ] Critical: This document has incorrect or missing information. Add the `error/critical` label to this issue.
- [x] FYI: The document is misleading or could benefit from additional context or guidance. Add the `error/FYI` label to this issue.
- [ ] Typo: Add the `error/typo` label to this issue.
  
**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**

Configuration for email alerting in Alertmanager is not defined in the our [Enterprise Alerting documentation](https://www.astronomer.io/docs/enterprise/v0.25/monitor/platform-alerts)

zendesk ticket: [#6506](https://astronomer.zendesk.com/agent/tickets/6506)

The documentation also lists a list of available endpoints for Alertmanager to fire alerts but does not provide any clear examples except for `slack_configs`.

```
You can configure Alertmanager to send Astronomer's built-in alerts to email, HipChat, PagerDuty, Pushover, Slack, OpsGenie, and more by defining alert receivers in the Alertmanager Helm chart and pushing them to the Alertmanager ConfigMap.
```

Additionally, the link for `the Alertmanager ConfigMap` links to itself. I would think it shouldn't link to anything or maybe Alertmanager's documentation on their [configuration file](https://prometheus.io/docs/alerting/latest/configuration/#configuration-file).

**Comment by kwcanuck** [comment]
From the Slack conversation with @wolfier:

_I think there should be something that links to the email config parameters._

_The example may not have any incorrect parameters, which is what was wrong before, but the customers doesn't know that there are other possible configurations. They are available under:
https://prometheus.io/docs/alerting/latest/configuration/#email_config_

**Comment by kwcanuck** [comment]
@wolfier the revised documentation is now ready for your review.
