### ISSUE TITLE
Review intro to airflow docs resources

### ISSUE THREAD

**Issue by lzdanski** [astronomer/docs#2023]
**Affected Document:**
* https://docs.astronomer.io/learn/intro-to-airflow (Compare with other Intro to Airflow)

**Problem Type (Priority):**

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [x] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**
- Remove redundant content
- Clarify existing content

**Additional Notes:**
- review details from friction logs in https://www.notion.so/astronomerio/Tech-Writer-Onboarding-f6bb33352e5f4f64b63655d256d9f93d?pvs=4

**Comment by kentdanas** [comment]
@lzdanski I'm going to reassign this to Tamara, who is taking on updating this doc after content audit last week. We will review your notes in notion from when you started, but if you have additional context let us know!
