### ISSUE TITLE
Referencing Kubernetes Secrets in Astro

### ISSUE THREAD

**Issue by wolfier** [astronomer/docs#2025]
**Request type:**

- [x] **New document:** Add the `docs-content` label to this issue.
- [ ] **Addition to an existing document**: Add the `enhancement` label to this issue.

**What is the purpose of the document/enhancement? Select all that apply:**

- [ ] Document a new feature for an upcoming release. Add the appropriate release version label to this issue.
- [x] Information for an existing feature that isn't yet documented.
- [ ] Additional considerations/ reference material for an existing document.

**Problem/feature that requires documentation:**

I would like a documentation section describing how environment variables marked as secrets are stored as Kubernetes Secrets and specifically in a secret named `env-secrets`.

Users who execute `KubernetesPodOperators` or task instances with `KubernetesExecutor` may want to mount an environment variable that is marked secrets in their tasks. In Astro, Environment Variables marked as secrets are stored as a Kubernetes secret named `env-secrets`. Informing the customer of this Kubernetes Secret enables them to mount a secret on their tasks. In Airflow, it would look like this.

```
import pendulum
from airflow.kubernetes.secret import Secret

from airflow.models import DAG
from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
from airflow.configuration import conf

with DAG(
        dag_id='test-kube-pod-secret',
        start_date=pendulum.datetime(2022, 1, 1, tz="UTC"),
        end_date=pendulum.datetime(2022, 1, 5, tz="UTC"),
        schedule_interval="@once",
) as dag:

    secret_env = Secret(deploy_type="env", deploy_target="MY_SECRET", secret="env-secrets", key="MY_SECRET")

    namespace = conf.get("kubernetes", "NAMESPACE")

    k = KubernetesPodOperator(
        namespace=namespace,
        image="ubuntu:16.04",
        cmds=["bash", "-cx"],
        arguments=["echo $MY_SECRET && sleep 150"],
        name="test-name",
        task_id="test-task",
        get_logs=True,
        secrets=[secret_env],
    )
```

For `KubernetesPodOperators`, users can inject the environment variable through the `env_var` but the value is exposed in the templated view. For tasks instance queued by the `KubernetesExecutor`, users can only reference existing Kubernetes objects and to reference a secret, they would need to know the Kubernetes Secret name.

**Are you the right person to review a draft of the document for technical accuracy? If not, who is?**

I can help review the documentation!

**Comment by erdos2n** [comment]
Here is a KB to reference as well. Would be great for the FAQ sections we're working on @jwitz 

https://support.astronomer.io/hc/en-us/articles/14968015052179
