### ISSUE TITLE
Add docs for literal/expression switching in the Cloud IDE

### ISSUE THREAD

**Issue by jlaneve** [astronomer/docs#2030]
**Request type:**

- [x] **New document:** Add the `docs-content` label to this issue.
- [ ] **Addition to an existing document**: Add the `enhancement` label to this issue.

**What is the purpose of the document/enhancement? Select all that apply:**

- [ ] Document a new feature for an upcoming release. Add the appropriate release version label to this issue.
- [x] Information for an existing feature that isn't yet documented.
- [ ] Additional considerations/ reference material for an existing document.

**Problem/feature that requires documentation:**

Cloud IDE recently added support for the ability to switch between literals and expressions. Currently (without feature flags enabled), the only visible change is in the Warehouse SQL cell, but as soon as we have registry and custom cell types, this will be a much broader feature so it deserves a doc of its own.

When you use a cell that has a supported input (non-code fields for now, so just the database/schema/table in Warehouse SQL), there is a literal/expression switcher now available. See screenshot below.

<img width="739" alt="Screen Shot 2023-03-20 at 1 54 56 PM" src="https://user-images.githubusercontent.com/5252587/226425981-b601dfac-f27d-4605-b5e5-d1f00ed7a598.png">

By default, the left icon (literal) is selected. This represents the old behavior - when you enter a value, it gets populated in the dagfile as a string. For example, if you enter `my_schema` in the cell input form field, in the dagfile it appears as `"my_string"`. However, sometimes a user wants more control or a more advanced input - this is where they can use the expression input. By clicking the expression icon (to the right of the literal icon), the input changes to a code block. See screenshot below.

<img width="734" alt="Screen Shot 2023-03-20 at 1 56 50 PM" src="https://user-images.githubusercontent.com/5252587/226426380-d747de16-d8d2-46a8-87ac-d8db0cc30bb8.png">

This allows them to enter a Python expression directly. For example, this could be a reference to a variable declared in the global imports, an Airflow/environment variable, etc. When a user enters `my_schema` in this field, in the dagfile it becomes `my_schema` directly (no quotes).

**Are you the right person to review a draft of the document for technical accuracy? If not, who is?**

Yes

**Comment by jwitz** [comment]
Also, did we add more configurable fields for Warehouse SQL cells? I could have sworn that we only had **Output table** a few weeks ago.

**Comment by jlaneve** [comment]
The literal/expression switching will be available to all applicable fields, which becomes more prevalent with custom and registry cell types. We only have non-code inputs today with the Warehouse SQL cell, which is why I called that one out specifically here. But, if you create a custom cell type, _all_ fields will have this functionality.
