### ISSUE TITLE
Guide for ExternalPythonOperator on Astro Runtime

### ISSUE THREAD

**Issue by RNHTTR** [astronomer/docs#2050]
**Request type:**

- [x] **New tutorial:**: Add the `docs-content` and `area/learn` labels to this issue.
- [ ] **New Airflow concept:**: Add the `docs-content` and `area/learn` label to this issue.
- [ ] **Addition to an existing guide**: Add the `area-learn` and `enhancement` labels to this issue.

**Use case or feature that should be covered:**
How to use the ExternalPythonOperator for Astro Runtime.

**Who the guide is intended for:**
e.g. users who are new to Airflow, users who are migrating from a legacy scheduler, etc.
Any Astro Runtime user who needs to use a Python version different than 3.9. Specifically folks migrating from Astronomer Certified

**Are you the right person to review a draft of the guide for technical accuracy? If not, who is?**
I think I can review a draft.

**Comment by jwitz** [comment]
We do have a specific tutorial on using the ExternalPythonOperator with Snowpark: https://docs.astronomer.io/learn/external-python-operator

Agreed that we could use a dedicated topic/ page solely for understanding the ExternalPythonOperator outside of the tutorial context
