### ISSUE TITLE
Release note subheadings are too big

### ISSUE THREAD

**Issue by collinmcnulty** [astronomer/docs#2055]
**Affected Document:**
Release notes

**Problem Type (Priority):**

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [ ] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [X] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**
The subheadings on release notes look remarkably similar to the main headings. It is difficult at a glance to determine that they're components of a release above, not separate releases.

![image](https://user-images.githubusercontent.com/13177948/227576737-f6e07556-4894-4289-a7c7-2e2e1b0f2ac4.png)

**Comment by lzdanski** [comment]
Closing issue due to time since it was opened, currently can't get to these kinds of enhancements given our priorities.
