### ISSUE TITLE
Clarify precedence in Airflow connections guide

### ISSUE THREAD

**Issue by kentdanas** [astronomer/docs#2057]
**Affected Document:** https://docs.astronomer.io/learn/connections

**Problem Type (Priority):**

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [x] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):** Somewhere in this guide we should mention which methods of defining connections take precedence (i.e. if the same connection is defined differently as an env var and in the UI, which does Airflow choose). 

**Additional Notes:** I couldn't find this info in the [Airflow docs](https://airflow.apache.org/docs/apache-airflow/stable/howto/connection.html) either, so we may have to ask internally how this works.

**Comment by manmeetkaur** [comment]
@kentdanas have you checked this PR - https://github.com/astronomer/docs/pull/2219 - this explains the issues that you have mentioned. Anything that you feel is missing ? (also it is mentioned on [this](https://docs.astronomer.io/astro/secrets-backend#benefits) page)

**Comment by kentdanas** [comment]
@manmeetkaur that PR does answer the question, but the original request was to add that info to this Learn guide: https://docs.astronomer.io/learn/connections. Not sure what the plan is for consolidating your PR with that guide (or if there is one), but if we're going to maintain both docs we should have the note about precedence in both places.
