### ISSUE TITLE
Astronomer version table with support timelines

### ISSUE THREAD

**Issue by danielhoherd** [astronomer/docs#206]
**Request type:**

- [ ] **New document:**: Add the `docs-content` label to this issue.
- [X] **Addition to an existing document**: Add the `enhancement` label to this issue.

**What is the purpose of the document/enhancement? Select all that apply:**

- [ ] Document a new feature for an upcoming release. Add the appropriate release version label to this issue.
- [ ] Information for an existing feature that isn't yet documented.
- [X] Additional considerations/ reference material for an existing document.

**Problem/feature that requires documentation:**

As a follow-up to https://github.com/astronomer/docs-archived/issues/516 in which I think I was ambiguous, I'd like to see a version table for Astronomer releases with their release and end-of-support dates. Currently I only see a table showing dates for AC and airflow, not Astronomer Enterprise.

For instance, I would like to know when 0.16 is EOL and we will stop supporting it. Where do I find that information?

**Are you the right person to review a draft of the document for technical accuracy? If not, who is?**

Honestly I'm not sure.

**Comment by paolaperaza** [comment]
@danielhoherd We actually just published an official "Enterprise Version Lifecycle Policy" here: https://docs.astronomer.io/enterprise/release-lifecycle-policy/

That addresses a few things:
- How Astronomer is versioned
- Which versions of Astronomer Enterprise are currently available
- Release channels and the maintenance schedule for all versions

Screenshot here for the section you're looking for:

![image](https://user-images.githubusercontent.com/31111752/146567819-b5d0bc6d-9475-483f-a354-441c6667daea.png)

Closing out this GitHub issue.
