### ISSUE TITLE
Astro alerts: Pipeline alerting

### ISSUE THREAD

**Issue by harels** [astronomer/docs#2064]
PRD: https://docs.google.com/document/d/1MsvjUJeAmRrE4lFOUkSVPCXOA5BUN4nn5_iZHElcAB0/edit
Design doc: https://docs.google.com/document/d/16x3wG0hfNjYmrWLImJ-bmfROzbro2YVGMXu6EuvZ4dU/edit#heading=h.gkc7jij2ajm6

Alerts can be defined in Workspace Settings:
<img width="1790" alt="image" src="https://user-images.githubusercontent.com/1336663/228031301-c517dbff-3ada-4dcd-9f41-e1533c5f990b.png">

We can alert on Pipeline (DAG) failure or task duration currently, and we can send notifications to PagerDuty and Slack:
<img width="858" alt="image" src="https://user-images.githubusercontent.com/1336663/228031486-d32e7670-9e46-4cc0-9604-fcd518d92524.png">

We would need to add an instructions page on how a customer would create a slack webhook, I have a sketch here: https://docs.google.com/document/d/1tcfVcAHm-2NhKQ7-8fZ5PAQ9ZOra8aI6WdaJqOEyiEw/edit?usp=sharing
Maybe we should also link to the example doc in slack for more details.

For PagerDuty, a user also needs to provide an integration key - that should be available from PagerDuty's side as well. Not sure if we want to create our own docs or redirect there?

Other workflows:
- Add Pipelines / Tasks to an existing alert rule
- Edit config to alert rule
- delete tasks / pipelines from alert rule
- delete alert rule

IMPORTANT to note that SLA duration alerting for tasks only works for Airflow 2.5+. Exact version requirements are specified in the PRD.

When we introduce the docs for this, please tag myself and @wslulciuc to review.

This feature will be in Private Preview right now, targeting GA sometime in April. do we want the docs live before GA?

**Comment by paolaperaza** [comment]
**Notes from Meeting with @harels and @lzdanski**

- You can pick individual DAGs and tasks for each of the alerts. Most customers will do this.
- You can also do bulk iteration
- Extra button that says `Edit Alerts` next to Deployments -- but for now all of this is in the Workspace page
- Go to Slack application, this webhook goes to these channels
- The Slack webhook URL you can use for more than 1 Workspace
- PagerDuty -- you need to create an integration if you don't have one, and an events API v2
- Why Airflow Alerts via. Astro Alerts
      - You don't have to modify your code, at the task or DAG level
      -  Astro has a growing alerting framework
      - You don't have to set up SMTP. Email alerts on Astro is coming soon.
- You can't do this in Astro CLI yet, but that's coming

<img width="1143" alt="image" src="https://user-images.githubusercontent.com/31111752/229631908-93baedb2-b241-482e-8b58-0562e97259ae.png">

<img width="984" alt="image" src="https://user-images.githubusercontent.com/31111752/229632075-1186c30a-66ab-4816-ad5f-b8c667b497cc.png">

**Comment by lzdanski** [comment]
Notes for external resource:
    - You must have Events API v2 for pager duty through add an integration
        - [https://developer.pagerduty.com/docs/ZG9jOjExMDI5NTgw-events-api-v2-overview#getting-started](https://developer.pagerduty.com/docs/ZG9jOjExMDI5NTgw-events-api-v2-overview#getting-started)

**Comment by lzdanski** [comment]
Preview docs published: https://docs.astronomer.io/astro/pipeline-alerts
