### ISSUE TITLE
Collapse Astro CLI menus for all top-level commands

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#2065]
### Context

We've recently collapsed the `organization` and `workspace` command sub-menus in the Astro CLI docs, but we haven't done it for all top-level commands.

<img width="279" alt="image" src="https://user-images.githubusercontent.com/31111752/228095438-e81a1552-a8c6-4228-97a1-041f17bdf7d8.png">

This makes it easier to find what you need at a glance and get a better idea of the functionality that the Astro CLI has.

### Ask

- [ ] Let's do this for the following sub-commands as well:
        - `astro user`
        - `astro dev`
        - `astro deployment`
        - `astro context`
        - `astro config`
- [ ] Make sure to keep these organized in alphabetical order (aka not my list above)

**Comment by jwitz** [comment]
This was easy enough to hotfix, closing out! https://github.com/astronomer/docs/commit/e9e7ff4d2019cb2bfb0ecfc2899d9734dcbdab53
