### ISSUE TITLE
Add Upgrade to 0.23 to sidebar for 0.23 site

### ISSUE THREAD

**Issue by rbankston** [astronomer/docs#207]
**Request type:**

- [ ] **New document:**: Add the `docs-content` label to this issue.
- [x] **Addition to an existing document**: Add the `enhancement` label to this issue.

**What is the purpose of the document/enhancement? Select all that apply:**

- [ ] Document a new feature for an upcoming release. Add the appropriate release version label to this issue.
- [x] Information for an existing feature that isn't yet documented.
- [ ] Additional considerations/ reference material for an existing document.

**Problem/feature that requires documentation:**
https://docs.astronomer.io/enterprise/0.23/upgrade-to-0-23/

isn't linked in the sidebar for the 0.23 documentation

**Are you the right person to review a draft of the document for technical accuracy? If not, who is?**

**Comment by jwitz** [comment]
Ty for the catch @rbankston, should be fixed now!
