### ISSUE TITLE
Add more info on deleted Deployments + refresh rate of Astro Usage tab

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#2085]
### Context

From @magdagultekin:

> I was looking for an info [here](https://docs.astronomer.io/astro/deployment-metrics#astro-usage) about how frequently the Usage tab is being refresh and didn't find anything about that - do we know what's the time interval? If so, could we add it to the doc?

### Ask

- [ ] Confirm two things with @conorbev or in #product-astro:
      - How often does this tab get refreshed with task count?
      - Do deleted Deployments show up here?
- [ ] Update the Astro Usage section with this info: https://docs.astronomer.io/astro/deployment-metrics#astro-usage

**Comment by jwitz** [comment]
Following up on this in Slack, but seems like the deleted Deployments thing is a bug that hasn't been fixed.

**Comment by jwitz** [comment]
Not heard another request for this since and there's some known issues with the usage tab. Given how we're shifting from task run pricing to other pricing types, I'm gonna close this out.
