### ISSUE TITLE
Confusion on Runtime vs. Global Env Vars

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#2086]
### Context

From @ReadytoRocc:

> Parallelism is not listed here in our [Global Environment doc](https://docs.astronomer.io/astro/platform-variables). Is this not automatically set based on the Worker Concurrency & Max Worker Count of a deployment?

We currently have two places where we document system env vars:

- System env Vars that you can't change: https://docs.astronomer.io/astro/platform-variables
- Smart defaults in Astro Runtime: https://docs.astronomer.io/astro/runtime-image-architecture

That thematically makes sense, but might be net-more confusing for users.

### Ask

Reconsider this approach. We can either:

1. Add clearer linkage between the two sections, and link out to runtime arch doc in worker queues or Kube Exec doc
2. Remove that section from the Astro Runtime doc and just have it all in the global env vars doc

Let's chat as a docs team about this and get a PR in front of @ReadytoRocc to review.

**Comment by jwitz** [comment]
Whoops I accidentally pushed the changes to main 😬 https://github.com/astronomer/docs/commit/ee758642465b58a16d8270d8983f5802e51532a1

Seems straightforward enough though, feel free to make suggestions around the wording I used
