### ISSUE TITLE
Enterprise: Houston Error Logging into Astro via Auth0

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#21]
An Enterprise customer mid-install is seeing a Houston error where users that are assigned the app in Okta are able to successfully authenticate to Okta via Auth0 but they can’t access the Astronomer app.

Error:

```
[DEBUG] Executing GQL resolver for operation 'authConfig' 
Failed to finalize OAuth flow
Error: You are not authorized to login, please contact the platform owner to request an invitation.
    at AuthorizationRoute.action (/usr/lib/node_modules/houston-api/src/routes/oauth.js:40:19)
    at <anonymous>
```

@vparekh94 It looks like it just means that user has to first create an account/workspace/perhaps deployment on Astronomer if they're the first user, so we should just add a note that having access through Auth0 and Okta doesn't by default give you access to a teammate's workspace, and a breakdown of the right steps to do so.

(This is all just from what I can tell - so whoever has more related knoweldge feel free to throw in more context or correct me if I'm wrong)

**Comment by vparekh94** [comment]
@paolaperaza I think this is an old issue from Conde that we ended up resolving. There's no action I can take on it now so going to close - we can re-open if it comes up again
