### ISSUE TITLE
Update screenshots for invite members

### ISSUE THREAD

**Issue by lzdanski** [astronomer/docs#2113]
**Affected Document:**
https://docs.astronomer.io/astro/add-user#add-a-user-to-an-organization

**Problem Type (Priority):**

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [x] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**
![image (1)](https://user-images.githubusercontent.com/25642903/230454305-b40248c2-8eab-4ba5-b38e-e70f4e4c8754.png)
![image (2)](https://user-images.githubusercontent.com/25642903/230454437-5f2beca9-c624-4899-8a13-7b3d8cf0d49a.png)

Crop screenshots to remove email addresses and replace deprecated ones in the doc for inviting new members.

**Additional Notes:**

**Comment by lzdanski** [comment]
<img width="1467" alt="Screenshot 2023-04-06 at 1 55 25 PM" src="https://user-images.githubusercontent.com/25642903/230469886-fc87bb9c-634c-4afe-9ac0-44ce63938f92.png">

**Comment by jwitz** [comment]
I'd even be up for removing these screenshots entirely, the path to these buttons seems pretty obvious based on the text instructions (it wasn't as obvious when those screenshots were taken)
