### ISSUE TITLE
Fix all references to `WORKSPACE_VIEWER` to `WORKSPACE_MEMBER`

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#2147]
Originally reported by a customer via @pohek321 - https://astronomer.slack.com/archives/CL44PA4DB/p1681752028479329

### Context

We no longer use `WORKSPACE VIEWER` as a role in Astro, but this language is still in this doc: https://docs.astronomer.io/astro/user-permissions. Jake recently hot-fixed a similar change in CLI docs.

<img width="628" alt="image" src="https://user-images.githubusercontent.com/31111752/232572915-6f267ea8-de69-4751-b00e-6c718c19466f.png">

### Ask

- [ ] Check ALL instances of "workspace viewer" in all of our docs
- [ ] Change to Workspace member
- [ ] Make sure that this change is documented in release notes somewhere

**Comment by jwitz** [comment]
There was only one remaining reference with Workspace Viewer in Astro left, so I hotfixed it: https://github.com/astronomer/docs/commit/92d63e1c00453e98e58d1c06dff5fba8f2310c40
