### ISSUE TITLE
Add pubDate to RSS feed for each item

### ISSUE THREAD

**Issue by stuart23** [astronomer/docs#2156]
Following up to the PR https://github.com/astronomer/docs/pull/2044, we need to add a pubDate attribute to each element of the channel.

_We had requested the <pubDate> element be added and it's currently only present under <channel> but in order for the Slack integration to work, the <pubDate> is needed under each <item> element in the feed._

Resources
https://slack.com/intl/en-in/help/articles/218688467-Add-RSS-feeds-to-Slack
https://docs.astronomer.io/astro/release-notes-subscribe

**Comment by javihernovoa** [comment]
Hi, I noticed the message is missing some text, here's the full thing:

We had requested the <pubDate> element be added and it's currently only present under <channel> but in order for the Slack integration to work, the <pubDate> is needed under each <item> element in the feed.
