### ISSUE TITLE
Azure Enterprise Install - change sslmode from 'require' to 'prefer'

### ISSUE THREAD

**Issue by aspain** [astronomer/docs#218]
**Affected Document:**
https://docs.astronomer.io/enterprise/install-azure

**Problem Type (Priority):**

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [X] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**
1. In the 2 locations below, update the sslmode setting`require` to `prefer`
2. Update the 'Configure the Database' command

**Additional Notes:**
After speaking w/ @park-peter and other folks on Solutions Eng team, there have been issues when using `sslmode=require` and customers have had issues where we end up instructing them to update this value in their helm chart.

There are 2 locations in the guide where it would need to change from `require` to `prefer`: 
1. In the [Configure the Database](https://docs.astronomer.io/enterprise/install-azure#step-6-configure-the-database) section it mentions  "it enforces TLS/SSL and requires that you set sslmode to **require** in your config.yaml."
2. In Step 7 '[Configure Helm Chart](https://docs.astronomer.io/enterprise/install-azure#step-7-configure-your-helm-chart)' step, in the config.yaml example in the SSL section it mentions:

```
  ssl:
    enabled: true
    mode: "require"
 ```

Additionally, the [Configure the Database](https://docs.astronomer.io/enterprise/install-azure/#step-6-configure-the-database) command for Azure should be updated by removing the `/<DATABASE>?sslmode=<mode>"` portion, to match the command shown in GCP install guide. Also, since the step earlier in "[Create a Kubernetes Namespace](https://docs.astronomer.io/enterprise/0.25/install-azure#step-3-create-a-kubernetes-namespace)" sets the namespace to `Astronomer`, the command should have this included rather than `<your-namespace>`

Current Azure command:
```
kubectl create secret generic astronomer-bootstrap --from-literal connection="postgres://<USERNAME>:<PASSWORD>@<HOST>:5432/<DATABASE>?sslmode=<mode>" --namespace <your-namespace>
```

What it should be updated to:
```
kubectl create secret generic astronomer-bootstrap \
  --from-literal connection="postgres://USERNAME:$PASSWORD@host:5432" \
  --namespace astronomer
```

**Comment by fritz-astronomer** [comment]
👍 this - just spent a decent chunk of time re-discovering the same fix :/
