### ISSUE TITLE
Enhance S3 and GCS CI/CD templates to support project configuration

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#2185]
**Affected Document:** https://docs.astronomer.io/astro/ci-cd-templates/aws-s3 and https://docs.astronomer.io/astro/ci-cd-templates/gcs

Our bucket-based templates allow users to deploy DAGs to Astro without worrying about deploying an image. However, admins or other managers cannot use these templates to update project configurations without potentially overriding their Astro DAGs.

If you make a project configuration change with an out of date version of DAGs (because the DAGs and the Astro project are hosted in two separate places), the image rebuild will deploy the out of date DAGs. We should create an action/ workflow that accounts for users wanting to make configuration changes, and if possible this should be automated and without risk to DAG deploys.

**Comment by manmeetkaur** [comment]
This is in progress, did some work for MoonActive for this. will create the PR next week.

**Comment by jwitz** [comment]
@manmeetkaur Do you have any updated templates that we can update ththeese docs with? Otherwise I might close this issue out

**Comment by manmeetkaur** [comment]
Not atm. We can close this out for now. will revisit later.
