### ISSUE TITLE
Make "--no-hooks" section more visible as really non-default option which has to be considered before usage

### ISSUE THREAD

**Issue by afastronomer** [astronomer/docs#2192]
**Affected Document:**
https://docs.astronomer.io/software/upgrade-astronomer#running-the-030-upgrade-script-with---no-hooks

**Problem Type (Priority):**

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [x] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**
This section looks like a one more step and people accidentally use it. Please make it more visible as uncommon option, what is **possible to set** but only **when you have reasons**. For common cases - you don't need it.

**Additional Notes:**

**Comment by jwitz** [comment]
I can't make it more hidden, but I did make the language more clear. Hopefully it's harder to misinterpret the steps now! https://github.com/astronomer/docs/commit/7e83e1bffdcc72f7afeebd07d998b52c6f68732d
