### ISSUE TITLE
Incorrect Link in Deployment Logs docs (both Cloud & Enterprise)

### ISSUE THREAD

**Issue by ben-astro** [astronomer/docs#220]
## What kind of documentation change are you requesting?
* **Fix to an existing document**: See below for what labels to add
  
#### _Link to affected document(s):_
https://www.astronomer.io/docs/cloud/stable/deploy/deployment-logs
https://www.astronomer.io/docs/enterprise/v0.23/deploy/deployment-logs
  
#### _How severe is the problem?_
- [ X] Critical: The document has incorrect or missing information that is preventing customers from being successful (Add the `error/itf` label to this issue).
Marking as critical as link to appropriate guide is not included (i.e. missing info). 

- [ ] FYI: The document could benefit from a change, but there's nothing that's currently preventing customers from being successful without it (Add the `error/useful` label to this issue).
- [ ] Typo: There's a noticeable grammar, spelling, or formatting issue in a document (Add the `error/typo` label to this issue). 
  
#### _Describe your suggestion for the change. In addition, include links to any relevant existing documentation, support tickets, messages, or external content:_
I do not know what link/guide/article to which this link is supposed to point
  
### Other Context
_Add any additional context about the problem here._

I was leveraging this doc in support of a potential cloud customer who is attempting to programmatically grab logs from our Houston API.

**Comment by paolaperaza** [comment]
Hotfix here: https://github.com/astronomer/docs/commit/404e0fc9ea2a6a015ed831eeb21f532442d73b87?short_path=b4dd331#diff-b4dd331548ebdb5f00826a9834b7775cfe4db5300fe5469fd69f6599b4fd6982
