### ISSUE TITLE
Private Repo Instructions Outdated for Software

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#222]
@collinmcnulty commented on [Thu Sep 30 2021](https://github.com/astronomer/docs-archived/issues/476)

**Affected Document:** https://www.astronomer.io/docs/cloud/stable/develop/customize-image#build-from-a-private-repository
  
**Severity:**

- [X] Critical: This document has incorrect or missing information. Add the `error/critical` label to this issue.
- [ ] FYI: The document is misleading or could benefit from additional context or guidance. Add the `error/FYI` label to this issue.
- [ ] Typo: Add the `error/typo` label to this issue.
  
**Suggested Change:**

Update the document to include instructions that work on a buster image. It's currently built with alpine, and just changing apk to apt-get apparently doesn't work. I don't quite know how to make the instructions correct and don't fully understand how the dockerfile is working.

Triggered by a customer ticket https://astronomer.zendesk.com/agent/tickets/6210

**Additional Notes:** 

---

@collinmcnulty commented on [Thu Sep 30 2021](https://github.com/astronomer/docs-archived/issues/476#issuecomment-931622600)

@paolaperaza

**Comment by paolaperaza** [comment]
Outdated instructions in Software doc reported by customers: https://astronomer.zendesk.com/agent/tickets/9443

> As we were trying that out, we noticed that the documentation isn't compatible with the newer versions of the certified image. For example, the base is a Debian image so we need to use `apt-get` instead of `apk`. Is there an updated example? If not, can you confirm that the same process of using Dockerfile.build is still supported?
> 
> Apart from doing our customizations, am I correct in assuming we just need the build file to execute the ONBUILD commands? Is there a place where I can see those and just copy-paste them?
