### ISSUE TITLE
Update to Pipeline/Slack Alerts

### ISSUE THREAD

**Issue by lzdanski** [astronomer/docs#2226]
**Affected Document:**
https://docs.astronomer.io/astro/alerts

**Problem Type (Priority):**

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [x] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**

1. It's a bit hard to find the service integrations section, needs a small adjustment in setting the context. 

* For pagerduty description - https://docs.astronomer.io/astro/alerts?tab=PagerDuty#step-1-configure-your-communication-channel
* In the pager duty console, go to the service where you want to receive your pipeline alerts. 
* Go to integrations
* Add another integration

2. We need screenshots of Slack and PagerDuty for illustration purposes

**Additional Notes:**

**Comment by lzdanski** [comment]
Related - https://github.com/astronomer/docs/issues/2064

**Comment by manmeetkaur** [comment]
<img width="859" alt="5  PagerDuty Events API V2 Copy Integration Key" src="https://github.com/astronomer/docs/assets/75730393/35ac58bd-3221-4a8e-b37d-fd9ecb2cf514">
<img width="1290" alt="4  PagerDuty Events API V2 Settings" src="https://github.com/astronomer/docs/assets/75730393/d4c1af57-0e82-4739-a107-092b51389984">
<img width="722" alt="3  PagerDuty Add Integration" src="https://github.com/astronomer/docs/assets/75730393/794ca1c8-0eac-4964-8e01-2f7c56a3b53d">
<img width="891" alt="2  PagerDuty Integrations" src="https://github.com/astronomer/docs/assets/75730393/e4f873c5-6b70-4a06-9cf4-e8f4adc1ea93">
<img width="1718" alt="1  PagerDuty Service Page" src="https://github.com/astronomer/docs/assets/75730393/eeb7dadf-7dee-457f-9c9c-86140afaa55e">
