### ISSUE TITLE
Deployment Tuning

### ISSUE THREAD

**Issue by erdos2n** [astronomer/docs#2227]
**Request type:**

- [ X] **New document:** Add the `docs-content` label to this issue.
- [ ] **Addition to an existing document**: Add the `enhancement` label to this issue.

**What is the purpose of the document/enhancement? Select all that apply:**

- [ ] Document a new feature for an upcoming release. Add the appropriate release version label to this issue.
- [ ] Information for an existing feature that isn't yet documented.
- [ X] Additional considerations/ reference material for an existing document.

**Problem/feature that requires documentation:**
This document is intended to help customers tune their deployment parameters if they're having consistent issues with scheduler liveness probe failures, triggerer liveness probe failures and webserver liveness probe failures. 

There are some good best practices to put in place and some knobs they can turn to help alleviate this issue, depending on what they experience. 

**Are you the right person to review a draft of the document for technical accuracy? If not, who is?**
Yes, but would also love more eyes on it if possible

**Comment by paolaperaza** [comment]
Closing in favor of: https://github.com/astronomer/docs/issues/3545
