### ISSUE TITLE
Astro-runtime release notes 8.0.0 notifier links broken

### ISSUE THREAD

**Issue by 17jmumford** [astronomer/docs#2233]
**Affected Document:**
Astro-runtime release notes
**Problem Type (Priority):**
- [ ] Error (non-critical): The 8.0.0 release notes has links to notifier and slack notifier that don't work.

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**
Replace links. 
**Additional Notes:**
Correct link to slack notifier: https://airflow.apache.org/docs/apache-airflow-providers-slack/stable/_api/airflow/providers/slack/notifications/slack_notifier/index.html#airflow.providers.slack.notifications.slack_notifier.SlackNotifier

Link to creating a notifier: https://airflow.apache.org/docs/apache-airflow/stable/howto/notifications.html

**Comment by lzdanski** [comment]
@17jmumford - Thanks so much for reporting this! We really appreciate it.
