### ISSUE TITLE
Add steps for exporting logs to 3rd party monitoring services

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#225]
@jwitz commented on [Tue Sep 14 2021](https://github.com/astronomer/docs-archived/issues/459)

**Request type:**

- [ ] **New document:**: Add the `newcontent` label to this issue. 
- [X] **Significant change to an existing document**: Add the `enhancement` label to this issue. 

**What is the purpose of the document/enhancement? Select all that apply:**

- [ ] Document a new feature for an upcoming release. Add the appropriate release version label to this issue. 
- [X] Information for an existing feature that isn't yet documented.
- [ ] Additional considerations/ reference material for an existing feature or document.

**Problem/feature that requires documentation:** We need to document how to export logs to CloudWatch and New Relic, as well as any other services we eventually extend exportability to. This information can live in our existing Logging doc in our Enterprise docset.

**Comment by kwcanuck** [comment]
@jwitz or @paolaperaza is this still something we want to document? With the recent discussions about Datadog, perhaps this issue should be closed? If not, I'm happy to take it on.

**Comment by jwitz** [comment]
Oof this is an ancient issue, I think it makes more sense to close this and open up more specific issues as we develop official workflows for exporting logs as we did with Datadog.
