### ISSUE TITLE
Cloud IDE custom and registry cell types

### ISSUE THREAD

**Issue by jlaneve** [astronomer/docs#2250]
**Request type:**

- [x] **New document:** Add the `docs-content` label to this issue.
- [ ] **Addition to an existing document**: Add the `enhancement` label to this issue.

**What is the purpose of the document/enhancement? Select all that apply:**

- [x] Document a new feature for an upcoming release. Add the appropriate release version label to this issue.
- [ ] Information for an existing feature that isn't yet documented.
- [ ] Additional considerations/ reference material for an existing document.

**Problem/feature that requires documentation:**

We plan to release custom and registry cell types in the Cloud IDE in the next ~2 weeks (they're currently under a feature flag).

For custom cell types, I have some docs written here already: https://www.notion.so/astronomerio/Cloud-IDE-Custom-Cell-Types-21220202d3174cfaa5b40b9da993197b?pvs=4

For Registry cell types, I scheduled time with @jwitz and @paolaperaza to review, but can also write up a draft if helpful.

**Are you the right person to review a draft of the document for technical accuracy? If not, who is?**

Yes

**Comment by jwitz** [comment]
Notes from meeting:

## Custom cells 

Custom cells are no longer used for OSS operators, but they could be used to limit OSS parameters on a purely visual basis. 

Custom operator code is only stored on GitHub, but configs are available to everyone

## Registry cell

Do not refer to as "registry cell", that's an implementation detail

Some parameters are automatically detected with the right format, but it’s not guaranteed that we get all right. The ones we can’t detect are interpreted as an expression by default. 

Literal expression: User input is not formatted at all, we don’t clock errors 

Python expression: Safety wheels, IDE helps you format the value

Possible rename to “Operator cell”, frame around Airflow operator usage

AsyncOperator cells don’t work, sensors don’t work when you run them 

When you add a cell type from a provider package, we automatically add requirements to all projects. To remove the dependency, you have to delete all cell types using that dependency

## To do

Build submenu that’s more action-oriented, don’t focus on cells focus on actions. 

Julian to add custom cell type config in example doc
