### ISSUE TITLE
How to mount Kubernetes Secrets on KubernetesPodOperators

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#226]
@wolfier commented on [Fri Jun 25 2021](https://github.com/astronomer/docs-archived/issues/399)

**Request type:**

- [ ] **New document:**: Add the `newcontent` label to this issue. 
- [x] **Significant change to an existing document**: Add the `enhancement` label to this issue. 

**What is the purpose of the document/enhancement? Select all that apply:**

- [ ] Document a new feature for an upcoming release. Add the appropriate release version label to this issue. 
- [ ] Information for an existing feature that isn't yet documented.
- [x] Additional considerations/ reference material for an existing feature or document.

**Problem/feature that requires documentation:**
 
A customer has provided feedback that instructions for how to use mount Kubernetse Secrets on KubernetesPodOperators is not available in the our documentation on [KubernetesPodOperator](https://www.astronomer.io/docs/cloud/stable/customize-airflow/kubepodoperator).

I know this is not Astronomer specific but I wanted to ask anyway. 

If the better place for this information to go is an example in the Airflow documentation, please close out this issue.

**Are you the right person to review a draft of the document for technical accuracy? If not, who is?**

Yes, I would like to review it.

**Additional Information**:

Zendesk Ticket: 
https://astronomer.zendesk.com/agent/tickets/5150
https://astronomer.zendesk.com/agent/tickets/5148

---

@jwitz commented on [Mon Oct 11 2021](https://github.com/astronomer/docs-archived/issues/399#issuecomment-939864054)

@wolfier There seems to be a decent amount of secret mounting examples on [this page](https://airflow.apache.org/docs/apache-airflow-providers-cncf-kubernetes/stable/operators.html#how-to-use-cluster-configmaps-secrets-and-volumes-with-pod), are they looking for anything more specific than that? I think linking there is a good first step, but agreed that we should have more detailed documentation akin to [Cloud Composer](https://cloud.google.com/composer/docs/how-to/using/using-kubernetes-pod-operator#secret-config). I would need somebody else to write that content, though.

**Comment by wolfier** [comment]
Yeah I agree linking the [apache-airflow-providers-cncf-kubernetes](https://airflow.apache.org/docs/apache-airflow-providers-cncf-kubernetes/stable/operators.html#how-to-use-cluster-configmaps-secrets-and-volumes-with-pod) docs would be a good first step!

**Comment by jwitz** [comment]
We have an example of mounting secrets within the context of running an image from a private registry, so there's some information here: https://docs.astronomer.io/astro/kubernetespodoperator#step-1-create-a-kubernetes-secret

Given that we're expanding our Airflow guides and integrating those closer to docs soon, I think it's better to wait on documenting this until we have a better platform for documenting product-agnostic Airflow advice.

**Comment by kwcanuck** [comment]
@jwitz the links have been added as discussed. PR incoming.
