### ISSUE TITLE
New Tutorial: MLOps with Dynamic task mapping

### ISSUE THREAD

**Issue by TJaniF** [astronomer/docs#2261]
**Request type:**

- [X] **New tutorial:**: Add the `docs-content` and `area/learn` labels to this issue.

**Use case or feature that should be covered:**
Using dynamic task mapping to train different models in the same DAG.

**Who the guide is intended for:**
MLOps and ML engineers interested in Airflow.

**Are you the right person to review a draft of the guide for technical accuracy? If not, who is?**
Well, I have an example DAG made by @mpgreg :)

**Comment by kentdanas** [comment]
Will be a use case, rather than tutorial

**Comment by kentdanas** [comment]
@TJaniF I think given performance of use cases on Learn that this would be better suited for the blog. I updated the Notion backlog task, and am going to close this issue.
