### ISSUE TITLE
Entire Code life-cycle CI/CD using image-based and DAG-based deploy

### ISSUE THREAD

**Issue by manmeetkaur** [astronomer/docs#2266]
**Request type:**

- [X] **New document:** Add the `docs-content` label to this issue.
- [ ] **Addition to an existing document**: Add the `enhancement` label to this issue.

**What is the purpose of the document/enhancement? Select all that apply:**

- [ ] Document a new feature for an upcoming release. Add the appropriate release version label to this issue.
- [ ] Information for an existing feature that isn't yet documented.
- [X] Additional considerations/ reference material for an existing document.

**Problem/feature that requires documentation:** 

**Are you the right person to review a draft of the document for technical accuracy? If not, who is?**

**Comment by jwitz** [comment]
@manmeetkaur I think this is a duplicate of https://github.com/astronomer/docs/issues/2185

**Comment by manmeetkaur** [comment]
> @manmeetkaur I think this is a duplicate of #2185

you are correct sir! i will close this one.
