### ISSUE TITLE
0.25 and 0.23 Debugging your cluster are incorrect for postgresql usage

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#227]
@rbankston commented on [Mon Jun 21 2021](https://github.com/astronomer/docs-archived/issues/393)

**Affected Document:**
  https://www.astronomer.io/docs/enterprise/v0.25/troubleshoot/debug-install and https://www.astronomer.io/docs/enterprise/v0.23/troubleshoot/debug-install

**Severity:**

- [ ] Critical: This document has incorrect or missing information. Add the `error/critical` label to this issue.
- [x] FYI: The document is misleading or could benefit from additional context or guidance. Add the `error/FYI` label to this issue.
- [ ] Typo: Add the `error/typo` label to this issue.
  
**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**

Page looks like it comes from 0.16 when houston ran as root. Houston now only runs as houston. You can exec into one of the stan or nats pods to run the same commands as the root user.

**Additional Notes:**

**Comment by jwitz** [comment]
@rbankston Can you list the specific commands here that need updating? I'm not super familiar with this workflow or our various pods

**Comment by rbankston** [comment]
Hey @jwitz and @kwcanuck  

The graphic shows prisma which hasn't existed since 0.16 in our platform. Only Houston and Grafana connect directly and aren't root so you can no longer apk add postgresql directly. 

You can start a postgresql pod in your cluster and attempt to connect with it by running:

```
kubectl run psql --rm -it --restart=Never --namespace <astronomer-namespace> --image bitnami/postgresql --command -- psql $(kubectl get secret -n astronomer astronomer-houston-backend --template='{{.data.connection | base64decode }}' | sed 's/?.*//g')
```
