### ISSUE TITLE
Clarify sub-steps in Step 4: Configure TLS of Enterprise 0.23 GKE install guide

### ISSUE THREAD

**Issue by kentdanas** [astronomer/docs#228]
## What kind of documentation change are you requesting?
Fix

#### _Link to affected document:_
https://www.astronomer.io/docs/enterprise/v0.23/install/gcp/install-gcp-standard#step-4-configure-tls
  
#### _How severe is the problem?_
FYI
  
#### _Describe your suggestion for the change. In addition, include links to any relevant existing documentation, support tickets, messages, or external content:_
In Step 4, there are four sub-headers at the same level, two with different options for obtaining a cert, one with a step that only applies to private CAs, and one for creating a k8s secret, which is always necessary. We received some feedback from a prospect that they did not complete the k8s secret step because they assumed it was not needed if proceeding with Option 1 for generating the cert because of how the headers were laid out. Maybe there is a way we can clarify the steps in this section to ensure users understand what is/is not required in each case. For example, maybe something like this:
###Obtain a TLS Certificate
####Option 1...
####Option 2...
###Verify certificate order (private CA only)
###Create a Kubernetes secret

**Comment by jwitz** [comment]
@kentdanas This is interesting, and I'm sorry that a prospect had trouble following these steps. It was my understanding that you only had to create a Kubernetes secret if you requested the certificate from your organization. In our [Renew TLS](https://www.astronomer.io/docs/enterprise/v0.23/manage-astronomer/renew-tls-cert) guide, I had assumed that the ClusterIssuer and Certificate Resources managed that process. 

If creating a Kubernetes secret is always necessary, I can break that out into its own step. If it's only necessary for certificates issues through a security team, then I think moving that topic closer to the option 2 instructions (and potentially getting rid of the header) would suffice. What do you think?

**Comment by kentdanas** [comment]
@jwitz my experience is a little limited here, but my understanding is that you shouldn't need to recreate the k8s secret when you renew the cert. But when you are installing initially you always need to create the k8s secret, so the generally steps are obtain a cert (and there are multiple ways you can do this), then create the k8s secret for that cert. If you don't create the secret, the cluster won't be able to find the cert and the helm install of the platform will fail. So I think for clarification it would be helpful to note somehow, either through changing the header layout or something else, that this step is necessary regardless of which option you used for generating the cert.

**Comment by jwitz** [comment]
Sounds good, I will get on this ASAP and add you for review to confirm that the new structure of steps makes sense based on the prospect's feedback. Thank you for writing this up!
