### ISSUE TITLE
Programmatic Access to Deployments

### ISSUE THREAD

**Issue by manmeetkaur** [astronomer/docs#2286]
Our docs have a document that talks about [Manage Deployments as Code](https://docs.astronomer.io/astro/manage-deployments-as-code); But it is either missing some commands or is too long where the customer was unable to find it and/or refer it. 

Related [Slack Thread](https://astronomer.slack.com/archives/C03CT3DNZMH/p1683801595695069)

**Comment by jwitz** [comment]
@manmeetkaur I see that the linked PR for API tokens will close this issue, but in the original Slack thread we discussed making a new doc that described all of the ways you can programmatically authenticate to Astro. Do you still think that's something we should do? If so, I can start a draft.

**Comment by jwitz** [comment]
Reassigning this to @manmeetkaur as part of her "Run Astro scripts" documentation

**Comment by manmeetkaur** [comment]
Addressed in #2595
