### ISSUE TITLE
Explain different ways we can access GCP/AWS Services from Astro.

### ISSUE THREAD

**Issue by manmeetkaur** [astronomer/docs#2300]
**Request type:**

- [x] **New document:** Add the `docs-content` label to this issue.
- [ ] **Addition to an existing document**: Add the `enhancement` label to this issue.

**What is the purpose of the document/enhancement? Select all that apply:**

- [ ] Document a new feature for an upcoming release. Add the appropriate release version label to this issue.
- [ ] Information for an existing feature that isn't yet documented.
- [x] Additional considerations/ reference material for an existing document.

**Problem/feature that requires documentation:** 
The [current document](https://docs.astronomer.io/astro/connect-gcp#authorization-options) that talks about connecting to GCP services is very brief and leaves a lot to "figure-out" without defining a clear path. My intention behind creating this issue is to clearly define different authorization methods, their steps and the pros/cons of each allowing the user to decide what to chose. 

When a new customer is onboarded, if they have a template to follow for connection, authorization with step-by-step guidance which they can self-refer , it will reduce the burden of CSE.

Reference slack thread: https://astronomer.slack.com/archives/C03L31FBXM5/p1684340846649079

**Are you the right person to review a draft of the document for technical accuracy? If not, who is?**

**Comment by jwitz** [comment]
Btw @manmeetkaur I'm making some edits to these docs as part of the updates for Hosted, let me know if there's anything I should immediately include for launch! 

Related: https://github.com/astronomer/docs/issues/1957
