### ISSUE TITLE
Backport provider version specification

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#231]
@jwitz commented on [Fri Apr 30 2021](https://github.com/astronomer/docs-archived/issues/336)

@wolfier commented on [Fri Apr 30 2021](https://github.com/astronomer/issues/issues/2928)

**What kind of documentation change are you requesting?** backport provider version specification

**For new documents, answer the following questions**

_What is the purpose of the document? Select all that apply:_
- [ ] Setup steps a new feature for an upcoming release (Add the appropriate version label to this issue). 
- [ ] Information for an existing feature that isn't yet documented.
- [x] Additional considerations/ reference material for an existing feature or document.

_Describe the problem that requires documentation:_ 

The behaviour when installing backport packages with pinned version in the `requirements.txt` file for Airflow 1.10.x install OSS apache-airflow 1.10.15. This is **expected** behaviour due to requirements of the backport providers.

The requirement for the backport provider is `<2.0.0` where `1!2.0.0` is not less than `2.0.0`. In SemVer / Python packaging a version with 1! (epoch) is always greater than any version without an epoch.

Here is an example of `requirement.txt` that will produce behaviour that may confuse the user.
```
apache-airflow-backport-providers-cncf-kubernetes==2021.3.3
```

The current workaround is to not pin the version or specify the `1!` prefix of the pinned version.

`requirement.txt` requesting the latest available version.
```
apache-airflow-backport-providers-cncf-kubernetes
```

`requirement.txt` with the prefix.
```
apache-airflow-backport-providers-cncf-kubernetes==2021.3.3
```

I do not believe we have any documentation on using backport providers. I'm also not sure where it should go. 

_Describe the documentation request, making sure to outline what users should be able to achieve with the doc. In addition, include links to any relevant existing documentation, support tickets, messages, or external content:_

Zendesk: https://astronomer.zendesk.com/agent/tickets/4436

_Are you the right person to review a draft of the document for technical accuracy? If not, who is?_ @kaxil 

---

@kaxil commented on [Fri Apr 30 2021](https://github.com/astronomer/docs-archived/issues/336#issuecomment-830342929)

Yeah me or Ash could review it

**Comment by paolaperaza** [comment]
@wolfier This is an old one... is this problem still relevant do you think? Perhaps not since we've standardize on 2.0 on Astro? Or are you still running into this on Software?

cc: @cmarteepants

**Comment by cmarteepants** [comment]
IMO we can close this one out

**Comment by kwcanuck** [comment]
@wolfier indicated in a Slack conversation "I think we can close it out as noted by constance". Closing the issue.
