### ISSUE TITLE
Astro Teams feature

### ISSUE THREAD

**Issue by manmeetkaur** [astronomer/docs#2318]
**Request type:**

- [X] **New document:** Add the `docs-content` label to this issue.
- [] **Addition to an existing document**: Add the `enhancement` label to this issue.

**What is the purpose of the document/enhancement? Select all that apply:**

- [X] Document a new feature for an upcoming release. Add the appropriate release version label to this issue.
- [ ] Information for an existing feature that isn't yet documented.
- [ ] Additional considerations/ reference material for an existing document.

**Problem/feature that requires documentation:**

Teams feature is launching soon in Astro, which will be available in Organization and Workspace Access Management.

**Are you the right person to review a draft of the document for technical accuracy? If not, who is?**

**Comment by chomipi88** [comment]
Thanks for creating the issue @manmeetkaur.

Astro Teams is a new user management concept in Astro to help alleviate and streamline user management responsibilities. A team is a group of users that can be granted a Workspace role vs having to grant individual user access. A user can also be granted a Workspace role individually. In that case, the higher privileged role takes precedence.

Organization Owners are able to create, update, and delete Teams. Both Organization Owners and Workspace Admins can grant a Workspace role to a team. The same team can be granted different roles to different Workspaces.

**Comment by lzdanski** [comment]
- Updated through the Cloud UI
- Have to be org owner to create a team, org owner is defined in org settings
- Can use https://cloud.astronomer.io/clh66n3gn00jk01i7hzg2d158/settings/access/teams for screenshots about workspace level teams
- Only organization owners can create/modify/delete teams but workspace admin can add teams to workspace/change role.

Target Timeframe - sometime this week would be ideal

**Comment by lzdanski** [comment]
- [ ] Add a section to Manage Astro Users about Creating Teams (https://docs.astronomer.io/astro/add-user)
- [ ] Update Manage Astro User permissions with information about how to use teams (https://docs.astronomer.io/astro/user-permissions)
- [ ] Add section about how workspace admins can control adding teams to workspaces/changing their role within workspace (new doc, but near https://docs.astronomer.io/astro/workspace-api-tokens in nav)
- [ ] Add section to both org access management and workspace access management about what level of permissions are honored when a user receives individual permissions that differ from the team permissions.

**Comment by lzdanski** [comment]
@chomipi88 - A couple of questions

- I made a Docs team and added you + me to it, but when I added that team to a workspace with only me, it did not add the other Team members to the workspace.

<img width="1223" alt="Screenshot 2023-05-23 at 5 54 10 PM" src="https://github.com/astronomer/docs/assets/25642903/3a8ff946-6a2f-4311-8076-485c4e005e9a">
<img width="1287" alt="Screenshot 2023-05-23 at 5 53 52 PM" src="https://github.com/astronomer/docs/assets/25642903/5085d3dc-2816-4b7a-a4f7-e16736358144">

**Comment by chomipi88** [comment]
@lzdanski you are listed as a user because you created the workspace. Under the Teams tab you can see the Team, members and roles as per your screenshot.
