### ISSUE TITLE
Diagram to explain Workspace & Deployment relationship

### ISSUE THREAD

**Issue by manmeetkaur** [astronomer/docs#2321]
**Problem Statement**: We have many components in Astro which interact with each other and are related to each other. For example, Cluster, Workspace, Deployment, Worker Queues, Worker Node Pool etc. We do not have diagrams to clearly demarcate the line between Infrastructure components and logical components and how they impact the user and organization's use of Astro.

I am hoping this issue be one of the first in the series of issues that will involve around a graphical representation of Astro not just from a high-level. 

We can start with the most basic and commonly used components that a user can easily relate to. 

Workspace -> Deployment -> Airflow

@paolaperaza do we want to also define a specific format, shapes that we will use. Should we use Figma or can we just use Lucid to create these like I did [here](https://docs.astronomer.io/astro/modify-cluster#about-worker-node-pools)

**Comment by lzdanski** [comment]
Related - the workspace + organization relationship with regards to user access. Piotr made a diagram in relation to the Astro teams and user access work (https://github.com/astronomer/docs/issues/2318) and it might be helpful here as well. https://www.figma.com/file/tqfDMHtOjbrSqQSTFoUZZe/Astro-RBAC---Current?type=whiteboard&node-id=0%3A1&t=OovjsJAXr60ZAzBY-1

**Comment by jwitz** [comment]
Per https://github.com/astronomer/docs/issues/2320, would be good to have an overview arch of RBAC in our "Astro Architecture"as well as an in-depth one deeper in documentation

**Comment by jwitz** [comment]
![Screenshot 2023-06-12 at 4 22 20 PM](https://github.com/astronomer/docs/assets/74574233/6dc17c32-2cb7-493a-bf1f-5147967452b7)
Simple RBAC diagram

**Comment by manmeetkaur** [comment]
more requests coming for this https://astronomer.slack.com/archives/C015V2JFKT5/p1689082545405859
