### ISSUE TITLE
Explain the differences between HA Deployment vs non-HA Deployment

### ISSUE THREAD

**Issue by manmeetkaur** [astronomer/docs#2323]
With Astro Hosted going live today, we have a new feature that is getting released, HA vs non-HA deployment.

I am not sure if have details of what HA and non-HA means, are all components HA , what is the scope of **all**, does it mean multi-AZ, how it impacts the costs and so on. 

We can try to find the answers from Product, and if get clarity well and good, if not, I can run some tests when I come back from my vacation. 

<img width="186" alt="Screenshot 2023-05-23 at 11 41 02 AM" src="https://github.com/astronomer/docs/assets/75730393/aea243f1-6514-4385-adb4-cc61a8ec4849">

**Comment by jwitz** [comment]
Follow up:

Clarify high availability on Hybrid, list components for Hosted/ Hybrid that _are_ highly available. Clarify how many instances, or how we scale.

Work with @chomipi88 and @cmarteepants to get clarity on these answers.
