### ISSUE TITLE
rename Astro dbt provider to Cosmos

### ISSUE THREAD

**Issue by harels** [astronomer/docs#2331]
There are a few place where we refer to Cosmos as `Astro dbt provider`.
We are trying to build more steam around community efforts there, and we mostly call is Cosmos.
We should make sure our docs reflect that as well, and we should probably call this Cosmos across the board.

**Comment by kentdanas** [comment]
@TJaniF can you incorporate this change into your PR that updates the example in this tutorial?

**Comment by TJaniF** [comment]
Very happy to do that :)
