### ISSUE TITLE
DAG default params now convert empty string to null

### ISSUE THREAD

**Issue by masonhopkins** [astronomer/docs#2342]
We just recently upgraded to the latest Astro runtime `FROM quay.io/astronomer/astro-runtime:8.2.0`, and now default params that are intentionally set to empty strings are interpreted as null when triggering manually (with/without config). The previous behavior is that params with empty strings set as default were also empty strings in the UI. I don't think null should be the expected result when setting a default arg as an empty string, as an empty string may be an intentional choice.

New behavior:
![Screen Shot 2023-05-26 at 4 41 48 PM](https://github.com/astronomer/docs/assets/77858111/ec1775a8-811d-44f5-9a13-25c2f9e69045)

Old behavior:
![Screen Shot 2023-05-26 at 4 42 00 PM](https://github.com/astronomer/docs/assets/77858111/a747428f-6adc-42f4-a662-4991629455c0)

**Comment by jwitz** [comment]
I'm going to close this out, as it's unrelated to Astro functionality or documentation.
