### ISSUE TITLE
Fully document Houston API

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#235]
@jwitz commented on [Thu Dec 17 2020](https://github.com/astronomer/docs-archived/issues/139)

@schnie commented on [Mon Jun 29 2020](https://github.com/astronomer/issues/issues/1472)

Right now we only have some very targeted, use-case specific documentation on Houston's API.

A lot of folks want to directly integrate astronomer into their other software so this is becoming a critical issue.

In addition to documenting this API, we'll need to think about how we evolve the API. We haven't paid too much effort into ensuring anything other than our CLI and UI are compatible. We need to start thinking about how we transition old APIs away and introduce new ones.

This can all be part of the documentation. There may be some automated stuff we can get from using GraphQL. I haven't looked in a while, but I vaguely remember something.

---

@vishwas-astro commented on [Tue Jul 21 2020](https://github.com/astronomer/issues/issues/1472#issuecomment-661642035)

@schnie may be https://github.com/2fd/graphdoc OR https://www.npmjs.com/package/graphql-docs

May be we can pull this into an Aug or September release.

---

@schnie commented on [Wed Jul 22 2020](https://github.com/astronomer/issues/issues/1472#issuecomment-662656765)

Yea I'm testing graphdoc as well as with the playground.

Can grab some screenshots soon.

---

@vishwas-astro commented on [Mon Aug 31 2020](https://github.com/astronomer/issues/issues/1472#issuecomment-683877628)

NATS was priority for 0.19. Prisma2 and Deployment level RBAC in Astro app is taking the team's time for 0.20. We will re-visit this as soon as possible after that.

**Comment by kwcanuck** [comment]
@jwitz is fully documenting the Houston API still required? I see that we have an existing topic ([Houston API](https://docs.astronomer.io/software/houston-api)) that seems to provide this information. Can you confirm if this is still required?

Temporarily assigning this to you for analysis and a response. Thanks!

**Comment by jwitz** [comment]
Yeah I don't think this is ever going to be a priority. By "fully documenting the Houston API," we mean "document all possible mutations/ values/ objects that you can run queries on". This is already a reality in the GraphQL playground linked in the doc. 

Creating static docs for this that aren't generated directly off of the Houston API code is a maintenance nightmare, so let's wait until we have a more elegant solution for generating these docs. Closing for now.
