### ISSUE TITLE
Integrations simplification: Sagemaker

### ISSUE THREAD

**Issue by TJaniF** [astronomer/docs#2350]
**Request type:**

- [x] **Addition to an existing guide**: Add the `area-learn` and `enhancement` labels to this issue.

**Use case or feature that should be covered:**

Short tutorial showing how to use Airflow with AWS Sagemaker. 

**Who the guide is intended for:**
Users who want to know how to use Airflow with AWS Sagemaker.

**Are you the right person to review a draft of the guide for technical accuracy? If not, who is?**
@mpgreg or @fletchjeff ?

**Comment by kentdanas** [comment]
Let's not touch this one - it would be hard to simplify it more than it already is given the use case.
