### ISSUE TITLE
Integrations simplification: Azure Container Services

### ISSUE THREAD

**Issue by TJaniF** [astronomer/docs#2352]
**Request type:**

- [x] **Addition to an existing guide**: Add the `area-learn` and `enhancement` labels to this issue.

**Use case or feature that should be covered:**

Short tutorial showing how to use Airflow with Azure Container Instances. The existing tutorial is already fairly simple, maybe a question of removing some of the explanation surrounding it.

**Who the guide is intended for:**
Users who want to know how to use Airflow with Azure Container Instances.

**Are you the right person to review a draft of the guide for technical accuracy? If not, who is?**
?

**Comment by kentdanas** [comment]
Closing this one - the explanation around the example is fine, we just don't want the examples to be overly complex or include a lot of other tools :)
