### ISSUE TITLE
Integrations simplification: Azure Data Explorer

### ISSUE THREAD

**Issue by TJaniF** [astronomer/docs#2353]
**Request type:**

- [x] **Addition to an existing guide**: Add the `area-learn` and `enhancement` labels to this issue.

**Use case or feature that should be covered:**

Short tutorial showing how to use Airflow with Azure Data Explorer. The existing example is already pretty simple.

**Who the guide is intended for:**
Users who want to know how to use Airflow with Azure Data Explorer.

**Are you the right person to review a draft of the guide for technical accuracy? If not, who is?**
?

**Comment by kentdanas** [comment]
I think this one can remain as-is. There's nothing extraneous in the current example DAG, so I'll close this for now
