### ISSUE TITLE
Integration simplification: ADF

### ISSUE THREAD

**Issue by TJaniF** [astronomer/docs#2354]
**Request type:**

- [x] **Addition to an existing guide**: Add the `area-learn` and `enhancement` labels to this issue.

**Use case or feature that should be covered:**

Short tutorial showing how to use Airflow with ADF. There are a lot of Azure screenshot up front, DAG code is a bit further down.

**Who the guide is intended for:**
Users who want to know how to use Airflow with ADF.

**Are you the right person to review a draft of the guide for technical accuracy? If not, who is?**
?

**Comment by kentdanas** [comment]
I'm going to update a few of the screenshots in this one to clean it up, but otherwise I think the example is fine as is. I don't want to actually get rid of that first section, since it is important for running the example, and was tricky to figure out.
