### ISSUE TITLE
Integration simplification: Talend

### ISSUE THREAD

**Issue by TJaniF** [astronomer/docs#2361]
**Request type:**

- [x] **Addition to an existing guide**: Add the `area-learn` and `enhancement` labels to this issue.

**Use case or feature that should be covered:**

Short tutorial showing how to use Airflow with Talend. Is not in tutorial format yet.

**Who the guide is intended for:**
Users who want to know how to use Airflow with Talend

**Are you the right person to review a draft of the guide for technical accuracy? If not, who is?**
?

**Comment by kentdanas** [comment]
This one can be very low priority. It gets hardly any views and I don't think Talend is nearly as popular now as it was when we first wrote this.

**Comment by kentdanas** [comment]
Actually, I'm going to close this. I don't think it's worth touching this one.
