### ISSUE TITLE
Integration simplification: W&B

### ISSUE THREAD

**Issue by TJaniF** [astronomer/docs#2362]
**Request type:**

- [x] **Addition to an existing guide**: Add the `area-learn` and `enhancement` labels to this issue.

**Use case or feature that should be covered:**

Short tutorial showing how to use Airflow with W&B. Very new tutorial but with a longer use case.

**Who the guide is intended for:**
Users who want to know how to use Airflow with W&B.

**Are you the right person to review a draft of the guide for technical accuracy? If not, who is?**
@kentdanas , @mpgreg

**Comment by kentdanas** [comment]
This one is already about as simple as it can reasonably be while still showing how the integration works.
