### ISSUE TITLE
CLI Quickstart / General Quickstart are redundant

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#237]
@jwitz commented on [Tue Jan 05 2021](https://github.com/astronomer/docs-archived/issues/183)

About half of our [CLI Quickstart guide](https://www.astronomer.io/docs/cloud/stable/develop/cli-quickstart) is redundant to the [general quickstart guide ](https://www.astronomer.io/docs/cloud/stable/get-started/quickstart). At some point, we should consider having one comprehensive Quickstart guide while moving all CLI-specific info to a separately-titled document.

**Comment by paolaperaza** [comment]
Our Gen2 docs address this redundancy by having separate docs for the following:

- Install the Astronomer CLI
- Create a Project
- Develop a Project
- Test and Troubleshoot Locally


@jwitz I'm going to go ahead and close this out for now.... let's revisit/create a new issue when we're ready to adapt this change to Enterprise docs and redefine the need here with a new scope.
