### ISSUE TITLE
Add example of workspace level API key usage

### ISSUE THREAD

**Issue by afastronomer** [astronomer/docs#2372]
### Issue Type

Missing or misleading content

### Links to Affected Docs

https://docs.astronomer.io/software/ci-cd#workspace-level-service-account

### Describe the Issue and Proposed Fix

Our examples are showing different manipulations with particular deployment. Some customers would like to use `workspace API key`  powerful permissions to manage deployments via CI\CD. Could you please add examples for deployment creation\deletion.

**Comment by lzdanski** [comment]
Closing issue as API keys have been deprecated in favor of API tokens as of 10/10.
