### ISSUE TITLE
Add Docs and Release Notes for Billing & Pay via Credit Card

### ISSUE THREAD

**Issue by nicholasfilippi** [astronomer/docs#2383]
### New Feature Description

Customers are now able to fully subscribe to our Astro Hosted Basic plan by adding their credit card through the Astro UI.  This subscription does not require any upfront fee or annual commitment, and customers only pay for what they actually use.  Customers that are willing to commit to an annual contract are encouraged to engage with our sales team to explore potential discounts.

The ability to enter your credit card can be found within the Org Settings > Billing page.  

In addition, we provide accurate usage during your billing cycle to monitor consumption and spend.  Note that this data may have up to a 2 hour delay.

### Required Reviewers

Dee Zhou

### Links to Internal Info or Resources

Engineering
https://www.notion.so/astronomerio/Billing-Hosted-Engineering-2023-Q2-ecd006fa2c114f1babf5157e41092032

### Release date

6/13/2023

**Comment by jwitz** [comment]
Notes from meeting:

- Credits will not be implemented in time but there will be a UI element for credits
- Billing email autofills and is the email used for credit alerts (TBD)
- For current trial users, accrued charges will be nonzero but balance due will be zero.
- **Invoices** page will show breakdown of bill by component usage
    - **Quantity** is number of hours
    - At 10AM, usage will be grabbed from 8AM - 9AM

- **Usage** page shows total hours across multiple Deployments, meaning you could have 25 hours in one day for a Deployment type.
