### ISSUE TITLE
Add a note Resource Quotas is only for Hosted customers

### ISSUE THREAD

**Issue by manmeetkaur** [astronomer/docs#2424]
Wasn’t sure exactly where to ask this, but trying to follow this <https://docs.astronomer.io/astro/kubernetespodoperator#configure-the-kubernetespodoperator-in-the-cloud-ui|Astro Documentation> for configuring resource quotas, but I don’t see anything labeled “Resource quotas” in the Cloud UI view for a deployment…

[Slack Message](https://astronomer.slack.com/archives/C01UA03TPV1/p1686589787145299?thread_ts=1686589787.145299&cid=C01UA03TPV1)

**Comment by jwitz** [comment]
Looks like this issue was fixed when we merged the refactor of our executor docs.
