### ISSUE TITLE
Improve Windows CLI Doc

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#243]
@petedejoy commented on [Fri Nov 15 2019](https://github.com/astronomer/issues/issues/563)

We had a prospect (JustEat) run into issues following our [Windows CLI doc](https://www.astronomer.io/docs/cli-installation-windows-10/). We have a more up-to-date [Windows + Airflow guide](https://www.astronomer.io/guides/airflow-wsl/), but we should port all Astronomer-specific information over to that CLI doc so that we're consistent and up-to-date.

Guides should be approached as community-facing marketing material whereas docs should be user-facing product material.

---

@vparekh94 commented on [Mon Nov 25 2019](https://github.com/astronomer/issues/issues/563#issuecomment-558238419)

- [ ] Remove  https://www.astronomer.io/docs/cli-installation-windows-10/
- [ ] Create installation/setup page on CLI with each section hashed out
- [ ] Add link to this https://www.astronomer.io/guides/airflow-wsl/ and preface it with suggestion with using WSL
- [ ] Verify how the CLI works in windows natively

---

@andrewhharmon commented on [Fri Jan 10 2020](https://github.com/astronomer/issues/issues/563#issuecomment-573196102)

got a comment from the user that the link for the native windows cli points to 8.3... not sure how we get that pointing to the latest. maybe just link to the release page and not a particular version

**Comment by paolaperaza** [comment]
Closing! Handled

- Here: https://docs.astronomer.io/software/install-cli
- Here: https://docs.astronomer.io/astro/cli/configure-cli#install-the-cli
