### ISSUE TITLE
Secrets backends docs commands don't work

### ISSUE THREAD

**Issue by jlaneve** [astronomer/docs#2431]
### Issue Type

Typo

### Links to Affected Docs

https://docs.astronomer.io/astro/secrets-backend#deploy-environment-variables-to-astro

These commands don't work (at least, not on macOS):

```
$ astro deployment variable create --deployment-id <your-deployment-id> AIRFLOW__SECRETS__BACKEND_KWARGS={"connections_prefix": "airflow/connections", "variables_prefix": "airflow/variables",  "role_arn": "<your-role-arn>", "region_name": "<your-region>"} --secret
```

### Describe the Issue and Proposed Fix

The `{ ... }` needs to be surrounded by quotes, like so:

```
$ astro deployment variable create --deployment-id <your-deployment-id> AIRFLOW__SECRETS__BACKEND_KWARGS='{"connections_prefix": "airflow/connections", "variables_prefix": "airflow/variables",  "role_arn": "<your-role-arn>", "region_name": "<your-region>"}' --secret
```

**Comment by jwitz** [comment]
Seemed simple enough to hotfix, did just that! Thanks for catching it https://github.com/astronomer/docs/commit/8a323b58b4ea0b452772e07ccd10ae96f3781c65
