### ISSUE TITLE
UniversalTransferOperator tutorial

### ISSUE THREAD

**Issue by TJaniF** [astronomer/docs#2432]
### Content type

Airflow tutorials

### Request type

New guide for a specific use case (for example, how to integrate Airflow with a specific 3rd party tool)

### Describe your Learn request.

A short tutorial showing how to use the UTO: https://github.com/astronomer/apache-airflow-provider-transfers

### Desired publish date

If possible before a related webinar/live

### Reviewer

Yes

**Comment by kentdanas** [comment]
Closing this for now since UTO is not being actively developed and likely eventually replaced by ObjectStore
