### ISSUE TITLE
Add `Is this Helpful?` To Sigma

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#2439]
### Context

We recently shipped a new `Was this page helpful?` feedback widget at the bottom of every single doc. This data is being tracked as a Segment event that is going into Snowflake.

PR: https://github.com/astronomer/docs/pull/2408

### Ask

Let's:
- Confirm where exactly in Snowflake this is going, and what the name of the event is (cc: @katiebrady-astro)
- Add this to our Docs Sigma Dashboard, ideally a list of docs with aggregate thumbs up/thumbs down responses each
- Need to be able to filter over time

**Comment by jwitz** [comment]
I've made a request for the data team to ingest these Segment events into Sigma

**Comment by katiebrady-astro** [comment]
Hey @paolaperaza and @jwitz! The Segment event name is `Feedback Button Click`.
<img width="368" alt="image" src="https://github.com/astronomer/docs/assets/96535736/73b00993-ed58-4550-802e-532854e23f9f">

**Comment by jwitz** [comment]
https://astronomer.atlassian.net/servicedesk/customer/portal/1/DM-121

Closing this out from the repo, as there's no more work to be done on our end
