### ISSUE TITLE
Table formatting bug

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#245]
**Affected Document:** https://docs.astronomer.io/cloud/runtime-version-lifecycle-policy

**Problem Type (Priority):**

We need to fix our table formatting for tables that don't scroll. Small tables still look as if they're loading into a big table:

![Screen Shot 2021-12-20 at 10 52 27 AM](https://user-images.githubusercontent.com/74574233/146756061-ff3f196f-d259-4d3b-9b9d-8a4b8ce7a1f8.png)

**Comment by brittanyleigh** [comment]
@ryanahamilton Can you take a look at this? The current styles I added awhile back to get large, scrollable tables looking good but that's got these small tables looking wonky. I'm not sure of a solution that addresses small tables without undoing the styling for large tables. 🤔

**Comment by ryanahamilton** [comment]
> @ryanahamilton Can you take a look at this? The current styles I added awhile back to get large, scrollable tables looking good but that's got these small tables looking wonky. I'm not sure of a solution that addresses small tables without undoing the styling for large tables. 🤔

The `display: block;` on the table element really isn't ideal. The ideal solution would probably involve having a custom wrapper div around all tables for us to handle the overflow. Not sure if there's a future solution where we could have universal control over particular elements like that? That said, I was fiddling with it in my inspector and it appears that you can add `max-width: fit-content;` to the table and it will yield the desired result.
