### ISSUE TITLE
Sharepoint and Airflow integration

### ISSUE THREAD

**Issue by manmeetkaur** [astronomer/docs#2452]
### Content type

Integrations

### Request type

New guide for a specific use case (for example, how to integrate Airflow with a specific 3rd party tool)

### Describe your Learn request.

Sharepoint is widely used in the Microsoft world and I happened to integrate it with Airflow for someone. it is not easy and pretty tricky. I have the notes on the steps. Can compile and share the steps.

**Comment by TJaniF** [comment]
Thank you! Yeah, I heard about people using Sharepoint a lot but I think I never did so myself. Yes please, send me the steps 🦸‍♀️ ❤️ ! :)

**Comment by manmeetkaur** [comment]
@TJaniF sorry for the delay on this, here you go - https://www.notion.so/astronomerio/Sharepoint-and-Airflow-Integration-67d7ceae6d544be491c71782e7a77155?pvs=4

Please feel free to reach out if you run into any issues.

**Comment by kentdanas** [comment]
New integration docs that don't map to one of our company initiatives are not going to be a priority for DevRel. But @manmeetkaur if you'd like to PR something we'll happily review :)
