### ISSUE TITLE
Need more complete documentation about how to customize the Python version on ap-airflow on cloud Gen1

### ISSUE THREAD

**Issue by alex-astronomer** [astronomer/docs#247]
**Affected Document:**
https://www.astronomer.io/docs/cloud/stable/develop/customize-image#build-with-a-different-python-version

**Problem Type (Priority):**

- [x] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [ ] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**
Two step process:

1. `docker build --build-arg PYTHON_MAJOR_MINOR_VERSION=3.7 --build-arg VERSION=2.2.0-4 -t ap-airflow:2.2.0-python-3.7 https://github.com/astronomer/ap-airflow.git#master:2.2.0/bullseye`
2. `docker build -f Dockerfile.onbuild-bullseye --build-arg baseimage=ap-airflow:2.2.0-python-3.7 -t ap-airflow:2.2.0-python-3.7-onbuild https://github.com/astronomer/ap-airflow.git#master:common`

**Additional Notes:**
First step builds the ap-airflow image with the custom Python version.

Second step takes that image and turns it into the onbuild image that is required.

**Comment by jwitz** [comment]
Closing this out, as it looks like it's been merged on cloud
