### ISSUE TITLE
Debug DAG from PyCharm

### ISSUE THREAD

**Issue by manmeetkaur** [astronomer/docs#2470]
### Content type

Airflow tutorials

### Request type

New guide for a specific use case (for example, how to integrate Airflow with a specific 3rd party tool)

### Describe your Learn request.

It is based on this forum post - https://forum.astronomer.io/t/how-to-run-dag-from-code-pycharm-without-getting-message-no-run-dates-were-found-for-the-given-dates-and-dag-interval/1824. Will add details after I dig more.

**Comment by kentdanas** [comment]
@manmeetkaur is this issue actually something related to PyCharm? At first glance it seems like their issue may be that the `schedule` is None, so no DAG runs are created with the `dag.run` backfill? Unless this is indeed something PyCharm specific, I don't think we need a separate guide for this. We already have a section on using `dag.test()` [here](https://docs.astronomer.io/learn/testing-airflow#debug-interactively-with-dagtest), which we would recommend over using debug executor anyway.

**Comment by manmeetkaur** [comment]
closing based on the comment above
