### ISSUE TITLE
Self-Service Cluster Creation for Hosted Dedicated in Azure

### ISSUE THREAD

**Issue by cmarteepants** [astronomer/docs#2478]
### New Feature Description

We are planning on turning on self-service cluster creation in Hosted Dedicated in Azure. This will align the hosted experience for Azure to how it works for AWS and GCP.

### Required Reviewers

@melugoyal (Mehul)

### Release Date

We are planning on enabling the feature flag next week, after the prod release. https://app.launchdarkly.com/default/production/features/enableAutomatedHostedAzure/targeting

### Additional Notes

As far as I can tell, this is what will need to be updated: https://docs.astronomer.io/astro/create-dedicated-cluster?tab=azure#create-a-cluster

The steps are roughly the same as AWS. We will need customers to choose a region, and provide us with a subnet range. The default is fine.

![CleanShot 2023-06-23 at 13 24 25](https://github.com/astronomer/docs/assets/34171166/36cb0222-95f9-49a9-b6d0-24fc44cf27ee)

**Comment by melugoyal** [comment]
@jwitz planning on enabling this as part of tomorrow's release. will the docs be ready?

**Comment by jwitz** [comment]
@melugoyal Yes, should have a PR out shortly!

**Comment by cmarteepants** [comment]
@jwitz do we plan to update [https://docs.astronomer.io/astro/create-dedicated-cluster?tab=azure#create-a-cluster](https://docs.astronomer.io/astro/create-dedicated-cluster?tab=azure#create-a-cluster) or just release notes?

**Comment by melugoyal** [comment]
fyi, i'm holding off on flipping the feature flag till the above is resolved

**Comment by jwitz** [comment]
Oh whoops, I missed the Create Cluster docs when I made the updates yesterday. Will get these updated today!

**Comment by jwitz** [comment]
Closing out as missing docs have been added back
