### ISSUE TITLE
Audit logs are downloaded as ndjson, not json

### ISSUE THREAD

**Issue by cdabella** [astronomer/docs#2483]
Unless something has changed, audit logs are exported as new-line delimited JSON, not pure JSON. Maybe worth linking to https://github.com/ndjson/ndjson-spec as well.

https://github.com/astronomer/docs/blob/a28f7be13affbe3b8f488a1efb97df27748c7f8d/astro/audit-logs.md?plain=1#L25

**Comment by jwitz** [comment]
Closed this via hotfix! https://github.com/astronomer/docs/commit/520f66fe73b67b825d6eb66d1643d9d4bfdf0b38
