### ISSUE TITLE
Email Notification Channel for Alerts

### ISSUE THREAD

**Issue by AmandaYao00** [astronomer/docs#2489]
### New Feature Description

We are adding a email notification channel to alerts. This feature has been requested by customers who want to receive email notifications for alerts.

Users are able to configure any number of emails for an alert. 
<img width="1393" alt="Screenshot 2023-06-27 at 12 52 36 PM" src="https://github.com/astronomer/docs/assets/70288484/2028621a-c51c-4864-bd4e-1c3831facfa7">

### Required Reviewers

Willy Lulciuc, Peter Hicks, Julian LaNeve

### Links to Internal Info or Resources

Users can click on a "learn more" link when configuring an alert, which takes them to this page: https://docs.astronomer.io/astro/alerts?tab=Slack. There are currently tabs for Slack and PagerDuty, and we want to add a page for Email.

### Release Date

Merged to Dev, expected release date next week.

**Comment by jwitz** [comment]
@AmandaYao00 Is there an updated timeline for this release? I'm not seeing it in production

**Comment by AmandaYao00** [comment]
@jwitz Oh yes, thanks for pointing it out! The release was delayed. We merged the code into dev yesterday and are expecting to see it in prod next week.
