### ISSUE TITLE
Enterprise - Upgrade Astronomer page has formatting issue

### ISSUE THREAD

**Issue by aspain** [astronomer/docs#249]
**Affected Document:**
https://docs.astronomer.io/enterprise/upgrade-astronomer-stable#step-3-run-astronomers-patch-upgrade-script
**Problem Type (Priority):**

- [X] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [ ] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**

**Additional Notes:**
Screenshot of formatting issue:
![image](https://user-images.githubusercontent.com/15913202/146982386-632fb92b-03d0-487b-bee7-1795212bf474.png)

**Comment by jwitz** [comment]
Thanks for the catch @aspain ! Closed out with https://github.com/astronomer/docs/pull/251/files
