### ISSUE TITLE
Add GCP option to 'table of contents' at top secrets backend page

### ISSUE THREAD

**Issue by aspain** [astronomer/docs#250]
**Affected Document:**
https://docs.astronomer.io/enterprise/secrets-backend/

**Problem Type (Priority):**

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [X] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**
GCP should be added to the 'table of contents' section at the top since it is included at the bottom: https://docs.astronomer.io/enterprise/secrets-backend/#google-cloud-secret-manager

```
This guide will walk you through how to leverage Airflow's latest feature on Astronomer with specific instructions for the following tools:

Hashicorp Vault
AWS SSM Parameter Store
```

**Additional Notes:**

**Comment by jwitz** [comment]
[Hotfixed](https://github.com/astronomer/docs/commit/1c055be50d9aad8befd7dd49da1dd271f45ff844)! Thank you @aspain
