### ISSUE TITLE
Example screen shot shows ability to upgrade to 2.0 when a Deployment is on 1.10.7

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#251]
**Affected Document:** https://www.astronomer.io/docs/cloud/stable/customize-airflow/manage-airflow-versions
  
**Severity:**

- [ ] Critical: This document has incorrect or missing information. Add the `error/critical` label to this issue.
- [X] FYI: The document is misleading or could benefit from additional context or guidance. Add the `error/FYI` label to this issue.
- [ ] Typo: Add the `error/typo` label to this issue.
  
**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):** Our current screen shots on this doc show that Airflow 2.0 is a possible upgrade option when a Deployment is on 1.10.7, but this is not the case. We've since blocked upgrades like this, so we should update the screen shot to either show an upgrade from 1.10.14 to 2.0.0 or from 1.10.7 to 1.10.14.

**Comment by paolaperaza** [comment]
All done here! Doc: https://www.astronomer.io/docs/cloud/stable/customize-airflow/manage-airflow-versions

New GIF here, showing a user upgrading from 1.10.7 to 1.10.4 (and 2.0 grayed out): 
![airflow-upgrade-astro-ui](https://user-images.githubusercontent.com/31111752/108007053-3e044700-6fba-11eb-9477-f59c9a1e6fec.gif)
