### ISSUE TITLE
0.25 version used in "Upgrade to v0.26" Doc

### ISSUE THREAD

**Issue by danielhoherd** [astronomer/docs#254]
**Affected Document:**

https://docs.astronomer.io/enterprise/0.26/upgrade-astronomer-stable/

**Problem Type (Priority):**

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [X] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**

This page refers to 0.25 but the doc is for 0.26

**Additional notes**

Could be a good case to start using [cog](https://til.simonwillison.net/python/cog-to-update-help-in-readme) ?

**Comment by paolaperaza** [comment]
Thanks for reporting this @danielhoherd! Sorry you ran into this. We're indeed working on cleaning up our process around versioned changes.

Change to this doc in progress in a PR with a few more changes here: https://github.com/astronomer/docs/pull/256
