### ISSUE TITLE
add "helm release name" warning to the lts upgrade doc

### ISSUE THREAD

**Issue by krisdock** [astronomer/docs#254]
**Affected Document:**

https://www.astronomer.io/docs/enterprise/v0.23/manage-astronomer/upgrade-to-0-23
  
**Severity:**

- [x] Critical: This document has incorrect or missing information. Add the `error/critical` label to this issue.
- [ ] FYI: The document is misleading or could benefit from additional context or guidance. Add the `error/FYI` label to this issue.
- [ ] Typo: Add the `error/typo` label to this issue.
  
**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**

we need to add a note to this doc instructing customers to find their helm release name. the standard is "astronomer", but some customers change this or allow helm to pick a name. if there's a hyphen in the name of their helm release, this upgrade script won't currently work.

**Additional Notes:**

**Comment by jwitz** [comment]
Closing this out since @rbankston whipped up a proper fix for this in the system - thank you!
