### ISSUE TITLE
New DAGs UI live on Hybrid

### ISSUE THREAD

**Issue by chomipi88** [astronomer/docs#2563]
### Issue Type

Inaccurate, misleading, or out-of-date information

### Links to Affected Docs

https://docs.astronomer.io/astro/manage-dags

### The Issue or Context

We've been slowly rolling out the underlying software to Hybrid clusters and have recently enabled the UI portion to complete the release.

**Comment by jwitz** [comment]
Closed via hotfix https://github.com/astronomer/docs/commit/4ecfef876c08dac522eb40cc30061f7f0404089e
