### ISSUE TITLE
Update Deployment Create Doc

### ISSUE THREAD

**Issue by cmarteepants** [astronomer/docs#2566]
### Issue Type

Inaccurate, misleading, or out-of-date information

### Links to Affected Docs

https://docs.astronomer.io/astro/create-deployment#create-a-deployment

### The Issue or Context

In the UI, the KubernetesExecutor & KPO pods section is in "Execution". In the docs, we have it under "Advanced".

<img width="944" alt="CleanShot 2023-07-13 at 20 41 54@2x" src="https://github.com/astronomer/docs/assets/34171166/ea1b3f84-5997-456e-af6a-7c3ed3e627ff">

<img width="976" alt="CleanShot 2023-07-13 at 20 42 41@2x" src="https://github.com/astronomer/docs/assets/34171166/edb3d848-e98c-4834-a4fb-d356dc6cf9a9">

### Fix or Proposed Change

We need to move the bullet point to the "Execution" section

**Comment by cmarteepants** [comment]
Semi-related, the Public Preview disclaimer is being removed next week, and pod size fields will become configurable.

**Comment by jwitz** [comment]
Thanks for writing up an issue! This was resolved through a hotfix https://github.com/astronomer/docs/commit/1667402ca2c0c71a13ff07221f89fa9ae7fb36f8
