### ISSUE TITLE
Fix & update astro/user-permissions.md with exhaustive set of permissions

### ISSUE THREAD

**Issue by RNHTTR** [astronomer/docs#2585]
### Issue Type

Missing content for an existing feature

### Links to Affected Docs

https://docs.astronomer.io/astro/user-permissions#workspace-roles

### The Issue or Context

The current [documentation on Workspace Roles](https://docs.astronomer.io/astro/user-permissions#workspace-roles) lists `Member` instead of `Viewer`, and doesn't include all possible actions in the Airflow UI (e.g. who can delete task instances or DAG runs?)

### Fix or Proposed Change

Include all possible actions in the Airflow UI (e.g. who can delete task instances or DAG runs?)

**Comment by manmeetkaur** [comment]
Closing the issue out based on [this conversation](https://astronomer.slack.com/archives/C01UA03TPV1/p1690549276174879).

**Comment by RNHTTR** [comment]
The discrepancy of viewer / member is only one element of this Issue, and I don't think that part was covered in the Slack discussion. Separately, the docs still don't cover who is able to interact with the Airflow database (e.g. delete task instances or dag runs from the UI).

**Comment by jwitz** [comment]
Gonna cover this as part of https://github.com/astronomer/docs/issues/2676 next week
