### ISSUE TITLE
Gen2 Cloud - Deploy Code Page - broken CI/CD Link

### ISSUE THREAD

**Issue by aspain** [astronomer/docs#260]
**Affected Document:**
https://docs.astronomer.io/cloud/deploy-code/

**Problem Type (Priority):**

- [X] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [ ] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**

The CI/CD Link leads to this Page Not Found URL: https://docs.astronomer.io/cloud/deploy-code/ci-cd#workflow-overview

**Additional Notes:**
The `CI/CD: Workflow Overview` link in the 'Info' callout on this page leads to a 'Page Not Found' error

![image](https://user-images.githubusercontent.com/15913202/147679723-bcf1608a-7e1c-4cbc-bc69-73cd9f1c5ab3.png)

**Comment by jwitz** [comment]
Nice catch @aspain, our doc links sometimes don't work if you forget to add an `.md` to the file name. This commit should fix it and be live momentarily! https://github.com/astronomer/docs/commit/491bfbfc91975bb87183c516bb04556335ac73c5
