### ISSUE TITLE
Gen 1 docs for astro-cli install incorrect.

### ISSUE THREAD

**Issue by dylanbstorey** [astronomer/docs#263]
**Affected Document:**
https://www.astronomer.io/docs/cloud/stable/develop/cli-quickstart

https://github.com/astronomer/astro-site/blob/main/src/content/astro-docs/cloud/stable/02_develop/01_cli-quickstart.md

**Problem Type (Priority):**

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [x] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**

The invoked install script for the Apple M1 cURL based install method will never work as `darwin/arm64` will throw an explicit error as un supported every time. 

We should : 
- remove the suggested install instructions 
- redirect to the astro-hub installation instructions if appropriate.

**Additional Notes:**
- [Training materials](https://academy.astronomer.io/astronomer-certification-apache-airflow-fundamentals-preparation/723556)  using this link for install should decide if they want to continue using this information as well.

**Comment by jwitz** [comment]
Closing this out by updating our docs to recommend only the Homebrew install for m1 chips: https://github.com/astronomer/docs/pull/277#issuecomment-1007370215

If we get a verified installation for cURL, I'll add that back into the docs. 

The Gen 1 Cloud docs have been updated, but there seems to be an issue with triggering a web build on Netlify. Working on getting those published currently.
