### ISSUE TITLE
Connect to external resources - Deployment or Astro 

### ISSUE THREAD

**Issue by manmeetkaur** [astronomer/docs#2638]
<img width="1438" alt="Screenshot 2023-08-02 at 11 09 42 AM" src="https://github.com/astronomer/docs/assets/75730393/5d584035-a182-409a-8a42-5898d4b02e80">

When you think about "connecting to external resources" it is more of connecting Astro and not just a Deployment. And it is more an Admin work carried during setup. 

**_food for thought:_**
Own menu or sub-menu in Administration called **Integrate Astro** or **Connect external resources** or **Connect Astro to Data stack**

**Comment by jwitz** [comment]
If it's mostly admin users that are setting this up, I think this makes sense.
