### ISSUE TITLE
New "Runtime overview" doc

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#2657]
We don't have a great doc to share as an introduction to Astro Runtime. Under "Overview", we should have a new doc that has the following content:

- What is Astro Runtime
- How it works as a Docker image
- Feature table with checkmarks for Apache Airflow vs Astro Runtime

It should be short and sweet!

**Comment by manmeetkaur** [comment]
I am going to close this and add a Notion doc for Improvement details and then we can see if we want to do this or not.
