### ISSUE TITLE
standardize supported kubernetes versions in two guides

### ISSUE THREAD

**Issue by krisdock** [astronomer/docs#266]
**Affected Document:**

https://www.astronomer.io/docs/enterprise/v0.23/manage-astronomer/upgrade-to-0-23
https://www.astronomer.io/docs/enterprise/v0.23/install/aws/install-aws-standard  

**Severity:**

- [ ] Critical: This document has incorrect or missing information. Add the `error/critical` label to this issue.
- [x] FYI: The document is misleading or could benefit from additional context or guidance. Add the `error/FYI` label to this issue.
- [ ] Typo: Add the `error/typo` label to this issue.
  
**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**

in [upgrade-to-0-23](https://www.astronomer.io/docs/enterprise/v0.23/manage-astronomer/upgrade-to-0-23), we state:

> Your version must be greater than or equal to 1.14 and less than 1.19

in [install-aws-standard](https://www.astronomer.io/docs/enterprise/v0.23/install/aws/install-aws-standard), we state:

> Astronomer currently supports Kubernetes versions 1.14, 1.15, 1.16 and 1.17 on EKS

the doc that we should consider the source of truth on version compatibility, [version-compatibility-reference](https://www.astronomer.io/docs/enterprise/v0.16/resources/version-compatibility-reference), we list the following k8s versions:

> 1.16, 1.17, 1.18

we should make sure those two guides reflect the same information as our version compatibility reference

**Additional Notes:**

**Comment by jwitz** [comment]
Hey @krisdock, gonna close this since we have a PR out which addresses this exact issue: https://github.com/astronomer/docs/pull/256

Once Paola is back and responds to my comments there, I'll get it merged asap!
