### ISSUE TITLE
Fix Azure AD SCIM Mappings

### ISSUE THREAD

**Issue by chomipi88** [astronomer/docs#2667]
### Issue Type

Inaccurate, misleading, or out-of-date information

### Links to Affected Docs

https://docs.astronomer.io/astro/set-up-scim-provisioning?tab=Azure#setup

### The Issue or Context

There are two Attribute Mappings configurations (Groups and Users). For both the Create, Update, and Delete "Target Object Actions" should be enabled.

As for the mappings, they should be configured as per below.
**Groups Mappings:**

displayName > displayName
members > members

![image](https://github.com/astronomer/docs/assets/87984472/7b06e597-eaa9-46e4-ac2f-50fb9af37de1)

**Users Mappings:** 

userPrincipalName > userName
Switch([IsSoftDeleted], , "False", "True", "True", "False") > active
displayName > displayName
givenName > name.givenName
surname > name.familyName

![image](https://github.com/astronomer/docs/assets/87984472/7e880637-e6d8-4fc2-8e76-15dd37053e07)

**Comment by jwitz** [comment]
Resolved by https://github.com/astronomer/docs/pull/2673

**Comment by aliotta** [comment]
The docs are still incorrect see my comments on the PR
