### ISSUE TITLE
CustomLogging guide - Using an external logging service

### ISSUE THREAD

**Issue by stuart23** [astronomer/docs#267]
**Request type:**

- [x] **New document:**: Add the `docs-content` label to this issue.
- [ ] **Addition to an existing document**: Add the `enhancement` label to this issue.

**What is the purpose of the document/enhancement? Select all that apply:**

- [ ] Document a new feature for an upcoming release. Add the appropriate release version label to this issue.
- [x] Information for an existing feature that isn't yet documented.
- [ ] Additional considerations/ reference material for an existing document.

**Problem/feature that requires documentation:**

I put together a guide for a customer wanting to use an external elasticsearch deployment: https://docs.google.com/document/d/18khnOK7bRabDpxBMj0KSMLGewDC19hLVXNPHpVrpZW4/

This guide extends the WIP guide(s) here: https://www.notion.so/astronomerio/External-Elasticsearch-Integration-WiP-d5b691bc7b844b2aad6ddec2d9d18c67

The WIP guide on notion has some of the config parameters wrongly named, and I have included a few more steps in mine.

**Are you the right person to review a draft of the document for technical accuracy? If not, who is?**

I can help writing. Will refer to @pgvishnuram for review.

**Comment by kwcanuck** [comment]
Discussed this request with @cmarteepants 2022-07-22 and she indicated "we should have this documented". We agreed that it should be added to the existing topic [Export task logs to ElasticSearch](https://docs.astronomer.io/software/export-task-logs) as a new section.

**Comment by kwcanuck** [comment]
New branch created for this work: Add Elasticsearch as an External Logging Service.
