### ISSUE TITLE
Info on deprecated version of Docker Engine for new Astronomer CLI release (Gen1)

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#268]
@jwitz I got a question from @neel-astro on updating CLI docs for Gen1/Enterprise in 1-2 weeks.

> We are planning to migrate docker-compose from v2 to v3.1 in astro-cli Gen1 in our next release, and as a result the minimum docker engine version required to run astro dev commands would change from 1.10.0 (released in Feb 2016) to 1.13.1 (released in Feb 2017). This will not disrupt current users of existing CLI versions - will affect only from this release and beyond

Based on this change, I think we need to:

- Include a clear "breaking change" message in release notes targeted at people running the older versions that are being deprecated
- update the prerequisites to CLI install docs with minimum docker version (I think we just say "Docker" right now)

Worth noting that users who are running `1.10.0` - `1.13.1` will NOT get an error in their terminal when they upgrade and try to run `astro dev start` with the new version of the CLI that's incompatible. It'll just fail with a docker error.

**Comment by kwcanuck** [comment]
@jwitz is there anything I can do to help move this forward? Should the issue be closed?
