### ISSUE TITLE
link on secrets-backend page goes to a broken page

### ISSUE THREAD

**Issue by krisdock** [astronomer/docs#269]
**Affected Document:**

https://www.astronomer.io/docs/enterprise/v0.23/customize-airflow/secrets-backend#aws-ssm-parameter-store  

**Severity:**

- [x] Critical: This document has incorrect or missing information. Add the `error/critical` label to this issue.
- [ ] FYI: The document is misleading or could benefit from additional context or guidance. Add the `error/FYI` label to this issue.
- [ ] Typo: Add the `error/typo` label to this issue.
  
**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**

this section:

> If you're interested in further customizing what the interaction between Airflow and your SSM server looks like, learn more by reading the full list of available kwargs for this integration.

the end of that sentence is a hyperlink to: https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/contrib/secrets/aws_systems_manager/index.html

which doesn't exist

https://airflow.apache.org/docs/apache-airflow/1.10.12/_api/airflow/contrib/secrets/aws_systems_manager/index.html

works ^

https://airflow.apache.org/docs/apache-airflow/1.10.14/_api/airflow/contrib/secrets/aws_systems_manager/index.html

works ^

**Additional Notes:**

not sure we want to point to a static version of the upstream doc, but that may be our only option

**Comment by paolaperaza** [comment]
@krisdock Thanks for the catch and reporting this! Hotfix: https://github.com/astronomer/docs/commit/caa7847007fde14c397344845c5cd9e9f219588a

These docs were split up post-2.0 given Airflow providers, so the new link for this information is confusingly here:
- https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/_api/airflow/providers/amazon/aws/secrets/systems_manager/index.html

That's a "stable" URL - should be good 2.0+ w/o pinning.
