### ISSUE TITLE
correction for environment variable at installation page

### ISSUE THREAD

**Issue by afastronomer** [astronomer/docs#2690]
### Issue Type

Typo or broken link

### Links to Affected Docs

https://docs.astronomer.io/software/install-gcp#step-8-configure-your-helm-chart
https://docs.astronomer.io/software/install-aws#step-8-configure-your-helm-chart

### The Issue or Context

Correct line is `envName: "EMAIL__SMTP_URL"` but in some docs specified `envName: "<smtp_uri_secret>"`.

**Comment by jwitz** [comment]
Thank you @afastronomer ! Merged the linked PR, so closing this issue out
