### ISSUE TITLE
Discuss/Update to Astro Security Doc

### ISSUE THREAD

**Issue by lzdanski** [astronomer/docs#2712]
### Issue Type

Inaccurate, misleading, or out-of-date information

### Links to Affected Docs

https://docs.astronomer.io/astro/security

### The Issue or Context

After launching Astro Hosted, we need to update this page to change the security focus/value props to the new deployment model. 

### Fix or Proposed Change

The new page needs to cover:
- Overview
- Compliance
- Authentication
- Authorization

And then we need to remove —
- Shared responsibility
- Resilience
- DR
- Data protection
- Secrets management

With all content based on Hosted-first

### Additional Notes

Related Issue: https://github.com/astronomer/docs/issues/2710

Slack thread: https://astronomer.slack.com/archives/C03CT3DNZMH/p1692291115400649

**Comment by jwitz** [comment]
Generally the docs team has not owned or updated these docs, save for review. Should we be working with Piotr and asking him to update these for Hosted? 

I also think we shouldn't straight up remove the Hybrid content. Might make sense to archive/ unlist that content in the "Manage Astro Hybrid" tab.

**Comment by lzdanski** [comment]
Related PR: https://github.com/astronomer/docs/pull/2711

**Comment by lzdanski** [comment]
@jwitz - do you think we need to do anything else with this? If not - go ahead and close!

**Comment by jwitz** [comment]
Yep this is good to close!
