### ISSUE TITLE
Replace URL unfurl image on docs

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#2716]
### Context

Currently, our docs unfurl images have our old colors and branding on them -- 
<img width="710" alt="image" src="https://github.com/astronomer/docs/assets/31111752/a932a786-651a-42e7-ade4-8056418fb75d">

### Ask

Let's replace that unfurl image with this one -- 

![Astronomer - Documentation - Purple   Dark Blue](https://github.com/astronomer/docs/assets/31111752/343ee52d-bb87-4114-ac39-e42d64d91dd7)

@katiebrady-astro The original file is in this slack thread too -- https://astronomer.slack.com/archives/C04U1AXJVGC/p1692203332256579

**Comment by katiebrady-astro** [comment]
Hey @paolaperaza PR now open to get this updated! 🙌
