### ISSUE TITLE
Azure Key Vault - Secrets Backend

### ISSUE THREAD

**Issue by aspain** [astronomer/docs#272]
I put together a sample guide in Notion for implementing Azure Key Vault as a secrets backend and was wondering if it would be a good fit for an addition to the guides page. Our existing docs are pretty sparse around how to set it up. 
I plan on cleaning this up and putting it in a repo for the registry as well

https://www.notion.so/astronomerio/Azure-Key-Vault-Secrets-Backend-Example-c8dc814a1ef84a68868a59769aafbf29

**Comment by aspain** [comment]
thanks @kentdanas and @jwitz for taking a look
@jwitz - I also have this write-up in a git repo if that format is helpful for any of the doc page addition: https://github.com/astronomer/cs-tutorial-azurekeyvault

**Comment by paolaperaza** [comment]
Closing this out! Addressed by #265 and now live here: https://docs.astronomer.io/cloud/secrets-backend#microsoft-azure-key-vault
