### ISSUE TITLE
Integration simplification for SnowSQL with Airflow 

### ISSUE THREAD

**Issue by KunD17** [astronomer/docs#2736]
### Content type

Airflow tutorials, Integrations, I am not sure where this best fits

### Request type

New content for an undocumented or under-documented Airflow feature

### Describe your Learn request.

There are issues currently to run SnowSQL with Airflow using Docker containers. When deploying Airflow with Astronomer in a Docker container it is not possible to install SnowSQL (in the manner described in the snowflake documentation). The procedure to be able to do this should be documented for clarify of use. This aspect is useful for people intending to use SnowSQL for Snowflake with Airflow. 

### Airflow Version

2.6.3

### Reviewer

Yes

### Additional information

Link to the installer for SnowSQL: https://docs.snowflake.com/en/user-guide/snowsql-install-config

**Comment by kentdanas** [comment]
Can you provide a use case for why you would want to use SnowSQL with Airflow? Typically you wouldn't use a CLI to run queries against a database from Airflow, unless maybe there wasn't an API to use. For Snowflake, you should use the operators in the Snowflake provider (https://registry.astronomer.io/providers/apache-airflow-providers-snowflake/versions/4.4.2) to run queries.
