### ISSUE TITLE
Add example for how to do cross DAG dependencies across Airflow instances 

### ISSUE THREAD

**Issue by conorbev** [astronomer/docs#2748]
### Content type

Airflow concepts

### Request type

Additional information for an existing guide or tutorial

### Describe your Learn request.

I was speaking with a user who said that they were using this documentation: https://docs.astronomer.io/learn/cross-dag-dependencies ( which they found helpful ) but would like to see an additional example of how to do the cross DAG dependency when the DAGs are in different Airflow instances.

This [support case](https://astronomer.zendesk.com/agent/tickets/20392) may have more context. It's from the same person that I spoke with. They said that they were eventually able to figure it out but thought it would be a useful additional to the doc.

**Comment by kentdanas** [comment]
Hey @conorbev, that doc already has a section for cross-deployment DAG depedencies (https://docs.astronomer.io/learn/cross-dag-dependencies#cross-deployment-dependencies), which walks through the steps of setting this up on Astro. The example DAG itself is in the Airflow API section (https://docs.astronomer.io/learn/cross-dag-dependencies#airflow-api) as this is the method we suggest for cross-deployment. I'm not clear on what else they're looking for here.
