### ISSUE TITLE
Create pull request templates for core doc contributors

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#2763]
### Issue Type

Issue with website functionality

### Links to Affected Docs

N/A

### The Issue or Context

We should have PR templates for core docs members to use for more complex PRs that explain:

- What problem is being solved
- How it's being solved

It could also have a section for including links to preview pages so that reviewers don't have to navigate from the Netlify comment each time.

**Comment by lzdanski** [comment]
We've shifted to adding more detail to github issues and added docs projects templates to our workflow to add more background to our PR's. Closing issue.
