### ISSUE TITLE
add a CONTRIBUTING.md page

### ISSUE THREAD

**Issue by erdos2n** [astronomer/docs#2773]
### New Feature Description

This can help inform new contributors on best practices to add to the docs page.

### Required Reviewers

Paola, Jake

**Comment by jwitz** [comment]
@erdos2n Does the contributing section in our README cover this? https://github.com/astronomer/docs#contribute

I want to include information on contributing, but not too much that it seems like a huge lift to contribute for the first time. Would rather have someone contribute without any sense of style/ best practices if it means their content gets into a PR faster.

As an aside, we are also planning to create some templates for different docs types. I could see us moving our existing Contributing content and those templates to a new `contributing` directory that. Would that work?

**Comment by fritz-astronomer** [comment]
fwiw - my opinions on a `CONTRIBUTING.md` doc should mostly go into "here's the PR and CICD process, and anything you'd need to know to successfully get a contribution across the line". I do think you're pretty good with that section in the `README`, maybe it could be pulled out to a `CONTRIBUTING` and linked? It's a semi-standard practice to have a separate readme for devs.
