### ISSUE TITLE
Add `-n astronomer` to TLS secret creation step in Enterprise install guides

### ISSUE THREAD

**Issue by aspain** [astronomer/docs#279]
**Affected Document:**
https://docs.astronomer.io/enterprise/install-aws#step-5-create-a-kubernetes-tls-secret
https://docs.astronomer.io/enterprise/install-gcp/#step-5-create-a-kubernetes-tls-secret
https://docs.astronomer.io/enterprise/install-azure/#step-5-create-a-kubernetes-tls-secret

**Problem Type (Priority):**

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [X] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**
Add `-n astronomer` flag to have the tls secret created in the astronomer namespace for **both** commands in step 5

**Before**
`kubectl create secret tls astronomer-tls --cert <your-certificate-filepath> --key <your-private-key-filepath>`
`kubectl create secret generic private-root-ca --from-file=cert.pem=./<your-certificate-filepath>`

**After**
`kubectl create secret tls astronomer-tls --cert <your-certificate-filepath> --key <your-private-key-filepath> -n astronomer`
`kubectl create secret generic private-root-ca --from-file=cert.pem=./<your-certificate-filepath> -n astronomer`

**Additional Notes:**
Can cause confusion if the secret is not initially placed in the astronomer namespace since [step 3](https://docs.astronomer.io/enterprise/install-aws#step-3-create-a-namespace) has users create the `astronomer` namespace

**Comment by jwitz** [comment]
Fixed via https://github.com/astronomer/docs/commit/aa64296520899189040baaf36a014d58d539e994! Thanks @aspain
