### ISSUE TITLE
Enterprise Install guide: change `--namespace=<your-platform-namespace>` to `--namespace astronomer`

### ISSUE THREAD

**Issue by aspain** [astronomer/docs#280]
**Affected Document:**
https://docs.astronomer.io/enterprise/install-azure/#step-9-install-astronomer
https://docs.astronomer.io/enterprise/install-aws#step-9-install-astronomer
https://docs.astronomer.io/enterprise/install-gcp/#step-9-install-astronomer

**Problem Type (Priority):**

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [X] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**
In the Helm Install command: `helm install -f config.yaml --version=0.27 --namespace=<your-platform-namespace> <your-platform-release-name> astronomer/astronomer`

change `--namespace=<your-platform-namespace>` to `--namespace=astronomer` since the namespace was already set as `astronomer` in step 3 in the `kubectl create namespace astronomer` command

**Additional Notes:**

**Comment by paolaperaza** [comment]
Done! https://github.com/astronomer/docs/commit/47a5916d3e0b2963b5cd7c106a79401bf9140a5f

Thanks @aspain, good eye. Steps were confusing - closing this out 😊
