### ISSUE TITLE
Evaluate Cloud UI for accessibility/ screen readers and update docs accordingly

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#2833]
### Issue Type

Missing content for an existing feature

### Links to Affected Docs

Any doc with a screenshot or instruction related to an icon button without visible text.

### The Issue or Context

Some elements in the Cloud UI have an icon without descriptive text. We should find a better strategy to document these, and if there's no good "Anchor" text to use for explaining these icons then we should raise an issue with the UI team.

**Comment by lzdanski** [comment]
In roadmap planning, this issue is included as a "Nice to have" goal. will reopen when ready to action.
