### ISSUE TITLE
CI/CD image recommendations should be version-neutral

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#285]
**Affected Document:**
  
**Severity:**

- [ ] Critical: This document has incorrect or missing information. Add the `error/critical` label to this issue.
- [X] FYI: The document is misleading or could benefit from additional context or guidance. Add the `error/FYI` label to this issue.
- [ ] Typo: Add the `error/typo` label to this issue.
  
**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):** We should not be using specific image versions in our CI/CD templates. Instead, we should use `quay.io/astronomer/ap-build:latest` and maybe include a note about changing versions if needed. 

**Additional Notes:**

**Comment by blimmer** [comment]
Looks like this is fixed by #288

**Comment by jwitz** [comment]
Thanks for catching @blimmer ! Closing now.
