### ISSUE TITLE
Should pinning dependencies really be recommended?

### ISSUE THREAD

**Issue by RNHTTR** [astronomer/docs#2871]
### Issue Type

Inaccurate, misleading, or out-of-date information

### Links to Affected Docs

astro/upgrade-runtime.md
https://docs.astronomer.io/astro/upgrade-runtime#step-2-optional-pin-provider-package-versions

### The Issue or Context

Should pinning provider packages really be recommended? This can be potentially problematic long-term if provider packages are always pinned to what will eventually become a really old set of dependencies.

### Fix or Proposed Change

I think we should consider at least switching the order of steps 2 and 3. So, `astro dev upgrade-test` should be step 2, and if there are any issues, users could then pin the requirements.

### Additional Notes

This is also potentially misleading for folks who are trying to migrate to Astro from Nebula.

**Comment by jwitz** [comment]
Related GitHub issue and Slack discussion are here: https://github.com/astronomer/docs/issues/2010

Maybe we could make it more clear that you also have to unpin them after the upgrade, but if users follow the steps exactly then they should be doing that: https://docs.astronomer.io/astro/upgrade-runtime#step-6-optional-upgrade-and-test-provider-packages

**Comment by RNHTTR** [comment]
WHat's the point of pinning only to unpin? Once you unpin, there's no guarantee that there won't be dependency conflicts

**Comment by jwitz** [comment]
I think it's useful for people who are upgrading with many packages. After you upgrade Airflow, you can upgrade packages one-by-one and deal with issues as they come instead of doing the "big bang" approach like Ash mentioned. 

The calculus of this might change once the CLI team releases the "conflict" test for `astro dev upgrade-test`

**Comment by fritz-astronomer** [comment]
Yes @RNHTTR it should be recommended :) Folks should upgrade providers intentionally and carefully. Maybe we could recommend looser than an exact version pin? But, it's still a better practice.

**Comment by jwitz** [comment]
@RNHTTR gonna close this out but feel free to reopen if you have more thoughts!
