### ISSUE TITLE
Floating tags for major Runtime versions

### ISSUE THREAD

**Issue by jedcunningham** [astronomer/docs#2875]
### New Feature Description

To complement all of our existing Runtime tags, we will soon have a floating tag for each major versions 5+.

Meaning:

* `9.2.0` would also be tagged as `9`
* `9.2.0-base` would also be tagged as `9-base`
* `9.2.0-python-3.8` would also be tagged as `9-python-3.8`

This gives customers a way to always use the latest release in a given Runtime major (though we should suggest folks still use a specific version).

### Required Reviewers

@jedcunningham

### Release Date

Runtime 9 will have this very soon, and the remaining majors will follow suit relatively soon. No real rush though - folks need to opt in to use this.

**Comment by jedcunningham** [comment]
One thing we want to call out explicitly is that using the floating tag can lead to updates when doing new deployments, which can include updates to Airflow/providers/etc, and can also include db migrations which can mean you can't move backwards to the version they were on previously.

**Comment by jwitz** [comment]
Closing this out as this isn't in a current development cycle
