### ISSUE TITLE
Suggest Deployment API tokens more frequently

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#2882]
### Issue Type

Missing content for an existing feature

### Links to Affected Docs

https://docs.astronomer.io/astro/airflow-api#step-1-retrieve-your-access-token

### The Issue or Context

With the rushed publication of Deployment API key docs, we missed some places to mention it in docs. The linked doc is just one example, but there are probably other places as well.

**Comment by jwitz** [comment]
@lzdanski Assigning you this as part of the work for API key deprecation!

**Comment by lzdanski** [comment]
Resolved by https://github.com/astronomer/docs/pull/3026
