### ISSUE TITLE
Add Info on Worker Autoscaling Logic to Docs

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#289]
@paolaperaza commented on [Tue Jan 11 2022](https://github.com/astronomer/cloud/issues/268)

Slack convo: https://astronomer.slack.com/archives/C028YCH4682/p1641889479063400

To our "Configure a Deployment" doc, we should:

- Correct "minimum workers" from 0 to 1
- Add a note on how celery workers actually autoscale based on below
- Add note on 10 AU being the minimum for Workers. [Slack convo here](https://astronomer.slack.com/archives/C028YCH4682/p1641856989053300?thread_ts=1641856185.052200&cid=C028YCH4682).

> Sum of tasks in queued + running state, divided by 16. 16 is the default worker concurrency. It can be overridden as an env var but we need to expose this as a top-level configuration in our system so we can push the env var configuration and set that same value as the divisor in the autoscaling logic.

**Comment by jwitz** [comment]
Resolved via https://github.com/astronomer/docs/pull/293/files
