### ISSUE TITLE
add a note to lts upgrade doc about older kubernetes versions

### ISSUE THREAD

**Issue by krisdock** [astronomer/docs#290]
**Affected Document:**

https://www.astronomer.io/docs/enterprise/v0.23/manage-astronomer/upgrade-to-0-23  

**Severity:**

- [x] Critical: This document has incorrect or missing information. Add the `error/critical` label to this issue.
- [ ] FYI: The document is misleading or could benefit from additional context or guidance. Add the `error/FYI` label to this issue.
- [ ] Typo: Add the `error/typo` label to this issue.
  
**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**

per @rbankston, we should add a note to the lts upgrade doc specifically calling out scenarios where customers are running older versions of kubernetes. due to api deprecations, they can run into a situation where helm upgrade commands won't complete successfully.

**Additional Notes:**

**Comment by jwitz** [comment]
@krisdock @rbankston Is this for Kubernetes < 1.14? We already have a note about Kubernetes versions needing to be within a specific range, so I'm not sure what else we could add here:

> Kubernetes: Your version must be greater than or equal to 1.14 and less than 1.19. If you need to upgrade Kubernetes, contact your cloud provider's support or your Kubernetes administrator.

**Comment by rbankston** [comment]
Kubernetes > 1.16 and Astronomer < 0.16.15 present this process.

**Comment by jwitz** [comment]
@rbankston do you mean "Kubernetes **<** 1.16" ? That seems more consistent with what Kris suggested above
