### ISSUE TITLE
Documentation for  Azure workload Identity

### ISSUE THREAD

**Issue by vatsrahul1001** [astronomer/docs#2916]
### New Feature Description

With the release of Runtime 9.2.0, we have implemented Azure Workload Identity. This implementation involves setting the `AZURE_TENANT_ID` and `AZURE_CLIENT_ID` environment variables within Astro. It's important to note that if any customer explicitly set environment variables with the same names in deployments, Astro will override them with different values.

### Required Reviewers

Jed ,Phani

### Links to Internal Info or Resources

- https://github.com/astronomer/astronomer-providers-logging/issues/45
- https://github.com/astronomer/astronomer-providers-logging/pull/51/files/9937f370d5be4c30f2684b4d7d4bd88ee5d601a8#diff-04740d13c4b6482902b309017367005e97141d04b6b47c9014bc32dfeffd9c37
- https://azure.github.io/azure-workload-identity/docs/installation/mutating-admission-webhook.html

### Release Date

10/9

### Additional Notes

https://docs.astronomer.io/astro/authorize-deployments-to-your-cloud

**Comment by lzdanski** [comment]
@jwitz - Should I assign this over to you after our discussion in the Monday prioritization meeting? Not sure where we finally landed on this.

**Comment by jwitz** [comment]
Just assigned myself, I was speaking with Mehul and we're planning to document this alongside a blog post coming out in two weeks

**Comment by chomipi88** [comment]
Important limitations to be aware of: https://learn.microsoft.com/en-us/entra/workload-id/workload-identity-federation-create-trust?pivots=identity-wif-apps-methods-azp#important-considerations-and-restrictions

The maximum of 20 means that a maximum of 4 deployments can use the same managed identity because we require the user to create 4 federated identity credentials per deployment for a given managed identity.
https://github.com/astronomer/astro/pull/17703

**Comment by chomipi88** [comment]
We are planning to ship this feature to prod next week 11/29. It will be featured and demo'd on a Webinar with Microsoft that same day. At the same time, a blog post announcing this feature will go out around the same time. Link to blog post below for more information: 
https://docs.google.com/document/d/1TYizCb1-4k1ql_zeny8lKyHhs5Ql2oosl0JJah96cBk/edit#heading=h.212fm23wyua

@jwitz happy to work with you to get this doc up by 11/29 ideally
