### ISSUE TITLE
KPO/KE requests must equal limits, new behavior enforces this 

### ISSUE THREAD

**Issue by lzdanski** [astronomer/docs#2918]
### Issue Type

Inaccurate, misleading, or out-of-date information

### Links to Affected Docs

- https://docs.astronomer.io/astro/manage-billing
- https://docs.astronomer.io/astro/kubernetes-executor

### The Issue or Context

Astro Hosted users that work with the Kubernetes Executor and Kubernetes Pod Operator. 

Prior behavior required that the KE and KPO resources allocated for tasks to be equal. However, if using the KE/KPO and limits and resources are not equivalent, they will be raised to the maximum limit to make them equivalent. 

If limit is not set - Airflow automatically configures the limit to equal the size of the request. ([PR](https://github.com/astronomer/astro/pull/16807/files#diff-b88c0dc2dad9c3395700cb235aade626227a97ca7c26d8f1eb7328afa4ba6764R264))

If request is not specified, but the limit is set - Airflow automatically requests the maximum limit ([PR Link](https://github.com/astronomer/astro/pull/16807/files#diff-b88c0dc2dad9c3395700cb235aade626227a97ca7c26d8f1eb7328afa4ba6764R268)). 

If the request exceeds the limit, then the DAG fails. 

This is an important behavior change because previously if the request size was not equal to the configured limit, the DAG would fail. Now DAGs that previously failed can succeed, but consume more worker resource than the user might expect.

### Fix or Proposed Change

- Add information about behavior change to https://docs.astronomer.io/astro/kubernetes-executor 
- Add information about behavior change to https://docs.astronomer.io/astro/kubernetespodoperator#configure-task-level-pod-resources and https://docs.astronomer.io/astro/kubernetespodoperator#known-limitations

- Add links to both resources directing them to Billing for more information about how to find resource use, invoices, and usage (https://docs.astronomer.io/astro/manage-billing). Do not need to update this page specifically.

- Will add note in release notes for next week that points to KE/KPO pages and Billing.

### Additional Notes

* https://github.com/astronomer/astro/pull/16807
* https://astronomer.slack.com/archives/C0547LMQA2E/p1696452811275159

### Required Reviewers

@fritz

**Comment by fritz-astronomer** [comment]
> Astro Hosted users that work with the Kubernetes Executor and Kubernetes Pod Operator.

👍 yea, important that it's ONLY this audience. 

> If limit is not set - Airflow automatically configures the limit to equal the size of the request. (PR)
If request is not specified, but the limit is set - Airflow automatically requests the maximum limit (PR Link).

that probably isn't so important, as it can be inferred from "requests must equal limits" 🤷 , it's just ensuring that everything is equal in the event that we only see half

>  if the request size was not equal to the configured limit, the DAG would fail

Wouldn't be parsed, to be specific. There'd be a big red message in the Airflow UI saying the DAG didn't pass validation

**Comment by lzdanski** [comment]
Modified behavior so KubernetesExecutor and KubernetesPodOperator pods running in-cluster have equivalent resource requests and limits or are modified to the become the limits. Previously, the DAG was entirely rejected from running on Astro Hosted.
