### ISSUE TITLE
NGINX ingres annotations

### ISSUE THREAD

**Issue by rbankston** [astronomer/docs#292]
**Request type:**

- [ ] **New document:**: Add the `newcontent` label to this issue. 
- [x] **Significant change to an existing document**: Add the `enhancement` label to this issue. 

**What is the purpose of the document/enhancement? Select all that apply:**

- [x] Document a new feature for an upcoming release. Add the appropriate release version label to this issue. 
- [ ] Information for an existing feature that isn't yet documented.
- [ ] Additional considerations/ reference material for an existing feature or document.

**Problem/feature that requires documentation:**
https://www.astronomer.io/docs/enterprise/v0.23/install/aws/install-aws-standard#step-7-configure-your-helm-chart 

In https://github.com/astronomer/astronomer/pull/1039#event-4483547005 the next release of 0.23 the NGINX annotations are being changed to be brought in via a dictionary so customers can add arbitrary annotations for their respective clouds. If we could update the AWS documentation with "service.beta.kubernetes.io/aws-load-balancer-type" "nlb" so customers have an example and also nlb load balancers.
  
**Are you the right person to review a draft of the document for technical accuracy? If not, who is?**

**Comment by jwitz** [comment]
@rbankston Is the example value you included something we expect all AWS customers to want by default? In the future we should have a full chart config guide, but I don't want to provide opinionated setup in a general installation guide.

If this is something we want everyone to configure, is there an equivalent, generally-used value we can configure for GCP and AKS?  If it's not something for everyone, I will probably just link out to [this doc](https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/advanced-configuration-with-annotations/) in the inline comments and let users figure out what they need.

**Comment by rbankston** [comment]
That would be the equivalent of this pull request https://github.com/astronomer/issues/issues/1546 being there for customers by default
