### ISSUE TITLE
Update Software IDP docs 

### ISSUE THREAD

**Issue by lzdanski** [astronomer/docs#2960]
### Issue Type

Missing content for an existing feature

### Links to Affected Docs

https://docs.astronomer.io/software/integrate-auth-system#store-and-encrypt-identity-provider-secrets
https://docs.astronomer.io/software/integrate-auth-system?tab=azuread#scim

### The Issue or Context

Need to document a general way of referencing secrets for Software IDP. Current description implies that users should store as plaintext in a config.yaml file, which is not correct.

We have documentation about this flow for SSO, but not SCIM. 

There are environment variables available so that users can define their secrets in a Kubernetes secrets file, and then reference those values with environment variables.

### Fix or Proposed Change

Update step 3 with examples of SCIM environment variables for https://docs.astronomer.io/software/integrate-auth-system#store-and-encrypt-identity-provider-secrets

### Additional Notes

* https://astronomer.slack.com/archives/CEPE4K68P/p1697571752436819
* https://github.com/astronomer/houston-api/blob/main/config/custom-environment-variables.yaml
* https://github.com/astronomer/astronomer/blob/master/charts/astronomer/values.yaml#L105-L113

Excerpt from slack conversation:

For any idp, you can pass credentials as plain text in config yaml file, or pass it as an env. Users need to be sure that the same env var name should be present in custom environment variable yaml file in Houston too.

This is what each of the env values would set

```
__name: "AUTH__OPENID_CONNECT__OKTA__ENABLED"
      scimAuthCode: "SCIM_AUTH_CODE_OKTA"
      clientId: "AUTH__OPENID_CONNECT__OKTA__CLIENT_ID"
      clientSecret: "AUTH__OPENID_CONNECT__OKTA__CLIENT_SECRET"
      discoveryUrl: "AUTH__OPENID_CONNECT__OKTA__DISCOVERY_URL"
      audience: "AUTH__OPENID_CONNECT__OKTA__AUTH_URL_PARAMS__AUDIENCE" 
```

Then, you can have one k8s secret that holds multiple keys and point for each env value

For SCIM:
- you can use SCIM_AUTH_CODE_OKTA and point as env

For SSO:
```
 secret:
  - envName: "AUTH__OPENID_CONNECT__OKTA__CLIENT_ID"
    secretName: "my-scret"
    secretKey: "okta_client_id"
```

**Comment by jwitz** [comment]
To summarize, it sounds like we need to recommend the steps in https://docs.astronomer.io/software/integrate-auth-system#store-and-encrypt-identity-provider-secrets and apply them to https://docs.astronomer.io/software/integrate-auth-system#manage-users-and-teams-with-scim and any other setups where you don't want to store a sensitive value in plain text. Is that right?

**Comment by lzdanski** [comment]
Relates to https://github.com/astronomer/docs/issues/935
