### ISSUE TITLE
Broken links for non-cloud installations

### ISSUE THREAD

**Issue by msumit** [astronomer/docs#297]
**Affected Document:**

On https://www.astronomer.io/docs/enterprise/ under`Installation` section, the only links related to cloud vendor works, while all other 3 links reload the same page.
  
**Severity:**

- [ ] Critical: This document has incorrect or missing information. Add the `error/critical` label to this issue.
- [ ] FYI: The document is misleading or could benefit from additional context or guidance. Add the `error/FYI` label to this issue.
- [ ] Typo: Add the `error/typo` label to this issue.
  
**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**

**Additional Notes:**

**Comment by jwitz** [comment]
Thanks for writing up this issue @msumit ! We've hotfixed this, so now it should only show the working installation guide.
