### ISSUE TITLE
Details to HA Deployments on Hosted

### ISSUE THREAD

**Issue by chomipi88** [astronomer/docs#2972]
### Issue Type

Inaccurate, misleading, or out-of-date information

### Links to Affected Docs

https://docs.astronomer.io/astro/deployment-settings#enable-high-availability

### The Issue or Context

Add details to describe how HA is achieved for the `pgbouncer` and `scheduler` components with HA enabled. We set node anti affinity to `required` guaranteeing that a replica of each runs on separate nodes. Additionally, we are also introducing `preferred` zone anti affinity for best effort scheduling of the replicas on separate availability zones as well.

https://github.com/astronomer/astro/pull/16673#event-10700577225

### Required Reviewers

chomipi88, pritt20

**Comment by lzdanski** [comment]
@chomipi88 - is this different from this previously opened issue? https://github.com/astronomer/docs/issues/2897

**Comment by chomipi88** [comment]
@lzdanski closed the other issue as the implementation had to be slightly adjusted.

**Comment by chomipi88** [comment]
@lzdanski can we tackle this issue this week? changes went out a few days back.
nothing noticeable to the customer, but figure we close the effort out completely.

**Comment by lzdanski** [comment]
@chomipi88 - I think we're waiting on your review here: https://github.com/astronomer/docs/pull/3011

**Comment by chomipi88** [comment]
sorry missed that! just left a comment
