### ISSUE TITLE
Rework Security Model and Airflow Deployments Docs

### ISSUE THREAD

**Issue by vparekh94** [astronomer/docs#30]

**Comment by paolaperaza** [comment]
Update on this: Content on "Airflow Deployments" was cleaned up and renamed to "Astronomer UI" [here](https://www.astronomer.io/docs/astronomer-ui/). Redirect is live to make sure anyone linked to `/airflow-deployments` is sent to the correct page.

This issue originally encapsulated work for the "Security Mode" page on our docs, but I went ahead and transferred next-steps on that front to issue #31 in this repo
