### ISSUE TITLE
Azure AD Auth Example screenshot is missing `/` in the example

### ISSUE THREAD

**Issue by aspain** [astronomer/docs#301]
**Affected Document:**
https://docs.astronomer.io/enterprise/integrate-auth-system/#azure-ad

**Problem Type (Priority):**

- [X] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [ ] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**
During an install today, the customer based their Redirect URI off of the screenshot rather than copying from the text block which caused a lot of troubleshooting - both should match to be as clear as possible. 

The **text** is correct for this step, but the screenshot does not reflect the proper URL, it is missing the `/` in the `Redirect URI`

```
To start, register the application. As you do so, make sure to specify the Redirect URI as https://houston.BASEDOMAIN/v1/oauth/redirect/.
```

![image](https://user-images.githubusercontent.com/15913202/150219803-7315791e-3d31-41bc-8e81-7919368f39c3.png)

**Additional Notes:**
Here is an example of what the screenshot should reflect: 
![image](https://user-images.githubusercontent.com/15913202/150220393-c4002bc3-6f53-406e-8c18-4b3ea390b73a.png)

**Comment by aspain** [comment]
@dintorf FYI

**Comment by jwitz** [comment]
Closed via https://github.com/astronomer/docs/commit/9ea094660ffc47963226c2cad4eb5b6302118861!
