### ISSUE TITLE
Bug when using link to specific API operation

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#3015]
### Issue Type

Issue with website functionality

### Links to Affected Docs

https://docs.astronomer.io/astro/api/platform-api-reference#tag/Deployment/operation/UpdateDeployment, as an example.

### The Issue or Context

When you use an anchor link in the API reference docs, there is a high chance that the page jumps to an unrelated API operation. It seems to get worse if you try using a link for an operation lower down on the page.

**Comment by katiebrady-astro** [comment]
@jwitz @lzdanski PR open and preivew ready! 

https://github.com/astronomer/docs/pull/3076

https://deploy-preview-3076--gallant-neumann-56599d.netlify.app/astro/api/iam-api-reference#tag/Invite/operation/DeleteUserInvite
