### ISSUE TITLE
0.26 Release Notes Reference 0.27

### ISSUE THREAD

**Issue by rbankston** [astronomer/docs#309]
**Affected Document:**
https://docs.astronomer.io/enterprise/0.26/release-notes

**Problem Type (Priority):**

- [x] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [x] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**

0.27.6 should be changed to 0.26.6

**Additional Notes:**

It also appears that 0.26.5 doesn't have any release notes

**Comment by jwitz** [comment]
Cheers @rbankston , this should be resolved by https://github.com/astronomer/docs/commit/ba7a5ba7f74ab8fe52447b72699e424e7177b433
