### ISSUE TITLE
Add guidance on code and user management best practices on Astro

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#313]
Need to work with Field & Solutions Engineering

**Comment by kwcanuck** [comment]
From @paolaperaza 2022-07-18:

_This one actually is still needed, but it just doesn’t fit in the format of our current docs and was originally going to be our first “tutorial”. Let’s leave this one open but blocked. Once we have our new “guides”/“tutorials” section, we can get into this one. New Workspace RBAC will also force us to push this forward a bit. So, we’re not quite blocked on this from a development standpoint but we’re blocked on it from a product recommendation + publishing format standpoint._

**Comment by kwcanuck** [comment]
From @paolaperaza 2022-10-20:

_Let’s keep open but rename to: Add guidance on code and user management best practices on Astro and keep it blocked for now, pending RBAC changes_

**Comment by kwcanuck** [comment]
Unsuccessful attempt to solicit the feedback necessary to move this issue forward January 4, 2023. This issue has been open for almost a year without any action and the last update was three months ago. Closing for now - it can be reopened if the information necessary to complete it becomes available, or it is considered a priority.
