### ISSUE TITLE
Migrate Gen1Cloud Docs to `nebula.astronomer.io`

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#315]
Final Decisions for Gen1 Cloud Docs

- Create new docusaurus page at nebula.astronomer.io
- Redeploy site from `gen1-cloud-docs` GitHub repo
- Does not need to be password protected
- All link to astronomer.io/cloud/docs should redirect to docs.astronomer.io (Gen2)
- Add button:
     - `Log In` > https://app.gcp0001.us-east4.astronomer.io/login
- Make sure we link out to Support & resources in the footer
- Make sure the Gen1 Astronomer UI (and Airflow UI) links out to `nebula.astronomer.io`

cc: @allenbrady-astro Would you be able to help @jwitz with the button here?

**Comment by allenbrady-astro** [comment]
Sure thing! So we need login button added to the new Docusaurus Gen 1 Cloud Docs site and all appropriate redirects setup on www.astronomer.io?

@jwitz This CSS snippet should style the button to match new branding.

```
.button {
  display: inline-block;
  position: relative;
  line-height: 1;
  text-decoration: none;
  padding: 12px 23px 10px 23px;
  font-size: 18px;
  background-color: #9ee5d9;
  color: var(--gray-8);
  box-shadow: 0 1px 1px 0 rgba(65, 66, 70, 0.34);
  -webkit-background-clip: padding-box;
  background-clip: padding-box;
  border-radius: 20px;
  border: solid 1.5px transparent;
  font-weight: 500;
  transition: background-color 0.3s ease;
}

.button:before {
  content: "";
  position: absolute;
  top: 0;
  bottom: 0;
  right: 0;
  left: 0;
  z-index: -1;
  margin: -1.5px;
  border-radius: inherit;
  background: linear-gradient(to bottom, #cff2ec, #6fd7c6);
}

.button:hover {
  background-color: #4fceba;
}
```
