### ISSUE TITLE
Additional info on security of connection management feature

### ISSUE THREAD

**Issue by kentdanas** [astronomer/docs#3165]
### Issue Type

Missing content for an existing feature

### Links to Affected Docs

https://docs.astronomer.io/astro/create-and-link-connections
https://docs.astronomer.io/astro/user-permissions

### The Issue or Context

The field has provided some feedback on additional information that would be helpful for customers around the security of the connections management feature. Currently, there is not information on which roles can access the feature, and how connections are stored, encrypted, and transmitted. These will be common security concerns for many customers, so we should address them directly in the docs.

### Fix or Proposed Change

- [x] - Add connection management feature to the [workspace roles](https://docs.astronomer.io/astro/user-permissions#workspace-roles) permissions table.
- [x] - Add a note to the [Create Airflow connections in the Cloud UI](https://docs.astronomer.io/astro/create-and-link-connections) doc to note that Workspace authors can import/export/view connections (including secret values). This is covered in the import/export connections/variables doc, but will be notable to many customers using the feature, so should be explicitly mentioned in the doc for creating connections as well.
- [ ] - Add specifics on how connections are stored, encrypted, and transmitted, similar to what we have for [env vars](https://docs.astronomer.io/astro/environment-variables#how-environment-variables-are-stored-in-the-cloud-ui) 

### Required Reviewers

Chris Abella

**Comment by lzdanski** [comment]
Additional updates:

- [ ] - Remove `Airflow` from sidebar menu
- [ ] - Rename `Requirements` to `Prerequisites`
- [ ] - Typo on `Celery executors`
- [ ] - Pull out `Public Preview`
- [ ] - Need to add `Org Settings` to docs
