### ISSUE TITLE
Add if a CLI parameter is optional or required

### ISSUE THREAD

**Issue by erdos2n** [astronomer/docs#3170]
### Issue Type

Inaccurate, misleading, or out-of-date information

### Links to Affected Docs

There are many other commands, as well

https://docs.astronomer.io/astro/cli/astro-deployment-pool-create

### The Issue or Context

Under the OPTIONS section we should specify if an option is required or optional

### Fix or Proposed Change

Add a column called Required and fill in with `True` if required

**Comment by lzdanski** [comment]
We've added `Required` to the description of new and older parameters, but closing issue due to scope change size.
