### ISSUE TITLE
Add Secrets Backend section to Gen2 Cloud Docs

### ISSUE THREAD

**Issue by aspain** [astronomer/docs#322]
**Request type:**

- [ ] **New document:**: Add the `docs-content` label to this issue.
- [X] **Addition to an existing document**: Add the `enhancement` label to this issue.

**What is the purpose of the document/enhancement? Select all that apply:**

- [ ] Document a new feature for an upcoming release. Add the appropriate release version label to this issue.
- [ ] Information for an existing feature that isn't yet documented.
- [X] Additional considerations/ reference material for an existing document.

**Problem/feature that requires documentation:**
Our  [gen2 docs](https://docs.astronomer.io/cloud) only have a couple of very brief mentions of using a 'secrets backend' but there isn't a page to show users how to implement. 

This page exists, but only in the Enterprise docs section: https://docs.astronomer.io/enterprise/secrets-backend

Can this same page be added to our Gen2 docs if there are no limitations on implementing a secrets backend on gen2?

**Comment by paolaperaza** [comment]
Yes, sorry @aspain ! GH issue here: #180
