### ISSUE TITLE
Badges for Astro, Software, Airflow, and CLI

### ISSUE THREAD

**Issue by lzdanski** [astronomer/docs#3220]
### Issue Type

Missing content for an existing feature

### Links to Affected Docs

- Astro CLI commands (https://docs.astronomer.io/astro/cli/reference)

### The Issue or Context

We need a clean, straightforward way to communicate and emphasize to users which CLI commands apply to which contexts (Astro or Software). Right now, we're using [info boxes](https://docs.astronomer.io/astro/cli/astro-deployment-airflow-upgrade), but it would be amazing to have a badge or some other visual element that's nicer-looking, similar to the [Hybrid](https://docs.astronomer.io/astro/release-notes#per-deployment-iam-workload-identities-on-aws) badge we use in release notes

### Fix or Proposed Change

- Distinct colors for each Software/Astro badge

### Additional Notes

@paolaperaza probably needs to give feedback on this!

**Comment by katiebrady-astro** [comment]
@lzdanski PR opened to (finally) add these badges! https://github.com/astronomer/docs/pull/3511

Examples
<img width="666" alt="image" src="https://github.com/astronomer/docs/assets/96535736/8088c558-c480-45a0-b117-7f60826773d1">
