### ISSUE TITLE
Clarity on `What happens during a code deploy` section of Gen2 Docs

### ISSUE THREAD

**Issue by aspain** [astronomer/docs#323]
**Affected Document:**
https://docs.astronomer.io/cloud/deploy-code#what-happens-during-a-code-deploy

**Problem Type (Priority):**

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [X] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**

I've had a few customers ask about this recently, and I think the doc is missing a few important details such as:
- What happens to a DAG (as a whole) that was executing at the time of a new code deployment? 
- Our doc mentions that `Tasks that are running will continue to execute on existing Celery Workers and will not be interrupted`, but what about any remaining downstream tasks within that same DAG that were not yet scheduled, queued, or running? If that DAG remains unchanged, will it pick up where it left off and finish running the tasks from that run? 

Can we add a couple of sentences around what will and will not continue to run if a DAG is changed or unchanged from a new deploy?

**Additional Notes:**

**Comment by paolaperaza** [comment]
This is good feedback @aspain - thanks. Questions for the folks who I think are the most experts on this & Celery -

- What happens to a DAG (as a whole) that was executing at the time of a new code deployment?
- Our doc mentions that `Tasks that are running will continue to execute on existing Celery Workers and will not be interrupted`, but what about any remaining downstream tasks within that same DAG that were not yet scheduled, queued, or running? If that DAG remains unchanged, will it pick up where it left off and finish running the tasks from that run?

@schnie Do you know for sure? cc: @cmarteepants @jaketf

**Comment by aspain** [comment]
thanks @paolaperaza  - FWIW I received this same question twice today and have a handful of times in the last few weeks as well

**Comment by aspain** [comment]
I also noticed this "What happens during a code deploy" page only exists on our gen2 docs, but not on the Enterprise docs - would the same apply to Enterprise? If so could we add it in one of the Develop/Deploy sections?

**Comment by cmarteepants** [comment]
Great questions, very detailed!

> What happens to a DAG (as a whole) that was executing at the time of a
new code deployment?

Nothing special. A DAG is just logical grouping of dependent tasks. The
DagRun will be a running state until all tasks are executed.

> Our doc mentions that Tasks that are running will continue to execute on
existing Celery Workers and will not be interrupted, but what about any
remaining downstream tasks within that same DAG that were not yet
scheduled, queued, or running? If that DAG remains unchanged, will it pick
up where it left off and finish running the tasks from that run?

Tasks that are running on a pod that is marked for termination will
continue to run up until it finishes, or whatever is set as grace period
(whichever is first). Grace period is 24 hours for Astronomer Cloud, 10
minute default for enterprise/gen1. You might have two sets of pods running
at the same time during this period. The next task (or retry) will run in a
new pod, with the updated image/code.

I don't know what happens to a task in the scheduled and queued states. I
suspect that tasks that have the state "scheduled" will be rescheduled to
run in the new pod, but that queued tasks that were already allocated to
the old pod will run there. This should be confirmed.

**Comment by cmarteepants** [comment]
Right, same thing applies. A _DagRun_ is just a group of task instances that are being executed in a certain order. Once tasks are scheduled for execution, high-level Airflow doesn't care which _DagRun_ they are part of. It just knows it has a pool of tasks to execute in a certain order, with tasks coming from different __DagRuns__. 

When a redeploy happens, K8s will put the celery pod into a terminating state and launch a new one with updated code. The scheduler then stops allocating tasks to the old celery pod. It doesn't matter if the tasks that have not yet run are from the same DAG, or different DAGs, they will be ran on the new pod.

In your example:

Redeploy happens, and `task A` is running. `task B` and `task C` need to be ran after `task A` finishes. 

1. K8s will put old celery pod into a terminating state. It will keep the pod alive until 1 of 2 things happen (whichever comes first) - `task A` finishes running, or you hit the max grace period (24 hours if Gen2, 10 minutes default if Enterprise). If `task A` doesn't finish on time, the pod will be killed and the task will fail. Depending on your DAG config, it might be retried.  

2. New celery worker pod comes up. `task B` and `task C` will run on that new pod

**Comment by aspain** [comment]
thanks @cmarteepants for the chat and clarifying this today

based on this slack convo, are there still any plans to increase/remove the Grace Period setting for gen1/enterprise Celery deployments?  https://astronomer.slack.com/archives/C01UA03TPV1/p1634759368417800?thread_ts=1634751202.378100&cid=C01UA03TPV1

I imagine many customers aren't implementing retries correctly and end up with failed tasks/dags that won't end up completing as a result of a deploy mid-dag run

**Comment by schnie** [comment]
Late here, but additionally I think there will also be some future enhancements to the experience when deploying an updated DAG, while that DAG is already executing. @kaxil was working on some DAG versioning stuff that would let us track the historical changes of a serialized DAG. My understanding of this feature would be that if a DAGRun was underway while we do a code deploy, the version of the DAG that was halfway executed would be finished, as the DAG existed in the version where it started. The _next full_ run of the DAG would be the new version.

Today, I think the updated version of the DAG would persist into the metadata db and become the source of truth for that DAG. I believe this means that any downstream tasks that changed in the code deploy would take effect immediately. 

Could be mis-remembering something here so please correct me if I'm wrong!
