### ISSUE TITLE
Typo in `docker-compose-override` doc

### ISSUE THREAD

**Issue by aspain** [astronomer/docs#329]
**Affected Document:**
https://docs.astronomer.io/enterprise/customize-image/#docker-compose-override
**Problem Type (Priority):**

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [ ] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [X] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**
"will" is misspelled in the sentence "Any values in this file wil override"
**Additional Notes:**

![image](https://user-images.githubusercontent.com/15913202/151384808-abadb4f9-1f99-4187-9956-83c7778e48bb.png)

**Comment by jwitz** [comment]
Fixed!
