### ISSUE TITLE
Gen2 - CI/CD - GitHub Actions Secret Variable name update

### ISSUE THREAD

**Issue by aspain** [astronomer/docs#335]
**Affected Document:**
https://docs.astronomer.io/cloud/ci-cd/#github-actions

In this section in particular, users are instructed to create github secrets with the prefix `secrets.` 

```
Set the following as GitHub secrets:

secrets.ASTRONOMER_KEY_ID = <your-key-id>
secrets.ASTRONOMER_KEY_SECRET = <your-key-secret>
```

**Problem Type (Priority):**

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [X] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**

Github does not allow `.` character in the secret name and will throw an error:

![image](https://user-images.githubusercontent.com/15913202/151589033-0a206452-ce47-46f5-9851-1be0307390c5.png)

The lines in the yaml example **are** correctly using `secrets.` prefix, but the prefix cannot be used in the actual variable name. Example line from the yaml:
`--data-raw '{ "client_id": "${{ secrets.ASTRONOMER_KEY_ID }}` 

Instead, I think the doc should remove the `secrets.` prefix in step 1 where users are instructed to create the secrets:

```
Set the following as GitHub secrets:

ASTRONOMER_KEY_ID = <your-key-id>
ASTRONOMER_KEY_SECRET = <your-key-secret>
```

**Additional Notes:**
The notes about how to find the Organization and Deployment IDs are included at the top in the Prerequisites section, but might make more sense to include where to find those values in step 2 on the [Github Actions](https://docs.astronomer.io/cloud/ci-cd/#github-actions) section

**Comment by paolaperaza** [comment]
Thank you for filing this, @aspain !! We'll fix this.
