### ISSUE TITLE
Manage DAG runs should be part of Observability - Thoughts ? 

### ISSUE THREAD

**Issue by manmeetkaur** [astronomer/docs#3354]
### Issue Type

Issue with website functionality

### Links to Affected Docs

https://docs.astronomer.io/astro/manage-dags

### The Issue or Context

The content in the Manage DAG Runs page is more of how to see your DAG runs and how you can act upon the DAG/Task Runs. Seems like more of a observability feature.

**Comment by lzdanski** [comment]
Superceded by new issue. Closing.
