### ISSUE TITLE
Configurable Ephemeral Storage for Worker Pods

### ISSUE THREAD

**Issue by chomipi88** [astronomer/docs#3362]
### New Feature Description

Today Astro Hosted Workers (Celery, Kubernetes and KPO) are both limited to 10Gi of ephemeral storage. Ephemeral storage refers to the filesystem that exists inside each worker. Any files created and written to the filesystem during the life of any given worker counts against this quota. 

## Goals

The primary goal of this project is to give customers access to much larger storage capacity in their Airflow workers, while billing them for the additional requested capacity. At a high level this includes:

1. **Celery Executor Worker Queues** - Default to remain at 10 GiB. Allow customers to configure a new property on their Celery Executor Worker Queues. This new field will be an integer representing the amount of ephemeral storage that we will request in our Kubernetes resources in Gibibytes.
2. **Kubernetes Executor Workers** - Default to be reduced to 0.25 GiB. Allow customers to also specify ephemeral storage requests and limits in their *DAG code*, specifically the `executor_config` section on task definitions.
3. **Both Workers** - Default to be reduced to 0.25 GiB. Allow customers to override the *default* ephemeral storage for `KubernetesExecutor` pods, as well as `KubernetesPodOperators`. 

Customers will be enabled to select higher values if they need additional capacity, up to a max of 100Gi, for each worker type.

### Required Reviewers

chomipi88

### Links to Internal Info or Resources

https://www.notion.so/astronomerio/Astro-Hosted-Ephemeral-Storage-d198aaff1b6c4d0288b9bb5dee33fa49

### Release Date

Pub Preview week of 6/3

**Comment by lzdanski** [comment]
Related - https://github.com/astronomer/docs/issues/3625

**Comment by lzdanski** [comment]
Related: https://github.com/astronomer/astro/pull/21258
