### ISSUE TITLE
Update perms for Workspace Member

### ISSUE THREAD

**Issue by chomipi88** [astronomer/docs#3368]
### Issue Type

Inaccurate, misleading, or out-of-date information

### Links to Affected Docs

https://github.com/astronomer/astro/pull/19131

### The Issue or Context

We are enabling the `Cluster Activity` view in Airflow UI to Workspace Member role. This was a new permission recently added and it defaulted to Workspace Owner only. In OSS its also enabled to the lowest role... Viewer.

### Required Reviewers

chomipi88

**Comment by lzdanski** [comment]
Docs changes visible here: https://docs.astronomer.io/astro/user-permissions#workspace-roles
