### ISSUE TITLE
Add example for how to use CLI/Local Webserver Port Override

### ISSUE THREAD

**Issue by aspain** [astronomer/docs#337]
**Affected Document:**
https://docs.astronomer.io/cloud/develop-project/#override-the-clis-docker-compose-file-local-development-only

**Problem Type (Priority):**

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [X] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**

The doc mentions using `docker-compose.override.yml` to modify ports but only shows an example for adding a volume mount.

I found instead that these ports can be overridden in the `.astro/config.yaml` file such as:

(Edit per @paolaperaza 's [link](https://forum.astronomer.io/t/i-already-have-the-ports-that-the-cli-is-trying-to-use-8080-5432-occupied-can-i-change-the-ports-when-starting-a-project/48) with postgres included):
```
project:
  name: my-project-name
webserver:
  port: 8081
postgres:
  port: 5435
```

**Additional Notes:**
Tested this using astrocloud CLI and confirmed webserver worked on port 8081 with this method

**Comment by paolaperaza** [comment]
Notes from conversation with @sunkickr. Let's -

- Add a new section (maybe to local troubleshooting doc) on `config.yaml` file & how to change your port
- Remove port example from docker override doc
- Clarify in docker override section that it doesn't "override", it just adds

These are the full configs you can set in `config.yaml` - 

```
CloudAPIProtocol:  newCfg("cloud.api.protocol", "https"),
		CloudAPIPort:      newCfg("cloud.api.port", "443"),
		CloudWSProtocol:   newCfg("cloud.api.ws_protocol", "wss"),
		CloudAPIToken:     newCfg("cloud.api.token", ""),
		Context:           newCfg("context", ""),
		Contexts:          newCfg("contexts", ""),
		LocalAstro:        newCfg("local.astrohub", "http://localhost:8871/v1"),
		LocalPublicAstro:  newCfg("local.public_astrohub", "http://localhost:8871/graphql"),
		LocalRegistry:     newCfg("local.registry", "localhost:5555"),
		PostgresUser:      newCfg("postgres.user", "postgres"),
		PostgresPassword:  newCfg("postgres.password", "postgres"),
		PostgresHost:      newCfg("postgres.host", "postgres"),
		PostgresPort:      newCfg("postgres.port", "5432"),
		ProjectDeployment: newCfg("project.deployment", ""),
		ProjectName:       newCfg("project.name", ""),
		ProjectWorkspace:  newCfg("project.workspace", ""),
		WebserverPort:     newCfg("webserver.port", "8080"),
		ShowWarnings:      newCfg("show_warnings", "true"),
```
