### ISSUE TITLE
Update Astro Cloudwatch task log export env var

### ISSUE THREAD

**Issue by conorbev** [astronomer/docs#3377]
### Issue Type

Inaccurate, misleading, or out-of-date information

### Links to Affected Docs

https://github.com/astronomer/docs/blob/55beaea7528d8c87934e9d7c8d53a64342b36435/astro/export-cloudwatch.md?plain=1#L74

### The Issue or Context

This should be `ASTRO_CLOUDWATCH_TASK_LOGS_GROUP_STREAM`

**Comment by lzdanski** [comment]
Fixed[ per slack conversation](https://astronomer.slack.com/archives/C01UA03TPV1/p1707354979646539?thread_ts=1707345187.777269&cid=C01UA03TPV1). Env var needed to be `ASTRO_CLOUDWATCH_TASK_LOGS_LOG_GROUP` not `ASTRO_CLOUDWATCH_TASK_LOGS_GROUP_STREAM`
