### ISSUE TITLE
Update all Astro Docs with Feature Entitlements

### ISSUE THREAD

**Issue by lzdanski** [astronomer/docs#3379]
### New Feature Description

Clearly communicate to users with UI elements, notes, and diagrams the different feature availabilities. 

### Required Reviewers

paola

**Comment by paolaperaza** [comment]
A couple of resources here as reference:

- https://www.notion.so/astronomerio/Hybrid-Hosted-Feature-Differentiation-Differences-4f9922c83d184973917e8733b577c232
- https://docs.google.com/presentation/d/1MoPSnjlO2I5FaxQryG9TfBDVOIUVB92sN7puIm1K4P8/edit#slide=id.gf20f28b234_0_37
- https://docs.google.com/presentation/d/1-tXXARYazj8emNV3SyyXV0w7RGo5x-d945fUd13iXRc/edit#slide=id.g2b7b3249ec4_0_972


Let's also have @iamakashladdha review this. CC: @fritz-astronomer
