### ISSUE TITLE
Label features with `Hosted` and `Hybrid`

### ISSUE THREAD

**Issue by lzdanski** [astronomer/docs#3383]
### Issue Type

Inaccurate, misleading, or out-of-date information

### Links to Affected Docs

- Docs listed and identified [via slack](https://astronomer.slack.com/archives/C01UA03TPV1/p1707483624297009)

### The Issue or Context

We need to clearly label and organize features that are Hosted only or Hybrid only. 

### Additional Notes

- Original [slack discussion](https://astronomer.slack.com/archives/C01UA03TPV1/p1707483624297009)

**Comment by jwitz** [comment]
- Create a "Hosted vs Hybrid" feature table, put this in the Reference menu
- Keep badges linked to overviews of both products, mention that Astro = Astro Hosted in Astro Overview
