### ISSUE TITLE
CLI Reference Updates

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#343]
Once we publish the CLI reference guide, let's 

- Add Astronomer Cloud CLI to meta descriptions of each doc.
- Add a column for optional or required in the "Options" sub-tables.
- Add docs or otherwise clarify autocompletion functionality.

**Comment by sunkickr** [comment]
We may want more concrete examples of `astrocloud completion`: https://astronomer.slack.com/archives/CL44PA4DB/p1643738295660819

**Comment by jwitz** [comment]
@kwcanuck When this issue was created there were a lot more required values in CLI commands. Now there's almost none - if you don't specify a Deployment ID in `astro deployment update`, for example, you are given a list of Deployments to choose from. In fact, I think the only sort of required value is when you need to create or update a custom value in the system:

https://docs.astronomer.io/astro/cli/astro-dev-run
https://docs.astronomer.io/astro/cli/astro-config-set
https://docs.astronomer.io/astro/cli/astro-deployment-update
https://docs.astronomer.io/astro/cli/astro-deployment-variable-create
https://docs.astronomer.io/astro/cli/astro-deployment-variable-update

These commands are tricky to set "required" flags for because there are multiple minimum viable commands. For example, you can run `astro deployment variable create --value=<value> --key=<key>` or your can run `astro deployment variable create --env=<env-file>`. Both are viable commands, but you need to run at least one method in order to successfully create a variable. So what really counts as "required" in this sense?

In my opinion, it makes more sense to add more context about requirements to the `Usage` section in each of these reference docs than to specify that information in tables, because tables might not be able to capture the complexities of these commands. 

Let me know if you want more context about what's required. I've got decent background on each command, but even if I don't I can test in the CLI to see what the behavior is.

**Comment by jwitz** [comment]
Closing this out for now - I don't think we're any closer to finishing this issue than we were in July. 
- The required/optional script is kind of a non-issue because most CLI commands now auto-prompt you for missing information
- The `completion` docs might be elaborated on in the future when we receive questions about them, but there's currently 0 demand for that.
