### ISSUE TITLE
Enterprise - Windows 10 CLI Install Instructions - Additional Clarity needed

### ISSUE THREAD

**Issue by aspain** [astronomer/docs#344]
**Affected Document:**
I've encountered several users who were unclear on the correct install steps for the Windows CLI on Enterprise

https://docs.astronomer.io/enterprise/cli-install-windows-10/#step-3-download-the-astro-cli
**Problem Type (Priority):**

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [X] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**
Currently the Step 3 links [here](https://github.com/astronomer/astro-cli/releases/) for downloading the CLI but once directed there, there are 10 different assets to choose from. It is not clear to a user which one they need to download. 

[This separate git page](https://github.com/astronomer/astro-cli#installing-on-windows) provides more clarity on this, and I think this information needs to be added to the enterprise doc. Specifically the note on `Extract the file ending in windows_386.zip`

**Additional Notes:**
Suggested rewording: 

```
Step 3. Download the Astro CLI
Currently, Astronomer on Windows outside of WSL is only supported by Astronomer CLI versions 0.8 and beyond.

You can download the latest version of the CLI [here](https://github.com/astronomer/astro-cli/releases/), specifically the Asset ending in `windows_386.zip`
```

**Comment by kwcanuck** [comment]
This is one of many issues created to address the Windows CLI installation updates. The PR associated with this issue has been merged, so I am closing this issue. New branches will be created to resolve the remaining issues.

**Comment by paolaperaza** [comment]
Closing! Handled by:

- Here: https://docs.astronomer.io/software/install-cli
- Here: https://docs.astronomer.io/astro/cli/configure-cli#install-the-cli
