### ISSUE TITLE
Add example/information on writing to `/tmp` folder

### ISSUE THREAD

**Issue by aspain** [astronomer/docs#354]
**Affected Document:**
Cloud & Enterprise docs

**Problem Type (Priority):**

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [X] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**
I often encounter customers attempting to use tasks to write files which gives them a `OSError: [Errno 30] Read-only file system` error. 

While customers _can_ pass data in xcoms or place in intermediary storage such as S3, we _do_ allow write-access to the `/tmp` folder. The only mention of `/tmp` I see in our docs is in our [Enterprise KOP](https://docs.astronomer.io/enterprise/kubernetes-executor/#configure-the-kubernetes-executor-using-pod-templates) docs

Could we add a brief section to both our Cloud & Enterprise docs mentioning this write access so we can point customers to it when they have questions?

**Additional Notes:**
A simplified example:

```
touch_file = BashOperator(
        task_id="touch_file",
        bash_command='touch /tmp/my-file-to-write.txt'
    )
```

**Comment by frankcash** [comment]
Here is a sample of a DAG with one Task that writes to a local temp file and then reads it to `logging.info`

Assumes that you've uploaded the worlde dataset from kaggle <https://www.kaggle.com/bcruise/wordle-valid-words> to your s3 bucket, so please feel free to change the keys

```python

from datetime import datetime

from airflow import DAG
from airflow.operators.bash import BashOperator
from airflow.operators.python import PythonOperator
from airflow.providers.amazon.aws.hooks.s3 import S3Hook
import logging

def read_report():
    keys = ['valid_solutions.csv', 'valid_guesses.csv']
    hook = S3Hook("aws_east")
    for key in keys:
        filename = hook.download_file(key=f"temp/{key}", local_path="/tmp")
        f = open(filename, 'rb')
        result = f.read()
        logging.info(f"{result=}")
    pass

with DAG(
    'local_file_sample',
    default_args={'retries': 1},
    schedule_interval='@once',
    start_date=datetime(2022, 2, 1),
    catchup=False,
    tags=['example']
) as dag:

    t0 = PythonOperator(task_id='s3_pull', python_callable=read_report)

    t0
```

**Comment by jwitz** [comment]
We don't quite have a home yet for Airflow-specific recommendations on product docs.. is write access to `tmp` specific to Astronomer in any way?  Maybe this info belongs in one of our Airflow Guides, such as https://www.astronomer.io/guides/airflow-passing-data-between-tasks#intermediary-data-storage

cc: @kentdanas
