### ISSUE TITLE
Datadog Api Key var name change

### ISSUE THREAD

**Issue by alex-astronomer** [astronomer/docs#3568]
### Issue Type

Inaccurate, misleading, or out-of-date information

### Links to Affected Docs

https://docs.astronomer.io/astro/export-datadog

### The Issue or Context

In this document we instruct customers to set `DATADOG_API_KEY`.  I received a notification for a customer that their statsd pod was crash looping because it is missing the variable `DD_API_KEY`.  We have seen this for other customers as well.  Not sure who defines and uses this variable (datadog platform/app or our platform) however it seems that the name of this var possibly changed.

**Requires more research.**

### Fix or Proposed Change

If we find out that the variable name `DATADOG_API_KEY` is deprecated, then we can change our docs and replace that name with `DD_API_KEY`.

### Additional Notes

Not confirmed through datadog docs, just making an assumption based on the influx of tickets that we've been receiving over the last few months.

Seems the first ticket that references this is some time in fall or winter of 2023, just for reference.

**Comment by lzdanski** [comment]
We found this bug in the Datadog repo that relates -https://github.com/DataDog/datadog-ci/issues/823

**Comment by lzdanski** [comment]
Under investigation. [Slack thread](https://astronomer.slack.com/archives/C015V2JFKT5/p1711556874569189)
