### ISSUE TITLE
external secrets backend on astronomer cloud doc is misleading

### ISSUE THREAD

**Issue by krisdock** [astronomer/docs#358]
**Affected Document:**

https://www.astronomer.io/docs/cloud/stable/customize-airflow/secrets-backend
  
**Severity:**

- [ ] Critical: This document has incorrect or missing information. Add the `error/critical` label to this issue.
- [x] FYI: The document is misleading or could benefit from additional context or guidance. Add the `error/FYI` label to this issue.
- [ ] Typo: Add the `error/typo` label to this issue.
  
**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**

we call out gcp secret manager as a backend secrets tool that's configurable, but then we don't provide instructions on how to set it up despite doing so for the other tools on the list. we should improve the document and provide the instructions for configuring gcp secret manager.

**Additional Notes:**

https://astronomer.zendesk.com/agent/tickets/4660

**Comment by jwitz** [comment]
@krisdock Starting on this using this Notion doc as reference https://www.notion.so/astronomerio/How-to-enable-Google-CloudSecretManager-as-secret-backend-2104169da0e048eaa41006b0859af883#34d25f8072504205b2bcefb76f6e66e3, let me know if there's more considerations here
