### ISSUE TITLE
Make version support info more clear

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#359]
**Affected Document:** https://docs.astronomer.io/enterprise/ac-support-policy/#astronomer-certified-lifecycle-schedule

We can improve our support policies in two ways:

1. Make it more clear that Stable and LTS channels can have new features/ testing regardless of the channel, but that generally speaking more new/ cutting edge features go into Stable than LTS. 
2. Add back the "Release Channel" column to our support tables to make it clear which release is which. It's hard to figure out what channels are Stable right now, especially with the variable dates for the most recent releases. Alternatively, we can break out release channels into two separate tables if that's more legible.

**Comment by frankbreetz** [comment]
I think it would be more clear to have an Stable EoM Column(could be in the past) and a LTS EoM Column.
