### ISSUE TITLE
Enterprise docs reference Gen1 Cloud base domain for Airflow upgrade process

### ISSUE THREAD

**Issue by aspain** [astronomer/docs#360]
**Affected Document:**
https://docs.astronomer.io/enterprise/manage-airflow-versions/#via-the-astronomer-cli

```
To initialize the Airflow upgrade process via the Astronomer CLI, first make sure you're authenticated by running $ astro auth login gcp0001.us-east4.astronomer.io.
```

**Problem Type (Priority):**

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [X] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**
This line in our Enterprise 'manage airflow versions' section provides the Gen1 Cloud base URL for the `astro auth login` command

```
To initialize the Airflow upgrade process via the Astronomer CLI, first make sure you're authenticated by running $ astro auth login gcp0001.us-east4.astronomer.io.
```

Might be best to change it to:  `$ astro auth login <YOUR-BASE-DOMAIN>`
**Additional Notes:**

**Comment by jwitz** [comment]
Closed via https://github.com/astronomer/docs/commit/ec832021155fc52d7be8a6d64ca3a58284b69f04!
