### ISSUE TITLE
CircleCI CI/CD

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#364]

**Comment by pohek321** [comment]
I modified [this CircleCI script](https://github.com/astronomer/airflow_meta/blob/main/.circleci/config.yml) (provided by Chris Cardillo in product) to be more generic and reusable for a customer. It's currently saved [here](https://astronomerio.notion.site/CircleCI-CI-CD-Gen2-96266f8caed1495b86580f76c534f92d) in a Notion Doc. This could be a great starting point for completing this Issue.

**Comment by pohek321** [comment]
Updated the Notion Doc to follow the same CI/CD pattern that is documented for [GitHub Actions](https://docs.astronomer.io/astro/ci-cd#github-actions) and [Jenkins](https://docs.astronomer.io/astro/ci-cd#jenkins). Opened a PR and requested @jwitz to review.
