### ISSUE TITLE
Custom Plugin Support for Airflow Menus

### ISSUE THREAD

**Issue by chomipi88** [astronomer/docs#3653]
### Issue Type

Missing content for an existing feature

### Links to Affected Docs

https://docs.astronomer.io/astro/cli/develop-project#add-airflow-plugins
https://docs.astronomer.io/astro/user-permissions#workspace-roles
https://docs.astronomer.io/astro/deployment-role-reference

### The Issue or Context

We are adding support for custom plugins that provide a custom view in the Airflow UI, via a new permission `deployment.airflow.customMenu.get`.
The permission will be enabled by default for the `Workspace Member` role and be enabled for the `Deployment Viewer` custom deployment role template.
The required Runtime support will be released in the next 9, 10, and 11 releases.

### Additional Notes

Below is an example template and required additions to plugin code for adding support.

```
from airflow.configuration import conf // a line they will have to add

# Creating a flask appbuilder BaseView
class TestAppBuilderBaseView(AppBuilderBaseView): // they can have their own plugin code defined here but the @has_access should be as written here
    class_permission_name = "Custom Menu"
    default_view = "test"

    @expose("/")
    @has_access(
        [
            (permissions.ACTION_CAN_ACCESS_MENU, "Custom Menu"), // a line they will have to add
        ]
    )
    def test(self):
        return "Hello galaxy!"

v_appbuilder_view = TestAppBuilderBaseView() //boiler plate they likely already have

v_appbuilder_package = { //boiler plate they likely already have
    "view": v_appbuilder_view,
}
baseUrl = conf.get("webserver", "base_url") // a line they will have to add
my_new_endpoint = { // a line they will have to add
    "name": "Custom Menu",
    "label": "DAGs Folder",
    "href":  str(baseUrl) + "/testappbuilderbaseview",
}

# Defining the plugin class
class AirflowTestPlugin(AirflowPlugin):
    name = "test_plugin"
    hooks = [PluginHook]
    macros = [plugin_macro]
    flask_blueprints = [bp]
    appbuilder_views = [v_appbuilder_package]
    appbuilder_menu_items = [my_new_endpoint] // a line they will have to add
```

### Required Reviewers

chomipi88, aliotta

**Comment by sreenusuuda** [comment]
We need to have below two import statements as well.

from airflow.www.auth import has_access
from airflow.security import permissions

**Comment by jwitz** [comment]
@chomipi88 Are the required lines in the code sample only required for Astro, or is that general plugin setup? I'm thinking we could update https://docs.astronomer.io/learn/using-airflow-plugins#appbuilder-menu-items with an Astro-specific note so that we keep all plugin docs on a single page

**Comment by sreenusuuda** [comment]
They are Astro specific and yes should update in the above link. @aliotta correct If I am wrong.
