### ISSUE TITLE
BitBucket CI/CD

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#366]

**Comment by kwcanuck** [comment]
@jwitz can you clarify the requirements for this issue?

**Comment by jwitz** [comment]
Let’s go ahead and close these placeholder CI/CD issues. It’s unclear whether any Astro users or prospects have the need for these tools yet, and if they do then I expect the field to come to us with those needs and potential templates.

**Comment by paolaperaza** [comment]
This one was actually solved for this week with: https://github.com/astronomer/docs/pull/997

Thanks @aspain 😊
