### ISSUE TITLE
[user reported] Variable name for Datadog API Key incorrect

### ISSUE THREAD

**Issue by manmeetkaur** [astronomer/docs#3666]
### Issue Type

Inaccurate, misleading, or out-of-date information

### Links to Affected Docs

https://docs.astronomer.io/astro/export-datadog

### The Issue or Context

`DD_API_KEY` is incorrect. It should be `DATADOG_API_KEY`

One can tell this from the error thrown by astro_logging.py 
```ValueError: Datadog API Key must be provided or set in the DATADOG_API_KEY environment variable```

### Additional Notes

I will have to test it before I submit a PR

**Comment by lzdanski** [comment]
So this is a problem on the DataDog end of things - will have to do a bit of investigation to determine the right docs fix. https://github.com/astronomer/docs/issues/3568

**Comment by lzdanski** [comment]
Fixed here - https://github.com/astronomer/docs/pull/3682/files
