### ISSUE TITLE
Add `yanked` versions to astro docs

### ISSUE THREAD

**Issue by lzdanski** [astronomer/docs#3734]
### Issue Type

Missing content for an existing feature

### Links to Affected Docs

- https://docs.astronomer.io/astro/runtime-version-lifecycle-policy#restricted-runtime-versions
- https://docs.astronomer.io/astro/upgrade-runtime#upgrade-considerations

### The Issue or Context

We now mark broken runtime versions that should not be used to create deployments with `yanked`, but we need to include which versions are yanked in the docs.

### Fix or Proposed Change

- Add a table with the yanked versions to the relevant docs
- add a note to any relevant versions in "upgrade considerations" that are also yanked

### Additional Notes

https://astronomer.slack.com/archives/C03CT3DNZMH/p1715625194608939

**Comment by cmarteepants** [comment]
Should we indicate in the release notes for specific versions that they are yanked?
