### ISSUE TITLE
Optimize Software sidebar structure

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#374]
Now that we've fully migrated Enterprise over to Docusaurus, we should spend some time restructuring the docs sidebar. Specifically, we should make it more clear which docs are for administrative tasks and which docs are for daily user tasks. This could also involve moving content between docs, but hoping to just touch the sidebar for this v1

**Comment by paolaperaza** [comment]
While we figure out the new IA, I'd say this actually isn't actionable quite yet. Going to close this out for now and we can re-open as soon as we've got something ready to be worked on.
