### ISSUE TITLE
Add documentation for AWS Secrets Manager

### ISSUE THREAD

**Issue by pohek321** [astronomer/docs#376]
**Request type:**

- [ ] **New document:**: Add the `docs-content` label to this issue.
- [ x ] **Addition to an existing document**: Add the `enhancement` label to this issue.

**What is the purpose of the document/enhancement? Select all that apply:**

- [ ] Document a new feature for an upcoming release. Add the appropriate release version label to this issue.
- [ x ] Information for an existing feature that isn't yet documented.
- [ ] Additional considerations/ reference material for an existing document.

**Problem/feature that requires documentation:**
We currently have documentation for AWS Parameter Store [here](https://docs.astronomer.io/cloud/secrets-backend#aws-systems-manager-parameter-store), but not for AWS Secrets Manager. I've created a customer facing Notion for this [here](https://astronomerio.notion.site/AWS-Secrets-Manager-f606d2b8f0e5443991b621b0e2ed9230), but it would be nice to have it in our official cloud docs.

**Are you the right person to review a draft of the document for technical accuracy? If not, who is?**
I can review if needs be, the Notion doc that I linked above has been tested in a development and production environment.

**Comment by paolaperaza** [comment]
@pohek321 There's actually already a GitHub issue for this here - https://github.com/astronomer/docs/issues/339

Going to close this out as a duplicate! I didn't realize you already had an internal Notion doc on this though, that's huge - will link out in other issue.  Thank you !
