### ISSUE TITLE
Customer Managed Identity Support on Astro Hosted (AWS)

### ISSUE THREAD

**Issue by chomipi88** [astronomer/docs#3805]
### New Feature Description

**Introducing Customer Managed Identity Support**

Astro now also supports the ability for customers to assign a workload identity, specifically an AWS IAM role, to their Airflow Deployments on Astro. The Deployment and configured Airflow connections will authorize to customer data services using the customer managed identity. This release also adds the following benefits:

- Re-use or share a customer managed identity across N deployments (ephemeral or static)
- Leverage existing identities when migrating from Cloud Composer environments
- Reduced migration friction and change risk

Important Details for executing the provided bash script:
- IF executing from a local terminal the user is required to have **aws, jq, and openssl** clis
- IF executing from. with AWS cloud shell, all 3 requires clis are built in

Additional details for less friction if using this feature for Ephemeral Deployments on DEDICATED clusters only. Major security risk doing this on STANDARD clusters.

As part of configuring the IAM Trust Policy, instead of specifying the deployment release name (see bolded part below) as provided in the Astro UI, customers can use a wildcard to apply said trust policy for any deployment that gets created on that cluster. The **account-id** and **cluster oidc url** are unique and specific to a given dedicated cluster.

{
    "Effect": "Allow",
    "Principal": {
      "Federated": "arn:aws:iam::868745184497:oidc-provider/oidc.eks.eu-central-1.amazonaws.com/id/24AFC4AF8C5916E8867198F6582E3396"
    },
    "Action": "sts:AssumeRoleWithWebIdentity",
    "Condition": {
      "StringLike": {
        "[oidc.eks.eu-central-1.amazonaws.com/id/24AFC4AF8C5916E8867198F6582E3396:aud](http://oidc.eks.eu-central-1.amazonaws.com/id/24AFC4AF8C5916E8867198F6582E3396:aud)": "[sts.amazonaws.com](http://sts.amazonaws.com/)",
        "[oidc.eks.eu-central-1.amazonaws.com/id/24AFC4AF8C5916E8867198F6582E3396:sub](http://oidc.eks.eu-central-1.amazonaws.com/id/24AFC4AF8C5916E8867198F6582E3396:sub)": "system:serviceaccount:**lunar-inclination-7874**:*"
      }
    }
  }

### Required Reviewers

chomipi88

### Links to Internal Info or Resources

same feature as previously released for GCP

### Release Date

tbd

**Comment by chomipi88** [comment]
Related PR; https://github.com/astronomer/astro/pull/21335

**Comment by chomipi88** [comment]
Private Preview: Week of June 10th
Public Preview: Week of June 24th

**Comment by lzdanski** [comment]
https://github.com/astronomer/astro/pull/21863
