### ISSUE TITLE
Confusion about DAG writing best practices 

### ISSUE THREAD

**Issue by wolfier** [astronomer/docs#381]
**Affected Document:**  [DAG Writing Best Practices](https://www.astronomer.io/guides/dag-best-practices)
  

**Severity:** 

- [ ] Critical: This document has incorrect or missing information. Add the `error/critical` label to this issue.
- [x] FYI: The document is misleading or could benefit from additional context or guidance. Add the `error/FYI` label to this issue.
- [ ] Typo: Add the `error/typo` label to this issue.
  
**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**

This issue is just for the section titled "Avoid Top-Level Code in Your DAG File". 

A better example would be a dynamic DAG dependent on data in a database. You would need to query the database and then use that data to build your DAG commonly done through iterating the result.

```python
result = PostgresHook.get_records("SELECT * FROM grocery_list;")

with DAG(
...
) as dag:
    for grocery_item in result:
        p = PostgresOperator(
            ...        
            sql="INSERT INTO purchase_order VALUES (value1, value2, value3);"
        )
```

In the code above, the DAG is dependent on the grocery_list table. When the scheduler parses this dag file, it will query the database to construct the DAG and operators.

In the example given in the guide, the dag code is only defining a PostgresOperator which does NOT reach out to a database. This would not be considered a top level code. However, that example is perfect for showing how to improve readability.

My suggestion is to create an additional example for explicitly the detrimental impact of top level code like a dynamic dag making database calls.

**Additional Notes:**

This was raised by a customer in [Zendesk #4920](https://astronomer.zendesk.com/agent/tickets/4920).

Slack converstation in [#docs](https://astronomer.slack.com/archives/C015V2JFKT5/p1623082277009300).

Tagging @kentdanas

**Comment by kentdanas** [comment]
PR to clarify language and add a new example here: https://github.com/astronomer/airflow-guides/pull/214

**Comment by kentdanas** [comment]
PR astronomer/airflow-guides#214 merged!
