### ISSUE TITLE
Add `Example CICD Workflow` example/diagram to Astro Cloud CI/CD Doc

### ISSUE THREAD

**Issue by aspain** [astronomer/docs#381]
**Affected Document:**
https://docs.astronomer.io/cloud/ci-cd
**Problem Type (Priority):**

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [X] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**
Customers often ask for examples/explanation of how CI/CD can be incorporated in their deployments - the [Enterprise docs](https://docs.astronomer.io/enterprise/ci-cd#example-cicd-workflow) have a great blurb and diagram showing an example, can this be added to the Cloud doc as well? 

**Additional Notes:**
This section and image in particular:
![image](https://user-images.githubusercontent.com/15913202/153659936-3dee2e64-02bd-419b-81a4-53a70b3cd9c4.png)

**Comment by paolaperaza** [comment]
This is actually done! As part of Multi-branch CI/CD for GitHub Actions: https://docs.astronomer.io/astro/ci-cd#cicd-templates

![image.png](https://images.zenhubusercontent.com/59d78295b0222d5de47a8bfe/bdf00812-7658-48bc-83d6-be7279c6d86c)
