### ISSUE TITLE
Update PgBouncer support snippet

### ISSUE THREAD

**Issue by aspain** [astronomer/docs#384]
**Affected Document:**
https://docs.astronomer.io/cloud/known-limitations/#known-limitations

This doc mentions `We do not currently support PgBouncer` but it was rolled out last month based on this message: https://astronomer.slack.com/archives/C01UA03TPV1/p1642012737101000

Slack convo around this doc fix: https://astronomer.slack.com/archives/C01UA03TPV1/p1644846468079319
**Problem Type (Priority):**

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [X] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**
Update wording around not supporting PgBouncer or add messaging around support/how it is used somewhere in Cloud docs

**Additional Notes:**

**Comment by paolaperaza** [comment]
@aspain We removed the statement around PgBouncer not being supported from our Known Limitations doc! Thanks for the catch.

There's not an obvious place to document PgBouncer in general and I don't have a compelling reason to do so given it's an infra resilience thing that customers really shouldn't need to know about.

Going to close this out for now... let me know if this comes up with customers though and we can add something back in.
