### ISSUE TITLE
AWS Enterprise NLB - extra documentation / misconfiguration

### ISSUE THREAD

**Issue by fritz-astronomer** [astronomer/docs#386]
**Affected Document:**
https://www.astronomer.io/docs/enterprise/v0.25/install/aws/install-aws-standard
  
**Severity:**
- [ ] Critical: This document has incorrect or missing information. Add the `error/critical` label to this issue.
- [x] FYI: The document is misleading or could benefit from additional context or guidance. Add the `error/FYI` label to this issue.
- [ ] Typo: Add the `error/typo` label to this issue.
  
**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**
A customer (Amount) brought this up. Apparently in a private VPC, if you have an NLB, there's a weird 60s timeout that makes our web interface **very** slow. The fix is to use a classic load balancer - not NLB. 

Our install documentation includes NLB in the default `config.yaml` snippet. We should probably include a note on it, and specifically mention not to use it in this instance. @cmarteepants might have more info around exactly what the issue is

**Comment by cmarteepants** [comment]
Just to clarify the issue - I might have some details wrong - but I encountered this problem when installing a production self-hosted Gitlab instance in EKS.

If the following is true:

- the ec2 nodegroups for EKS are on private subnets
- the vpc does not have a NAT gateway configured. (traffic is first routed to a shared account via transit gateway where they eventually have external access in client's case)

When using AWS NLB with an ingress controller (nginx), if two pods are collocated on the same node and attempt to communicate using an external dns, the source IP and destination IP are - according to nginx - one and the same, and thinks that the packets are malformed and throws an error. It'll keep retrying and will eventually try other pods if there are replicas available. To the end-user for clusters with more than one worker node, it appears as though there are intermittent connectivity problems and performance issues. 

For example - if I have a self-hosted docker registry in my cluster at `registry.example.com` and I have a pod that builds and pushes docker images - if my docker-build pod tries to login to the registry via `registry.example.com` and both pods are on Node A, it won't work and the client will eventually see an nginx error on their web browser. However, if there is a replica on Node B, it will eventually try forwarding the traffic to the pod on Node B. For the user, it feels like the application is slow.

**Comment by pgagnon** [comment]
is `externalTrafficPolicy` set to `Local` or `Cluster`?

**Comment by cmarteepants** [comment]
It would have been whatever the default is. Client resolved it themselves by removing the nlb annotation and preferred using classic. I didn’t push further

**Comment by jwitz** [comment]
@cmarteepants I'm curious about how common this setup is, and whether we need to make note of it to all customers. Amazon [specifically recommends](https://docs.aws.amazon.com/vpc/latest/userguide/vpc-nat.html) using NAT Gateways with VPC. I don't want to document something that already isn't best practice in our Helm chart, but if there's a good reason to have this configuration then I can see adding a note about it.

**Comment by cmarteepants** [comment]
I think it's just a matter of putting a disclaimer saying to switch the
"nlb" to "elb" if your nodegroup is private, and you are not utilizing a
nat gateway - we don't need to modify the chart. Ingress Annotations aren't
there by default if I recall correctly, but it is in the example config in
the install instructions.

You _should_ be using a nat gateway, but if you are in an multi-account
environment and traffic is routed to a shared account first and then
diverted to a different account via TransitGateway, that is acceptable.
Some products such as AWS Landing Zone force this pattern. I don't think
it's super common in small orgs, but multi-account is a common pattern in
bigger heavily controlled places.

**Comment by pgagnon** [comment]
An alternative option would be to use the rewrite plugin in coredns to rewrite calls to `*.<base domain>` to `astronomer-nginx.astronomer.svc`. That would avoid the hairpin.
