### ISSUE TITLE
Missing documentation for Astro CLI command "astro organization audit-logs"

### ISSUE THREAD

**Issue by wolfier** [astronomer/docs#3884]
### Issue Type

Missing content for an existing feature

### Links to Affected Docs

https://www.astronomer.io/docs/astro/category/astro-organization

### The Issue or Context

There are references in the [Astro docs](https://www.astronomer.io/docs/astro/audit-logs#export-audit-logs) but no documentation on the command `astro organization audit-logs`.

**Comment by EdwardAngert** [comment]
@wolfier - is that <https://www.astronomer.io/docs/astro/audit-logs>?

looks like it's currently under **Platform observability**, but when I run `astro organization audit-logs -h`, I get:

```shell
Manage your Organization audit logs.

Current Context: Astro

Usage:
  astro organization audit-logs [command]

Aliases:
  audit-logs, al

Available Commands:
  export      Export your Organization audit logs in GZIP. Requires Organization Owner permissions.

Flags:
  -h, --help   help for audit-logs

Global Flags:
      --verbosity string   Log level (debug, info, warn, error, fatal, panic (default "warning")

Use "astro organization audit-logs [command] --help" for more information about a command.
```

It might be easy enough to add a link to it in the sidebar (leaving the file where it is), but I can't find a way to make it look consistent in Docusaurus:

<img width="1136" alt="SCR-20240718-twfh" src="https://github.com/user-attachments/assets/37cb4ec0-9f45-448a-954c-5d984159b5ca">

---

Now that I've written all that out to test it, I'll just put in a PR and let you all decide if that works.
