### ISSUE TITLE
Ephemeral Storage support in Deployment Analytics

### ISSUE THREAD

**Issue by chomipi88** [astronomer/docs#3899]
### Issue Type

Missing content for an existing feature

### Links to Affected Docs

https://www.astronomer.io/docs/astro/deployment-metrics#deployment-analytics

### The Issue or Context

https://astronomer.slack.com/archives/C01UA03TPV1/p1720467346182709

### Fix or Proposed Change

- Add ephemeral storage support metric for Celery Workers and Schedulers.
- Add new section for KE/KPO metrics with ephemeral storage support metric.
- Highlight new Dynamic Y-axis Scaling capability on Worker, KE/KPO, and Scheduler panel graphs

### Required Reviewers

chomipi88

**Comment by lzdanski** [comment]
Resolved by https://github.com/astronomer/docs/pull/3903
