### ISSUE TITLE
Astro logo opens new tab

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#393]
The logo on the top left corner of docs.astronomer.io links back to https://docs.astronomer.io/astro/ correctly but it opens up a new tab. It should NOT open up a new tab.

![GIF](https://user-images.githubusercontent.com/31111752/154759498-050debea-7dab-4f34-b766-69d4e0b51785.gif)

**Comment by jwitz** [comment]
Resolved by using the `target` config in Docusaurus, changes should be live shortly https://github.com/astronomer/docs/commit/e564fd14b0b87d2a3cfec784582f71b07cd1e72e

**Comment by paolaperaza** [comment]
Confirmed! Thanks Jake.
