### ISSUE TITLE
Update https://github.com/astronomer/astronomer/blob/master/UPDATING.md

### ISSUE THREAD

**Issue by danielhoherd** [astronomer/docs#408]
**Affected Document:**
  
https://github.com/astronomer/astronomer/blob/master/UPDATING.md

**Severity:**

- [X] FYI: The document is misleading or could benefit from additional context or guidance. Add the `error/FYI` label to this issue.
  
**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**

The contents of this doc are WAY out of date, beyond useless.

**Comment by jwitz** [comment]
We should probably just delete this, or link out to our existing docs? Not a fan of having two sources of truth for updates. I'd probably go for the latter option

**Comment by danielhoherd** [comment]
I think it should be fine to delete UPDATING.md and leave a link in some other doc, probably README.md, pointing to the official docs.
