### ISSUE TITLE
Add CLI Install Instructions for Apple M1

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#415]
Users installing the Astronomer CLI on an Apple M1 machine often need to take a few extra steps. Given the amount of requests and support tickets around this, our team has created instructions here:

- https://www.notion.so/astronomerio/Installing-Astro-CLI-on-Apple-Mac-M1-c40caf2524e24b08a23faf67f388c6af

Related:
- https://forum.astronomer.io/t/airflow-2-0-on-applem1-machine-qemu-uncaught-target-signal-4-illegal-instructions-core-dumped/1154

@jwitz When you get a chance, could you take a look at these resources, verify 'em, and then add to our CLI Quickstart? That doc is getting a bit long, so we could consider splitting this out. Will defer to you!

cc: @shmanu017 @rbankston

**Comment by rbankston** [comment]
1. Install x86_64 version of homebrew via:

```
arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```

2. Confirm that the script has successfully installed homebrew on /usr/local.  FYI, arm64 version of homebrew gets installed into /opt/Homebrew.

3. Once x86_64 homebrew is installed, run (replace version with whatever version of your choice):

```
arch -x86_64 /usr/local/Homebrew/bin/brew install astronomer/tap/astro@0.25.1
```

4. You should be able to now run astro version to confirm that CLI is working.
