### ISSUE TITLE
Software Airflow Version Upgrade link is broken

### ISSUE THREAD

**Issue by fletchjeff** [astronomer/docs#416]
https://www.astronomer.io/docs/cloud/stable/customize-airflow/manage-airflow-versions

Error (Critical)

In the Astronomer Software UI when you upgrade the Airflow Version for a deployment, there is a link that pops up to request the user to follow specific instructions. That [link](https://www.astronomer.io/docs/cloud/stable/customize-airflow/manage-airflow-versions)is now gone and reverts to the main docs page.

**Comment by paolaperaza** [comment]
@jwitz Can you add a redirect so we catch this particular change for users?

- From: https://www.astronomer.io/docs/cloud/stable/customize-airflow/manage-airflow-versions
- To: https://docs.astronomer.io/software/manage-airflow-versions

**Comment by jwitz** [comment]
Waiting to see if this works, but just added a specific redirect to our base site: https://github.com/astronomer/astro-site/blob/main/static/_redirects

Once I confirm that the redirect works, I'll close out this issue

**Comment by allenbrady-astro** [comment]
Hey @jwitz got you added to the repo!
