### ISSUE TITLE
Make footer consistent with main product page

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#420]
It would be good to have our footer look similar between different Astronomer contexts by having the "A" logo and individual logos for external platforms. 

<img width="1366" alt="Screen Shot 2022-02-24 at 7 53 24 PM" src="https://user-images.githubusercontent.com/74574233/155597261-05bfcc4e-afce-4d55-a078-5de1442d7f2a.png">

**Comment by kwcanuck** [comment]
@jwitz is this still something you want to do? Adding the logo to the footer _might_ cause issues with the existing navigation aids.

![image](https://user-images.githubusercontent.com/104205257/181508273-d66fb18f-795a-4c6d-b754-ec5a31c2990d.png)

Also, the top banner already contains branding:

![image](https://user-images.githubusercontent.com/104205257/181508412-a5e525b2-89e2-4802-a44a-6ec2ea8e7325.png)

**Comment by jwitz** [comment]
V stale issue, closing because there are no current plans to address this.
