### ISSUE TITLE
Update CI/CD, Deployment API Keys, and Deploy Code Doc with new CLI-First Flow

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#429]
Based on: https://docs.astronomer.io/astro/cli-release-notes/#deploy-to-astro-with-deployment-api-keys-for-simpler-cicd

### CI/CD Doc

This change should include -

- Update to Workflow Overview
     - Add install CLI step
     - Replace steps 2 + 3 with `astrocloud deploy` command/functionality
- An update to all CI/CD script examples
- An update to example bash script
- Change to any mention of access token

### Deployment API Key Doc

- Modification or removal of the `request-access-token` section in https://docs.astronomer.io/astro/api-keys/

### Deploy Code 

- NEW section below `What Happens during a Code Deploy`
- Is called "Run pytests on a Code Deploy"
- Explains functionality that's hinted at here: https://docs.astronomer.io/astro/cli-release-notes#new-command-to-run-dag-unit-tests-with-pytest

Assigning to you both, @sunkickr & @jwitz. Let's get this done this week 🙏

**Comment by jwitz** [comment]
I think the Pytest flag is better kept in a tip box for the Deploy Code doc. We can then make the Test and Troubleshoot doc section the primary source of information for Pytest and link out to there.
