### ISSUE TITLE
How to scale up an instance

### ISSUE THREAD

**Issue by vparekh94** [astronomer/docs#43]
It isn't clear what needs to happen to get your airflow instance to execute more tasks - if you add a celery worker, you need to change concurrency+parallelism settings. At a certain point, you'll need scale up your scheduler as well to avoid scheduling delays. 

This doc should:

- Go through how to add a worker
- Which configurations to change to get your instance to run more total tasks
- How to get your workers to do more than 16 tasks each
- Other things you can tune

**Comment by andrewhharmon** [comment]
just pushed this up to the repo
