### ISSUE TITLE
Fix fonts on headers to be consistent

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#430]
It doesn't look like our headers in docs are using the same font that body text is using. Should be `Inter`. Let's confirm and change if needed.

![image](https://user-images.githubusercontent.com/31111752/156093674-2a4f0116-650b-4241-9da5-b02790c91a55.png)

**Comment by allenbrady-astro** [comment]
Hey @jwitz, looks like we're loading the normal, 600 and 800 font weights for Inter at the top of custom.css and just need to adjust one line of CSS to get em bolder (should be line 172):
```
h1,
h2,
h3,
h4,
h5,
h6 {
  font-weight: 600;
  font-family: var(--font-sans-heading);
}
```

I put 600 there but if you want _even bolder_ you could put 800. Here's what 600 looks like:
<img width="793" alt="image" src="https://user-images.githubusercontent.com/96535736/156189459-bd13d8d6-f4e8-48d9-a9c7-a12cc3030975.png">

And here's 800
<img width="785" alt="image" src="https://user-images.githubusercontent.com/96535736/156189511-1ddc5023-7da3-4fd4-a106-b847d4a691ff.png">
