### ISSUE TITLE
Use MGMT UI to fetch user info

### ISSUE THREAD

**Issue by moonwonlee** [astronomer/docs#437]

**Comment by paolaperaza** [comment]
Hey @moonwonlee ! Did you mean to add this to the docs repo? 😄

**Comment by moonwonlee** [comment]
> Hey @moonwonlee ! Did you mean to add this to the docs repo? 😄

ohhhh my bad, I just figured out that my zenhub default repo was set to be astronomer/docs. I changed it! Sry!
