### ISSUE TITLE
Helm Version Documentation with releases

### ISSUE THREAD

**Issue by rbankston** [astronomer/docs#439]
**Request type:**

- [ ] **New document:**: Add the `newcontent` label to this issue. 
- [x] **Significant change to an existing document**: Add the `enhancement` label to this issue. 

**What is the purpose of the document/enhancement? Select all that apply:**

- [ ] Document a new feature for an upcoming release. Add the appropriate release version label to this issue. 
- [x] Information for an existing feature that isn't yet documented.
- [ ] Additional considerations/ reference material for an existing feature or document.

**Problem/feature that requires documentation:**
Our newer helm chart uses features only available in newer helm (3.6) versions. Could we document recommended versions of helm with the release notes?
  
**Are you the right person to review a draft of the document for technical accuracy? If not, who is?**
@danielhoherd

**Comment by danielhoherd** [comment]
What are the features that are required by helm 3.6? I know tests require helm>=3.6, but I am not aware of anything else.

**Comment by rbankston** [comment]
Had an instance where a customer was using an old 3.2 version of helm that didn't handle timeouts as expected when a helm upgrade failed. Upgrading to helm 3.6 resolved that issue.
