### ISSUE TITLE
Docusaurus Admonitions no longer have color

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#447]
Some of our [Docusaurus Admonitions](https://docusaurus.io/docs/markdown-features/admonitions) broke after the site redesign: 
![image (9)](https://user-images.githubusercontent.com/74574233/156399538-445d2420-3d6e-434e-bf57-56251cd61da2.png)

These styles of note should all be colored in with the versions of colors that align with our theme style

**Comment by allenbrady-astro** [comment]
Fix made and PR open!
<img width="914" alt="image" src="https://user-images.githubusercontent.com/96535736/156413332-4a08f9a1-4639-4325-bd98-4b59ca06466e.png">

**Comment by allenbrady-astro** [comment]
Also just pushed an update for warnings to be the Docusaurs red instead of the same orange as caution (since we don't have a brand red at the moment):
<img width="898" alt="image" src="https://user-images.githubusercontent.com/96535736/156413744-510f55da-b5ba-4c9c-b8cb-d1a11e38ae30.png">
