### ISSUE TITLE
Remove or improve SECURITY.md in astronomer/astronomer

### ISSUE THREAD

**Issue by danielhoherd** [astronomer/docs#458]
**Affected Document:**

https://github.com/astronomer/astronomer/blob/master/SECURITY.md

**Problem Type (Priority):**

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [X] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**

The SECURITY.md file has no useful content in it, and has not been updated in nearly 2 years. We should either remove this file or use it to link to external documentation.

**Comment by paolaperaza** [comment]
@danielhoherd -  Not sure that a cleanup of this repo and/or file belongs in the domain of the docs team, as it's not published on `docs.astronomer.io`. @cmarteepants Any idea on what you wanna do here?

**Comment by cmarteepants** [comment]
Removing this is fine for me, there is almost no content and what is there doesn't seem to be useful. Agree that this isn't a Docs issue though.
