### ISSUE TITLE
AKS Install Guide

### ISSUE THREAD

**Issue by ianstanton** [astronomer/docs#46]
Write installation guide for Astronomer on Azure Kubernetes Service (AKS).

**Comment by ianstanton** [comment]
@vparekh94 could you proofread and close out this issue when you make changes?

**Comment by vparekh94** [comment]
@ianstanton do we need to keep the `preserveIP` param true like we do for google (where we create a static ip first) ? I'm not really sure what that param does, but would it help to explicitly set it one way or the other.

Other than that, LGTM :)

**Comment by vparekh94** [comment]
:shipit:
