### ISSUE TITLE
Add Info on `KubernetesPodOperatorAsync` + v3.0 to KPO Doc

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#467]
### Context
Two recent releases warrant a review and added information to our KPO Doc
- The latest version of the `astronomer-providers` [package](https://github.com/astronomer/astronomer-providers/blob/main/CHANGELOG.rst#100-2022-03-01), which includes `KubernetesPodOperatorAsync`
- The release of [v3.0.0 of the KubernetesPodOperator](https://pypi.org/project/apache-airflow-providers-cncf-kubernetes/3.0.0rc1/)

### Action

Let's expand our KPO doc to:
- Add a section on the AsyncKubernetesPodOperator, with guidance and nuance on technical differences and requirements
- Update/modify information as needed based on 3.0.0 release

From @dstandish - 

> Largely this is a no-change-in-behavior refactor.  But there are a lot of method renames, and changes to a few helper utils in the provider which are only used by KPO (PodLauncher -> PodManager, PodStatus -> PodPhase — these classes are only used by KPO).
> Because a lot of the methods in KPO and PodManager are renamed / removed / replaced, if you have extended KPO in any way you might need to make changes in order to use this provider.
> And there is one behavioral change namely we have changed the default for is_delete_operator_pod from False to True.
> Users can pin the provider to  <3.0 if they need time to make updates to internal subclasses.
> Note that this change could also affect EksPodOperator and GKEStartPodOperator since they are subclasses of KPO.  For EksPodOperator and GKEStartPodOperator, we did not change the delete pods default and did not bump major.  But if users have extended these, then they will be affected by renames too and may require you to pin cncf provider [or make updates] if things are broken.

Related thread here: https://astronomer.slack.com/archives/CGQSYG25V/p1641224431195700

**Comment by paolaperaza** [comment]
Another note from @dstandish on [upcoming changes for KPO](https://astronomer.slack.com/archives/CGQSYG25V/p1654556015660189), expected in a future release of Airflow: 

> Just want to give a heads up for people interested in KPO.
> Recently we [merged a change](https://github.com/apache/airflow/pull/20578) that allows you to configure KubernetesPodOperator using airflow connections.  So, that’s coming soon.
> On a related note, It also deprecates consideration of any “core” k8s config items (by this I mean the [kubernetes] section in airflow.cfg.  In general the core k8s config items are for k8s executor, but the following 5 were historically also considered by KPO: enable_tcp_keepalive, enable_verify_ssl, in_cluster, cluster_context, and config_file.  The deprecation behavior should be that if users left these core settings alone (i.e. default values) then they won’t notice any change.  But if they have them set to non-default, then until they override them with params in KPO or through use of airflow connection, they will get a deprecation warning.
> The change has not been released yet but just want to give a heads up.  If anyone is interested in doing testing and wants help with patching the changes lemme know.

**Comment by dstandish** [comment]
other feedback for that example here https://docs.astronomer.io/astro/kubernetespodoperator#configure-task-level-pod-resources

there are a few parameters that i think you can remove, which should make this example cleaner

`is_delete_operator_pod` now defaults to true, so prob can remove it

`   in_cluster=True` can probably also be removed because now we'll try in cluster if nothing supplied.  but you should confirm on astro.

`get_logs` default is true so this can be removed.

**Comment by dstandish** [comment]
on a related note, inspired by this example, i've created a PR https://github.com/apache/airflow/pull/27116 to make it so that you shouldn't need to provide namespace

**Comment by dstandish** [comment]
on related note, why do we require `name` i wonder? 🤔  maybe we can derive that from task_id

**Comment by dstandish** [comment]
if those two are merged, then ultimately (after those changes released and make it into runtime image) then we can simplify the KPO example to this:

```python
KubernetesPodOperator(
    image="<your-docker-image>",
    cmds=["<commands-for-image>"],
    arguments=["<arguments-for-image>"],
    task_id="<task-name>",
)
```

**Comment by kwcanuck** [comment]
I have done some investigative work on this issue and that is what prompted the previous comments and changes submitted by @dstandish. I also discussed this at length with @phanikumv and @pankajastro and determined that 
KubernetesPodOperatorAsync is just another deferrable operator. Deferrable operators are well documented in the existing topic _[Deferrable operators](https://docs.astronomer.io/astro/deferrable-operators)_.  Individual deferrable operators aren't discussed in the _Deferrable operators_ topic, but a link to _[Available Operators and Sensors](Available Operators and Sensors)_ is provided. The KubernetesPodOperatorAsync operator is included in this list.

@dstandish did a quick review of the existing topics and indicated that he didn't "see anything that needs to change". However, Daniel has made some changes to the operator and I'll add his recommended changes after his PRs are merged.
