### ISSUE TITLE
astrocloud CLI release 1.3.0 fix

### ISSUE THREAD

**Issue by aspain** [astronomer/docs#468]
**Affected Document:**
https://docs.astronomer.io/astro/cli-release-notes/#new-command-to-parse-dags-for-errors
https://docs.astronomer.io/astro/test-and-troubleshoot-locally/#parse-dags
**Problem Type (Priority):**

- [X] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [ ] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**

For this page: https://docs.astronomer.io/astro/cli-release-notes/#new-command-to-parse-dags-for-errors
This line should be updated to `astrocloud dev pytest` rather than `astro dev pytest`:

```
This includes the DAG integrity test that is run with astro dev pytest which checks that your DAGs will run on the Airflow Webserver.
```

For this page: https://docs.astronomer.io/astro/test-and-troubleshoot-locally/#parse-dags
This line has the same issue using `astro dev pytest` instead of `astrocloud dev pytest`

```
Generally speaking, astrocloud dev parse is a more convenient but less customizable version of astro dev pytest.
```

**Additional Notes:**

**Comment by jwitz** [comment]
Looks like this will be resolved in https://github.com/astronomer/docs/pull/471!
