### ISSUE TITLE
Mobile Friendly Breadcrumbs

### ISSUE THREAD

**Issue by astrorfox** [astronomer/docs#469]
Google Search Console is reporting that the new breadcrumbs in Docs are unfriendly for mobile devices with text too small. In general, text sizing seems unbalanced.

![image](https://user-images.githubusercontent.com/68031732/157127071-02acb822-30a7-419c-958a-ba8a0cb1b10a.png)

**Comment by allenbrady-astro** [comment]
PR open to improve those mobile font sizes and breadcrumbs! Local Lighthouse didn't seem to ding them, but probably good to check the deploy preview to make sure the size is big enough now to pass Google's test. 🔍 

https://github.com/astronomer/docs/pull/476
