### ISSUE TITLE
Verify CI/CD template builds

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#479]
**Affected Document:** https://docs.astronomer.io/astro/ci-cd

**Problem Type (Priority):**

- [X] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [ ] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):** Users are running in to errors when using the CI/CD templates out of the box. Specifically, homebrew isn't installed by default, so it's impossible to install the Astro CLI.

We should rewrite these actions and verify them so that users can make the most of the new CLI features

**Additional Notes:**

**Comment by sunkickr** [comment]
This is an issue with the jenkins script

**Comment by aspain** [comment]
@jwitz  Here is the script we were able to get working: 

```
pipeline {
 agent any
   stages {
     stage('Deploy to Astronomer') {
       when {
        expression {
          return env.GIT_BRANCH == "origin/main"
        }
       }
       steps {
         script {
           sh 'curl https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v1.3.0/cloud-cli_1.3.0_Linux_x86_64.tar.gz -o astrocloudcli.tar.gz'
           sh 'tar xzf astrocloudcli.tar.gz'
           sh "./astrocloud deploy ${DEPLOYMENT_ID} -f"
         }
       }
     }
   }
 post {
   always {
     cleanWs()
   }
 }
}
```

One note, I added `DEPLOYMENT_ID` as a Jenkins pipeline variable, along with `ASTRONOMER_KEY_ID` and `ASTRONOMER_KEY_SECRET`, so we may want to update this piece of the docs to reflect that `DEPLOYMENT_ID` needs to be configured as a variable rather than hardcoding it into the Jenkinsfile:

From [this section](https://docs.astronomer.io/astro/ci-cd/#jenkins) my suggested update is:
**BEFORE:**
```
In your Git repository, configure the following environment variables:

ASTRONOMER_KEY_ID: Your Deployment API key ID
ASTRONOMER_KEY_SECRET: Your Deployment API key secret
```

**AFTER:**
```
In your Jenkins pipeline configuration, add the following environment variables:

DEPLOYMENT_ID: Your Astronomer Deployment ID
ASTRONOMER_KEY_ID: Your Deployment API key ID
ASTRONOMER_KEY_SECRET: Your Deployment API key secret
```
