### ISSUE TITLE
Missing import statement in Secrets Manager Doc

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#488]
From @cdabella -

> For the sample code in https://docs.astronomer.io/software/secrets-backend/#step-4-test-key-vault-locally, it looks like we're missing an import of the Variable. Just need to add from airflow.models import Variable to the code as well

This note applies to our Astro doc as well: https://docs.astronomer.io/astro/secrets-backend

**Comment by jwitz** [comment]
This turned out to only be a problem in the Software docs - closed via https://github.com/astronomer/docs/commit/c93c32a8310d9494194c3e575cba3c10ff1e0aca
