### ISSUE TITLE
Broken page content: https://www.astronomer.io/docs/cloud/stable/develop/cli-quickstart

### ISSUE THREAD

**Issue by danielhoherd** [astronomer/docs#490]
**Affected Document:**

https://www.astronomer.io/docs/cloud/stable/develop/cli-quickstart
  
**Additional Notes:**

Found in astro-cli

```
danielh@cloudshell:~/astro-dag-1 (astronomer-cloud-prod)$ astro deploy
A new minor version of Astro CLI is available. Your version is 0.20.0 and 0.25.8 is the latest.
See https://www.astronomer.io/docs/cli-quickstart for more information.
Project directory has uncommmited changes, use `astro deploy [releaseName] -f` to force deploy.
```

**Comment by jwitz** [comment]
Huh, weird. Hoping this is resolved by our Enterprise migration. Closing out for now, and if it persists we can deal with it on github.com/astronomer/cloud-docs
