### ISSUE TITLE
New Doc on Enabling Data Lineage for your Organization

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#500]
Standalone doc that covers -

- How do ENABLE Data Lineage for your Organization
- Once this is done, you go to the "Integrate Data Lineage with Astro Doc" which is at the Deployment level

This doc maybe goes under Administration if it requires higher permissions, or may go under our Observability tab.

**Comment by paolaperaza** [comment]
Closing out, this doc is live: https://docs.astronomer.io/astro/set-up-data-lineage
