### ISSUE TITLE
Oauth code bring your own idp provider documentation

### ISSUE THREAD

**Issue by aliotta** [astronomer/docs#512]
We have added some new environment variables customers can use to configure their auth0, okta, and bring their own idp's. We should document these changes.

here's a full list of env vars related to these sign on methods. Some of these are likely documented already others are certainly not.

`AUTH__OPENID_CONNECT__OKTA__ENABLED="true"
AUTH__OPENID_CONNECT__OKTA__CLIENT_ID="0oa257gdf96DADd0W5d7"
AUTH__OPENID_CONNECT__OKTA__CLIENT_SECRET="VwEC5FdTM4Z7t3WeRNP1IjRnHb-VyenIyNGrqYAx"
AUTH__OPENID_CONNECT__OKTA__DISCOVERY_URL="https://dev-46981039.okta.com/.well-known/openid-configuration"
AUTH__OPENID_CONNECT__OKTA__AUTH_URL_PARAMS__AUDIENCE="0oa257gdf96DADd0W5d7"
AUTH__OPENID_CONNECT__FLOW="code"
AUTH__OPENID_CONNECT__OKTA__BASE_DOMAIN="dev-46981039.okta.com"
AUTH__OPENID_CONNECT__AUTH0__ENABLED="true"
AUTH__OPENID_CONNECT__AUTH0__CLIENT_ID="LC3NCoZuKbbCsft37jShf3zeQAcTQVlB"
AUTH__OPENID_CONNECT__AUTH0__CLIENT_SECRET="PTYrXNHWMg7xKkZEtqace9VRTAKouGvZtw0b834O2h1sdOLiZ8FKJgiDqz8HqamQ"
AUTH__OPENID_CONNECT__AUTH0__DISCOVERY_URL="https://nonprod-astronomerio.us.auth0.com"
AUTH__OPENID_CONNECT__AUTH0__AUTH_URL_PARAMS__AUDIENCE="https://nonprod-astronomerio.us.auth0.com/api/v2/"
AUTH__OPENID_CONNECT__AUTH0__BASE_DOMAIN="nonprod-astronomerio.us.auth0.com"
AUTH__OPENID_CONNECT__GOOGLE__ENABLED="true"
AUTH__OPENID_CONNECT__CUSTOM__ENABLED="true"
AUTH__OPENID_CONNECT__CUSTOM__CLIENT_ID="LC3NCoZuKbbCsft37jShf3zeQAcTQVlB"
AUTH__OPENID_CONNECT__CUSTOM__CLIENT_SECRET="PTYrXNHWMg7xKkZEtqace9VRTAKouGvZtw0b834O2h1sdOLiZ8FKJgiDqz8HqamQ"
AUTH__OPENID_CONNECT__CUSTOM__DISCOVERY_URL="https://nonprod-astronomerio.us.auth0.com"
AUTH__OPENID_CONNECT__CUSTOM__AUTH_URL_PARAMS__AUDIENCE="https://nonprod-astronomerio.us.auth0.com/api/v2/"
AUTH__OPENID_CONNECT__CUSTOM__BASE_DOMAIN="nonprod-astronomerio.us.auth0.com"
AUTH__OPENID_CONNECT__CUSTOM__DISPLAY_NAME="Custom Oauth"`

**Comment by jwitz** [comment]
Cleaning out this repo, closing this out as it's been documented in our 0.27 PR: https://github.com/astronomer/cloud-docs/pull/197/files/2796600e6a531f1677955ecc2f55a55c532de661#diff-e131965765c89a1eb5559ebd4b3d26eaf4f78001ca649c308dd13e7e3b577f58
