### ISSUE TITLE
Fix the HyperLink to the correct section of System Permissions

### ISSUE THREAD

**Issue by manmeetkaur** [astronomer/docs#512]
**Affected Document:** https://docs.astronomer.io/software/manage-platform-users#reference-platform-permissions

**Problem Type (Priority):** 

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [ ] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [X] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):** Fix the link to https://docs.astronomer.io/software/manage-platform-users#reference-system-permissions

**Additional Notes:**
<img width="992" alt="Screenshot 2022-03-17 at 12 24 51 PM" src="https://user-images.githubusercontent.com/75730393/158753872-14d6fe59-ce3a-4c8f-8fe7-f369de71ef39.png">

**Comment by jwitz** [comment]
Fixed via https://github.com/astronomer/docs/commit/0d755b1edb6837e93c2b6d3fc23ac27e281d7923 and https://github.com/astronomer/docs/commit/881ae5f9271bc42fec31fa7b1bedd2f5557798ec. Thanks for catching this @manmeetkaur !
