### ISSUE TITLE
0.26.4 patch upgrade notes

### ISSUE THREAD

**Issue by aliotta** [astronomer/docs#515]
Version 0.26 of the platform has some potentially breaking changes that we need to inform our users about. Specifically they may see an error message of the following form when they attempt to upgrade. 

`
Error: INSTALLATION FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
astronomer:
- astronomer.houston.config.deployments.helm: Additional property redis is not allowed
- astronomer.houston.config.deployments.helm: Additional property podMutation is not allowed
- astronomer.houston.config.deployments.helm: Additional property defaultAirflowRepository is not allowed
- astronomer.houston.config.deployments.helm: Additional property images is not allowed
- astronomer.houston.config.deployments.helm: Additional property pgbouncer is not allowed
- astronomer.houston.config.deployments.helm: Additional property scheduler is not allowed
- astronomer.houston.config.deployments.helm: Additional property webserver is not allowed
- astronomer.houston.config.deployments.helm: Additional property affinity is not allowed
- astronomer.houston.config.deployments.helm: Additional property data is not allowed
- astronomer.houston.config.deployments.helm.workers: Additional property keda is not allowed
- astronomer.houston.config.deployments.helm.workers: Additional property resources is not allowed
`

To resolve the above issues the values above will need to be migrated to their new expected location under the "astronomer.houston.config.deployments.helm.airflow" param.

**Comment by jwitz** [comment]
Closing out because these issues are addressed in https://github.com/astronomer/docs/pull/491
