### ISSUE TITLE
Request: Supported version table

### ISSUE THREAD

**Issue by danielhoherd** [astronomer/docs#516]
## Request type

- [x] **New document:**: Add the `newcontent` label to this issue.
- [ ] **Significant change to an existing document**: Add the `enhancement` label to this issue.

## What is the purpose of the document/enhancement? Select all that apply

- [ ] Document a new feature for an upcoming release. Add the appropriate release version label to this issue.
- [ ] Information for an existing feature that isn't yet documented.
- [x] Additional considerations/ reference material for an existing feature or document.

## Problem/feature that requires documentation

I would like to see a table showing our versions and the duration of their availability and support. This is a reference for the kind of thing I'd like to see: https://en.wikipedia.org/wiki/Ubuntu_version_history#Version_timeline

## Are you the right person to review a draft of the document for technical accuracy? If not, who is?

Yes. But the data team is likely a better source for info on how to implement this.

## See also

- <https://towardsdatascience.com/gantt-charts-with-pythons-matplotlib-395b7af72d72>

**Comment by jwitz** [comment]
This should be resolved once we publish this PR! https://github.com/astronomer/docs/pull/492/files/fafa3d1ce4cdda4da8eeb2efab97e3be5d8ec6a0..7baf6185caf930577e5280e29c38d4511fe2d325
