### ISSUE TITLE
Astronomer Enterprise - Platform Alerts Page - Link Errors

### ISSUE THREAD

**Issue by aspain** [astronomer/docs#518]
**Affected Document:**
[Enterprise Platform Alerts](https://www.astronomer.io/docs/enterprise/v0.25/monitor/platform-alerts) page  

Severity:
- [X] Error/Broken Link
  
**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**
In the [Subscribe to Alerts](https://www.astronomer.io/docs/enterprise/v0.25/monitor/platform-alerts#subscribe-to-alerts) section of this doc, there are two references to the 'Alertmanager ConfigMap' YAML file in git. Clicking either of these URLs just appends the git url to the current page's URL in the search bar, but does not redirect to the git page. 

**Additional Notes:**
Example after clicking one of the two URLs:
![image](https://user-images.githubusercontent.com/15913202/142440138-4998c67e-eaf2-483d-9172-dfe9d57e6192.png)

**Comment by jwitz** [comment]
Closing this out here as this should be resolved in our Enterprise migration! https://github.com/astronomer/cloud-docs/pull/156
