### ISSUE TITLE
0.26 Release Notes Docs link to the 0.25 `Configure a Deployment` docs.

### ISSUE THREAD

**Issue by ReadytoRocc** [astronomer/docs#523]
## Affected Document
https://www.astronomer.io/docs/enterprise/v0.26/resources/release-notes

## Severity

- [ ] Critical: This document has incorrect or missing information. Add the `error/critical` label to this issue.
- [ ] FYI: The document is misleading or could benefit from additional context or guidance. Add the `error/FYI` label to this issue.
- [x] Typo: Add the `error/typo` label to this issue.

## Suggested Change (include links to relevant existing docs, support tickets, messages, or external content)
Update the ` Configure a Deployment` link under `Deferrable Operators` from https://www.astronomer.io/docs/enterprise/v0.25/deploy/configure-deployment to https://www.astronomer.io/docs/enterprise/v0.26/deploy/configure-deployment

**Comment by jwitz** [comment]
Closing this out, as all version-related issues should be fixed this Thursday by our migration: https://github.com/astronomer/cloud-docs/pull/197
