### ISSUE TITLE
Clicking the '4' to go to page 4 of providers page is empty

### ISSUE THREAD

**Issue by aspain** [astronomer/docs#526]
## Affected Document
https://registry.astronomer.io/providers/?page=1
## Severity

- [X ] Critical: This document has incorrect or missing information. Add the `error/critical` label to this issue.

## Suggested Change (include links to relevant existing docs, support tickets, messages, or external content)
When on the providers page of the registry, clicking the '4' in the bottom-right leads to a blank page

## Additional Notes
![image](https://user-images.githubusercontent.com/15913202/144641764-2607348b-a440-4b3e-ac0b-5210f29bf992.png)

![image](https://user-images.githubusercontent.com/15913202/144641714-d002797f-5239-4c73-87c9-0e1c8f487852.png)

**Comment by jwitz** [comment]
cc @petedejoy @samblackk @pgzmnk not sure what our repo for Registry issues is!

**Comment by jwitz** [comment]
Issue moved to [astronomer/registry #334](https://github.com/astronomer/registry/issues/334) via [**ZenHub**](https://www.zenhub.com/)
