### ISSUE TITLE
no `helm install` command in guide

### ISSUE THREAD

**Issue by ryw** [astronomer/docs#53]
Looks like the actual install command is missing here https://www.astronomer.io/docs/ee-installation-gke and stuff beyond that that is in https://www.astronomer.io/docs/ee-installation-eks/

**Comment by ianstanton** [comment]
There was apparently a problem rendering the Markdown due to comments. Viraj has removed the comments. The EKS guide looks good, but I believe the website needs to be rebuilt once more for the GKE changes to show up. CC @vparekh94 to confirm.

**Comment by ianstanton** [comment]
@ryw Website rebuilt and looks as intended now :+1:
