### ISSUE TITLE
Open External Links in New Tab

### ISSUE THREAD

**Issue by astrorfox** [astronomer/docs#552]
In order to avoid accidental site exits, we should ensure all external links from our docs open in new tabs. One of the Docusaurus maintainers recommended [this plugin](https://github.com/vitaliy-bobrov/remarkable-extlink), but we could explore other options.

**Comment by paolaperaza** [comment]
Good add here @astrorfox - agree! @allenbrady-astro Let us know if you need anything from @jwitz or myself on this.

**Comment by jwitz** [comment]
Is there a place where you're noticing that this is happening @astrorfox ? I've tried a few different external links across the site, and they all seem to open up in external windows.

**Comment by astrorfox** [comment]
Maybe I'm imagining things, but I can't seem to replicate anymore... @allenbrady-astro did you already look at this?

**Comment by allenbrady-astro** [comment]
Hey ya'll! I started looking at this last week but haven't had time to push anything up yet haha 😅 So looks like we're good to go with external links?

**Comment by astrorfox** [comment]
Yeah, I guess we're good. Sorry for the confusion!
