### ISSUE TITLE
Cloud Quickstart + FAQ doc

### ISSUE THREAD

**Issue by vparekh94** [astronomer/docs#57]
I held off on including a cloud quickstart section in the new docs menu since I'm not sure how you want to present that information. 

The quickstart guide should be a standalone guide to getting an account set up, downloading the CLI, authenticating, and deploying a DAG. It should link out to other docs for more detailed information on any piece.

FAQs should be a bunch of questions that are asked during sales conversations/frequent forum posts

Would love if you could knock this out ASAP so I can push up my enterprise quickstart!

I followed the DO structure for as much as I could. 
https://www.digitalocean.com/docs/droplets/quickstart/

**Comment by petedejoy** [comment]
Docs menu has been restructured to accommodate this- just need to make a few small tweaks to the quickstart guide. Waiting on FAQ doc from @paolaperaza then we can close this out.

**Comment by paolaperaza** [comment]
MVP is out and up on Preview: https://preview.astronomer.io/docs/cloud-faq/

I'm gonna go ahead and close this issue out, but @petedejoy feel free to add as you see fit.
