### ISSUE TITLE
Add New "Tutorials" Tab

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#589]
In order to launch Tutorials, we need to:

- Create a new directory in this repo for `tutorials`
- Add a new tab to the right of `Software` on docs.astronomer.io
- This tab should have its own sidebar menu

![image](https://user-images.githubusercontent.com/31111752/163010198-f9a3a669-745f-47df-944e-72966a832463.png)

**Comment by jwitz** [comment]
Closing this out- we have successfully launched the "Learn" tab!
