### ISSUE TITLE
Clean up Windows 10 CLI Install Doc

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#59]
A few things have come up here that we should add:

- [x] Fix typo in second paragraph - `,but this giude should work for other distrubutions as well`
- [x] Add a line about support for Windows 7 (we do)
- [x] Make pre-requisites clearer/more nicely formatted
- [x] Add a section on how to install without WSL (pending @andriisoldatenko's instructions)
- [x] We've seen 2 customers have issues related to the directory they initialize this with. We should add the following line:

> It's worth noting that whenever you run a docker-compose up, you'll want to make sure you navigate to the /c/Users/nick/dev/myapp location first, otherwise your volume won't work. In other words, never access /mnt/c directly.

- [x] Clean up formatting across the board
- [ ] Consider linking in the nav (right now it's only linked at the bottom of the general CLI install guide)
- [x] Update [forum issue](https://forum.astronomer.io/t/can-i-run-astros-cli-on-windows-but-without-the-subsystem-for-linux-wsl/172) accordingly

**Comment by paolaperaza** [comment]
@benjamingregory I just pushed up an MVP to reflect the checklist above! Can you give it a lookover and make final changes if needed or close out if it looks good?

**Comment by benjamingregory** [comment]
Made a few minor changes. Looks good!
