### ISSUE TITLE
Expand "Test and Troubleshoot Locally" Doc with more Common Issues/Errors

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#594]
**Request type:**

- [X] **New document:**: Add the `docs-content` label to this issue.

**What is the purpose of the document/enhancement? Select all that apply:**

We should have a "troubleshooting" doc that addresses specific error messages that someone might get when using the Astro CLI or the Astro UI. I want readers to be able to search for the error message and immediately be brought to a doc that addresses the error. 

For example, we might include info from https://github.com/astronomer/docs/pull/582 in this section, as well as any Docker-based errors that we've addressed on our forum over time.

**Comment by jwitz** [comment]
Okay turns out we already have a PR for this lol, but a lot of this content should probably be reworked and potentially in a separate doc: https://github.com/astronomer/docs/pull/350/files

**Comment by paolaperaza** [comment]
Slack thread on a Docker issue that @pohek321 ran into with some versions of Astro Runtime. He had to allocate more disk space to Docker and clean up existing volumes -

https://astronomer.slack.com/archives/C02MS2WHQ5N/p1652804008738649
