### ISSUE TITLE
Add a "Download to PDF" button to our Docs

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#599]
There is currently no easy way for a user to download an individual or multiple pages of our documentation as a PDF. This might be helpful:

- If you need to reference our documentation without requiring an internet connection
- If you need to share or save documentation internally or externally

We should add a "Download to PDF" button to all pages of our docs that:
- Downloads a PDF straight from the browser
- Works on any browser
- Fits a nice branded template
- Has a banner that reads "This doc was downloaded on X date and may be outdated. > URL"

**Comment by kwcanuck** [comment]
@jwitz it appears there are plug-ins available for adding this functionality. For example, [docusaurus-plugin-papersaurus](https://www.npmjs.com/package/docusaurus-plugin-papersaurus?activeTab=readme). Many of the solutions seem to require that you link to existing PDF versions of the topics. Are users still interested in PDF documentation? Most of my previous employers dropped this option.

**Comment by kwcanuck** [comment]
@jwitz when time permits, could you review my comment? If this is something we can implement, let me know. If not, maybe it's time to close the issue?

**Comment by jwitz** [comment]
@kwcanuck I just tried the plugin you shared locally. It's easy to configure, but the "Download" button appears as a massive chunk of text in the overview. If we're going to do this, we'd need to customize the .pdf plugin further to make a more subtle download button/ location. 

We can talk about this at check in, but I don't think this project can move forward without the web team. And if we end up not having time to work on this in at least the next month, then I think it's safe to close the issue.

**Comment by jwitz** [comment]
Closing because this issue is stale/ unlikely to be completed any time soon.
