### ISSUE TITLE
CICD for TeamCity

### ISSUE THREAD

**Issue by stuart23** [astronomer/docs#607]
**Request type:**

- [ ] **New document:**: Add the `docs-content` label to this issue.
- [x] **Addition to an existing document**: Add the `enhancement` label to this issue.

**What is the purpose of the document/enhancement? Select all that apply:**

- [ ] Document a new feature for an upcoming release. Add the appropriate release version label to this issue.
- [ ] Information for an existing feature that isn't yet documented.
- [x] Additional considerations/ reference material for an existing document.

**Problem/feature that requires documentation:**

Write instructions for TeamCity CICD

https://astronomer.zendesk.com/agent/tickets/9089

**Are you the right person to review a draft of the document for technical accuracy? If not, who is?**

Yes

**Comment by kwcanuck** [comment]
Discussed with @stuart23 and @erdos2n 2022-06-09 and 2022-06-13:

- The new content should appear in the existing topic [Automate Code Deploys with CI/CD](https://docs.astronomer.io/astro/ci-cd) below a new TeamCity heading.

- Rafael Carrasco will provide the procedure steps for the task. He'll review 2022-06-14 after returning from PTO.

-  it isn't "super high priority

**Comment by kwcanuck** [comment]
Meeting scheduled with @erdos2n 2022-08-02 to discuss this issue and determine a way forward.

**Comment by kwcanuck** [comment]
Discussed with @erdos2n and @stuart23 and it was determined that TeamCity has "limited use and is challenging to set up". Closing this issue for now. It can be revisited if and when there is a need.
