### ISSUE TITLE
Update existing documentation that mentions .env files

### ISSUE THREAD

**Issue by sunkickr** [astronomer/docs#608]
Astro CLI v1.4.0 was recently released and includes a variety of features around environment variables. While we've published release notes and CLI reference documentation, we still need to:

- Update the [Develop Project doc ](https://docs.astronomer.io/astro/develop-project/#set-environment-variables-via-env-local-development-only) around setting env vars locally and using `astrocloud deployment list --save` to pull Env Vars from Astro Deployments to a local file
- Update the general Env Vars doc with a "tip" that you can also use the Astro CLI to create them
- Any other recommendation on how to use .env files now that these commands exist

**Comment by kwcanuck** [comment]
Recommendations from @sunkickr 2022-06-09:

- I think the first step to improving this doc with the new commands is adding a tip or a new step after the first step of "Set Environment Variables via .env" Saying something like if you have environment variables saved in a Astronomer deployment you can copy them to a local env file with astro deployment variable list --save This command saves your deployment variables to a local env file of your choosing.

- We also need to add section at the end of the env var section explaining that you can send env variables from a .env file to a cloud deployment with astro deployment variable create/update --load. This command can send a group of variables from a specific env file to a specific deployment.
