### ISSUE TITLE
Replace BASEDOMAIN with `gcp0001.us-east4.astronomer.io` in all Nebula Docs

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#611]
On Astronomer Nebula, the base domain is always the same: `gcp0001.us-east4.astronomer.io`. Let's replace all mentions of `BASEDOMAIN` with this value.

Instances include:
- Airflow API Doc: https://nebula.astronomer.io/airflow-api/#step-2-make-an-airflow-api-request
- Configure a Deployment Doc: https://nebula.astronomer.io/configure-deployment#create-a-deployment
- Deploy CLI/Auth step: https://nebula.astronomer.io/deploy-cli#step-1-authenticate-to-astronomer

Reported by @collinmcnulty

**Comment by paolaperaza** [comment]
Hey @kwcanuck I’m using ZenHub in GitHub, [click this link](https://app.zenhub.com/workspaces/documentation-5fcfce583ed44e0011db3db5/board) to join my workspace and see other features available in GitHub or [download the ZenHub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [ZenHub](https://www.zenhub.com)_

**Comment by kwcanuck** [comment]
@paolaperaza can you confirm that I should replace instances of `<your-base-domain>` and `app.BASEDOMAIN` with _gcp0001.us-east4.astronomer.io_?  The only doc containing a  standalone instance of BASEDOMAIN was deploy-cli.md.

**Comment by kwcanuck** [comment]
@paolaperaza for your reference, here are the results of a global search for BASEDOMAIN
[BASEDOMAIN Search Results.txt](https://github.com/astronomer/docs/files/8619925/BASEDOMAIN.Search.Results.txt)
:

**Comment by kwcanuck** [comment]
Resolved by https://github.com/astronomer/nebula-docs/pull/5
