### ISSUE TITLE
Google shows Software Docs first > Investigate SEO

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#618]
### Problem

When you search Astronomer documentation on Google, the Astronomer Software version of our docs is persistently shown at the top, and the Astro docs are less prominent.

![image](https://user-images.githubusercontent.com/31111752/164772897-0fb9b4b1-39c7-4fd3-9b90-e68610d99715.png)

### Next Step
Let's work with marketing team to look into this.
- Is this because of the longer history those docs have on Software?
- Is there anything we can do with titles or meta descriptions to boost our SEO?

**Comment by astrorfox** [comment]
Before removing /software from Google's index altogether, three recommendations I suggest we take up:
1. Enable [trailingSlash on the site](https://docusaurus.io/docs/api/docusaurus-config#trailing-slash). We're doing this through Netlify optimization anyhow, but will make the Sitemap match reality, which should improve SEO for new pages.
2. Set the [Priority](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-sitemap#priority) for Astro pages to `0.7` and Software pages to `0.3` to indicate to search engines the relative priority between them.
3. Set the [changefreq](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-sitemap#changefreq) to a more realistic value of `daily`.

**Comment by astrorfox** [comment]
Whoops @jwitz!...we (after a fair concern from @paolaperaza) decided to keep trailingSlash to false and optimize for consistency without the trailing slash. Can we set this back to `false`?

I'm also seeing all pages as 0.3 now instead of Astro at 0.7 for priority in the sitemap and still seeing the versioned Software pages.

**Comment by jwitz** [comment]
Yeah I was trying to troubleshoot this without deploying, but it's hard to see how the site actually generates a sitemap without deploying first. It seems like there's some bugs with the Docusaurus site plugin with regards to running multiple docs instances. I've tried a few different configurations and it doesn't seem to recognize the difference between docset ids when generating those priorities. I'll see if this is a proper bug by opening an issue in Docusaurus. 

As for the versioned docs in the sitemap, the Sitemap plugin does support an [ignorePatterns](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-sitemap#ignorePatterns), but I similarly had trouble getting this to run with our multi-instance setup. I have some proof that Docusuarus does automatically unindex versioned docs ( for example, https://docs.astronomer.io/software/0.25/upgrade-to-0-25 does not appear in search results). I'll have to configure this more at a later date.

Just rolled back the `trailingslash` change, so the only change now live in production should be to `changefreq`. I'll try to work on the rest in a separate PR not tied in with an upgrade.

**Comment by astrorfox** [comment]
Google not indexing the versioned docs is due to the temporary suppression that I submitted in Google Search Console. We'll need to fix root cause to maintain that.

You should be able to take the base path and add /sitemap.xml on a preview deployment to get it to show (like: https://deploy-preview-684--gallant-neumann-56599d.netlify.app/sitemap.xml)

**Comment by jwitz** [comment]
Good news, this change should be doable soon. One of the Docusaurus maintainers responded to my proposal saying it was possible/ planned: https://docusaurus.io/feature-requests/p/support-multi-instance-sitemaps-plugins

**Comment by astrorfox** [comment]
As a practice, you shouldn't include something in the sitemap that you are blocking in robots.txt
