### ISSUE TITLE
KPO limitations discussion for customers coming from Kubernetes Executor

### ISSUE THREAD

**Issue by collinmcnulty** [astronomer/docs#620]
**Request type:**

- [x] **New document:**: Add the `docs-content` label to this issue.
- [ ] **Addition to an existing document**: Add the `enhancement` label to this issue.

**What is the purpose of the document/enhancement? Select all that apply:**

- [ ] Document a new feature for an upcoming release. Add the appropriate release version label to this issue.
- [ ] Information for an existing feature that isn't yet documented.
- [ ] Additional considerations/ reference material for an existing document.

**Problem/feature that requires documentation:**
Right now, customers who previously used Kubernetes Executor are told that they can do resource sizing on KPO. While strictly true, this undersells some of the difficulties involved in working with KPO. We should document them clearly. Discussions are being held to talk about what that could look like, and I wanted to open an Issue to have a place to record those thoughts for eventual inclusion in docs.

**Are you the right person to review a draft of the document for technical accuracy? If not, who is?**
Yes, after discussion. This is something of a placeholder for now.

**Comment by kwcanuck** [comment]
Numerous attempts to get the information necessary to resolve this issue wee unsuccessful. If @collinmcnulty can provide the necessary information, this issue can be reopened.
