### ISSUE TITLE
Triggerer/Configure Deployment doc doesn't show up in search

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#625]
Reported by @aspain - The [Triggerer](https://docs.astronomer.io/software/configure-deployment#triggerer) section of the Configure a Deploymentpage doesn't appear to be indexed in the search - when I search for "Triggerer" a few other less relevant pages are shown

Originally from #613. @jwitz Can you take a look at this when you get back?

**Comment by aspain** [comment]
Looks like it is now appearing in search properly:
<img width="768" alt="image" src="https://user-images.githubusercontent.com/15913202/165090017-1dc64d42-0ad2-41a1-a368-9c2c7792fe5d.png">

**Comment by jwitz** [comment]
Looks like this issue was fixed - closing it out! Will address any outstanding search issues in a separate GH issue (if they still exist)
