### ISSUE TITLE
Remove unnecessary Overview headings

### ISSUE THREAD

**Issue by kwcanuck** [astronomer/docs#628]
Currently, Astronomer documentation includes an _Overview_ heading that immediately follows the primary heading.  The secondary _Overview_ heading is unnecessary and redundant. 

The Microsoft Style Guide provides this guidance:

_Avoid having two headings in a row without text in between—that might indicate a problem with organization or that the headings are redundant. But don't insert filler text just to separate the headings._

Readers are accustomed to having introductory (or overview) conceptual information follow a primary heading. This is the accepted convention. For this reason, there is no need to call out this information with a separate _Overview_ heading. It's redundant.

**Comment by jwitz** [comment]
Hi @kwcanuck, is this your first issue in the Astronomer docs repo? If so, congrats!

Just to add some context here for why I maintain the Overview sections: in Docusaurus, each doc has a right-hand sidebar that consists of all doc headers _except_ for the title header.

![Screen Shot 2022-05-02 at 9 12 17 AM](https://user-images.githubusercontent.com/74574233/166258756-89d4ecb4-4434-4b57-8212-5300e3c500f8.png)

If you're halfway down a doc, the easiest way to jump back to the top of a page is by clicking the "Overview" link in this sidebar. Agreed that it's a bit redundant content-wise, but I'd like to look more into how to maintain that anchor functionality before fully removing these.

**Comment by kwcanuck** [comment]
@jwitz got it.  

Do users need to get to the _Overview_ section quickly?  If users can get to the second heading (in your example _Create an API Key_), isn't that sufficient - it's just a small amount of scrolling to reach the top of the page. The intent of an overview is to _briefly_ describe the purpose of the content to the reader. I don't think this is significant enough to warrant a navigation link. There are other methods available to return to the top of a page. In my opinion, having an _Overview_ link in the sidebar is unnecessary.  If you feel strongly about allowing users to quickly reach the top of a page, a **Top** or similar control might work better. Just my two cents.

**Comment by kwcanuck** [comment]
From @jwitz 2022-06-06:

- CLI: reference can remove all “Description” headers in reference without adjustments
- Need a little intro in Configure the CLI
- “Data Lineage on Astro” doc needs a breakout of the overview section, not sure how we’d do that yet
- Deferrable Operators guide needs a new “why” section, or something to capture that bulk of info
- KPO doc on both Astro / Software could use a “Why KPO” section
- Does “Resilience” need any headers? I don’t think so
- Runtime version policy could use some of that info in a separate section, specifically the second paragraph
- Secrets backend needs a “Why secrets backend” section
- Set up Lineage doc needs a “Lineage architecture” section
- Upgrade Runtime needs a “Considerations” section
- Custom Image Registry needs some kind of titled section to capture the info in the Overview, not sure how we’d go about that yet
- Deploy via NFS needs a Considerations section
- IDP Group doc needs a Considerations section
- Integrate IAM needs a considerations section
- Secrets backend doc needs a “Why” Section
