### ISSUE TITLE
Node size recommendation in ee-install guides

### ISSUE THREAD

**Issue by ianstanton** [astronomer/docs#63]
* Each ee-install guide should include a note on recommended node size in Step 3 (creating cluster)
* This should include a link to the [Configuring Resources](https://www.astronomer.io/docs/ee-configuring-resources/) doc to justify the recommended node size

**Comment by vparekh94** [comment]
Also going to include guidance on the database size with this commit.

**Comment by vparekh94** [comment]
^ Closed
