### ISSUE TITLE
Platform Variables "values" are value-less to users / readers

### ISSUE THREAD

**Issue by jaketf** [astronomer/docs#63]
In the platform variables docs we list a value column for each of the env vars that we don't want users to set. 
however, these values are just copy / pasted from random lines of code and are often just variables names or go code.
it also puts us in a weird situation for values we don't want to share with customers, or are not human readable.

For example: `strconv.FormatInt(int64(statsd.IngestPort), baseTen)` is confusing as heck to users / readers as it's leaking implementation details from the operator that the reader / user should never have to think about. It also is misleading because at the end of the day the value we actually set is `9125`.

IMHO we should remove the value column entirely to avoid confusion.

https://github.com/astronomer/beta-docs/blob/main/docs/platform-variables.md

**Comment by jwitz** [comment]
@kwcanuck This is a really quick fix, so I went ahead and hotfixed it here: https://github.com/astronomer/docs/commit/b6670f329b11026fbc2787e4f4f06da94c79362d

I think this was fully fixed at one point, but then we added some more variables without applying this same standard.
