### ISSUE TITLE
Add CLI version Env Var to Software Doc for CLI Install on Windows

### ISSUE THREAD

**Issue by aspain** [astronomer/docs#640]
**Affected Document:**
https://docs.astronomer.io/software/cli-install-windows-10#step-6-final-command
**Problem Type (Priority):**

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [X] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**
Is there a macro we can put in place for the `Astronomer CLI Version: x.x.x` terminal output example so that it stays up-to-date with the current CLI version?

**Additional Notes:**
Recently a customer using the windows CLI was attempting to install version `0.8.2` of the CLI and it may be from the example in step 6 on the linked doc above

**Comment by kwcanuck** [comment]
Discussed at length with @cmarteepants and there are numerous inconsistencies and contradictions in our existing documentation. I will meet with Constance 2022-05-25 and we will run through the entire Windows install to make sure it is documented accurately.

**Comment by paolaperaza** [comment]
@jwitz Let's add the Astro CLI Env Var here to keep the version up to date on install, and split up this doc from the work @kwcanuck is doing on Windows CLI install process.
