### ISSUE TITLE
Guidelines on KPO in Astro

### ISSUE THREAD

**Issue by collinmcnulty** [astronomer/docs#645]
**Request type:**

- [X] **New document:**: Add the `docs-content` label to this issue.
- [ ] **Addition to an existing document**: Add the `enhancement` label to this issue.

**What is the purpose of the document/enhancement? Select all that apply:**

- [ ] Document a new feature for an upcoming release. Add the appropriate release version label to this issue.
- [X] Information for an existing feature that isn't yet documented.
- [ ] Additional considerations/ reference material for an existing document.

**Problem/feature that requires documentation:**
Astro's architecture is such that you cannot use cross-account service accounts nor persistent volumes for your KPO. We should document these and any other behaviors that we do not want our customers to attempt.

**Are you the right person to review a draft of the document for technical accuracy? If not, who is?**
I don't know.

**Comment by paolaperaza** [comment]
Related: We should document how to use IAM roles associated with a K8s Service Account (associated with the namespace or the pod) if that's something we officially support.

Slack: https://astronomer.slack.com/archives/C01UA03TPV1/p1654709916009399

**Comment by kwcanuck** [comment]
@collinmcnulty adding a new **Limitations** section in the existing topic _[Run the KubernetesPodOperator on Astro](https://docs.astronomer.io/astro/kubernetespodoperator)_ would probably resolve your concern. What are your thoughts? Would  this work? If so, I can add the two items you mentioned (cannot use cross-account service accounts or persistent volumes) to this section.
