### ISSUE TITLE
KubePodOperator Doc

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#66]
We need to have a doc that guides users on how to use the KubernetesPodOperator on Astronomer.

The only existing content around it is in [this forum post](https://forum.astronomer.io/t/how-should-i-use-the-kubernetespodoperator/79).

Tid-bits we might include:

- KubernetesPodOperator vs DockerOperator - we actually prevent users from using the DockerOperator on our cloud platform, so the KubebernetesPodOperator is 100% the way to go
- Make sure you're running Airflow 1.10.1
- Extra Capacity slider. Warning on "permission denied" error
- Clarification that you do not need your own k8s backend on Cloud
- There's a resource cap on a k8s pod - Right now the largest node a single pod can occupy is 13.01GB and 3.92 CPU — but we'll be introducing larger options in our next version.

**Comment by vparekh94** [comment]
@paolaperaza what's the timeline for this looking like?

**Comment by paolaperaza** [comment]
@vparekh94 Just pushed up a PR with my MVP. Lemme know what you think and we can get a v1 out there asap.

**Comment by vparekh94** [comment]
@paolaperaza I think this should be more of a "here's how you use..." than "If you're using, here are a few notes" type doc. I was thinking more of a numbered list of sort that imitates the user-flow when doing this, something like:


```
1. Verify version of Airflow

2. ....

```

I've been using the  DO "How-Tos" as an examples for the CLI and other docs

**Comment by paolaperaza** [comment]
Merged in sidenav! Closing this one out.
