### ISSUE TITLE
Update AC Versions list in Nebula Docs

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#665]
File: https://github.com/astronomer/nebula-docs/blob/main/docs/manage-airflow-versions.md

**ADD:**
- 2.2.4
- 2.2.5
- 2.3.0

**REMOVE:**
- 1.10.10
- 1.10.12
- 1.10.14
- Alpine image table column entirely

Source: https://quay.io/repository/astronomer/ap-airflow?tab=tags

**Comment by kwcanuck** [comment]
PR: https://github.com/astronomer/nebula-docs/pull/6

**Comment by paolaperaza** [comment]
Addressed by https://github.com/astronomer/nebula-docs/pull/6!
