### ISSUE TITLE
Curate search results for `.env`

### ISSUE THREAD

**Issue by aspain** [astronomer/docs#688]
**Affected Document:**
https://docs.astronomer.io/astro/develop-project#set-environment-variables-via-env-local-development-only

**Problem Type (Priority):**

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [X] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**

I noticed when using the search function for ".env", the page linked above does not appear in the search results unless you click the "See all 259 results" and then scroll about halfway down
![image](https://user-images.githubusercontent.com/15913202/168667426-d1e3647d-6cee-4049-bf22-6b0dc6daf18e.png)

Is it possible to increase search priority for certain pages or add this to the results that appear in the main search function? I would argue the link above is the most important page we have on the `.env` file but it is difficult to find as it's buried fairly far down in the [Develop a Project](https://docs.astronomer.io/astro/develop-project) section

This may be a bit of a stretch of an ask but wanted to check

**Additional Notes:**

**Comment by jwitz** [comment]
Hey @aspain this is a good thought and there's definitely other search words out there that we should be writing special rules for. Our current Algolia plan doesn't support re-ranking like this, but I can reach out to Zach to see if we can spend a little more on premium for this feature. 

With that said, I wouldn't want to spend more on all of those features without first implementing [click and conversion events](https://www.algolia.com/doc/guides/getting-analytics/search-analytics/advanced-analytics/), which has been on our plate for a while. Once we gather enough metrics for the premium features to be useful at scale, I'll work on this issue.

**Comment by jwitz** [comment]
@aspain We got a little excited about the prospect of curated searches on the docs team, so we went ahead and got a premium plan even though we haven't enabled those other key metrics yet!

Now we can set rules that help users get to the right docs they're looking for. If you try your search again, you should see the doc right where you want it

![Screen Shot 2022-05-19 at 3 39 15 PM](https://user-images.githubusercontent.com/74574233/169409029-d5cc6621-d4da-4d35-aba6-d979576d4787.png)

**Comment by paolaperaza** [comment]
🎉 !!!! Thanks @jwitz

**Comment by aspain** [comment]
yes thank you @jwitz this is awesome!
