### ISSUE TITLE
Add Worker Size Limits to GCP Resource Reference

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#692]
### Context

We recently added a new "Worker Size Limits" section to this AWS doc: https://docs.astronomer.io/astro/resource-reference-aws#deployment-worker-size-limits. This section tells users the maximum size workers they can provision per node instance type that AWS supports.

To make sure these numbers are "real" and take into account system overhead (at least approximately) the CRE team helped us calculate these #s per instance type.

### Action
Two things needed to complete this issue:

- [ ] Ask CRE team to perform the same exercise for all supported GCP node types as they did on AWS in this spreadsheet: https://docs.google.com/spreadsheets/d/1-ejFME01oaqI7-n2MfBqVNf1PbR4H1sg4kuui28nERA/edit#gid=0
- [ ] Add a new `Worker Size Limits` to this GCP doc, with a table of all supported node instance types and their corresponding Max AU/CPU/Memory values: https://docs.astronomer.io/astro/resource-reference-gcp

cc: @dnarain-astro

**Comment by afastronomer** [comment]
Hi Paola,
we had the case today with GKE cluster and real situation showed max size for n2-standard-4 instance is 25 AU. Looks like Daemonsets on GKE instances consumes more resources, so 27 AU was too much for launching new pod

**Comment by stuart23** [comment]
@afastronomer is going to look at the maximum worker size for the 2 node types we currently support and add similar table as in [the AWS document](https://github.com/astronomer/docs/blob/main/astro/resource-reference-aws.md#deployment-worker-size-limits) to [the gcp document](https://github.com/astronomer/docs/blob/main/astro/resource-reference-gcp.md)
