### ISSUE TITLE
Data Lineage Headers Missing

### ISSUE THREAD

**Issue by aspain** [astronomer/docs#694]
**Affected Document:**
https://docs.astronomer.io/astro/set-up-data-lineage

**Problem Type (Priority):**

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [X] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**

I think this page is missing a header for each of the available integrations, right now there are many "Verify", "Prerequisites", and "Setup" sections, but nothing to identify which provider it is for unless you read the instructions

**Additional Notes:**

Additionally it seems like some examples suggest adding packages to `requirements.txt`: 
![image](https://user-images.githubusercontent.com/15913202/168908959-dba9d27d-fd2f-4d1c-9677-c5cbdd333947.png)

while others suggest pip installing the package and setting ENV vars in a shell rather than in a local Astro project, is this intended to be different? 
![image](https://user-images.githubusercontent.com/15913202/168909031-74331d9b-d6e5-44de-b367-30c8c32445b4.png)

**Comment by jwitz** [comment]
Yikes @aspain thanks for catching this, I forgot to add some import statements to the doc to enable content tabs. Just fixed via https://github.com/astronomer/docs/commit/c78bf2dd761408c7272084842ffdf1fb1ba19669, should be live soon!

**Comment by aspain** [comment]
thanks @jwitz - for the dbt one in particular, it has instructions to `pip install` rather than adding to `requirements.txt` - is that difference on purpose?
