### ISSUE TITLE
Dependency Graph for Astronomer Software

### ISSUE THREAD

**Issue by rbankston** [astronomer/docs#695]
**Request type:**

- [x] **New document:**: Add the `docs-content` label to this issue.
- [ ] **Addition to an existing document**: Add the `enhancement` label to this issue.

**What is the purpose of the document/enhancement? Select all that apply:**

- [ ] Document a new feature for an upcoming release. Add the appropriate release version label to this issue.
- [ ] Information for an existing feature that isn't yet documented.
- [x] Additional considerations/ reference material for an existing document.

**Problem/feature that requires documentation:**

Dependency graph  for Astronomer Enterprise Software for troubleshooting purposes.

**Are you the right person to review a draft of the document for technical accuracy? If not, who is?**

Astronomer Software Team

Something similar to this but in official graphics

![Platform Dependency Graph](https://user-images.githubusercontent.com/130836/168916286-881a7dfe-2c81-4169-b2fa-066ec0ce1357.png)

**Comment by kwcanuck** [comment]
@jwitz could you take this issue, or show me how you create drawings?

**Comment by jwitz** [comment]
It looks like Mermaid support has been approved and acknowledged by the maintainers of Docusaurus: https://github.com/facebook/docusaurus/pull/7490

Let's wait until that feature is released before we tackle this issue. Mermaid should make it a lot easier to render and maintain diagrams like this one.

**Comment by cmarteepants** [comment]
Will defer to @rbankston on whether there is still a need

**Comment by kwcanuck** [comment]
This image is no longer required. If this changes in future, this issue can be reopened.
