### ISSUE TITLE
Document how to use KubernetesPodOperator and AssumeRole-based authorization (AWS)

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#701]
From @dnarain-astro:

### Problem
Pods that run using KubernetesPodOperator do not have access to cloud resources by default because they do not have IAM bindings by default.  Customers who want to authorize their pods to use resources in another account need to pass in the credentials into this pod to do so.

There will be customers who are unable to pass in credentials and want to use IAM (AssumeRole) based authorization.  We need to provide guidance on how customers can accomplish this.

### Process

AFAIK, this is the approach:

- have the aws cli in the docker image 
- get the deployment name by querying the namespace 
- use the <deploymentname>-worker as the service_account_name 
- Either
- create a trust policy on the remote IAM role that trusts the OIDC provider created for this cluster 
- use aws sts assume-role from within the pod to assume the remote role

Or

- create a trust policy on the remote IAM role that trusts AirflowS3Logs-<clustername>
- use aws sts assume-role-with-web-identity --role-arn <ARN of AirflowS3Logs> --web-identity-token $AWS_WEB_IDENTITY_TOKEN
- use aws sts assume-role --role-arn <ARN of the final role you need to assume>

Even though this approach has drawbacks - you need to know the cluster id, you may need to reverse engineer the OIDC provider, the <deploymentname>-worker is an over-authorized serviceaccount - we still need to publish guidance on how a user can accomplish this.

### Additional Notes
This was reported by/tried by Color. What they did:

1. Update the AirflowS3LogsRole to have AssumeRole
2. Create a trust policy in their target role that allows AirflowS3LogsRole to assume it
3. Use the k8s service account <deployment>-worker in their pod spec
4. Run the following command in their pod (NOTE: May be redundant) 
aws sts assume-role-with-web-identity \  --role-arn $ARN_OF_AIRFLOWS3LOGSROLE \  --web-identity-token file://$AWS_WEB_IDENTITY_TOKEN_FILE
5. Run the following command in their pod:
aws sts assume-role  --role-arn $ARN_OF_THECORRECTROLE

@dnarain-astro Do you know if Color got this to work in the end? Which of the following processes worked for them?

**Comment by kwcanuck** [comment]
I checked in with @dnarain-astro on this and this was his feedback:

"close it, its too messy and too niche to document.  We should make it a knowledgebase article"
