### ISSUE TITLE
Set AC 2.3 as LTS on Software + Nebula

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#704]
Docs: 
- https://nebula.astronomer.io/support-policy
- https://docs.astronomer.io/software/ac-support-policy#lts-releases

For Software, make sure to port over to all versions

**Comment by jwitz** [comment]
Software updated via https://github.com/astronomer/docs/commit/3f67ba31f7f207e68cad2ba6fcb379df071380ce
Nebula updated via https://github.com/astronomer/nebula-docs/commit/903e41fbb1fe4847f4463a52bdf3c8bf32a495bf
