### ISSUE TITLE
New Doc: Create a Deployment, Change: Configure a Deployment

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#708]
### Context
As we re-work the getting started experience in the context of the new Astro CLI, we've decided to separate our existing `Configure Deployment` doc into two:

1. A new "Create Deployment" Doc that is an intro to what a Deployment is and covers default values users have to set on creation
2. Rename"Configure Deployment" doc to `Configure Deployment Resources` doc that is more detailed, technical, and covers ALL values that users have to set, including those they don't have access to on "Create" (e.g. Environment Variables, Worker Queues)

### Ask
As part of this GitHub issue, let's:

- Create a new `Create Deployment` file (`create-deployment.md`) in the `Get Started` menu of docs page
- Delete `Configure a Workspace` section from current `Configure Deployment` doc into new `Create Deployment` doc
- Copy/pull out the steps in `Create a Deployment` section of `Configure Deployment` doc
- Create a Deployment doc should be:
```
   - ## Overview (what is a Deployment)
   - ## Step 1. Select a Workspace
   - ## Step 2. Create a Deployment
         - Info on name, description, runtime
   - ## Step 3. Set Deployment Resources
         - Basic info on scheduler + worker resources
   - ## Step 4. Access Airflow UI
   - ## Next Steps
        - Links to configure deployment resources + set env vars + api keys docs
```
- Rename `Configure a Deployment` doc to `Configure Deployment Resources` and include:
   ```
   - ## Overview
   - ## Worker Resources
        - ### Worker Autoscaling (pull out of tooltip)
   - ## Scheduler Resources
   - ## Next Steps
   ```
 - The `Worker Resources` section has a lot of info, so we can consider breaking it down a bit now that it has a more dedicated space

@kwcanuck Assigning this to you for when you get back 😊  Let's finish this in the same timeline as converged Astro CLI

**Comment by kwcanuck** [comment]
New branch created for this work: _Create-and-Configure-a-Deployment-Changes-(708)_
