### ISSUE TITLE
Cannot use local base image

### ISSUE THREAD

**Issue by BasPH** [astronomer/docs#721]
The instructions in https://docs.astronomer.io/astro/develop-project#step-3-build-a-custom-docker-image mention to use a local base image, but Docker defaults to fetching this from docker.io. Since you cannot specify any flags for Docker when using the astrocloud CLI, there's no way to use a local base image. It does work fine if you push the base image to a registry first:

```bash
[create ECR registry]
aws ecr get-login-password --region [region] | docker login --username AWS --password-stdin [account].dkr.ecr.[region].amazonaws.com
docker build -f Dockerfile.base -t [account].dkr.ecr.[region].amazonaws.com/[registry]:[tag] .
docker push [account].dkr.ecr.[region].amazonaws.com/[registry]:[tag]
```

And specify `[account].dkr.ecr.[region].amazonaws.com/[registry]:[tag]` in the Dockerfile.

**Affected Document:**
https://docs.astronomer.io/astro/develop-project#step-3-build-a-custom-docker-image

**Problem Type (Priority):**

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [x] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**
Add instructions to build & push to a repository, or figure out how to instruct Docker how to use a local base image.

**Additional Notes:**

**Comment by jwitz** [comment]
@BasPH Wouldn't Docker fetch the correct image when you add this line to your `dockerfile.build` file? 

```
FROM quay.io/astronomer/astro-runtime:5.0.0-base AS stage1
```

**Comment by BasPH** [comment]
It would yes, but we don't allow customers to push images to our quay.io repository. So they would have to set up their own registry and point to that e.g. `registry.mycompany.com/astro-runtime:5.0.0-base` so that Docker doesn't default to fetching from `docker.io`.

**Comment by kwcanuck** [comment]
Asked @BasPH to follow up in a Slack message 2022-06-14.
