### ISSUE TITLE
Port fixes from embedded lineage docs to Astro docs

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#735]
**Affected Document:** https://docs.astronomer.io/astro/set-up-data-lineage#integration-guides

**Problem Type (Priority):**

- [X] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [ ] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):** We need to update the Databricks setup in our Astro docs with the fixes from our embedded docs. Basically, we need to copy this text and update links/ references where necessary to fit our docs:

```
# Getting Started with Databricks

This guide outlines how to set up lineage collection for Spark running on a Databricks cluster.

## Prerequisites

To complete this setup, you need:

- A Databricks cluster.

## Setup

1. Download the `jar` for the latest release of OpenLineage via the [Maven Central Repository](https://search.maven.org/artifact/io.openlineage/openlineage-spark).
2. Download `open-lineage-init-script.sh` from the [OpenLineage GitHub](https://github.com/OpenLineage/OpenLineage/blob/main/integration/spark/databricks/open-lineage-init-script.sh).
3. In your Databricks cluster's [DBFS](https://docs.databricks.com/data/databricks-file-system.html), create a new directory at `dbfs:/databricks/openlineage/`.
4. Upload both the `jar` from Step 1 and `open-lineage-init-script.sh` to your new directory. 
5. Create a [cluster-scoped init script](https://docs.databricks.com/clusters/init-scripts.html#example-cluster-scoped-init-script) with the following line:

    ```sh
    dbfs:/databricks/openlineage/open-lineage-init-script.sh
    ```

    This script will install the `openlineage-spark` library upon cluster creation. 

5.  In the cluster configuration page for your Databricks cluster, specify the following [Spark configuration](https://docs.databricks.com/clusters/configure.html#spark-configuration):

    ```bash
    spark.driver.extraJavaOptions -Djava.security.properties=
    spark.executor.extraJavaOptions -Djava.security.properties=
    spark.openlineage.host https://{your astro base domain}
    spark.openlineage.apiKey {your lineage api key}
    spark.openlineage.namespace <NAMESPACE_NAME> // We recommend a meaningful namespace like `spark-dev`, `spark-prod`, etc.
    ```

> **Note:** You override the JVM security properties for the spark _driver_ and _executor_ with an _empty_ string as some TLS algorithms are disabled by default. For a more detailed explanation, see [this](https://docs.microsoft.com/en-us/answers/questions/170730/handshake-fails-trying-to-connect-from-azure-datab.html) discussion.

After you save this configuration, lineage will be enabled for all Spark jobs running on your cluster.

## Verify Setup

To test that lineage was configured correctly on your Databricks cluster, run a test Spark job on Databricks. After your job runs, , open the [Explore page](/explore/) page. If your configuration was successful, you should see your Spark job appear in the **Most Recent Runs** table. From here, you can click a job run to see it within a lineage graph.
```

**Comment by kwcanuck** [comment]
@jwitz can you provide any guidance on what needs to be done to resolve this issue? Where is the information currently located and where should it be added? If you can provide the necessary information, I can move this issue forward to resolution. Thanks!

**Comment by jwitz** [comment]
@kwcanuck Oh no! I had this issue fully written up but evidently forgot to save my changes. Just added the details to the main issue description. Also feel free to edit any wording as you see fit!
