### ISSUE TITLE
Expand on "Extra Capacity" Configs in KubePodOperator Doc

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#75]
Let's beef this section up a bit to:

- Clarify and expand on the `Extra Capacity` slider and the 3 configs it touches: quotas, limit ranges, and pod count
- Add setting `is_delete_operator_pod=True` as a requirement
- Warning against this error maybe?

```
Warning  FailedCreate  93s (x196 over 96m)  statefulset-controller  create Pod solar-orbit-4143-scheduler-0 in StatefulSet solar-orbit-4143-scheduler failed error: pods "solar-orbit-4143-scheduler-0" is forbidden: exceeded quota: solar-orbit-4143-resource-quota, requested: pods=1, used: pods=20, limited: pods=18
```

- Aaaand anything else you think is relevant, @vparekh94

**Comment by vparekh94** [comment]
^closed
