### ISSUE TITLE
Add more info on `astro context switch` for Software

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#752]
### Problem
We should add explicit guidance on how to switch contexts on Astronomer Software. This shouldn't apply to Astro as customers should only ever be on `cloud.astronomer.io`.

We need more guidance in either:
- `Install CLI` (Software) - https://deploy-preview-690--gallant-neumann-56599d.netlify.app/software/install-cli
- `Configure the Astro CLI` (Astro) - https://deploy-preview-690--gallant-neumann-56599d.netlify.app/astro/cli/configure-cli
- CLI reference (Software) but seems too low-visibility - https://deploy-preview-690--gallant-neumann-56599d.netlify.app/software/cli-reference#astro-context-switch

### Ask
Info should be a new `### Set Astro Context` (or something similar) that includes steps:

1. Run `astro login` to your target base domain
2. Run `astro context switch` to your target base domain
3. Run `astro context list` to confirm your new default

Additional info that'd be good to include:
- Clarify that you can authenticate to multiple domains while staying on the same context
- Clarify the difference between `astro context switch x` and `astro login x`. One authenticates, one sets the context _default_ on your machine but is not required to authenticate. It's just so you don't have to keep specifying the context on each command.
- Document errors you might get if you don't do this in the right way
- Document error you might get if you try to log in or switch to a context that doesn't exist

Related thread: https://astronomer.slack.com/archives/C01UA03TPV1/p1654046150644909?thread_ts=1654035005.197499&cid=C01UA03TPV1

cc: @sunkickr @conorbev David correct me if I'm wrong on any of this!

**Comment by kwcanuck** [comment]
New branch created for this work: Add_More_Info_on_Astro_Context_Switch_for_Software
