### ISSUE TITLE
Standardize `Astro project` in Software Docs

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#753]
With the release of Astro CLI 1.0.0, let's make sure that for Astro v0.28+ we:

- Remove all references to `Airflow project` and `Astronomer project`
- Replace them with `Astro project`
- (Make sure this is the case in all Astro docs too)

The Astro project is our main development unit regardless of product!

FYI: @kwcanuck This might have to wait until we merge #690 to avoid insane conflicts

**Comment by kwcanuck** [comment]
New branch created (Standardize Astro Project in Software Docs).

@jwitz can you let me know when you have merged #690 so I can get started on resolving this issue? Thanks!
