### ISSUE TITLE
Question on callout styling

### ISSUE THREAD

**Issue by stuart23** [astronomer/docs#766]
I'm seeing some callouts formatted as:
`> **Note:** `
e.g. https://github.com/astronomer/docs/blob/main/software/houston-api.md?plain=1#L32

and others using the info callouts:
`:::info`
e.g. https://github.com/astronomer/docs/blob/main/astro/airflow-api.md?plain=1#L41

Do we have a preferred callout format, or do we want to keep using both of them?

**Comment by jwitz** [comment]
Good question @stuart23 . `>**Note:**` is legacy formatting. If you see it in a doc, we just haven't gotten around to reformatting it. Whenever possible, we should use `:::info`
