### ISSUE TITLE
New: How to use a CI Process with Airflow API to programmatically update Airflow Variables on Astro Deployment

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#77]
While customers can leverage [`airflow_settings.yaml`](https://github.com/astronomer/docs/blob/master/v0.8/cli-airflow-configuration.md) to programmatically update Airflow Variables if they're developing locally, there's currently no direct way to do so for a remote Airflow deployment on our platform.

As a temporary solution, we should have a doc/guide on doing so via a CI process with the API.

@vparekh94 Would love your help on this, but I'll assign myself and @andrewhharmon as well to help out.

**Comment by vparekh94** [comment]
Ah, I think I was wrong on this - we've used the API to create DAG runs - not to create credentials.

This would is only possible on enterprise right now, and even then it's nontrivial - it'd depend on where the creds are stored. Most EE customers have found their own way around it.

Think it's best to close this for now until there is something more actionable in the short term
