### ISSUE TITLE
Guidelines around selecting cluster node sizes

### ISSUE THREAD

**Issue by stuart23** [astronomer/docs#789]
**Request type:**

- [x] **New document:**: Add the `docs-content` label to this issue.
- [ ] **Addition to an existing document**: Add the `enhancement` label to this issue.

**What is the purpose of the document/enhancement? Select all that apply:**

- [ ] Document a new feature for an upcoming release. Add the appropriate release version label to this issue.
- [ ] Information for an existing feature that isn't yet documented.
- [x] Additional considerations/ reference material for an existing document.

**Problem/feature that requires documentation:**

CRE are running into quite a few instances of clusters hitting their default number of nodes (20). We can increase this number, but it is inefficient and we should be increasing their node size. This can be more efficient because you will have more compute power available per dollar (each node has some daemonsets running - using fewer instances that are bigger means that less resources are dedicated to these daemonsets).

Here is an example of us reaching out to a customer about resizing their nodes: https://astronomer.zendesk.com/agent/tickets/9550

We are implementing some alerting around node usage so that we can find the customers that should go up a node size: https://github.com/astronomer/astrohub-hq-manifests/compare/stuart23-constanthighnodeusage?expand=1

We need a resource that we can point the customer to that will explain the benefits and reasoning behind increasing node size. This will be shared with the customer when we reach out to recommend that they increase node size, but it can also be used during the onboarding phase to help the customer select an appropriate starting node size, as well as in the sales discovery phase to demonstrate how Astro can scale with a customers usage effectively.

Some sample copy that I started writing:

_Astronomer constantly monitors your usage and number of nodes deployed in your cluster. As your usage of Airflow increases, Astronomer may reach out with recommendations to change your clusters node type to optimize your infrastructure spend or increase efficiency of your tasks._

**Are you the right person to review a draft of the document for technical accuracy? If not, who is?**

We have a little committee on worker node sizes - Deepak Narain, @ReadytoRocc, @RNHTTR

**Comment by kwcanuck** [comment]
Discussed with @paolaperaza at a Docs Team standup. It was determined that this request requires additional conversations to finalize requirements and define what information Astronomer should provide.

**Comment by stuart23** [comment]
I am happy to work with y'all to draft something up

**Comment by kwcanuck** [comment]
From @paolaperaza 2022-07-18:

_Worker Queues will totally change the game here, so let’s leave it open and revisit later this week as part of making progress on Worker Queues. Jake might end up tackling this one if he does that work, but let’s discuss in meeting today._
