### ISSUE TITLE
Clarify RBAC at workspace level only

### ISSUE THREAD

**Issue by stuart23** [astronomer/docs#799]
**Request type:**

- [ ] **New document:**: Add the `docs-content` label to this issue.
- [x] **Addition to an existing document**: Add the `enhancement` label to this issue.

**What is the purpose of the document/enhancement? Select all that apply:**

- [ ] Document a new feature for an upcoming release. Add the appropriate release version label to this issue.
- [x] Information for an existing feature that isn't yet documented.
- [ ] Additional considerations/ reference material for an existing document.

**Problem/feature that requires documentation:**

It is not clear that RBAC is done on a workspace level. and you cannot assign roles at the deployment level. This is confusing for users migrating across from Software.

https://docs.astronomer.io/astro/user-permissions

**Are you the right person to review a draft of the document for technical accuracy? If not, who is?**

Sure

**Comment by kwcanuck** [comment]
@stuart23 can this issue be resolved with the addition of a line of text to the Overview similar to the following:

_Role-based access control is not available for Deployments._

This new text would appear at the end of this statement:

_To better protect your data pipelines and cloud infrastructure, Astro offers role-based access control for Organizations and Workspaces. Each Astro user has a Workspace role in each Workspace they belong to, plus a single Organization role._

**Comment by stuart23** [comment]
Maybe something a little more descriptive?

"Workspaces are the most granular level that roles can be assigned. Role-based access control is not available for Deployments."

**Comment by kwcanuck** [comment]
@stuart23 I don't think the preceding sentence you added is necessary. I am concerned that the use of jargon such as "granular level" may not be easily understood by all readers. The overview already indicates "...Astro offers role-based access control for Organizations and Workspaces". I think adding the simple statement _Role-based access control is not available for Deployments_ should suffice and will alleviate your concern. With this simple statement, there is no ambiguity. 

If you feel strongly about adding another sentence, I'll see what I can do.

**Comment by stuart23** [comment]
LGTM!
