### ISSUE TITLE
Clarity on how to increase GCP quotas

### ISSUE THREAD

**Issue by stuart23** [astronomer/docs#800]
**Affected Document:**

Google Cloud Install Procedure

**Problem Type (Priority):**

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [x] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**

Customer was confused about how to increase quota (https://astronomer.zendesk.com/agent/tickets/10249) may need to make this section more descriptive.

**Additional Notes:**

**Comment by jwitz** [comment]
Would linking to [this GCP doc](https://cloud.google.com/docs/quota#managing_your_quota_console) in the prerequisites suffice for this? I don't want to document too much about GCP in our own docs, as those configuration steps are always subject to change by Google without us being notified.

**Comment by stuart23** [comment]
> Would linking to [this GCP doc](https://cloud.google.com/docs/quota#managing_your_quota_console) in the prerequisites suffice for this? I don't want to document too much about GCP in our own docs, as those configuration steps are always subject to change by Google without us being notified.

Yes perfect!
