### ISSUE TITLE
Circle CI Instructions may be incorrect

### ISSUE THREAD

**Issue by stuart23** [astronomer/docs#801]
**Affected Document:**

CI/CD - Circle CI Instructions

**Problem Type (Priority):**

- [x] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [ ] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**

The example does not seem to work. Can we please check it?
https://astronomer.zendesk.com/agent/tickets/10351

**Additional Notes:**

**Comment by jwitz** [comment]
Following the ticket in question, once the troubleshooting is resolved there I'll update the CI/CD doc

**Comment by jwitz** [comment]
This was resolved in https://github.com/astronomer/docs/pull/830!
