### ISSUE TITLE
Create diagram to demonstrate network isolation

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#813]
**Request type:**

- [ ] **New document:**: Add the `docs-content` label to this issue.
- [X] **Addition to an existing document**: Add the `enhancement` label to this issue.

**Problem/feature that requires documentation:** Let's create a more detailed architecture diagram that demonstrates how Deployments do not share network connections/ resources on the Data Plane. We can use this diagram as a starting point, but I'd like to eventually create a diagram with two Deployments to show what exactly is shared between Deployments and what isn't.

![Data Plane Architecture - Data Plane (1)](https://user-images.githubusercontent.com/74574233/173625518-7a2d7042-43d2-4004-b480-7b5b64afdfdf.png)

**Are you the right person to review a draft of the document for technical accuracy? If not, who is?**

**Comment by kwcanuck** [comment]
From @paolaperaza:

_Let’s close for now. It was us that requested the ask and it’s not clear why or what. We can create a new and more detailed issue when it comes up again._
