### ISSUE TITLE
New Doc on "Astronomer Telescope" (Software)

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#824]
### Context

Customer teams at Astronomer have built and standardized on a tool called "Telescope" that Astronomer Software customers install and then use to send data to Astronomer about their task usage and Airflow environments. This is largely because Astronomer Software customers run our product in their own clouds, which we don't have overall access to.

This data is necessary for us to understand how customers use our product as well as verify pricing and contracts.

### Ask

A Google Doc is currently used to instruct customers on how to install Telescope: https://docs.google.com/document/d/1XkRTnFP6aEIjjU82EKBAE1k-oSHW3Oy49NTmExRJ43o/edit#heading=h.k1ocimgipeas

Let's:
- Create a new Doc in the `Astronomer Software` tab called `Install Telescope`
- Add the content in this doc according to our formatting and copy standards

Where this doc lives is TBD. @cmarteepants Do you have any opinion here? Who else can we chat about to verify functionality and intended framing? cc: @fritz-astronomer @cfcastro24

**Comment by cmarteepants** [comment]
What are the support expectations for CRE and SLA's around Telescope? i.e, who is responsible if someone complains about CVE's or bugs? Only concern is that by publishing this, we're setting a different expectation with clients

**Comment by fritz-astronomer** [comment]
I am happy to help verify functionality and framing re: telescope.
@cmarteepants - great point without a good answer. There will be CVEs and Bugs. I hope this can be a communally maintained tool - I keep trying to encourage others to commit as anything comes up.
Luckily the fact that it's just a CLI that runs on your workstation, that doesn't need to touch your cluster, or have any permanent footprint; except when you run it may also put it in a different "place" in regards to that - but I can understand if that's not the case

**Comment by cmarteepants** [comment]
@fritz-astronomer Not saying y'all aren't doing a great job, more pointing out that if we add this as part of standard Software docs, it'll come with a different set of expectations and assumptions. Want to confirm that all relevant stakeholders (like CRE) are aware as and know what their new responsibilities (if any) are going forward.
