### ISSUE TITLE
NFS DAGs directory using cloud provider native container storage interfaces

### ISSUE THREAD

**Issue by stuart23** [astronomer/docs#839]
We currently have documentation on how to deploy DAGs using NFS [here](https://github.com/astronomer/docs/blob/main/software_versioned_docs/version-0.28/deploy-nfs.md).

Should we also have instructions on how to do this using other cloud provider native CSI's (EFS, Azure Files, Google FS)? Should this be the preferred option?

**Comment by kwcanuck** [comment]
@jwitz or @paolaperaza do we want to document DAG deployment with other cloud provider native CSI's?

**Comment by jwitz** [comment]
I spoke with @cmarteepants , and the ways to configure NFS are so vast and varied between companies that we might have to accept that ambiguity in the documentation. 

One thing we can say (assuming we're okay to add a "Support" line) is that customers are responsible for determining how to provision an NFS volume and how to add DAGs to that volume. If they're struggling with a solution, they can reach out to Astronomer support to explain their situation.

Over time, we might see a pattern of common requests and document those. But seeing as this deployment method could change in future iterations of Software, let's leave it mostly as-is for now. I'll still keep this issue open to track my changes mentioned above.

**Comment by kwcanuck** [comment]
@jwitz thanks for the quick review and analysis. If you prefer, you can assign this issue to me and I'll add the information you recommended.

**Comment by jwitz** [comment]
Actually per this comment from Collin, I think we should just go ahead and close this out 😄 

> I don't want the official process for anything to be “ask CRE”. So either we document it or we say no.

If we don't want to apply any more pressure to CRE on docs, then there's very little we can say about NFS at the moment. Let's keep any information about this internal for now and provide it to customers when they ask for it, but let's not encourage customers to ask open ended questions or ask for custom solutions in the docs.
