### ISSUE TITLE
We should document how to use the AssumeRole functionality of Airflow connections w/ Astro 

### ISSUE THREAD

**Issue by dnarain-astro** [astronomer/docs#856]
**Request type:**

- [ ] **New document:**: Add the `docs-content` label to this issue.
- [x] **Addition to an existing document**: Add the `enhancement` label to this issue.

**What is the purpose of the document/enhancement? Select all that apply:**
 I'm opening an issue vs putting in a PR because I wasn't sure where the right place for this was.  This isn't new Airflow functionality (but new to Astro, we didn't allow this till recently.  We've had enough Astro customers ask us how to set it up for Astro that it seems worth writing it down.   The reason for the confusion is that in Astro we generate the roles, vs in OSS, where the customer makes the roles and knows their names. 

- [ ] Document a new feature for an upcoming release. Add the appropriate release version label to this issue.
- [x] Information for an existing feature that isn't yet documented.
- [ ] Additional considerations/ reference material for an existing document.

**Problem/feature that requires documentation:**
How to use role_arn in AWS Connection to use AWS services without requiring any secrets.  Here is a summary of what needs to be done:
Create IAM Roles for the permissions they want Astro to have.
Add arn:aws:iam::<DATAPLANE-AWS-ACCOUNTID>:role/AirflowS3Logs-<CLUSTERID> as a Principal in the Trust of the Roles they created in step 1.
Cluster ID should be accessible via the Cluster Page in Astro.
Follow the OSS Connection Configuration: https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/connections/aws.html

**Are you the right person to review a draft of the document for technical accuracy? If not, who is?**

Yes

**Comment by kwcanuck** [comment]
New branch created for this work: Add-AssumeRole-Functionality-for-Airflow-Connections
