### ISSUE TITLE
New Documentation for Astro Runtime Executor (Stellar)

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#858]
To prepare for release of the new Astro Runtime Executor in July 2022, we need to prepare two new docs:

- Astro Runtime architecture
- Run the Astro Runtime executor

Initial drafts here: https://www.notion.so/astronomerio/Stellar-Executor-Documentation-Drafts-770fb210493e423184224065dae26873

Once we get approval on those drafts from the team, @jwitz will open 1 PR to merge these changes pending feature release.

**Comment by jwitz** [comment]
Closing for now, these docs will need to be changed substantially if we ever release.
