### ISSUE TITLE
New Docs: Log In to Astro, Log In to Software

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#871]
### Context

We don't explicitly have documentation that walks end-users through authenticating to Astronomer. The idea is that this is the complementary view to: https://docs.astronomer.io/astro/add-user

We need two new docs that walk users through authenticating to Astronomer.

- `Log in to Astro`
- `Log in to Software`

### Ask

Log in to Astro should include:
- How to log in to Cloud UI
- How to log in to Astro CLI
- A brief "tip" on `astro context switch`

Log in to Software should include:
- How to log in to Software UI
- Definition of base domain
- How to log in to Astro CLI
- Dedicated section on `astro context switch`

**Comment by kwcanuck** [comment]
New branch created for this work: Add Logging In to Astro and Software Docs.
