### ISSUE TITLE
Datadog integration for software

### ISSUE THREAD

**Issue by stuart23** [astronomer/docs#883]
**Request type:**

- [x] **New document:**: Add the `docs-content` label to this issue.
- [ ] **Addition to an existing document**: Add the `enhancement` label to this issue.

**What is the purpose of the document/enhancement? Select all that apply:**

- [ ] Document a new feature for an upcoming release. Add the appropriate release version label to this issue.
- [x] Information for an existing feature that isn't yet documented.
- [ ] Additional considerations/ reference material for an existing document.

**Problem/feature that requires documentation:**

We have an internal document on [how to integrate Datadog with software](https://support.astronomer.io/hc/en-us/articles/4416575082899-Datadog-Integration). A customer tried the Datadog instructions for Airflow and got stuck, if we included our instructions in the docs, the customer would have found them and been able to do the setup themselves. [Ticket 10672](https://astronomer.zendesk.com/agent/tickets/10672)
 
**Are you the right person to review a draft of the document for technical accuracy? If not, who is?**

Me or @rbankston can copy it from the knowledge base doc. Need to know if this is something we should include in docs first?

**Comment by kwcanuck** [comment]
Slack conversation: https://astronomer.slack.com/archives/CEPE4K68P/p1657115064067929

Discussed with @paolaperaza and @jwitz what the best location for this content would be and it was decided that the new topic should appear in the same section as _[Forward Astronomer Software logs to Amazon S3](https://docs.astronomer.io/software/logs-to-s3)_.

A new branch has been created for this work: _Add Datadog Integration Topic to Software Docs_
