### ISSUE TITLE
Create section on Querying Airflow Postgres with Astronomer

### ISSUE THREAD

**Issue by vparekh94** [astronomer/docs#90]
Forum post:

*Locally:* https://forum.astronomer.io/t/how-do-i-set-my-postgres-username-and-password-to-access-the-ad-hoc-query-feature-locally/139
*Cloud:* https://forum.astronomer.io/t/how-can-i-set-up-the-ad-hoc-query-feature-access-the-postgres-db-in-a-remote-deployment/143 (edited) 

This should be in the Using Astronomer section

**Comment by paolaperaza** [comment]
Published here: https://preview.astronomer.io/docs/query-airflow-database/

Closing this out!

**Comment by paolaperaza** [comment]
(Will link that last section for Enterprise customers to pull database creds to a new doc to come out of this issue: https://github.com/astronomer/docs/issues/91)
