### ISSUE TITLE
Create doc on getting database passwords for EE users

### ISSUE THREAD

**Issue by vparekh94** [astronomer/docs#91]
There should be a menu in `Administrating your Cluster` that shows users how to get passwords for airflow deployments in postgres from kubectl

**Comment by paolaperaza** [comment]
Doc live on Preview: https://preview.astronomer.io/docs/ee-administration-postgres-creds/

Waiting to close this out until I'm able to add it to the nav menu (getting an error when running that py script).

**Comment by paolaperaza** [comment]
Looks like my commit closed this issue but I'm opening this back up for @vparekh94 to take a look and make some changes if needed.

V, go ahead and comment in here or open up a PR with any edits if you have them and we can go from there.

**Comment by paolaperaza** [comment]
Got final confirmation from @vparekh94 that this final version looks good! Closing it out.
