### ISSUE TITLE
Add Kubernetes Executor Pricing

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#94]
**Topic:**
How will we (initially) price the KubernetesExecutor on Cloud?

**Cloud, EE, or Both?:**
Cloud, v0.9 and beyond. This info currently lives [here]( https://www.astronomer.io/docs/pricing/).

**Menu:**
Resources > Pricing

**User story**
I'm interested in running the Kubernetes Executor on Astronomer Cloud. How much will it coset me? How does it compare to other resources? Do I get to scale to zero?

**Comment by paolaperaza** [comment]
@ryw Can you shed some light on how we'll price the KubernetesExecutor to start with? Will we price resources the same, and rely on "Extra Capacity" the same way we do the KubePodOperator?

I know we've talked about a flat fee once it's fully a "scale to zero" feature, so want to make sure we're clear on pricing docs before it's fully released.

**Comment by ryw** [comment]
Yes we can consider K8sExecutor feature “alpha” and you have to use extra space to run it - so it’s not scale to zero yet. Once we get new usage tracking done we will change pricing model up. But for now, nothing changes.

**Comment by paolaperaza** [comment]
@ryw Got it - thanks!

**Comment by paolaperaza** [comment]
Added to our Pricing Doc: https://preview.astronomer.io/docs/pricing/

**Comment by ryw** [comment]
Nice work!
