### ISSUE TITLE
Info on whitelisting IPs

### ISSUE THREAD

**Issue by vparekh94** [astronomer/docs#95]
**Topic:**
We should pull out the forum post on whitelisting an IP to hit Redshift and make it into a doc. This will also flow nicely into a larger "Networking" doc at some point

**Cloud, EE, or Both?:**
Cloud

**Menu:**
Integrating Services

**Forum Post:**
https://forum.astronomer.io/t/how-do-i-whitelist-astronomer-cloud-on-aws-redshift/165

**User story**
As a user, I'm a data engineer with only basic infrastructure knowledge, which is pushing me towards a cloud service. I'd like to have a doc that walks me through what's needed to whitelist an IP.

**Comment by paolaperaza** [comment]
@vparekh94 MVP is up if you wanna take a look - https://preview.astronomer.io/docs/vpc-access/

My gut feeling is we could add more contextual info on Cloud networking but that's a bit outside my wheelhouse at the moment.

Anything info off the top of your head you think should be in here for any Cloud customers/prospects with related questions?

**Comment by vparekh94** [comment]
Looking good! Requested a few changes!

Might also be worth reading up segment's doc on how they did this and see if there is anything else that should be added, or what parts they give info on

https://segment.com/docs/destinations/redshift/

**Comment by paolaperaza** [comment]
@vparekh94 I just simplified the headers a bit in here, what do you think?

https://preview.astronomer.io/docs/vpc-access/

I did take a look at Segment's - they walk through creating a Redshift cluster in the first place (which we don't currently have - should we?), but the actual networking step is pretty much the same (though they have a different set of steps depending on what kind of cluster you have, EC2 Classic subnet or VPC subnet).

They also have a section on encrypting data, and on schema-naming best practices. Is there anything around that you think we should include in here?

**Comment by vparekh94** [comment]
Don't remember where we left it - can we close it?

**Comment by paolaperaza** [comment]
@vparekh94 I commented back on your reference to Segment's parallel doc, but if you think we're good we can close this
