### ISSUE TITLE
Use Doppler as a secrets backend

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#960]
**Request type:**

- [ ] **New document:**: Add the `docs-content` label to this issue.
- [X] **Addition to an existing document**: Add the `enhancement` label to this issue.

**What is the purpose of the document/enhancement? Select all that apply:**

Explain how to use Doppler as an Airflow secrets backend on Astronomer. Starting guide is here: https://www.notion.so/astronomerio/Doppler-Astro-Integration-dd3c19f5949d4e899d752d1314c00b1c

**Are you the right person to review a draft of the document for technical accuracy? If not, who is?** @manmeetkaur Should review

**Comment by kwcanuck** [comment]
This functionality is not officially supported currently. This request can be revisited when it is officially supported.
