### ISSUE TITLE
Document source code viewing functionality, limitations in OpenLineage

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#973]
To be documented only after Runtime receives an upgrade to its OpenLineage version.

Soon, the ability to view source code for lineage-emitting pipelines in the Lineage tab will be off by default. This is because we currently don't apply Workspace permissions to the UI, so Org users not belonging to a Workspace can still see Workspace code. Some users might wonder where this code went and how to bring it back, and for them we should document the process and limitations of enabling source code in the UI. This might be good info for https://docs.astronomer.io/astro/set-up-data-lineage

To turn back on source code viewing in OL, you need to set`OPENLINEAGE_AIRFLOW_DISABLE_SOURCE_CODE` to `False` as a Deployment environment variable.

**Comment by paolaperaza** [comment]
From @conorbev:

> The tab is labeled info and would still be there. This relates to python and bash operator source code only. If you're using an operator that has a SQL based extractor (like postgresoperator and others) it will still extract the sql and show it on that same tab

**Comment by paolaperaza** [comment]
A few things here from standup:

- Let's verify which version of OL this change was in, and confirm that it's present in Astro Runtime
- If so, add as its own bullet in Astro Runtime release notes
- Investigate how a user would turn this "on" (and why) and add to existing data lineage documentation

Source GH issue: https://github.com/OpenLineage/OpenLineage/pull/956
