### ISSUE TITLE
CLI Admonition doesn't work in night mode

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#976]
The new CLI admonition keeps the same colors when you switch to night mode despite my attempt to configure an alternative HTML theme. @allenbrady-astro would you be able to help with troubleshooting this?

**Comment by allenbrady-astro** [comment]
Hey Jake, got that color fixed up! Let me know if this looks good or if colors need a little more adjusting. 🙌 
<img width="1418" alt="image" src="https://user-images.githubusercontent.com/96535736/181821200-dfd2fe6e-3f11-46e6-ab37-86e5108cf34a.png">
