### ISSUE TITLE
Can't see toggle for dark mode in light mode

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#980]
The dark mode toggle in light mode isn't actually visible. It does come up in white on dark mode, but we should prob increase contrast there 

![181973873-34e8b15f-f02d-472b-adcd-8fe6da22fcb2](https://user-images.githubusercontent.com/31111752/181976559-12d0cd2b-9708-4d38-8b48-f7ae4a5f4a4f.png)

![181974449-6370637d-7364-4ce1-9916-7cafe5e253be](https://user-images.githubusercontent.com/31111752/181976510-2a551e3e-15b7-4bc4-9d58-f8b738dc0084.png)

**Comment by allenbrady-astro** [comment]
Hey @paolaperaza, got a PR open to fix the issue! #981

Default color
<img width="516" alt="Screen Shot 2022-08-01 at 9 52 01 AM" src="https://user-images.githubusercontent.com/96535736/182163395-d5b4838c-5d6e-4c88-b7c3-3a78b6579a52.png">

Hover state color
<img width="453" alt="Screen Shot 2022-08-01 at 9 52 09 AM" src="https://user-images.githubusercontent.com/96535736/182163425-c1ca5cbf-e517-41ec-a313-d2fa285d522e.png">
