### ISSUE TITLE
Update Install Astro on Azure Topic

### ISSUE THREAD

**Issue by kwcanuck** [astronomer/docs#986]
@dnarain-astro has requested a few minor changes to the existing _[Install Astro on Azure](https://docs.astronomer.io/astro/install-azure)_ topic.

**Comment by dnarain-astro** [comment]
Feedback that we should integrate (each of these was raised by at least 2 customers, so it seems legit):
- Application Administrator and Owner are only required for the cluster create process. They could be revoked after the cluster is created 
- Clarify that the word minimum in the pre-requistes section applies to quotas not resources 
- Assign an Owner role to your subcription should be Assign Owner role to the Astronomer Service Principal that will manage your subscription
